### ISSUE TITLE
just a thank you post and a quick question

### ISSUE THREAD

**Issue by mvucBmM0** [newsboat/newsboat#100]
Not an issue, just a thank you message to Minoru for keeping this project alive.
Just as a side note, for example, the only issue i have with (old newsbeuter) newsboat is this: https://github.com/akrennmair/newsbeuter/issues/103. It's not important enough, but I would just like to know if issues like those, on the old newsbeuter page, will be migrated here.
Again, thanks for sticking with this wonderful piece of software, and keep up the great work.

**Comment by Minoru** [comment]
You're very much welcome! ^_^

As for Newsbeuter issues, they're not forgotten—but see #31 for my thoughts on that.
