### ISSUE TITLE
Some feeds cause Newsboat tp crash (caught SIGHUP)

### ISSUE THREAD

**Issue by Mati20187** [newsboat/newsboat#1002]
**Newsboat version**: 2.19.0

**Config file**:

```
#auto-reload yes
auto-reload no
feed-sort-order none 
prepopulate-query-feeds yes
save-path "~/Documents/Articles"

bind-key j down
bind-key k up
bind-key G end
bind-key g home
bind-key D pagedown
bind-key U pageup
bind-key S sort
bind-key s save

browser firefox
macro , open-in-browser
macro v set browser "mpv"; open-in-browser ; set browser firefox

color listnormal blue default
color listfocus black yellow standout
color listnormal_unread cyan default bold 
color listfocus_unread yellow black bold
color article default default 
```
**Steps to reproduce the issue:**

1. Add one of the urls mentioned below to the urls file. 

2. Open newsboat, reload the feed and press enter on the feed.

3. Newsboat crashes.

**Other info you think is relevant**:
Upon pressing enter on some feeds (https://lbryfeed.melroy.org/channel/tv/veritasium, https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q and many others) Newsboat crashes. I've been using Newsboat on this particular machine running Arch Linux for a few days and the issue started occurring today.

Things I've tried: deleting config, clearing package manager cache, deleting newsboat database, reinstalling newsboat and its dependencies.

**Log:**
https://pastebin.com/QLsmUHyq

**The important part of log:**
```
[2020-06-14 17:12:38] DEBUG: ListFormatter::add_line: `<unread>  15 N  Sep 29         The Billion Ant Mega Colony and the Biggest War on Earth</>'
[2020-06-14 17:12:38] DEBUG: caught SIGHUP
[2020-06-14 17:12:38] DEBUG: caught SIGHUP
```

This issue only occurs on some feeds and I can't see any pattern that would explain why certain feeds cause Newsboat to crash while other feeds don't. 
Any help would be very appreciated. Thanks in advance!

**Comment by Mati20187** [comment]
Damn, that's annoying. I've spent an hour looking for information on this problem and when I think there's nothing more to find and open an issue, I find a solution not long after. 

Terminal related (st and emojis in feed titles don't go well together).

**Comment by Minoru** [comment]
That happens :) Thanks for writing about the root cause, though: if this happens to another user, I'll know to ask if they're using st.
