### ISSUE TITLE
Ask for confirmation before marking all feeds read

### ISSUE THREAD

**Issue by Ivan-Johnson** [newsboat/newsboat#1006]
I mistyped a shortcut earlier today and accidentally discovered that newsboat has an easy to type shortcut (`C`) that marks all items in all feeds as read without confirmation. As I understand it, Newsboat autosaves the read/unread status and has no ability to undo such changes which means that all the data about where I am in my YouTube channel, webcomic, and webnovel feeds has been deleted. Is this correct? If so that is a huge dataloss for me, particularly for webnovels that I tend to leave items as unread for months or years at a time until the backlog of chapters reaches roughly the size of a full novel. Thankfully I have a system backup from a couple weeks ago so I have the option of restoring from that and and being able to easily update the "read" status for a couple dozen items as opposed to having to skim through 43 novels to figure out where I was in each of them the last time I read them weeks or years ago.

Were it not for the fact that I'm surely in the minority for being so inconvenienced by having everything marked as "read", I would insist that something should change so that this can't happen, such as by asking for confirmation before marking everything read or adding the ability to undo such a change. As it stands, I probably am in a tiny minority so I have no rebuttal if you (the developers of newsboat) think that it's not worth the development effort and the inconvenience it would cause the majority of users, especially when people like me can just unbind those keys as I have now.

**Comment by Minoru** [comment]
Hi! It's been on the to-do list ever since Newsbeuter (https://github.com/akrennmair/newsbeuter/issues/476, https://github.com/akrennmair/newsbeuter/issues/257), but I haven't gotten around to it, and no-one else picked it up either. So here we are.

**Comment by anishmittal2020** [comment]
@Minoru  I see that this feature has been added to the latest Newsboat 2.21. **But is is possible to set in the configuration file of Newsboat, whether the user wants this feature or not?** 

For, some users (old) it might be useful to not to confirm as they have been using Newsboat for a long time, and they know important shortcuts. It was more frictionless for them, but now there is an additional step.

**Comment by Minoru** [comment]
@anishmittal2020 Not at the moment, but it does make sense to add a setting akin to the existing `confirm-exit`. I'll turn your comment into an issue.
