### ISSUE TITLE
Feature Request: `feedlist-format` `U`:

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#1008]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.19.0
System: Linux 5.4.0-37-generic (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 (compiled with 7.69.1)
SQLite: 3.32.1 (compiled with 3.31.1)
libxml2: compiled with 2.9.10

# Feature Request

In `feedlist-format`: `U`  indicates number of unread. Is it possible to not show anything when the value is 0. 

## Reasoning

- Visually it is more better, as our brains still needs to process those rows where 0 is written. 
- And the display is more cluttered with so many zeros!

**Comment by Minoru** [comment]
This is already possible: you can [press `l` to temporarily hide read feeds](https://newsboat.org/releases/2.19/docs/newsboat.html#toggle-show-read-feeds), or [unset `show-read-feeds` in your config](https://newsboat.org/releases/2.19/docs/newsboat.html#show-read-feeds).
