### ISSUE TITLE
Newsboat doesn't properly render plain text with <content type="text/plain">

### ISSUE THREAD

**Issue by somasis** [newsboat/newsboat#1010]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.19.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
cache-file ~/.cache/newsboat/cache.db

# Navigation settings
mark-as-read-on-hover yes       # moving down list marks articles as read

# Download/synchronization settings
download-full-page yes          # download link's contents when no summary is given
prepopulate-query-feeds yes     # without this query feeds are empty by default
reload-threads 4
refresh-on-startup yes

# Article display settings
show-keymap-hint no
text-width 100

# Color scheme
color listfocus white blue bold
color listnormal_unread green black bold
color listfocus_unread black green bold
color info white magenta bold

# Appearance settings
datetime-format     "%B %d"                         # March 19
feedlist-format     "%4i │ %t %> %?N?%U unread?"    # index │ title | feed title (aligned right)
articlelist-format  "%4i │ %-12D │ %t%> %?a?%a?"    # index | date | title | author (aligned right)

feedlist-title-format       "All feeds %?T? - tag `%T'&?%> %u unread, %t total"
articlelist-title-format    "%T%> %u unread, %t total"
searchresult-title-format   "Search result %> %u unread, %t total"
filebrowser-title-format    "%?O?Open File&Save File? - %f"
dirbrowser-title-format     "%?O?Open Directory&Save File? - %f"
help-title-format           "Help"
selecttag-title-format      "Select Tag"
selectfilter-title-format   "Select Filter"
itemview-title-format       "%T %> %F - %u unread, %t total"
urlview-title-format        "URLs"
dialogs-title-format        "Dialogs"
```

Steps to reproduce the issue:

1. Try to read a feed that provides plain text as content, ex. https://text.causal.agency/feed.atom

2. Newsboat renders the content without newlines or multiple spaces.

It looks like this:

![20200619_164840](https://user-images.githubusercontent.com/264788/85178570-cb857080-b24c-11ea-8ddd-dd3ae42e52d6.png)

But I would expect it to look more like this:

```text
IRC-SUITE(7)       FreeBSD Miscellaneous Information Manual       IRC-SUITE(7)

NAME
     IRC suite – my own IRC software

DESCRIPTION
     Over the past months (eight of them, according to git-log(1)) I developed
     a new “suite” of IRC software that I now use full-time, consisting of a
     bouncer, a new logging and search solution, and a terminal client.  These
     new programs share some characteristics: they are all TLS-only and use
     the libtls API from LibreSSL, they can all be entirely configured from
[...]
```

Discussion on IRC seems to indicate that Newsboat doesn't support MIME types at all.

**Comment by Minoru** [comment]
Strictly speaking, I can't reproduce, neither on r2.19 nor on master (https://github.com/newsboat/newsboat/commit/f70ab40de5ef0412b5519f5e851e6192430802e7). I see this instead:

![newsboat](https://user-images.githubusercontent.com/118875/85180471-3e620c00-b28c-11ea-9834-5d001dfe0d70.png)

But yeah, as mentioned on IRC, Newsboat doesn't support MIME types in `<content type="...">`, but [it should](https://tools.ietf.org/html/rfc4287#section-4.1.3.1).

An archive of the feed and the TXTs it links to, just in case: [1010-feed.tar.gz](https://github.com/newsboat/newsboat/files/4806758/1010-feed.tar.gz)

**Comment by Minoru** [comment]
Forgot to say: thank you for the report! I don't think I'll have time to dig into this on the weekend, but we'll see what I can do next week. It appears that all that needs to be done is to implement the steps outlined in the RFC.

**Comment by somasis** [comment]
I forgot to note, I had a filter stripping the <summary> tags from that feed, it will error if those are removed and newsboat tries to fetch the full content from the link! That's why you can't reproduce it. This is the filter I was using.

```sh
#!/bin/sh
# .local/lib/newsboat/filters/ignore-summary

temp=$(mktemp)
cat > "${temp}"

# if atom feed
if grep -q '<feed xmlns="http://www.w3.org/2005/Atom">' "${temp}"; then
    sed -E 's/<feed xmlns=.+>/<feed>/' "${temp}" \
        | xmlstarlet ed -d '//feed/entry/summary' \
        | sed -E 's|<feed>|<feed xmlns="http://www.w3.org/2005/Atom">|'
else
    xmlstarlet ed -d '//rss/channel/item/description' "${temp}"
fi

rm -f "${temp}"
```

And then in `urls`:

```text
filter:~/.local/lib/newsboat/filters/ignore-summary:https://text.causal.agency/feed.atom blog
```

**Comment by Minoru** [comment]
Ah, okay, so the problem is probably with `download-full-page`, then: it should examine `Content-Type` response header to figure out the format. I'm not sure if we have support for non-HTML content at all, though.

**Comment by Minoru** [comment]
Let this issue be about `<lilnk type="text/plain">`. The `download-full-page` problem should be discussed in #1022.

**Comment by Minoru** [comment]
Some relevant thoughts in https://github.com/newsboat/newsboat/pull/1224#discussion_r502544137.
