### ISSUE TITLE
Compile error while installing on gentoo

### ISSUE THREAD

**Issue by OnionMilk** [newsboat/newsboat#1014]
I was trying to install newsboat on gentoo, I got a compiler error. I'm not sure if this is because the version in the gentoo repos is old or some kind of dependency issue

When building the newest version from github I have no problems at all, so this might not be hugely important.

Steps to reproduce the issue:

Installing the package on Gentoo linux
(sudo emerge --ask newsboat)

The Output of the install command:
`$ sudo emerge --ask newsboat

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] net-news/newsboat-2.13

Would you like to merge these packages? [Yes/No] y

\>>> Verifying ebuild manifests

\>>> Emerging (1 of 1) net-news/newsboat-2.13::gentoo
 \* newsboat-2.13.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                                                                           [ ok ]
\>>> Unpacking source...
\>>> Unpacking newsboat-2.13.tar.xz to /var/tmp/portage/net-news/newsboat-2.13/work
\>>> Source unpacked in /var/tmp/portage/net-news/newsboat-2.13/work
\>>> Preparing source in /var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13 ...
 \* Applying newsboat-2.11-flags.patch ...                                                                                                                                                                     [ ok ]
\>>> Source prepared.
\>>> Configuring source in /var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13 ...
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... not found
Checking for package json-c... found
Checking for package ncursesw... found
curl was built with static libraries disabled
curl was built with static libraries disabled
\>>> Source configured.
\>>> Compiling source in /var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13 ...
make -j24 prefix=/usr CXX=x86_64-pc-linux-gnu-g++ AR=x86_64-pc-linux-gnu-ar RANLIB=x86_64-pc-linux-gnu-ranlib
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o doc/generate doc/generate.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o doc/generate2 doc/generate2.cpp
sed -E 's/^([^|]+)/[[\1]]<<\1,`\1`>>/' doc/configcommands.dsv > doc/configcommands-linked.dsv
sed -E 's/^([^|]+)/[[\1]]<<\1,`\1`>>/' doc/keycmds.dsv > doc/keycmds-linked.dsv
sed -E 's/^([^|]+)/[[\1]]<<\1,`\1`>>/' doc/podboat-cmds.dsv > doc/podboat-cmds-linked.dsv
mkdir -p doc/xhtml
./txt2h LICENSE > xlicense.h
a2x -f xhtml -D doc/xhtml doc/faq.txt
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/configcontainer.o -c src/configcontainer.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/configparser.o -c src/configparser.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/colormanager.o -c src/colormanager.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/keymap.o -c src/keymap.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/stflpp.o -c src/stflpp.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/logger.o -c src/logger.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/exception.o -c src/exception.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/utils.o -c src/utils.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/fslock.o -c src/fslock.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/matcher.o -c src/matcher.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/formatstring.o -c src/formatstring.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/strprintf.o -c src/strprintf.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o filter/Scanner.o -c filter/Scanner.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o filter/Parser.o -c filter/Parser.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o filter/FilterParser.o -c filter/FilterParser.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o newsboat.o -c newsboat.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/cache.o -c src/cache.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/htmlrenderer.o -c src/htmlrenderer.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/urlreader.o -c src/urlreader.cpp
./txt2h stfl/dialogs.stfl .stfl > stfl/dialogs.h
./txt2h stfl/feedlist.stfl .stfl > stfl/feedlist.h
./txt2h stfl/filebrowser.stfl .stfl > stfl/filebrowser.h
./txt2h stfl/help.stfl .stfl > stfl/help.h
./txt2h stfl/itemlist.stfl .stfl > stfl/itemlist.h
./txt2h stfl/itemview.stfl .stfl > stfl/itemview.h
./txt2h stfl/selecttag.stfl .stfl > stfl/selecttag.h
./txt2h stfl/urlview.stfl .stfl > stfl/urlview.h
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/controller.o -c src/controller.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/reloadthread.o -c src/reloadthread.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/tagsouppullparser.o -c src/tagsouppullparser.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/downloadthread.o -c src/downloadthread.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/rss.o -c src/rss.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/rss_parser.o -c src/rss_parser.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/formaction.o -c src/formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/list_formaction.o -c src/list_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/feedlist_formaction.o -c src/feedlist_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/itemlist_formaction.o -c src/itemlist_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/itemview_formaction.o -c src/itemview_formaction.cpp
chmod u+w doc/xhtml/docbook-xsl.css
echo "/* AsciiDoc's new tables have <p> inside <td> which wastes vertical space, so fix it */" >> doc/xhtml/docbook-xsl.css
echo "td > p { margin: 0; }" >> doc/xhtml/docbook-xsl.css
echo "td > p + p { margin-top: 0.5em; }" >> doc/xhtml/docbook-xsl.css
echo "td > pre { margin: 0; white-space: pre-wrap; }" >> doc/xhtml/docbook-xsl.css
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/help_formaction.o -c src/help_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/filebrowser_formaction.o -c src/filebrowser_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/urlview_formaction.o -c src/urlview_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/select_formaction.o -c src/select_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/history.o -c src/history.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/filtercontainer.o -c src/filtercontainer.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/listformatter.o -c src/listformatter.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/regexmanager.o -c src/regexmanager.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/dialogs_formaction.o -c src/dialogs_formaction.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/ttrss_api.o -c src/ttrss_api.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/ttrss_urlreader.o -c src/ttrss_urlreader.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/newsblur_api.o -c src/newsblur_api.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/newsblur_urlreader.o -c src/newsblur_urlreader.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/oldreader_urlreader.o -c src/oldreader_urlreader.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/oldreader_api.o -c src/oldreader_api.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/feedcontainer.o -c src/feedcontainer.cpp
src/newsblur_api.cpp: In function ‘bool newsboat::request_successfull(json_object*)’:
src/newsblur_api.cpp:168:63: error: ‘FALSE’ was not declared in this scope
  168 |  if (json_object_object_get_ex(payload, "result", &result) == FALSE) {
      |                                                               ^~~~~
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/feedhq_api.o -c src/feedhq_api.cpp
src/newsblur_api.cpp: In member function ‘rsspp::feed newsboat::newsblur_api::fetch_feed(const string&)’:
src/newsblur_api.cpp:243:46: error: ‘FALSE’ was not declared in this scope
  243 |        query_result, "stories", &stories) == FALSE) {
      |                                              ^~~~~
src/newsblur_api.cpp:272:44: error: ‘TRUE’ was not declared in this scope
  272 |         item_obj, "story_title", &node) == TRUE) {
      |                                            ^~~~
src/newsblur_api.cpp:277:46: error: ‘TRUE’ was not declared in this scope
  277 |         item_obj, "story_authors", &node) == TRUE) {
      |                                              ^~~~
src/newsblur_api.cpp:283:19: error: ‘TRUE’ was not declared in this scope
  283 |         &node) == TRUE) {
      |                   ^~~~
src/newsblur_api.cpp:288:46: error: ‘TRUE’ was not declared in this scope
  288 |         item_obj, "story_content", &node) == TRUE) {
      |                                              ^~~~
src/newsblur_api.cpp:295:5: error: ‘TRUE’ was not declared in this scope
  295 |     TRUE) {
      |     ^~~~
src/newsblur_api.cpp:302:44: error: ‘TRUE’ was not declared in this scope
  302 |         item_obj, "read_status", &node) == TRUE) {
      |                                            ^~~~
src/newsblur_api.cpp:313:43: error: ‘TRUE’ was not declared in this scope
  313 |         item_obj, "story_date", &node) == TRUE) {
      |                                           ^~~~
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/feedhq_urlreader.o -c src/feedhq_urlreader.cpp
x86_64-pc-linux-gnu-g++ -std=c++11 -Iinclude -Istfl -Ifilter -I. -Irss -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -march=native -O1 -o src/textformatter.o -c src/textformatter.cpp
src/newsblur_api.cpp: In function ‘bool newsboat::request_successfull(json_object*)’:
src/newsblur_api.cpp:167:15: warning: control reaches end of non-void function [-Wreturn-type]
  167 |  json_object* result{};
      |               ^~~~~~
make: *** [Makefile:114: src/newsblur_api.o] Error 1
make: *** Waiting for unfinished jobs....
 \* ERROR: net-news/newsboat-2.13::gentoo failed (compile phase):
 \*   emake failed
 \*
 \* If you need support, post the output of `emerge --info '=net-news/newsboat-2.13::gentoo'`,
 \* the complete build log and the output of `emerge -pqv '=net-news/newsboat-2.13::gentoo'`.
 \* The complete build log is located at '/var/tmp/portage/net-news/newsboat-2.13/temp/build.log'.
 \* The ebuild environment file is located at '/var/tmp/portage/net-news/newsboat-2.13/temp/environment'.
 \* Working directory: '/var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13'
 \* S: '/var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13'

\>>> Failed to emerge net-news/newsboat-2.13, Log file:

\>>>  '/var/tmp/portage/net-news/newsboat-2.13/temp/build.log'

 \* Messages for package net-news/newsboat-2.13:

 \* ERROR: net-news/newsboat-2.13::gentoo failed (compile phase):
 \*   emake failed
 \*
 \* If you need support, post the output of `emerge --info '=net-news/newsboat-2.13::gentoo'`,
 \* the complete build log and the output of `emerge -pqv '=net-news/newsboat-2.13::gentoo'`.
 \* The complete build log is located at '/var/tmp/portage/net-news/newsboat-2.13/temp/build.log'.
 \* The ebuild environment file is located at '/var/tmp/portage/net-news/newsboat-2.13/temp/environment'.
 \* Working directory: '/var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13'
 \* S: '/var/tmp/portage/net-news/newsboat-2.13/work/newsboat-2.13' `

ps. 
This is my first time filing an issue on github, if there is anything i can do better please let me know:)

**Comment by Minoru** [comment]
Hi! I suspect you're building with json-c 0.14. That version no longer declares `TRUE` and `FALSE`, hence the errors. We patched 2.20 for this (see https://github.com/newsboat/newsboat/pull/883), but earlier Newsboat versions will fail to build.

You can take the patch from #883 and apply it inside the ebuild. It looks like it already applies "newsboat-2.11-flags.patch", so you even have an example to follow.

Please let me know if that resolves it.

> This is my first time filing an issue on github, if there is anything i can do better please let me know:)

You did fine. Ignoring the issue template is generally frowned upon, but it was warranted in your case; good judgment! The only thing you could do better is put the listing inside triple backticks; that would make it display in a monospaced font, and GitHub won't turn parts of it into italics like it does right now.

Thank you for the report!

**Comment by Minoru** [comment]
@OnionMilk Did my comment resolve the problem?

**Comment by Minoru** [comment]
No response in two weeks, and I'm fairly certain that the failure is caused by an incompatible json-c version. Closing.

Please comment if applying the patch from #883 doesn't fix the problem.
