### ISSUE TITLE
youtube article does not load on mpv after update 2.20 - Error "usage: set <variable>[=<value>]"

### ISSUE THREAD

**Issue by colpshift** [newsboat/newsboat#1015]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

--- version start ---

ewsboat 2.20.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.20.0
System: Linux 5.7.4-arch1-1 (x86_64)
Compiler: g++ 10.1.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.70.0)
SQLite: 3.32.3 (compiled with 3.32.3)
libxml2: compiled with 2.9.10

--- version end ---

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# Feed settings
prepopulate-query-feeds yes
refresh-on-startup yes

browser "~/.scripts/newsboat-browser.sh" # surf urls
macro y set browser "mpv %u"; open-in-browser ; set browser "elinks %u" # youtube url

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread blue default
color listfocus_unread yellow default bold
color info red black bold
color article white default bold

highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default

```

Steps to reproduce the issue:

1. Open newsboat

2. Go to youtube article and open it

3. Press , + y to load article on mpv player.
.
**Other info you think is relevant**:
The error start after update 2.20.

**Comment by Liupold** [comment]
you need to add empty space between semicolon. (had same issue).
`macro y set browser "mpv %u" ; open-in-browser  ; set browser "elinks %u" # youtube url
`
see if this works.

**Comment by colpshift** [comment]
Perfect, works! Thanks for quick response.

**Comment by colpshift** [comment]
Quick response :-)

**Comment by Minoru** [comment]
This is a duplicate of #1013. (I'm making this comment just to inter-connect the duplicates of the same bug.)
