### ISSUE TITLE
Critical errors trying to create tables in db after fresh install

### ISSUE THREAD

**Issue by floehopper** [newsboat/newsboat#102]
**Newsboat version (copy from `newsboat -v`)**:

```
$ newsboat -v
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Darwin 16.7.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.54.0 SecureTransport zlib/1.2.8 (compiled with 7.51.0)
SQLite: 3.16.0 (compiled with 3.16.0)
libxml2: compiled with 2.9.4
```

Steps to reproduce the issue:

1. `brew install newsboat` on MacOS Sierra v10.12.6

2. Add a URL to the `.newsboat/urls` file

3. `newsboat -l 6 -d newsboat.log`

4. See the following critical error and other similar errors in log file:

```
[2018-01-20 15:24:06] CRITICAL: query "CREATE TABLE rss_feed (  rssurl VARCHAR(1024) PRIMARY KEY NOT NULL,  url VARCHAR(1024) NOT NULL,  title VARCHAR(1024) NOT NULL ); " failed: error = 1
```

**Comment by Minoru** [comment]
Hi! Did you already have ~/.newsboat/cache.db when you started Newsboat on step 3? If so, these errors are expected and are nothing to worry about—they mean your cache already has that table.

If you *didn't* have a cache file before, please post the whole newsboat.log.

**Comment by Minoru** [comment]
@floehopper, did I answer your question? Can this be closed now?

**Comment by floehopper** [comment]
@Minoru Hi. Sorry for the slow reply. Yes, I think there must have been a `~/.newsboat/cache.db` file from a previous start-up. I was having problems fetching a feed and I saw these errors in the log and jumped to the wrong conclusion. Sorry. I'm happy to close this now.
