### ISSUE TITLE
Newsboat doesn't properly render non-html articles downloaded by `download-full-page`

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1022]
(This is split out from #1010).

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.20-6-ge26e

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
download-full-page yes
```

Urls file:

```
file://test-feed.atom
```

Test feed in test-feed.atom file:

```
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>Test Feed</title>
    <link href="https://example.com/test.atom"/>
    <id>https://example.com/test.atom</id>
    <updated>2020-06-01T00:00:00Z</updated>

    <entry>
    <title>Test article</title>
    <link href="https://text.causal.agency/001-make.txt"/>
    <id>https://text.causal.agency/001-make.txt</id>
    <published>2020-06-01T00:00:00Z</published>
    <updated>2020-06-01T00:00:00Z</updated>
    </entry>
</feed>
```

Note that the `link` of the item points at a plain text document:

```
$ curl --head 'https://text.causal.agency/001-make.txt'
HTTP/1.1 200 OK
Server: nginx/1.16.1
Date: …
Content-Type: text/plain; charset=utf-8
Content-Length: 2650
Last-Modified: Sun, 31 May 2020 06:18:12 GMT
Connection: keep-alive
ETag: …
Strict-Transport-Security: max-age=31536000
Accept-Ranges: bytes
```

The document looks like a manpage:

```
$ curl --silent 'https://text.causal.agency/001-make.txt' | head
MAKE(7)            FreeBSD Miscellaneous Information Manual            MAKE(7)

NAME
     Using Make – writing less Makefile

DESCRIPTION
     Let's talk about make(1).  I think an important thing to know about
     make(1) is that you don't need to write a Makefile to use it.  There are
     default rules for C, C++ and probably Fortran.  To build foo from foo.c,
     just run:
```

Steps to reproduce the issue:

1. Start Newsboat, reload the feed, open its only article.

2. Observe that all the text is strung out into a single line like this:

    ```
    MAKE(7) FreeBSD Miscellaneous Information Manual MAKE(7) NAME Using Make – writing less Makefile …
    ```

**Comment by Minoru** [comment]
The high-level plan to fix this looks like this:

1. add a "content MIME type" field to `RssItem` and store it in `rss_item` table in the database;
2. amke `download-full-page` set the content MIME type from `Content-Type` HTTP header;
3. make `ItemViewFormAction` skip `HtmlRenderer` if the content is plain text—just output it as-is.

Interesting problem: should `text-width` apply to plain-text articles? In the example above, it shouldn't, since the text is pre-formatted. But there is no guarantee that the text follows any particular format. One possible solution is to implement #83 and let users specify per-feed `text-width`, enabling and disabling it as they wish. Any other ideas?

I'm not committing to working on this anytime soon, but I'm ready to discuss details with whoever wants to tackle this.

**Comment by der-lyse** [comment]
I reckon it should be customizable by feed, whether the text width should be applied or not–not only globally. This could also be implemented using our existing config file format like [`reset-unread-on-update`](https://newsboat.org/releases/2.20/docs/newsboat.html#reset-unread-on-update) already does today, if we don't want to wait on #82. It's not super convenient, but something like

```
apply-text-width yes "https://example.com/feed.atom" "https://foo.example.com/feed.rss"
apply-text-width no "https://bar.example.com/feed.atom"
```

might work. But I've no idea how hard this is to implement. And when moving to YAML or any other format, users must adapt this setting to the new format.

We could also implement different text widths for different feeds (however, I'm not sure whether this is even useful to people in the field) with something like this:

```
feed-text-width 80 "https://example.com/feed.atom" "https://foo.example.com/feed.rss"
feed-text-width 120 "https://bar.example.com/feed.atom"
```

I chose the name `feed-text-width` here to distinguish this setting from the already existing [`text-width`](https://newsboat.org/releases/2.20/docs/newsboat.html#text-width). Maybe the value of `-1` could be used to disable Newsboat's text wrapping altogether and show the article as defined by their authors (`0` is reserved for the the available terminal width already). Alternatively we could simply change the `text-width` setting to accept optional URLs.

I see another general problem with breaking text into multiple lines: Simply inserting newlines between words might render bullet points or indented fragments like quotes rather ugly:

```
This is some random text
breaking after 24 chars.

* this bullet point is
longer and when wrapping
does not line up with
the bullet point
* this really doesn't
look nice
```

To solve this we would rather need a text rendering engine, which is total overkill.
