### ISSUE TITLE
solved:Timeout was reached

### ISSUE THREAD

**Issue by n4avsl** [newsboat/newsboat#1023]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.20.0
System: Linux 5.7.4-arch1-1 (x86_64)
Compiler: g++ 10.1.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.70.0)
SQLite: 3.32.3 (compiled with 3.32.3)
libxml2: compiled with 2.9.10
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```
user-agent  "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.13; ko; rv:1.9.1b2) Gecko/20081201 Firefox/60.0"
use-proxy   yes
proxy-type  socks5
proxy   127.0.0.1:6666
color background          white   default
color listnormal          white   default
color listfocus           color36 black
color listnormal_unread   color133 default
color listfocus_unread    color36 black
color info                white  default  bold
color article             white   black
color end-of-text-marker    white black
browser "/usr/bin/firefox-developer-edition %u"
```
Related logs:
```
[2020-06-23 03:37:26] INFO: FeedListFormAction: reloading feed at position `39'
[2020-06-23 03:37:26] DEBUG: Reloader::reload: pos = 39 max = 0
[2020-06-23 03:37:26] DEBUG: Reloader::reload: created parser
[2020-06-23 03:37:26] DEBUG: RssParser::download_http: user-agent = Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.13; ko; rv:1.9.1b2) Gecko/20081201 Firefox/60.0
[2020-06-23 03:37:26] DEBUG: running query: SELECT lastmodified, etag FROM rss_feed WHERE rssurl = 'https://blog.torproject.org/rss.xml';
[2020-06-23 03:37:26] DEBUG: Cache::fetch_lastmodified: t = 0 etag = 
[2020-06-23 03:37:56] DEBUG: rsspp::Parser::parse_url: ret = 28 (Timeout was reached)
[2020-06-23 03:37:56] ERROR: rsspp::Parser::parse_url: curl_easy_perform returned err 28: Timeout was reached
[2020-06-23 03:37:56] USERERROR: Error while retrieving https://blog.torproject.org/rss.xml: Timeout was reached
[2020-06-23 03:38:10] INFO: ReloadThread: starting reload

```

Steps to reproduce the issue:

1. Only need to update these two urls: 
  - https://blog.torproject.org/rss.xml
  - https://intrusiontruth.wordpress.com/feed/

**Other info you think is relevant**:
Why does updating the following two fail (timeout)? I can open it normally in the browser,Other URLs are normal,my proxy is also working fine,I can't find the problem.

**Comment by Minoru** [comment]
I can't reproduce, which doesn't surprise me since I don't have your proxy. I only have one idea regarding how this issue can happen: since you're using `socks5` not `socks5h`, the domains are resolved to IPs that are very far from your proxy's exit point, thus leading to delays. But the default timeout in Newsboat is 30 seconds, which should be sufficient even for the slowest of connections.

My suggestions, in the order of decreasing priority:
1. change proxy type to `socks5h`, so DNS requests are proxied as well, and see if it helps;
2. bump [`download-timeout`](https://newsboat.org/releases/2.20/docs/newsboat.html#download-timeout);
3. try with an earlier Newsboat version to see if it's a regression.

Please report about the results.

**Comment by n4avsl** [comment]
> I can't reproduce, which doesn't surprise me since I don't have your proxy. I only have one idea regarding how this issue can happen: since you're using `socks5` not `socks5h`, the domains are resolved to IPs that are very far from your proxy's exit point, thus leading to delays. But the default timeout in Newsboat is 30 seconds, which should be sufficient even for the slowest of connections.
> 
> My suggestions, in the order of decreasing priority:
> 
>     1. change proxy type to `socks5h`, so DNS requests are proxied as well, and see if it helps;
> 
>     2. bump [`download-timeout`](https://newsboat.org/releases/2.20/docs/newsboat.html#download-timeout);
> 
>     3. try with an earlier Newsboat version to see if it's a regression.
> 
> 
> Please report about the results.

thank you very much! Now the problem is solved: just change the proxy-type from `socks5` to `socks5h`.
I get a timeout because curl does not proxy my DNS request, and the URL is polluted by DNS in my country.Everything works now.
