### ISSUE TITLE
toggleitemread-jump-to-next-unread does not work

### ISSUE THREAD

**Issue by jarbus** [newsboat/newsboat#1024]
newsboat 2.19.0
System: Linux 5.4.46-1-lts (x86_64)
Compiler: g++ 9.3.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.69.1)
SQLite: 3.32.2 (compiled with 3.31.1)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
toggleitemread-jumps-to-next-unread no
```

Steps to reproduce the issue:

1. Open Feed

2. Toggle Read Status

**Other info you think is relevant**:

**Comment by Minoru** [comment]
`toggle-article-read` (`N` key by default) automatically moves to the next item. If you're viewing a list of unread items, it might look like pressing `N` jumps to the next unread, but all it does is move one line down.

I'm not sure why it's done this way (is it just mimicking Mutt?), but I also don't see how it can inconvenience anyone. Can you explain how this behaviour makes your life harder, @jarbus?

(Pro tip: in bug reports, don't say "doesn't work" or "wrong" or "incorrect" or anything subjective like that. State what your expectations were and describe what you observed. That way other people can see the issue plainly, and don't have to wonder and guess like I did above.)

**Comment by jarbus** [comment]
Ah that would explain it, thank you, and apologies for the vague description. I was trying to move my cursor upwards to toggle a few read items as unread from bottom to top to remind myself to read them later, but every time I’d toggle, my cursor would move back down. It’s a very, very minor inconvenience to be sure, but I’ll live if it’s the intended functionality - I just assumed it was a bug worth reporting. Thank you for your hard work on newsboat!
