### ISSUE TITLE
Consider migrating to json.hpp library

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#103]
This is a continuation of https://github.com/akrennmair/newsbeuter/issues/279

Discussed this with @noctux on IRC today. He moved TT-RSS remote API implementation to this new JSON library and answered a few of my questions:
- porting the code from json-c is quite straightforward, but: 1) json.hpp won't implicitly convert things for us; 2) it throws exceptions;
- compilation times increased a bit: recompiling TT-RSS-related code takes 12 seconds instead of 8.

@noctux also noted that earlier version of json.hpp [failed a few parsing tests](http://seriot.ch/json/parsing.html#12), but we both don't consider this critical since we have some trust in producers of JSON that Newsboat consumes.

**Comment by noctux** [comment]
Something I realized while pushing to #120: As json.hpp is a header-only library, and the header might therefore be included in our repositry, we have to think about security how to keep the header up to date (preferably semi-automatically or monitored...)

**Comment by Minoru** [comment]
If I finally look into C++ package managers and pick one, we might use it to track that dependency. Until then, I'll just do what I'm already doing for Catch: add GitHub releases feed to my Newsboat and update the repo whenever a new release hits. Usually takes me no more than a week to react, should be fine.

**Comment by Minoru** [comment]
We're moving to Rust now (#89), so this refactoring no longer makes much sense.
