### ISSUE TITLE
newsboat failed to compile on macos

### ISSUE THREAD

**Issue by serprinss** [newsboat/newsboat#1034]
fails to compile with error:
```
./config.h:15:10: fatal error: 'libintl.h' file not found
```
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
commit c18dae93ee1ed681205c383d38081e55dab280f6 (HEAD -> master)
**Other info you think is relevant**:
macos version Mojave 10.14.5 (18F132)

**Comment by Minoru** [comment]
I think you're missing gettext.

Please install all the dependencies. The list is in the README and the HTML docs. .cirrus.yml has Homebrew commands that we use in CI.

**Comment by Minoru** [comment]
@serprinss Did that help at all? Did you manage to get it to compile?

**Comment by Minoru** [comment]
@serprinss, ping.

**Comment by Minoru** [comment]
No response from the reporter in a month, and I don't think it's a bug with Newsboat, so closing this. Please comment if the issue is still relevant—we can always re-open this.
