### ISSUE TITLE
export-to-opml creates invalid XML due to added echo message

### ISSUE THREAD

**Issue by rnkn** [newsboat/newsboat#104]
`newsboat --export-to-opml` echoes a line at beginning of the output...
~~~
Prepopulating query feeds...done.
~~~
...which invalidates XML output when redirected to a file, e.g. `newsboat -e > feeds.xml`

Not a big deal to delete it manually, but still.

**Newsboat version (copy from `newsboat -v`)**:
~~~
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Darwin 17.3.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0 (compiled with 7.54.0)
SQLite: 3.19.3 (compiled with 3.19.3)
libxml2: compiled with 2.9.4
~~~

Steps to reproduce the issue:

1. `newsboat -e > output.xml`
2. attempt to validate output.xml (e.g. in Emacs or importing to other feed reader

**Comment by Minoru** [comment]
JFTR: couldn't reproduce with an empty config, had to set "prepopulate-query-feeds" to "yes".

Thank you for the report! I've just pushed a fix.
