### ISSUE TITLE
Valid podcast downloads are dismissed because of MIME type

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#105]
Forwarded from the [debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888048)

> Hello,
>
> newsboat is a bit restrictive on podcast media types. This seems to come 
> from a commit[1] where only (some) audio types are accepted to choose 
> audio over jpeg[2] (and because newsboat can't handle more than one 
> media file per item?). However, this does dismiss other audio formats 
> like audio/aac and all of the video MIME types (video/mp4 in my case) 
> and overall looks like a lot of collateral damage.
> 
> Result: Nothing but the whitelisted media types can be downloaded with 
> newsboat/podboat.
> 
> I'm not sure adding more MIME types to the whitelist is the right thing 
> to do but might be at least a short term solution. Or just revert the 
> commit[1] and live with issue 604[2] for the moment? Eventually, support 
> for multiple media files per item seems like the right thing to do.
> 
> Thanks,
> Dirk
> 
> [1] https://github.com/newsboat/newsboat/commit/7901f2bc02556087dc01cde40f819c30881f63dc
> [2] https://github.com/akrennmair/newsbeuter/issues/604

**Comment by Minoru** [comment]
Thanks! I think I'm going to just extend the list, adding more containers (like MP4) and a few more audio formats (at least AAC); and will repeat the process until issues like that stop. Support for multiple enclosures would sure be nice, though.

**Comment by tsipinakis** [comment]
How about allowing `video/*` and `audio/*` and then selectively anything else that falls into these categories (like `application/ogg`)? Newsboat doesn't care about the format after all, all it does is download the file and lets the users player handle it.

**Comment by Minoru** [comment]
Right, that's even better! I'll change the code to use regexes sometime this week, on the weekend at worst. Thank you for the idea!
