### ISSUE TITLE
Compiling under Docker - cargo module and json are missing.

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#1064]
OS: Debian 10 buster

I downloaded the source code of the newsboat `newsboat-2.20.1.tar.xz` and the docker file `ubuntu_20.04-build-tools.dockerfile` then did the following commands:
```
# In the root of Newsboat's repository
tar xfv newsboat-2.20.1.tar.xz
cd newsboat-2.20.1/
mkdir docker
cd docker
wget https://raw.githubusercontent.com/newsboat/newsboat/master/docker/ubuntu_20.04-build-tools.dockerfile
cd ..
sudo docker build --tag=newsboat-build-tools --file=docker/ubuntu_20.04-build-tools.dockerfile docker
```
This went well. But the following not:
```
sudo docker run \
    --rm \
    --mount type=bind,source=$(pwd),target=/home/builder/src \
    --mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo \
    --user $(id -u):$(id -g) \
    newsboat-build-tools \
    make -j9
```
I got the error saying that cargo module is missing:
```
cargo build --package libnewsboat-ffi --verbose --release
make: cargo: Command not found
make: *** [Makefile:108: target/release/libnewsboat.a] Error 127
```
So I modified the docker file (added cargo in line 65) and rebuilded the docker image then ran compilation. Compilation went well

However only when I was packaging using AppImage then it complain about `json`:
```
-- Deploying executables -- 
Deploying executable newsboat 
WARNING: Could not find copyright files for file newsboat using dpkg-query 
Deploying dependencies for ELF file newsboat 
ERROR: Could not find dependency: libjson-c.so.4 
Failed to deploy executable: newsboat
```
Which json package should I add install to the docker image?

Could you also update the docker file? I can test it afterwards. :)

**Comment by ZaxonXP** [comment]
I also noticed from the build log that the following packages are missing:
```
Checking for package json... not found
/usr/bin/curl-config: 1: krb5-config: not found
```
Which packages are missing from the Ubuntu docker image?

**Comment by Minoru** [comment]
Cargo ought to be installed with Rustup [on line 87](https://github.com/newsboat/newsboat/blob/96a4f6d97917f63aafebbf27f95f07fbb23ddf38/docker/ubuntu_20.04-build-tools.dockerfile#L87). Let's check that:

```
$ docker run \
    --rm \
    --mount type=bind,source=$(pwd),target=/home/builder/src \
    --mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo \
    --user $(id -u):$(id -g) \
    --interactive --tty \ 
    newsboat-build-tools \
    bash
builder@caf6f44296c7:~/src$ whereis cargo
cargo: /home/builder/.cargo/bin/cargo
```

You should have the same path to `cargo` as shown above. Even if you remove the `--mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo`, it should be the same. If it's different, or there is no path, something's up with the image. I'm not sure how it can happen, though; my understanding is that it's either built correctly or it isn't, there's no "halfway built" state.

> However only when I was packaging using AppImage then it complain about json:

Are you running the AppImage command outside the container? That would explain why it can't find a library that's *inside* the container:

```
$ docker run \
    --rm \
    --mount type=bind,source=$(pwd),target=/home/builder/src \
    --mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo \
    --user $(id -u):$(id -g) \
    --interactive --tty \ 
    newsboat-build-tools \
    bash
builder@caf6f44296c7:~/src$ ls /usr/lib/x86_64-linux-gnu/libjson-c.so.4
/usr/lib/x86_64-linux-gnu/libjson-c.so.4
```

> Which packages are missing from the Ubuntu docker image?

None, everything's fine. json-c apparently has a couple different names, and we check all of them. We do the same for ncurses. krb5-config is just something that curl-config calls internally; it's Curl's business, and doesn't affect Newsboat.

**Comment by ZaxonXP** [comment]
So it looks like I need to modify the docker file to do all the operations inside the container and only then copy the AppImage package outside. Thanks for pointing that out.

**Comment by Minoru** [comment]
> So it looks like I need to modify the docker file to do all the operations inside the container and only then copy the AppImage package outside.

That's one approach, but I believe you should be able to use our Dockerfile without modifications, and run AppImage command with `docker run` (same as you ran `make -j9` inside the container on the files *outside* the container).

I'm still interested in figuring out what's going on with Cargo there, so let's reopen this. Have you tried to examine the container the way I showed, @ZaxonXP?

**Comment by ZaxonXP** [comment]
OK. I rebuilded the docker image with following commands:
```
mkdir docker
cd docker
wget https://raw.githubusercontent.com/newsboat/newsboat/master/docker/ubuntu_20.04-build-tools.dockerfile
cd ..
sudo docker build --tag=newsboat-build-tools --file=docker/ubuntu_20.04-build-tools.dockerfile docker
```
Then I checked with the following commands:
```
sudo docker run \
    --rm \
    --mount type=bind,source=$(pwd),target=/home/builder/src \
    --mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo \
    --user $(id -u):$(id -g) \
    --interactive --tty \
    newsboat-build-tools \
    bash
```
```
builder@4ab179f03b11:~/src$ whereis cargo
cargo:
builder@4ab179f03b11:~/src$ 
```
So in my case I do not have cargo installed, despite the fact that it downloads see the log 
[log_01.txt](https://github.com/newsboat/newsboat/files/4858835/log_01.txt)

**Comment by der-lyse** [comment]
I had the exact same problem a couple of days ago when I needed to rebuild the container (can't remember the reason). When building the Ubuntu 18.04 docker container `cargo` will now be installed into */home/builder/.rustup/toolchains/1.43.1-x86_64-unknown-linux-gnu/bin* for some reason. I don't know where it was located previously, but it was definitely somewhere in my `PATH`. I simply added this directory to my `PATH`:

    docker run \
        --rm \
        --mount type=bind,source=$(pwd),target=/home/builder/src \
        --mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo \
        --user $(id -u):$(id -g) \
        -e PATH=/home/builder/.rustup/toolchains/1.43.1-x86_64-unknown-linux-gnu/bin/:/home/builder/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin newsboat-build-tools \
        make -j9

**Comment by ZaxonXP** [comment]
@der-lyse: Indeed, also in my case the `cargo` end up in the same strange location. Thanks for the tip. :)

**Comment by Minoru** [comment]
@ZaxonXP, I created a Debian 10.4 VM and reproduced the problem there. I've no idea why it behaves like this :( I'm running Debian testing on my laptop, and it works fine there, as well as on CI. I'm investigating.

**Comment by Minoru** [comment]
Got it. `docker run --mount type=bind,source=$HOME/.cargo,target=/home/builder/.cargo …` does just what it says on the tin — it replaces ~/.cargo inside the container with the host's ~/.cargo. Since I happen to have rustup installed on the host as well, my host's ~/.cargo already contains all the binaries that rustup installs. These binaries are architecture-dependent, but since Docker runs on host's architecture, they work just fine inside the container.

On a fresh VM, I don't have rustup on the host, so I mount an *empty* ~/.cargo into the container. Naturally, it can no longer fine the binaries that should be there.

CI doesn't mount any of the host's directories into the container, so the image works fine there.

I'll change the mount option to be more specific. Its purpose is to share the cache with the host, so I'll replace it with two options that mount ~/.cargo/git and ~/.cargo/registry

**Comment by ZaxonXP** [comment]
So mystery solved. Good. :)
