### ISSUE TITLE
Feature request: put the generated manpages in the release tarball

### ISSUE THREAD

**Issue by q3cpma** [newsboat/newsboat#1068]
Hello,
would be nice to avoid installing a boatload of Ruby dependencies (including Ruby itself) just for that.

**Comment by Minoru** [comment]
Hi. Me and you already discussed this in https://github.com/newsboat/newsboat/pull/747, and my position hasn't changed since: tarballs should contain source code, not half-built artifacts.

**Comment by q3cpma** [comment]
Whoops, forgot this discussion had already taken place.

**Comment by q3cpma** [comment]
Maybe a way to download them on the website would do the trick?

**Comment by q3cpma** [comment]
Like a "download raw (ROFF)" button in the documentation section.

**Comment by Minoru** [comment]
Is that really easier than just installing Asciidoctor and running `make doc`?

**Comment by q3cpma** [comment]
It's probably not easier, but being on Gentoo, it means compiling all of these and bloating the system just for a one time manpage build.

But to be honest, I'm not lacking anything being "stuck" on 2.18, so no biggie.
