### ISSUE TITLE
Replace string constants with a proper enum in FilterParser

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1077]
#1076 adds three string constants to `FilterParser`: `EXPECTED_ATTRIBUTE_NAME`, `EXPECTED_OPERATORS`, and `EXPECTED_VALUE`. These are used to indicate what made the parser fail. We *had to* use strings because Nom 5 doesn't allow anything else for its `context` combinator.

Nom 6 relaxes the requirement (https://github.com/Geal/nom/issues/1131), so once that's released, we should migrate and replace our three strings with a proper `enum`.

**Comment by davbrito** [comment]
Hello @Minoru 
Assign this to me please.

**Comment by Minoru** [comment]
Wait, Nom 6 [is still in beta](https://crates.io/crates/nom). Are you sure this issue can be fixed yet, @davbrito?

**Comment by davbrito** [comment]
Oh. Sorry. I read wrong.

> Nom 6 relaxes the requirement ([Geal/nom#1131](https://github.com/Geal/nom/issues/1131)), so once that's released, we should migrate and replace our three strings with a proper `enum`.

Oh. Sorry. I read this wrong.

**Comment by Minoru** [comment]
No problem ;) Technically, you *could* implement this with Nom 6-beta, but you'd then have to rebase onto a current `master` once Nom 6 comes out, which might create Git conflicts for you to resolve. So I think it's better to just postpone this issue until Nom 6 is out.

**Comment by davbrito** [comment]
Ok. I think it's a good idea to wait.

**Comment by Minoru** [comment]
[Nom's author suggested an alternative approach](https://github.com/Geal/nom/issues/1197#issuecomment-715891128): create our own error type and write our own `context` combinator. I didn't look too deep into this, but apparently it'll require us to duplicate quite a bit of code, but that might just be a wrong impression. Further investigation required :)

I think it's fine to try this out against Nom 6 beta: by the time the prototype is ready, Nom 6 will probably be out. @davbrito, are you interested in this issue still?

**Comment by Minoru** [comment]
Hey @davbrito, Nom 6 just came out, and our code fails to build with it: https://github.com/newsboat/newsboat/pull/1260 Fixing that might be a good first step to learning about Nom 6 and how we use it. Would you like to work on that?

**Comment by davbrito** [comment]
@Minoru I can try it but I will take my time since I must understand a little more about your codebase and nom.

**Comment by Minoru** [comment]
We aren't in a particular hurry, so it's fine. Please ask questions, I'm happy to help (and to change code if something is done in a really obtuse and hard-to-grasp way).

**Comment by davbrito** [comment]
> We aren't in a particular hurry, so it's fine. Please ask questions, I'm happy to help (and to change code if something is done in a really obtuse and hard-to-grasp way).

Ok. So I'll do it. Thank you for the support.
