### ISSUE TITLE
What to do with "2-digits url shortcuts"?

### ISSUE THREAD

**Issue by aleprovencio** [newsboat/newsboat#108]
Hello,
when reading an article on newsboat it puts numbers in front of URL sources so if I press that number it will open that link. It goes well from 1 to 9, so what you do for 2-digits numbers ?

**Comment by aleprovencio** [comment]
@Minoru, thank YOU for the quick and useful replies :)

Using colon+number does work on feed list and article list as described on the docs, they even work while on "show-urls list". However, i couldn't make it work directly on the article view, which would be great since I wouldn't need to go to the "show-urls list" first and leaving the article page.

About the docs I really missed that info you provided. However, although it can be achieved with the cmdline command from lists like article, url or feeds, what I'm looking for is more like a "vim's normal mode command", from the article view.

**Comment by rnkn** [comment]
I'd also love to be able to open a double-digit URL from article-view this way.

Often an article might have many links, each with link text, but finding the corresponding URL can be rather difficult if the URLs are not descriptive, e.g. reddit posts.

**Comment by tsipinakis** [comment]
To open urls in article view you can use the `goto-url` operation by default bound to `#`.
Do `#21` for example to open URL 21.

**Comment by rnkn** [comment]
@tsipinakis thanks!

**Comment by aleprovencio** [comment]
@tsipinakis thats awesome, you got it

**Comment by Minoru** [comment]
Oh, that's embarrassing. Sorry I led you down the wrong path!

Re docs: I plan to add a sentence or two to the quickstart section, because it's the one that's most likely to be read in full by novices.

**Comment by Minoru** [comment]
Nothing wrong with you closing your own issue, but I'd prefer to keep it open as a reminder for me to update the docs ;)
