### ISSUE TITLE
can't use the feh macro from the docs

### ISSUE THREAD

**Issue by aleprovencio** [newsboat/newsboat#109]
Hello!

I'm using this setting ripped off the docs: ` macro i set browser "feh %u"; open-in-browser ; set browser "$BROWSER %u"`.
However nothing seems to happen when pressing `,i` from the "show urls list" (got there hitting `u` key). I have a macro with `mpv` working fine and `feh` also works fine outside newsboat.

Can you please help?

**Comment by Minoru** [comment]
Hi, thanks for filing the issue! Unfortunately, macros doesn't work in the URL view yet. We have an issue for that already—#23—so I'm going to close this one as a duplicate. Please click "Subscribe" in the other one to stay up to date with the progress!

**Comment by aleprovencio** [comment]
Alrighht thank you
