### ISSUE TITLE
UTF-8 (Polish) characters aren't correctly displayed.

### ISSUE THREAD

**Issue by samedamci** [newsboat/newsboat#1097]
Version(s): r2.19, r2.20, r2.20.1

Config file: default

Steps to reproduce the issue:
Add any feed with Polish characters and see question marks instead of Polish characters in title or content.

Example:
Correct: `chrząszcz`
Displayed: `chrz?szcz`

Example link to Polish feed: https://feeds.feedburner.com/sekurak

**Comment by dennisschagt** [comment]
Those characters seem to show up correctly for me in Newsboat:
![image](https://user-images.githubusercontent.com/4629607/87662926-4c0f9200-c763-11ea-9ce9-f1c3f5cd453b.png)

I think this might be an issue with your configured locale (just a guess).
Could you post the output of `locale` and `locale -a`?
