### ISSUE TITLE
Multiple newsbeuter references

### ISSUE THREAD

**Issue by khass1** [newsboat/newsboat#11]
**Newsboat version 2.10.1**:

The name "newsbeuter" appears on the main feed screen and on the gnome notifications when new feeds are added. Shouldn't the name newsboat be used instead?

**Comment by Minoru** [comment]
Hi, thanks for filing the issue! Can you please check if your config file includes `feedlist-title-format` and `notify-format` settings? I'm pretty sure they contain "Newsbeuter", because the defaults definitely use "Newsboat"—I just checked.

**Comment by khass1** [comment]
Hi,

You're right, my config has the newsbeuter word, it's like the one below:

notify-format "newsbeuter: %n unread articles within %f unread feeds"

You can probably close this issue, sorry for taking your time.

**Comment by Minoru** [comment]
No worries, thanks for taking the time to file an issue when you notice something's amiss ;)
