### ISSUE TITLE
Allow multiple keys to bind to the same operation.

### ISSUE THREAD

**Issue by uinput** [newsboat/newsboat#110]
Hello,

I stumbled across issue #36 when trying to find a way to use vim-like bindings for interface control. Obviously the library used in newsboat does not offer a simple way to implement half-page movement. Still, I'm looking for some solution as I keep pressing `Ctrl-D` and `Ctrl-U` in hope to move down a half page.

So I tried to use the following bindings to prevent newsboat from doing nothing at all when pressing according keys:
```
bind-key ^F pagedown
bind-key ^D pagedown
bind-key ^B pageup
bind-key ^U pageup
```

However, as I noticed, bindings will no longer be available as soon as another key is mapped to the same operation: `Ctrl-F` and `Ctrl-B` are not mapped as specified. Is there any way to make this work or do you have any idea for a workaround?

**Comment by Minoru** [comment]
Hmm, I don't know what's going on there. As far as I understand the `keymap` class, multiple binds should work just fine. I'll look deeper into this on the weekend. Thanks for opening the issue!

**Comment by Minoru** [comment]
Oh, thanks for picking this up, @kmws! I should really stop promising to do anything on weekends, it never ends well.

Up, Down, Page Up, Page Down, Home, and End are indeed special: they're handled directly by STFL. We have these parameters in STFL markup, e.g. https://github.com/newsboat/newsboat/blob/b6ba1181c700913ef119ffd52f49b38f177a9388/stfl/feedlist.stfl#L4-L9

and then we set `bind_home` etc. in https://github.com/newsboat/newsboat/blob/b6ba1181c700913ef119ffd52f49b38f177a9388/src/view.cpp#L127-L132

**Comment by dennisschagt** [comment]
> So, if the operation is `OP_SK_PGDOWN` (which is OP's operation of choice), the first key will become unbound. But this is done only for this range, so for example double-bind of `OP_QUIT` will work just fine.
> 
> `blame` for those two lines doesn't show clear reasoning either.

I expect this was done because `KeyMap::getkey()` only returns one key.
Allowing to bind multiple keys (without changing `KeyMap::getkey()`) would result in somewhat unpredictable behaviour.

> Up, Down, Page Up, Page Down, Home, and End are indeed special: they're handled directly by STFL.

This is true, but STFL does support binding multiple keys to the same operation.

I expect to have a PR with a fix ready soon.
