### ISSUE TITLE
[FeatureRequest] Implement a 'scrolloff' option

### ISSUE THREAD

**Issue by mrossinek** [newsboat/newsboat#1103]
I frequently have more unread entries in my feed, than fit on my screen. Thus, when going through them at some point I will end up with my cursorline stuck to the bottom of the list.

It would be nice, if an option in the style of Vim's [`scrolloff`](https://vimhelp.org/options.txt.html#%27scrolloff%27) could be implemented which would allow to specify an the
> Minimal number of screen lines to keep above and below the cursor.

By setting this option to a value other than 0 it, thus, allows to see further down the list in the scrolling position which prevents the user from (e.g.) scrolling too far down the list.

Care should be taken when the value of `scrolloff` is larger than half of the terminal height. This is commonly used to pin the cursorline to the center of the screen when neither the beginning nor end of the list is visible in the scrolled screen position.

**Comment by Minoru** [comment]
Thanks for filing this!

Linking previous Newsbeuter issue: https://github.com/akrennmair/newsbeuter/issues/191
