### ISSUE TITLE
Option to change color based on tags

### ISSUE THREAD

**Issue by johnlambrini** [newsboat/newsboat#1104]
It should be nice to have an option to set colors based on tags in feedlist.

**Comment by Minoru** [comment]
Can you please describe a use-case for this? How are tag selection and filters not enough to achieve the same goals?

**Comment by johnlambrini** [comment]
I usually put my favorites feeds on top of my list, the feeds hare all mixed together with various topics. I would like to define a color for a topic to know straight away the topic the feed belongs to. For example i have many youtube and other video subscription i would like to make them to a different color to make it clear its a video and so on for my other tags, i think would be nice also while scrolling through the feedlist.

**Comment by Minoru** [comment]
Can't you achieve this by putting a "label" of sorts into the title of the feed, then use `highlight` to give the label a colour? Is there some problems with this approach?

**Comment by johnlambrini** [comment]
Thanks that's exactly what i was looking for
