### ISSUE TITLE
Characters other than ASCII alpha-numerics replaced by underscores in file names when saving articles

### ISSUE THREAD

**Issue by crimsonskylark** [newsboat/newsboat#1110]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: newsboat 2.17.1 (but I also tested with 2e8c2aa58eacc669f50733d681bbf571be1f4ab5, which is the current `master`)

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload yes
show-read-articles no
show-read-feeds no
prepopulate-query-feeds no
feed-sort-order unreadarticlecount
show-keymap-hint yes
swap-title-and-hints no
text-width 72
save-path "~/Documents/archived-articles/rss"
confirm-exit yes
display-article-progress yes
browser firefox
macro a set browser "vidl %u &> /dev/null &"; open-in-browser ; set browser "firefox %u"
macro w set browser "mpv %u &> /dev/null &"; open-in-browser ; set browser "firefox %u"
macro s save-all
```

Steps to reproduce the issue:

1. Include a feed that posts content with the Cyrillic characters in the title ([like this (RSS feed)](https://habr.com/ru/rss/hub/system_programming/top/weekly/?fl=ru))

2. Select one of the items and press `s` to save, say, [this (image)](https://i.imgur.com/Fx97L40.png). Instead of getting the title in Cyrillic, all non-ASCII characters are ignored and instead you get [this (image)](https://i.imgur.com/OQwPz49.png)

3. Save the feed. For the aforementioned article, this is the file name I got: `________Android__iOS.txt`.

**Other info you think is relevant**:

From what I gather, this problem is caused by [view.cpp#286](https://github.com/newsboat/newsboat/blob/master/src/view.cpp#L286) because `isalnum` seems to ignore non ASCII characters.

**Comment by Minoru** [comment]
Reproduced with 2e8c2aa58eacc669f50733d681bbf571be1f4ab5 too. Thanks for the report, @crimsonskylark!

Unfortunately the commit that introduced `isalnum`, https://github.com/newsboat/newsboat/commit/f41adc224451a93688373ad4203882efb9c1b102, doesn't exactly say what problem it fixed; does macOS filesystem disallow anything other than NUL and slash? I'm inclined to just revert it, but then I'll have to find someone with macOS to verify that this didn't break anything. Alternatively, we can try `isalnum_l`, but I can't figure out if it's available on BSDs.

**Comment by crimsonskylark** [comment]
I also don't have access to a MacOS machine so I can't check it. Do you think this could be fixed by a macro to only build with this function in a MacOS environment?

**Comment by Minoru** [comment]
That's a viable workaround, but before doing this, I'd like to research what might've caused the bug that `isalnum` is supposed to fix.

**Comment by Minoru** [comment]
We have macOS workers in CI, so we can also perform experiments there, e.g. by adding a test.

**Comment by Minoru** [comment]
https://github.com/newsboat/newsboat/issues/1417#issuecomment-758150644 argues that this behaviour is correct, so I can no longer treat it as a bug. Instead, let's consider this a feature to be added: there should be a setting which, when enabled, restricts the filenames to alpha-numeric ASCII characters (that's the current behaviour, so this would be the default). When disabled, the filenames would contain whatever the original article contained.

When naming the setting, it'd be wise to look at the name chosen for a similar setting in Podboat: https://github.com/newsboat/newsboat/issues/1261

**Comment by crimsonskylark** [comment]
I can speak only for my case: I have feeds in Portuguese, French, Russian and English and the saving feature properly for the latter. Nevertheless, considering that it seems I was the first one to find/report this specific incompatibility, it would seem that my case is a very niche one and not really worth making significant changes to the software in order to accomodate. Worst case scenario I can just remove `isalnum` from my local copy and re-compile it, which is what I've done.

**Comment by aaronhatesregex** [comment]
> considering that it seems I was the first one to find/report this specific incompatibility

I had this issue when I started using newsboat a year ago, but back then when I search the issue tracker with keyword like "CJK" (but not "UTF-8" or "ASCII", which help me discover this issue today), the only issue came up was #334 which is about Rust port and irrelevant to my problem. Then I just forgot to report this :cry: .

> it would seem that my case is a very niche one

I do happen to know a few people having this issue including myself. For me, the issue is saving articles whose title contains CJK characters.

> not really worth making significant changes to the software in order to accomodate

Does it mean the code needs to be changed in a way that's not backward-compatible? I think the setting to unset the restriction of filenames to alpha-numeric ASCII characters does no harm to compatibility🤔.

**Comment by crimsonskylark** [comment]
>Does it mean the code needs to be changed in a way that's not backward-compatible? I think the setting to unset the restriction of filenames to alpha-numeric ASCII characters does no harm to compatibilitythinking

I'm not sure. I'm not very familiar with this code base, I just played around with it enough to track down the issue in the OP.

**Comment by Minoru** [comment]
The setting indeed won't harm compatibility: the current behaviour would be the default, and you folks would be able to change the setting to make Newsboat use all the original characters (in UTF-8).

**Comment by Minoru** [comment]
If anyone wants to work on this, the changes required to implement this feature are:

1. add a new setting to an array in src/configcontainer.cpp;
2. document that setting in doc/configcommands.dsv;
3. skip this loop if the setting is disabled: https://github.com/newsboat/newsboat/blob/c282d28504f47d8b2c92009285f5db2481545fcf/src/view.cpp#L289-L296
4. if you can, create test/view.cpp and write a test for both states of the setting;
5. submit a PR ^_^

**Comment by crimsonskylark** [comment]
Hi, some unfortunate things occupied my time but I hope to get around to this during the weekend and I'll PR the changes.
