### ISSUE TITLE
[Request] AppImage of latest version

### ISSUE THREAD

**Issue by mglh** [newsboat/newsboat#1116]
It would be nice to have an AppImage of the latest `newsboat` version available.

**Comment by Minoru** [comment]
Sorry, but no. Experience with Snap taught me that I'm not very keen on maintaining that sort of thing. Specifically, I don't want to be responsible for prompt updates when a library like Curl gets updated. Newsboat's snap uses strict confinement, so the security updates aren't as urgent there; as far as I understand, AppImage doesn't provide confinement/sandboxing by itself.

Software distribution can really benefit from centralizations, so please use your distro's packages/ports/derivations.
