### ISSUE TITLE
how to execute macro on a specific link ?

### ISSUE THREAD

**Issue by nsklaus** [newsboat/newsboat#1118]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.20.1
System: Linux 5.7.10-artix1-1 (x86_64)
Compiler: g++ 10.1.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.71.1)
SQLite: 3.32.3 (compiled with 3.32.3)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
#show-read-feeds no
#auto-reload yes
auto-reload no

external-url-viewer "urlscan -dc -r 'linkhandler {}'"

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key RIGHT open
bind-key LEFT quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete

color listnormal cyan default
color listfocus yellow default bold
color listnormal_unread blue default
color listfocus_unread yellow default bold
color info red default bold
color article white default bold

# color listnormal cyan default
# color listfocus black yellow standout bold
# color listnormal_unread blue default
# color listfocus_unread yellow default bold
# color info red black bold
# color article white default bold


browser linkhandler
macro , open-in-browser
macro t set browser "qndl" ; open-in-browser ; set browser linkhandler
macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best" ; open-in-browser ; set browser linkhandler
macro v set browser "setsid -f mpv" ; open-in-browser ; set browser linkhandler
macro w set browser "lynx" ; open-in-browser ; set browser linkhandler
macro p set browser "dmenuhandler" ; open-in-browser ; set browser linkhandler
macro c set browser "xsel -b <<<" ; open-in-browser ; set browser linkhandler
macro C set browser "youtube-viewer --comments=%u" ; open-in-browser ; set browser linkhandler
macro d set browser "curl -LO %u" ; open-in-browser ; set browser linkhandler


highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default
```

Steps to reproduce the issue:

1. select a news item with more than one link inside

2. try to execute macro on a specific link

3. only the first link is sent to the macro

**Other info you think is relevant**:
i have news items with few links inside.
one can lead to the web page about the podcast (1st link)
another link can lead to the actual podcast itself for direct download (2nd link)
yet another link can be a picture or whatever (3rd link)

i have defined a macro to have newsboat download through curl.
```
macro d set browser "curl -LO %u" ; open-in-browser ; set browser linkhandler
```
 but it is always the first link that is being sent to curl through the macro. what is the variable i could use to tell the macro i want   the 2nd or the 3rd link to be downloaded ?
i also tried to copy link to clipboard, and modified the macro to be: `curl -LO $(xclip -o -sel c)`
but newsboat didn't accept that. (although it works from command line).
where's the list of variable i need to be more specific about the items i want to get ? 
i tried to look at docs here: https://newsboat.org/releases/2.20.1/docs/newsboat.htm
but that wasn't clear to me. i could not find what i needed.
is it possible in newsboat to select a specific link to call a macro upon ?

idealy, when i'm listing all the link in a news item ("U"), if i could call the macro on the link that is currently selected that would be good.

**Comment by Minoru** [comment]
> idealy, when i'm listing all the link in a news item ("U"), if i could call the macro on the link that is currently selected that would be good.

This *is* how Newsboat works. Did you actually try this? What errors does Newsboat display? If it doesn't, what errors does Curl print out? (You'll have to quit Newsboat to see Curl's messages).

> i also tried to copy link to clipboard, and modified the macro to be: curl -LO $(xclip -o -sel c)
> but newsboat didn't accept that. (although it works from command line).

What do you mean by "didn't accept"? Can you quote error messages?

It might be lack of DISPLAY variable. `xclip` needs it in order to talk to the X server. Are you starting Newsboat from a terminal running under X? Are there any programs in between, like Tmux or Screen?

> but it is always the first link that is being sent to curl through the macro. what is the variable i could use to tell the macro i want the 2nd or the 3rd link to be downloaded ?

If you want a macro that always opens the second link, you can use `goto-url`:

```
macro d set browser "curl -LO %u" ; goto-url 2 ; set browser /usr/bin/firefox
```

You can use any other number, of course. The macro should be invoked from the item view, *not* the urls dialog. (Giving arguments to operations isn't actually documented, I have it written down somewhere to get around to do that...)

**Comment by nsklaus** [comment]
> > idealy, when i'm listing all the link in a news item ("U"), if i could call the macro on the link that is currently selected that would be good.
> 
> This _is_ how Newsboat works. Did you actually try this? What errors does Newsboat display? If it doesn't, what errors does Curl print out? (You'll have to quit Newsboat to see Curl's messages).

well, here, when i am on link list ("U") i cannot use macro at all. i tried like this: i highlight the link i want to work on (the 2nd link in the list) and i press `,d`  "comma" then "d". using macro like this in normal view works, but not on link list view. there is no error of any kind. just no response, no reaction. so from link list view the only way i found was to copy link to clipboard, then back on normal view i call macro that use clipboard.
curl with $(xclip -o -sel c) it works but with problem sometimes, i explain below.

> > i also tried to copy link to clipboard, and modified the macro to be: curl -LO $(xclip -o -sel c)
> > but newsboat didn't accept that. (although it works from command line).
> 
> What do you mean by "didn't accept"? Can you quote error messages?
> 
> It might be lack of DISPLAY variable. `xclip` needs it in order to talk to the X server. Are you starting Newsboat from a terminal running under X? Are there any programs in between, like Tmux or Screen?

curl complains the link is too long and it will not initiate the download:
```
Warning: r: File name too long
  0 20.8M    0   791    0     0    753      0  8:03:39  0:00:01  8:03:38  8505
curl: (23) Failure writing output to destination
```
using same link, wget doesn't complain about this, so i will try more with wget.
this is a problem with curl it seems not newsboat.
i thought that i had other kind of error previously but i cannot reproduce them at the moment so maybe i just did some mistake with curl options or something like that. sorry about that point.

> > but it is always the first link that is being sent to curl through the macro. what is the variable i could use to tell the macro i want the 2nd or the 3rd link to be downloaded ?
> 
> If you want a macro that always opens the second link, you can use `goto-url`:
> 
> ```
> macro d set browser "curl -LO %u" ; goto-url 2 ; set browser /usr/bin/firefox
> ```
> 
> You can use any other number, of course. The macro should be invoked from the item view, _not_ the urls dialog. (Giving arguments to operations isn't actually documented, I have it written down somewhere to get around to do that...)

goto-url 2 could be a workaround, i was after that kind of information. but it is a bit static. depending which rss feed i'm currently working with, i might be interested to download different link number, and while i can define 3 or 4 macros, each one to get a specfic link, it is not optimal. it would be better if i could tell newsboat which link number i want to work with, and from there have only one macro.

**Comment by Minoru** [comment]
Hi, sorry I'm slow to respond; I have a slightly hectic schedule at the moment.

> well, here, when i am on link list ("U") i cannot use macro at all.

My bad: I didn't read your config as attentively as I should have, and missed the fact that you're using an external url viewer. That explains it: since you're viewing URLs in `urlscan`, you are *outside* of Newsboat, so you can't use any of Newsboat features, including macros. I don't think this can be fixed.

> curl complains the link is too long and it will not initiate the download:

It says *file name* is too long. I'd replace that line with a script, and add some logging to figure out what exactly the script gets and why Curl complains like that.

> i thought that i had other kind of error previously but i cannot reproduce them at the moment so maybe i just did some mistake with curl options or something like that. sorry about that point.

No problem ;)

> is it possible to get the news item title to use in the macro as output filename ?
> […]
> also the file type is known apparently, i see: (type: audio/mpeg) if i could use that to make filename extension ? how to pass that kind of info to the macro definition ?

None of that is available from macros or anything else, it's just text in an item view :(

I get a feeling that all of this is really geared towards podcasts. Is it so? Have you tried [our podcast support](https://newsboat.org/releases/2.20.1/docs/newsboat.html#_podcast_support)?

**Comment by nsklaus** [comment]
> Hi, sorry I'm slow to respond; I have a slightly hectic schedule at the moment.

no problem, i'm not in a hurry. thank you for answering.

> My bad: I didn't read your config as attentively as I should have, and missed the fact that you're using an external url viewer. That explains it: since you're viewing URLs in `urlscan`, you are _outside_ of Newsboat, so you can't use any of Newsboat features, including macros. I don't think this can be fixed.

interesting, i will try without urlscan then.
i had just copied config that were available to me and started tweaking from there. i had just assumed this was how it was supposed to be.  

> > curl complains the link is too long and it will not initiate the download:
> 
> It says _file name_ is too long. I'd replace that line with a script, and add some logging to figure out what exactly the script gets and why Curl complains like that.

yes i dug a little bit more into this problem. as it turns out, the link itself is very long and doesn't directly point to the file. there's a hop involved. anyway curl and wget too, try use the link itself to make it the destination filename. so right now i'm forced to use a static destination filename such as:
`wget $(xclip -o -sel c) -O my_output` and i don't even get the file extension that way.
i'll have to make a script and get `file my_output` info, parse it and finally append it myself that way.  
what i wanted was, to confirm if there was any variables available that i could use to dynamically get the newsitem title from and use that in the macro. for example i see `%u` is available. i hoped there could be more, like a `%n` to get newsitem name or title so i could do: `wget $(xclip -o -sel c) -O %n` 
 

> > is it possible to get the news item title to use in the macro as output filename ?
> > […]
> > also the file type is known apparently, i see: (type: audio/mpeg) if i could use that to make filename extension ? how to pass that kind of info to the macro definition ?
> 
> None of that is available from macros or anything else, it's just text in an item view :(
i see .. well,  that answer my question above.


> I get a feeling that all of this is really geared towards podcasts. Is it so? Have you tried [our podcast support](https://newsboat.org/releases/2.20.1/docs/newsboat.html#_podcast_support)?

no it's more generic, i'm using newsboat to get quite a variety of different things.
from invidio.us / youtube new powsts in a given channel, 
also podcast, github commits, new articles on blogs, and so on.
and among all these, my news items from inside newsboat sometimes contain more than one link.
some contains many. and i wanted to know how to tell newsboat : " here, this macro i made, use it specificaly with This particular link, and ignore the rest" so depending the news item i'm reading it can be link number 2 or 4 or 6.. it may vary a lot. usualy what i want is to just download the file localy, and bypass as much as i can the big browsers such as firefox, chrome etc ...

**Comment by Minoru** [comment]
> and i wanted to know how to tell newsboat : " here, this macro i made, use it specificaly with This particular link, and ignore the rest"

Got it! I think the native URL view will provide that for you. If you want to stick with an external URL viewer, you'll have to script *that* to do what you want (e.g. look at the domain in the URL and call youtube-dl/curl/whatever).

It looks like this issue is kind of resolved now, but I'll wait for you to try using the internal URL view. Please tell me if it indeed resolves the problem!

**Comment by nsklaus** [comment]
what you're calling "internal / native url view" is the view one can get by pressing "U" key ?
once i'm there i can highlight a particular link but how do i act on it ? the only thing i could do is copy a given link to clipboard then back on normal view call a macro on that clipboard content.
that, or, still from url view "U", i can also call link-handler as you suggest but, in that case how do i do if the link doesn't provide an extension ? for example, here's my link-handler:

```
#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
	*mkv|*webm|*mp4|*youtube.com/watch*|*invidio.us/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
		setsid -f mpv -quiet "$1" >/dev/null 2>&1 ;;
	*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
	*mp3|*flac|*.ogg|*opus|*mp3?source*)
		# setsid -f tsp curl -LO "$1" >/dev/null 2>&1 ;;
		setsid -f curl -LO "$1" >/dev/null 2>&1 ;;
	*)
		if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR" "$1"
	else setsid -f "$BROWSER" "$1" >/dev/null 2>&1; fi ;;
esac
```

as you can see, it's based on file extension. but, if the link doesn't point directly on a file (making hops to the real file instead of pointing directly to it) and/or the url is too long that wouldn't work. here is below such an example with a link from one of my feed. it work using "U" -> copy link to clipboard, back to normal view, use macro on clipboard. 
```
macro d set browser "wget $(xclip -o -sel c) -O output.mp3" ; open-in-browser ; set browser linkhandler
```

and output of a transaction with that macro:
```
$ newsboat
Starting newsboat 2.20.1...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/klaus/.config/newsboat/urls...done.
Loading articles from cache...done.
--2020-08-05 14:07:57--  http://click.erfm.fr/click?d=LA_CHRONIQUE_JURIDIQUE_DE_DAMIEN_VIGUIER_N_4_EMISSION_DU_11_JUILLET_2020&t=La+chronique+juridique+de+Damien+Viguier+n%C2%B04+%E2%80%93+%C3%89mission+du+11+juillet+2020&rr
Resolving click.erfm.fr (click.erfm.fr)... 2606:4700:3036::681f:5fcf, 2606:4700:3035::681f:5ecf, 2606:4700:3034::ac43:ab5c, ...
Connecting to click.erfm.fr (click.erfm.fr)|2606:4700:3036::681f:5fcf|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://podcast.erfm.fr/LA_CHRONIQUE_JURIDIQUE_DE_DAMIEN_VIGUIER_N_4_EMISSION_DU_11_JUILLET_2020.mp3 [following]
--2020-08-05 14:07:58--  http://podcast.erfm.fr/LA_CHRONIQUE_JURIDIQUE_DE_DAMIEN_VIGUIER_N_4_EMISSION_DU_11_JUILLET_2020.mp3
Resolving podcast.erfm.fr (podcast.erfm.fr)... 2606:4700:3035::681f:5ecf, 2606:4700:3036::681f:5fcf, 2606:4700:3034::ac43:ab5c, ...
Reusing existing connection to [click.erfm.fr]:80.
HTTP request sent, awaiting response... 200 OK
Length: 7072220 (6,7M) [audio/mpeg]
Saving to: ‘output.mp3’
```
so it can workaround that way, using macro yes. but for link-hanler ? as you can see my link-handler could only work if it knows the filetype (by using file extension) but how could i proceed if link is too long, doesn't contain filename, or file extension, and require a hop ( resolving link, jumping, from link to link until it finaly reach the file itself) ? would that be a gray area where i have no other option but resort to the "clipboard + macro" workaround as shown above  ?

i understand it's not a problem about newsboat now. i will close this issue, but i just wanted to ask for your advice in such cases. if there's anything you could recommend. if you don't have time to reply to that, i'll understand, that's ok. i'll wait a bit and close the issue. many thanks for the help anyway.

**Comment by Minoru** [comment]
> what you're calling "internal / native url view" is the view one can get by pressing "U" key ?

Yep!

> as you can see my link-handler could only work if it knows the filetype (by using file extension) but how could i proceed if link is too long, doesn't contain filename, or file extension, and require a hop ( resolving link, jumping, from link to link until it finaly reach the file itself) ? would that be a gray area where i have no other option but resort to the "clipboard + macro" workaround as shown above ?

To be fair, Newsboat doesn't *always* know the filetype either. The filetype (a MIME type, to be precise) is only known for enclosures, e.g. podcasts and their "cover images"; even then, Newsboat relies on the feed not to lie about the type (i.e. Newsboat doesn't download the file to check it). All other links — the "Link:" header before the article and the links inside the article — don't have a MIME type associated with them. Newsboat only knows which tag was used, and classifies links into "images", "videos", and "links" that way. I'd argue it's not Newsboat's job to find out the MIME types for those links.

This means that the only info Newsboat can supply *reliably* is a URL. The rest has to be done by the link handler. The script you shown already uses a mixed approach: sometimes it uses filename extensions, other times it uses the domain name of the URL. You can also use `curl` to send a `HEAD` request, get `Content-Type` header of the response, and use it to decide on how to proceed. (`HEAD`, unlike `GET`, won't download the file; but `HEAD` might not be supported by some web servers.)

In any case, I don't think you have to resort to the "clipboard + macro" approach. It seems that you can either make the linkhandler "smart enough" to pick the correct tool, or create multiple macros and run them from the URL view.

And I'm fine with discussing these things here, even if it turns out that Newsboat can't really help. I never know what people need until they tell me, so — thanks for opening this issue! :+1:

**Comment by nsklaus** [comment]
i will look into it, and also without link-handler too.
many thanks for the suggestions and help.
