### ISSUE TITLE
Option to not double count articles because they're in query feeds

### ISSUE THREAD

**Issue by kevin-b-lockwood** [newsboat/newsboat#1120]
When I run `newsboat -x print-unread`, it counts all the new articles, and all the new articles in query feeds. The problem arises when I *exclusively* use query feeds, and the status bar script I wrote doesn't accurately portray how many new articles I have, because it counts articles more than once.

If there's a purpose to this, I would be glad to know, and perhaps there could be another command that only counts once.

**Comment by Minoru** [comment]
Reproduced with current HEAD, 62c9b2d2918709ffacf3b24617536b4961d2f63c. I think it's just omission; there is no reason to double-count the articles when calculating how many there are. Thanks for the report, @kevin-b-lockwood!

**Comment by Minoru** [comment]
@kevin-b-lockwood, I submitted a pull request that fixes this. Please check it out if you can compile from source: #1121 

I also discovered a workaround: if you set `prepopulate-query-feeds no` (which is the default), query feeds won't affect `-x print-unread` anymore (but you'll have to reload query feeds manually to populate them then).

**Comment by kevin-b-lockwood** [comment]
Wow, you're fast! I'll check it out if I get a chance. I do really like the prepopulation, but for the time being I may disable it until the fix is merged. Thanks a ton!

**Comment by Minoru** [comment]
I wish all bugs could be fixed as easily as this one. I spent more time refactoring tests than writing the fix :)

You can get *almost* the same experience as `prepopulate-query-feeds yes` if you enable auto-reload. That won't affect `-x print-unread`, but when you start Newsboat, it will immediately reload all feeds *and* update query feeds. There will be a small gap where query feeds appear to be empty, but that's as close as you can get to prepopulating without actually enabling it, I think.

**Comment by Minoru** [comment]
I replaced my initial PR with a new one, #1140, which is a bit more generic and fixes one other issue as well.
