### ISSUE TITLE
Make Inoreader 'sort by firsttag' useful 

### ISSUE THREAD

**Issue by JRuiBarros** [newsboat/newsboat#1128]
**newsboat 2.20.1**:

Hello everyone,

I've been pretty annoyed since I've started using Inoreader with this problem. When I wanted to sort my feed with the 'firsttag' option, I assumed it would sort it by folder name which would be pretty useful. Instead for some reason, it sorts the feed by title name, making it useless IMO since there is already an option for that.

So I started digging though the code, and I found out a solution for this. Looking at the following block of code:

https://github.com/newsboat/newsboat/blob/2e8c2aa58eacc669f50733d681bbf571be1f4ab5/src/inoreaderapi.cpp#L145-L163

We can see that the title is pushed to the tags list first than the folders names, making it the cause of the problem. If we moved the 'title tag' block after the 'for loop', then the 'firsttag' sorting option would sort the feed by folder names, making it in my opinion much more useful. I've already tried it locally an it works fine to me.

Please let me know what you all think of this.
Cheers!
José Rui

**Comment by Minoru** [comment]
Yup, sounds like a bug; tagging it as such. Thanks!

I'm not sure that changing the order is an appropriate fix, though. The same bug can probably be triggered by someone who keeps their feed URLs in ~/.newsboat/urls, or uses any other remote API. Instead, I suggest changing the sorting function, to make it skip the title tags until it finds a non-title tag. We even have tests for that (just `git grep firsttag -- test` to find it), so you can check that it doesn't break anything else :) And please amend the docs to mention this corner case. Would you be interested in submitting a PR for that, @JRuiBarros?

**Comment by JRuiBarros** [comment]
Hey @Minoru, I think I can tackle this so I'll submit a PR in the near future. Cheers!

**Comment by Minoru** [comment]
Cool!

I'm going offline for two weeks starting next Sunday, August 16th, so if you submit a PR in that timeframe, please don't get discouraged if I don't review it right away.

**Comment by JRuiBarros** [comment]
Hello @Minoru, 

I've been further checking the code base and wouldn't it be better if instead of changing the compare function on feedcontainer.cpp, to change the get_firsttag() method of the rssfeed class? The idea would be to have the method return the first non '~' and '!' tag, and in the case where only those types of tags exist to return an empty string. The get_tags() method already filters out these tags so why not this one as well? I've also found out that this method is also used in the format string system -> feedlist-format, but in that context does it makes sense to use the '~' and '!' tags? 

What are your thoughts on this? Thanks.

**Comment by Minoru** [comment]
Changing `RssFeed::get_firsttag()` is a great idea! Let's do that.

I think it should only exclude the '~' tags. though, because these are only used to rename feeds; they aren't displayed in the Tag Selection dialog, and one can't get to them via filter expressions. Hidden tags, on the other hand, *are* visible in the Tag Selection; they are not accessible from filter expressions, but I consider that a bug (#33). Hidden tags themselves are a bit of a problematic concept, but that's a separate issue (#500).
