### ISSUE TITLE
Syntax of Queue File for Podboat

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#1129]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
newsboat 2.20.1
System: Linux 5.4.0-42-generic (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 (compiled with 7.71.1)
SQLite: 3.32.3 (compiled with 3.32.3)
libxml2: compiled with 2.9.10
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload yes
download-path "/home/nikhil/Downloads"

browser google-chrome "$@" &
macro , open-in-browser

color listnormal green default
color listnormal_unread green default
color listfocus green default reverse
color listfocus_unread green default reverse
color info green default reverse
color background green default
color article green default
```
----

I want to listen to podcast: https://rss.art19.com/think-fast-talk-smart from the website: [Think Fast, Talk Smart: The Podcast](https://www.gsb.stanford.edu/insights/think-fast-talk-smart-podcast).

So I did

```bash
$ cat "${HOME}/.newsboat/GeneratedUrls/Podboat.gen.csv"
https://rss.art19.com/think-fast-talk-smart
```

```bash
$ podboat --queue-file=="${HOME}/.newsboat/GeneratedUrls/Podboat.gen.csv"
```

But I am not sure if the syntax of the queue file is correct or not. 

> Note: I am trying to use podboat independent of newsboat.

### Could you please tell me how can I do this?

**Comment by Minoru** [comment]
The queue file contains links to podcasts (the OGG/MP3/whatever files), their download destinations, plus a couple flags like "played". All the gory details can be found in [`QueueLoader::reload()`](https://github.com/newsboat/newsboat/blob/90a2de9693976ed3f248e49f0c6f5ac7b1b17966/src/queueloader.cpp#L31). The format is not documented anywhere; I certainly didn't expect anyone to use Podboat separately, and I guess the original author didn't either :)

The minimum queue file would look like this:

```
https://example.com/eposode-01.ogg "/home/minoru/Downloads/Episode 01.ogg"
```

Is that of any help?
