### ISSUE TITLE
How to cancel `save` article

### ISSUE THREAD

**Issue by brianbuccola** [newsboat/newsboat#113]
Here's an issue/question I've had since newsbeuter: if I accidentally hit `s` (save), how do I cancel and go back to the article list without saving the article? `^C` doesn't do anything. `^D` doesn't do anything. `^G` *does* get me back to the article list, but the article ends up getting saved anyway, once I press another key like `q`.

Steps to reproduce the issue:

1. Open `newsboat`, and go into a feed containing at least one article.
2. Press `s` (default: save).
3. Press `^G`, which brings you back to the article list.
4. Press `q`, which brings you back to the feed list *and saves the article*.

For now, I've done this, in order to stop accidentally saving articles:

```
unbind-key s
bind-key   S save
```

Newsboat version:

```
newsboat 2.10.2
System: Linux 4.15.1-2-ARCH (x86_64)
Compiler: g++ 7.2.1 20171215
ncurses: ncurses 6.0.20170902 (compiled with 6.0)
libcurl: libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.29.0 (compiled with 7.57.0)
SQLite: 3.22.0 (compiled with 3.21.0)
libxml2: compiled with 2.9.7
```

**Comment by brianbuccola** [comment]
I just figured out one way. From inside the save screen:

1. Press `^E` to go to the end of the line.
2. Hold `Backspace` until the file name string is empty (`^U` doesn't work).
3. Press `Enter`.
4. Then you'll see `Aborted saving.` at the bottom.

**Comment by Minoru** [comment]
Hi! You should be able to abort with Escape, see akrennmair/newsbeuter#252. (Not sure why I didn't add it to the changelog at the time).

**Comment by brianbuccola** [comment]
Ah, `Escape`. Should've been obvious, but at the same time, being a terminal application, my first thoughts were `^C` and `^G`, not `Escape`. Anyway, thanks!

**Comment by Minoru** [comment]
No, the behaviour of `^G` is wrong here. I've split that into a separate issue, #117, and will be closing this one now.
