### ISSUE TITLE
TT-RSS and The Old Reader at the same time?

### ISSUE THREAD

**Issue by Xtropy74** [newsboat/newsboat#1131]
Is it possible to run two different sources at the same time?

I have tried the following in my “config” file but none have worked:

urls-source "ttrss"; "oldreader"

urls-source "ttrss" "oldreader"

Separate lines for each, etc but I can only get one source to sync at a time

Thanks in advance for any help

**Comment by Minoru** [comment]
Hi! There can't be more than one urls-source at a time. Instead, create multiple configs, and run multiple instances of Newsboat:

```
$ newsboat --config-file=~/.newsboat/ttrss-config --cache-file=~/.newsboat/ttrss-cache.db --url-file=~/.newsboat/ttrss-urls
```

Note that you *must* use separate cache files, otherwise Newsboat will "forget" feeds and items.

Out of curiosity, why do you want to use multiple services at once?

**Comment by Xtropy74** [comment]
I am evaluating a self hosting solution instead of cloud based and wasn't ready to commit to it yet so thought I'd run them in parallel. Thanks for the info though, it answers my question.
