### ISSUE TITLE
Config for color of listfocus_unread has unwanted background color

### ISSUE THREAD

**Issue by oibind** [newsboat/newsboat#1142]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.20.1

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload yes
reload-time 20

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key l open
bind-key h quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key U show-urls

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread blue default
color listfocus_unread yellow default bold
color info red black bold
color article white default bold

browser linkhandler
macro , open-in-browser
macro c set browser "echo %u | xclip -selection clipboard" ; open-in-browser ; set browser linkhandler

```

Steps to reproduce the issue:

1. Open newsboat

2. Scroll to an unread article

Expected | Unexpected
--- | ---
![image](https://user-images.githubusercontent.com/25280584/90158380-d826d080-dd86-11ea-8ba4-183c28e817f4.png)  | ![image](https://user-images.githubusercontent.com/25280584/90158181-9433cb80-dd86-11ea-9c42-0fda9c3dc041.png)

**Comment by oibind** [comment]
I did an *oopsie doopsie* on my end.

**Comment by Minoru** [comment]
But wait, how did you fix it? Was the problem the "default background" in `listfocus_unread`? I'm happy you resolved this because I've no idea what's going on here ._.

**Comment by oibind** [comment]
@Minoru yes, it was with the `default` option set for `listfocus_unread`.

**Comment by Minoru** [comment]
Ah, okay. Thanks :)

**Comment by chinmaya1011** [comment]
Hi, I'm having this issue and I'm not sure how to solve it.

**Comment by Minoru** [comment]
@chinmaya1011 My understanding is that you have to explicitly define the background colour, i.e. instead of `color article blue default` you should use `color article blue black` (or whatever background colour you like).

**Comment by chinmaya1011** [comment]
```
color listnormal white black
color listfocus black white
color listnormal_unread cyan black bold
color listfocus_unread black cyan bold 
```
![image](https://user-images.githubusercontent.com/36993291/90187001-b7866700-ddd6-11ea-8c71-db052d93b0ab.png)

**Comment by Minoru** [comment]
Ah. The thing is, `listfocus_unread` is applied to the *text* on the unread item, not the whole line, so you have to use matching backgrounds:

```
listfocus black white
listfocus_unread black white bold
```

**Comment by NoSuck** [comment]
... so forget about using `reverse` to distinguish focus?  No way!  Padding with spaces is a more effective workaround in that case:

```
articlelist-format "%f%5i %D %t                                                                                                                                                                                                                                                                                                                                                                                            "
```
