### ISSUE TITLE
Is it possible to source/include multiple URL files from the urls configuration?

### ISSUE THREAD

**Issue by typkrft** [newsboat/newsboat#1144]
I see you can split up the configuration, but is this possible with the URLs? Essentially I would like to share my URLs publicly but there's a few I would like to hide.

**Comment by Minoru** [comment]
That's been on the to-consider list for a while: #118 It's clear that people want this feature, but I haven't gotten around to think how to best integrate it into the urls file, especially in light of #83 

I'm closing this in favour of #118.
