### ISSUE TITLE
Allow reloading feeds from the tag selection dialog

### ISSUE THREAD

**Issue by dashezup** [newsboat/newsboat#1145]
It seems newsboat could only reload currently selected feed or all feeds, I didn't find a way to reload some of feeds.

After added lots of feeds, it takes a while to reload all feeds, sometimes I only want to reload some feeds not all (such like rss of some github project release notes, youtube channels, blogs, or news).

Some ideas I thought of
1. Directory based `urls`, enable tree-alike view at main view when `urls` is a folder instead of file.
```
$ tree $HOME/.config/newsboat
/home/user/.config/newsboat
├── config
└── urls
    ├── blog
    ├── git
    ├── news
    ├── tech
    └── youtube

1 directory, 6 files
```
2. Tag based tree view, press T to switch to tree view of tags, something be like this
Press TAB on _All_ to to cycle from "expand all" and "tags list", move up/down to select tags and then TAB to collapse/expand feeds. While selected a tag, press "r" to reload all feeds under this tag.

(expand all)
```
All
├── blog
│   ├──  (1/10) alpha
│   └──  (0/10) beta
├── git
│   └── (10/10) Release notes from newsboat
└── youtube
    ├──  (0/10) bar
    └──  (0/10) foo
```
3. After t (select tag) - Enter - feeds list of a tag, Press `R` to reload all feeds under this tag not all feeds (in the other word, use ^R to reload all of currently listed feeds not all feeds).
This should require minimal modification to suit such needs but this is not as convenient as tree based view and feed reloading.

**Comment by Minoru** [comment]
Hi! Sorry for the delayed response; I was on a break.

I'm not too keen on your first idea, since it parallels a feature we already have—tags. Implementing both will create confusion and duplication.

Your third idea is actually what I'd suggest myself. As far as I understand, you find it less convenient because it requires more keystrokes? We could merge it with your second idea, then, and teach the tags dialog to reload all feeds under the currently selected tag:

1. open tags dialog
2. put a cursor on some tag
3. press `r` (or whatever key you configured) to reload all feeds under the currently highlighted tag.

How does that sound, @dashezup?

**Comment by dashezup** [comment]
I think tree based listing is more convenient because I won't need to enter - leave - re-enter to check between feeds in tags. Without wide range chages of UI, it's also more comfortable for eyes.

Regarding that you mentioned, it sounds good and enough for my needs. But after quit feeds list of a tag, I think it should back to tag dialog. Current it back to main UI.

Seems there are lack of keybings in tag dialog currently, J:next, K:prev and ?:Help does not work in tag dialog.

**Comment by Minoru** [comment]
> But after quit feeds list of a tag, I think it should back to tag dialog. Current it back to main UI.

Think of the tag selection dialog as a modal, like "Open file" or "Print" dialog in a GUI application. Modal dialogs don't exist by themselves, they only serve to affect some other part of the program. I realize it could've been done differently, but I think the effort to change this far outweighs the benefits.

> Seems there are lack of keybings in tag dialog currently, J:next, K:prev and ?:Help does not work in tag dialog.

J and K work for me. Are you sure you didn't re-bind those from their defaults? But yeah, that dialog doesn't support that many operations: https://github.com/newsboat/newsboat/blob/e2043498295355fc376ef47aeeac5ae170b36f20/src/selectformaction.cpp#L55-L145

**Comment by dashezup** [comment]
Sorry I just noticed I'm using an old version of newsboat (r2.19) those keybindings were not in that version. J/K should work in the latset version.

**Comment by g4570n** [comment]
Another approach could be to implement a tag like `"!"`, but that prevents that feed/URL from updating when we use `^R`, but it can update individually with `r` if we need it. 

It is an idea that I leave for consideration, I do not know if it is actually something viable.

**Comment by Minoru** [comment]
@g4570n, that only gives the user two "groups" of feeds, whereas the top post mentions four (but it's probably a good idea to support more than a user could possibly have, like a few thousand). Also, introducing new "special tags" is somewhat risky, since some poor soul might already be using the same tag for their workflow.

**Comment by g4570n** [comment]
Today reviewing the documentation I found an option in the **Configuration Commands** table, which I had overlooked, it is: `reload-only-visible-feeds`, if it is configured as `yes`, it only updates the feeds within a tag or filter that is visible, when we use `R` (reload-all)

This resolved the query I had made on the irc channel a few weeks ago :)

**Comment by dashezup** [comment]
@g4570n Thanks, I just tried `reload-only-visible-feeds`, so we just need to set this to `yes` and then list feeds under the tag, press `R` will only refresh feeds under this tag.

I think this issue can be closed now, `reload-only-visible-feeds` exactly solves the needs of reloading feeds under specific tag, extra implementation is not needed.
