### ISSUE TITLE
iframe URLs are not reflected on the article URL list 

### ISSUE THREAD

**Issue by smyru** [newsboat/newsboat#1153]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.20.1

Steps to reproduce the issue:
1. subscribe to https://tonsky.me/blog (URL: https://tonsky.me/blog/atom.xml)
2. fetch the feed
3. navigate to "Good times create weak men" article (URL: https://tonsky.me/blog/good-times-weak-men/)
4. locate Youtube movie link among the article URLs

**Other info you think is relevant**:
The article of the feed contains an iframe that places a Youtube video.

**Comment by Minoru** [comment]
Reproduced. Thanks for the report, @smyru, and sorry about the delayed response—I was on a break.
