### ISSUE TITLE
Possible to config newsboat to look at a web exposed directory and report changes

### ISSUE THREAD

**Issue by graysky2** [newsboat/newsboat#1157]
Is it possible to configure newsboat to look at a specific webpath and show the file listing as items?  As well, as new files are added, show them as new items?

For example: the kernel stable queue: https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-5.4

**Comment by Minoru** [comment]
Hi! Sorry for the delayed response, I was on a break.

You can implement this with a `filter:` in the urls file: write a program that reads HTML from stdin and prints out an RSS or Atom feed to stdout, and Newsboat would consume that feed and display it alongside other feeds you have. Does that answer the question, @graysky2?

**Comment by graysky2** [comment]
@Minoru - In principal, I understand.  Is there an example you can point me to illustrating the actual code needed?

**Comment by Minoru** [comment]
Newsboat copied that feature from Snownews, so you can look at [their examples](https://github.com/kouya/snownews/tree/master/contrib/filters) for inspiration. You then add something like `filter:~/.scripts/git2atom.sh:https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-5.4` to your urls file.

**Comment by graysky2** [comment]
@Minoru - I get it.  Thanks for tip.

**Comment by graysky2** [comment]
@Minoru - I hacked together a bash script that does this but I am getting 0/0 within newsboat.  What am I doing incorrectly?

Here is my html to rss script:

```
#!/bin/bash
#
# ~/.newsboat/stable-review.sh
# by graysky2

target="$1"
#target="https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/stable-review/"
mapfile -t items < <(lynx -dump -listonly "$target" | sed "s|.*$target||" | grep xz)

echo '<?xml version="1.0" encoding="UTF-8"?>'
echo '<rss version="2.0">'
echo 
echo '  <channel>'
echo '    <title>stable review</title>'
echo "    <link>$target</link>"
echo '    <description>Stable review patches</description>'

for i in "${items[@]}"; do
  echo "    <item>"
  echo "      <title>$i</title>"
  echo "      <link>$target$i</link>"
  echo "    </item>"
done
echo '  </channel>'
echo '</rss>'
```

I added the following to `~/.newsboat/urls`
```
filter:~/.newsboat/stable-review.sh:https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/stable-review/
```

Yet I get this within newsboat:
```
newsboat 2.20.1 - Your feeds (1 unread, 8 total)
   1         (0/0) stable review
...
```

**Comment by graysky2** [comment]
Here is my solution that might be helpful for others finding this.

My hacky script:
```
#!/bin/bash
# ~/.newsboat/stable-review.sh
# by graysky2 

tmpfile=/tmp/stable-review.txt
target="https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/stable-review/"
mapfile -t items < <(lynx -dump -listonly "$target" | sed "s|.*$target||" | grep xz)

cat <<EOF > "$tmpfile"
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
 
  <channel>
    <title>stable review</title>
    <link>$target</link>
    <description>Stable review patches</description>

EOF

for i in "${items[@]}"; do
	echo "    <item>" >> "$tmpfile"
	echo "      <title>$i</title>" >> "$tmpfile"
	echo "      <link>$target$i</link>" >> "$tmpfile"
	echo "    </item>" >> "$tmpfile"
done >> "$tmpfile"
echo '  </channel>' >> "$tmpfile"
echo '</rss>' >> "$tmpfile"

#redirect to stdin
cat <"$tmpfile"
rm -f "$tmpfile"
```

My entry in `~/.newsboat/urls`
```
filter:~/.newsboat/stable-review.sh:https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/stable-review
```

**Comment by graysky2** [comment]
Some examples based on this conversation: https://github.com/graysky2/newsboat_custom_stuff
