### ISSUE TITLE
Article is saved when save dialog is not in focus and `q` is pressed

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#117]
Extracted from #113.

**Newsboat version (copy from `newsboat -v`)**: 2.10.2

Steps to reproduce the issue:

1. Add a feed to the urls file, load the articles.

2. Enter the articlelist for that feed, press `s` to save the first article.

3. Press `^G` to switch from save dialog back to articlelist, then press `q`.

**Expected behaviour**: we get back to feedlist, articlelist is closed, save dialog stays open in background.

**Actual behaviour**: we get back to feedlist, articlelist is closed, save dialog stays open in background, *and the article is saved to the file*.

**Comment by dennisschagt** [comment]
While thinking about this issue, I came up with various solutions:
1. Make the save dialog actually modal, specifically:
    - Make it impossible to switch from an open save dialog to any other dialog (except by closing it altogether)
2. Cancel the save-dialog as soon as the user switches to a different dialog
3. Remove the special "modal" handling of the save dialogs. Instead, add callbacks (implementation provided by the initiating dialog) which the save dialogs can invoke when a filename is confirmed.
4. Pass all data (pairs of suggested filenames with their content) from the initiating dialog to the save dialogs. Let the save dialogs do the actual writing to file (instead of only selecting a filename). Then, the save dialogs can be handled like regular dialogs instead of modal dialogs.

My current idea is to remove the separate `run_modal()` event loop and implement something like option 3.

**Comment by Minoru** [comment]
Yeah, options 3 and 4 are better IMHO because the user can consult other dialogs before saving a file.

With option 3, how do you plan to ensure that the initiating dialog is not closed while the save dialog is still open? If this is not enforced, the callback might try to access deallocated memory (e.g.  `ItemListFormAction::save_file` requires access to `ItemListFormAction`'s `View` to display errors).

Option 4 doesn't have that weakness, but it also requires `{File,Dir}BrowserFormAction` to know how to save anything and everything — tight coupling, bad. So I think option 3 is the most promising.

**Comment by dennisschagt** [comment]
> With option 3, how do you plan to ensure that the initiating dialog is not closed while the save dialog is still open?

By capturing the shared pointer of the ItemListFormAction in the callback.
Getting a shared pointer to the FormAction (without ownership loops) can be done in two different ways:
- Let the `View` pass it into the `process_op()` function every time an event is handled
- Use `std::shared_from_this()`, mentioned here: https://devblogs.microsoft.com/oldnewthing/20190104-00/?p=100635 (doc: https://en.cppreference.com/w/cpp/memory/enable_shared_from_this/shared_from_this)

**Comment by Minoru** [comment]
Ah, so it *can* be closed, but we'll keep its memory around for as long as we need it. Makes sense.

Okay, another pitfall: if the save dialog is not modal anymore, the state of initiating dialog might change while the save dialog is running, and that can bork the callback. For example, the user could:

1. select an item in the itemlist and press `s`;
2. the save dialog opens;
3. user switches back to the itemlist and *moves the cursor to a different item*;
4. user switches back to the save dialog and presses `Enter` to save;
5. if we keep the current implementation of `save_article` call, this calls `save_article(filename, visible_items[itempos].first)` — saving the *current* item, not the one that was selected when the save dialog was started.

The solution, of course, is for the callback to capture all the state it needs, but that's a pretty fragile approach that rely completely on the discipline and attentiveness.

In that light, option 1 ("make dialogs actually modal") starts to look much better. Perhaps we should allow switching away from the save dialog, but deny everything else? But if the user switches away by accident, they might not know how to switch back, and if `?` is denied it'd be very confusing for them.

OTOH, "deny everything" can be a good first take. We can selectively allow things later.

Let me sleep on this.

**Comment by Minoru** [comment]
I think option 1 is really better. If anything, that's how people expect save dialogs to behave. I think it's fine if the initial implementation blocks `prev-dialog` and `next-dialog` ops, but we should be mindful of user experience. Ideally, users won't be able to bind those in save dialogs, but I don't think we have scaffolding for that. As a simpler measure, these ops can just display a message explaining why they don't work.
