### ISSUE TITLE
Nudge users towards enabling `cleanup-on-quit` or running `newsboat --cleanup`

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1184]
As discussed in #1181, our current default of `cleanup-on-quit yes` can lead to data loss. On the other hand, disabling the cleanup will lead to DB growth if the user constantly adds and removes feeds (which IMHO is a normal and expected situation, since interests change and people are constantly re-balancing their subscriptions lists to keep signal/noise ratio under control). We'll combat data loss by changing the default (#1183), and we'll combat the DB growth by raising the awareness.

Specifically, I suggest that upon quitting, Newsboat should:

* if `cleanup-on-quit` is enabled, do the cleanup;
* if `cleanup-on-quit` is disabled:
    1. count unreachable feeds and items;
    2. if any of the counts is non-zero, print out a message explaining that the user can remove them for good either by running `newsboat --cleanup`, or setting `cleanup-on-quit yes`.

Blocked on #1182.

**Comment by nick-cd** [comment]
Hey @Minoru! I was thinking about doing this one. I have a couple of questions:

Do you think it would make sense to implement this logic you're describing in `Cache::cleanup_cache()`?

Another thing, this patch would involve adding a new print statement, so would it make more sense to submit a PR after the release? I'd hate to add a new print statement after all the translators did all their work.

**Comment by Minoru** [comment]
> Do you think it would make sense to implement this logic you're describing in Cache::cleanup_cache()?

Sounds like a good starting point. Depending on how much code its ends up adding, it might make sense to move it into a separate method that gets called from `cleanup_cache()`.

> this patch would involve adding a new print statement, so would it make more sense to submit a PR after the release?

I think you can submit it right away, I just won't merge it until the release is out. Even if you already have all the code right now, the review will take a bit, and then it's just a few days until the release — I don't think that PR will sit in the queue for long ;)

Glad to see you around the project still, @nick-cd — if Internet is to be believed, contributors who come from HacktoberFest don't stick around for long. It's nice to see that it's not entirely true :)
