### ISSUE TITLE
Display the reason why the download failed

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1209]
(Split from #1208, particularly [this comment](https://github.com/newsboat/newsboat/issues/1208#issuecomment-702407004).)

If Podboat fails to write the file, e.g. because the filepath is too long, Podboat should display an error message explaining what went wrong.

**Comment by nick-cd** [comment]
Hey, I was thinking about this one. This one doesn't seem too difficult (I hope, lol).

Do you have a particular way you would want this implemented?

**Comment by Minoru** [comment]
Hey, cool! The message should be put into "msg" field of the dllist ­— see src/pbview.cpp. That field is displayed at the bottom of Podboat's window.

Other than that, I can't think of any other requirements.
