### ISSUE TITLE
Notify Snap users of confinement limitations

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#121]
Binaries in snaps can't "directly call" binaries from other snaps: https://forum.snapcraft.io/t/newsboat-browser-does-not-open/3991 This means that users effectively can't use anything but "xdg-open" as their "browser" (xdg-open is whitelisted, apparently).

What I think we should do about it:

1. Patch the snap to change default browser from lynx to xdg-open, so things that work out of the box.

2. Change our config-parsing code to emit warnings if user re-defines "browser", saying something like "You're running a Snap, confinement prevents you from using anything but xdg-open as your browser".

3. Emit the same warning whenever macro changes the browser setting.

4. (Later) Look into exact reasons behind the limitations, to see if we can somehow deal with it.

Minutes from IRC discussion:
- Lyse suggested adding a note to the FAQ; I disagree, because I think the FAQ shouldn't contain platform-specific things;
- noctux suggested adding a note to Snap description. I'm not sure that's an appropriate place for such notes.

**Comment by Minoru** [comment]
Here's an example of patching a Snap: https://github.com/snapcore/snapcraft/pull/1915/files

**Comment by taylorlee** [comment]
Thanks for publishing newsboat as a snap!
I'm super happy to have found this reader, and snaps are a pretty nice user experience compared to manually installing all the :)

Out of curiousity, is there a strong case for not defaulting to xdg-open over lynx?

**Comment by Minoru** [comment]
You're welcome! Many distributions provide Newsboat natively, and if you can, you'd be better off switching to that. Snap is still quite young and rough around the edges; for example, they don't provide a semi-automatic way to rebuild a snap if one of its dependencies gets updated. The only way to rebuild is to install Snap locally and compile new snaps for all the platforms. Yet they do provide auto-builders that build new snap (for all platforms) every time a new commit is pushed to our repository. Bewildering.

This is not a theoretical concern, either: curl got updated recently, but I haven't re-built the snap against that new version because I don't have the energy to set up a Snap build environment and go through the motions. Luckily there's a Newsboat release in a couple of weeks; everything will be rebuilt then.

> Out of curiousity, is there a strong case for not defaulting to xdg-open over lynx?

Backwards compatibility. Newsboat's predecessor, Newsbeuter, defaulted to `lynx`, so Newsboat does as well. If we change that to `xdg-open`, stuff might stop working for people who relied on the default.

The only reason I'm considering patching the Snap and changing the default there is because lynx newer worked there, so I'm positive I won't be breaking anyone's workflow.

**Comment by taylorlee** [comment]
Interesting about snap dependencies....

And yeah, I see newsboat in apt now that I look for it :upside_down_face: 
Would it be helpful if I update the README to mention alternate installs? (snap/apt/etc)

**Comment by Minoru** [comment]
Frankly, I'm not too keen on keeping such a list up-to-date, even though I see some other programs mention this in their docs.

Newsboat is pretty widespread, with packages in all major Linux distributions, a few BSDs, and Homebrew. I'm just assuming that if a person wants a *terminal* reader for *RSS* (both of which are pretty niche technologies nowadays), they're already trained to search their distro's repository first. That assumption was wrong in your case, but luckily it worked out because you wrote a comment here. So I can just keep pretending the assumption is true :)

**Comment by Minoru** [comment]
Let's consider this closed by #1470, and continue with patching in #1476.
