### ISSUE TITLE
Is it possible to export rss items to txt files?

### ISSUE THREAD

**Issue by bitcoinmeetups** [newsboat/newsboat#1210]
Is it possible to export rss items to txt files?

Yes or no?

**Comment by Minoru** [comment]
Yes, see [`save`](https://newsboat.org/releases/2.21/docs/newsboat.html#save) and [`save-all`](https://newsboat.org/releases/2.21/docs/newsboat.html#save-all) operations.

I believe this fully answers your question, so I'm closing the issue. If something is still unclear, please comment here; we can always re-open this.

**Comment by Minoru** [comment]
Ah, @ttldtor reminds me that Newsboat also have [a `save` command in the command line](https://newsboat.org/releases/2.21/docs/newsboat.html#cmd-save), so you can type `:save /path/to/file.txt` too.
