### ISSUE TITLE
Add setting to skip confirmation when marking all feeds read

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1214]
> @Minoru  I see that this feature has been added to the latest Newsboat 2.21. **But is is possible to set in the configuration file of Newsboat, whether the user wants this feature or not?** 
>
> For, some users (old) it might be useful to not to confirm as they have been using Newsboat for a long time, and they know important shortcuts. It was more frictionless for them, but now there is an additional step.

_Originally posted by @anishmittal2020 in https://github.com/newsboat/newsboat/issues/1006#issuecomment-703259122_

We can add a setting like the existing `confirm-exit`. I think it should default to `yes`, because we don't have a way to undo this action — better be safe than sorry.

**Comment by tarishij17** [comment]
can you plz telll where is this existing  "confirm-exit" setting, and where do we have to add the new one?

**Comment by Minoru** [comment]
Generally you could find answers to those by running `git grep confirm-exit`, and clicking through to the referenced issue #1006 and looking at the PR that fixed it (#1096).

So in this case, what has to be done is:

1. add an `if` in `case OP_MARKALLFEEDSREAD` in src/feedlistformaction.cpp. See src/view.cpp for how it's done for `confirm-exit`;
2. add an entry for the new setting in src/configcontainer.cpp (again, look for "confirm-exit" and do likewise);
3. document the new setting in doc/configcommands.dsv;
4. make a commit mentioning this issue and submit a PR :rocket:

**Comment by tarishij17** [comment]
thanks for the info. Plz assign this to me , I'd like to work on this

**Comment by Minoru** [comment]
Sure! Looking forward to your PR @tarishij17 ^_^

**Comment by tarishij17** [comment]
@Minoru any preferrable name of the new setting?

**Comment by tarishij17** [comment]
Plz review the PR and let me know for any updations : https://github.com/newsboat/newsboat/pull/1215

**Comment by Minoru** [comment]
Fixed by #1215.
