### ISSUE TITLE
Mention docs, IRC and mailing list in --help

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1233]
`cargo crev` nicely points people at the Matrix room and online docs:

```
$ cargo crev --help

... usage and help cut for brevity ...

Join Matrix channel for more help at https://matrix.to/#/!uBhYhtcoNlyEbzfYAW:matrix.org
Read user documentation at https://docs.rs/crate/cargo-crev
```

I like that, and would like Newsboat to do the same. To avoid taking up too much space, I think it should only mention our site, our IRC channel, and our mailing list.

This issue is a good place to start for someone who's only getting into hacking on Newsboat. I think you can find the places to update by grepping for "usage" ;) Feel free to ask questions here if you need any help!

**Comment by nick-cd** [comment]
May I do this? :)

**Comment by Minoru** [comment]
Sure! Assigning it to you.

**Comment by nick-cd** [comment]
Hey @Minoru, I referenced the issue to show what I was thinking before I open a PR. Is this ok?

**Comment by Minoru** [comment]
@nick-cd Looks good. Don't forget to update the other executable, Podboat, as well ;)

BTW, you can submit a so-called "draft PR" and make it ready for review whenever you want. PRs are preferred because the review tools there are much better than comments on individual commits.

**Comment by nick-cd** [comment]
> @nick-cd Looks good. Don't forget to update the other executable, Podboat, as well ;)

Oh lol, my bad.

> BTW, you can submit a so-called "draft PR" and make it ready for review whenever you want. PRs are preferred because the review tools there are much better than comments on individual commits.

Ah ok, thanks for letting me know :+1:
