### ISSUE TITLE
Constify ConfigActionHandler::dump_config

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1234]
(The method `ConfigActionHandler::dump_config`](https://github.com/newsboat/newsboat/blob/e4f28127f6126a82bc2bd5a3025c46858b4af9d1/include/configactionhandler.h#L15) writes the handler's configuration into a vector of strings. It's obvious that this method *shouldn't* modify its object, so we should mark it `const`. However, this requires updating all the implementers of this method, which is a bit of work.

It appears that this issue is mostly about replacing `std::map::operator[]` with `std::map::find()` (because the former doesn't work on `const` maps). Thus, this should be doable even for someone who has no idea about Newsboat's internals.

If you would like to work on this, please comment! And don't hesitate to ask questions if you get stuck.

**Comment by davbrito** [comment]
Assign this issue to me please.

**Comment by Minoru** [comment]
Sure. Thanks for taking a stab at this!

**Comment by Minoru** [comment]
@davbrito By the way, if you run into any trouble setting up a build environment for Newsboat, please comment here (or open new issues). I believe we have sufficient docs for that, but I'm not sure how many people are actually building Newsboat from scratch. It'd be nice to learn about all the bumps you run into (if any).
