### ISSUE TITLE
In docs, always capitalize "Newsboat" and "Podboat"

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1235]
Our docs currently use "newsboat" and "Newsboat" interchangeably. Ditto with "podboat" and "Podboat". I think this is wrong: lowercase names should denote commands, while capitalized versions should mean programs/products. We should go through the docs and adjust them accordingly.

Filing a whole issue for that because `sed -i 's/newsboat/Newsboat/'` is not sufficient :)

**Comment by panvicka** [comment]
Hello, 
can I work on this? Thanks :)

**Comment by Minoru** [comment]
Sure!

**Comment by Minoru** [comment]
#1236 uncovered a couple places where changing capitalization requires changing the code:
- https://github.com/newsboat/newsboat/pull/1236#discussion_r508785106
- https://github.com/newsboat/newsboat/pull/1236#discussion_r508788630
- https://github.com/newsboat/newsboat/pull/1236#discussion_r508789978

To fully fix this issue, these have to be updated as well.

**Comment by Minoru** [comment]
Unassigning @panvicka because they did their part, now we need to update the code to fix the remaining three places in the doc.
