### ISSUE TITLE
Show unread counter in tag view

### ISSUE THREAD

**Issue by mdosch** [newsboat/newsboat#1247]
First I want to thank you for this useful software. 👍 

Most of the time I navigate through the tag view `t` which shows me the tt-rss categories. But it looks like it is showing only the amount of feeds for each tag. I'd really appreciate if I'd see how many unread articles are there for each tag too.

If this can already be configured than I have to admit that I wasn't able to find it.

**Comment by dennisschagt** [comment]
This might be possible by configuring the `selecttag-format` option.
Its documentation suggests the following (example) configuration: `selecttag-format "[%2i] %T (%n unread articles in %f feeds, %u feeds total)"` where the `%n` identifier probably does what you want:
https://newsboat.org/releases/2.21/docs/newsboat.html#selecttag-format-n

**Comment by mdosch** [comment]
That's exactly what I want! Thank you. :)

**Comment by Minoru** [comment]
Since the question got answered, I'm going to close this. Thanks for handling this, @dennisschagt!
