### ISSUE TITLE
Support Gemini feeds

### ISSUE THREAD

**Issue by Seirdy** [newsboat/newsboat#1251]
It would be great if Newsboat could support `gemini://` feeds ([example](gemini://drewdevault.com/feed.xml)) without having to run something like a local gemini->http proxy. [More info about Gemini](https://gemini.circumlunar.space/)

**Comment by m040601** [comment]
+1 :+1:

**Comment by JJohnGreenSr** [comment]
+1 👍

**Comment by Minoru** [comment]
@Seirdy Thanks for the suggestion!

If anyone wants to work on this, the best way to implement it would be:

1. add a function somewhere in the rust/libnewsboat create that fetches a file from Gemini. It doesn't (probably even *shouldn't*) be async, as we don't have an async runtime yet, and I'm not ready to drag one into the project right now. It's fine, all our other fetchers are synchronous too.

    If curl already supports Gemini, that function can just call into curl;

2. call that function from `RssParser::retrieve_uri` (src/rssparser.cpp);

3. add a mention to the docs. The "Quick Start" section is probably a good place for this, but look around, perhaps there's other places that might benefit as well.

**Comment by Minoru** [comment]
@m040601, @JJohnGreenSr: GitHub supports [reactions](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments), which is a way to express your support without spamming all of the repo's watchers. Please use that in the future. Thanks.

**Comment by Minoru** [comment]
Out of curiosity I skimmed the spec. A couple things jumped out at me:

1. **there's no support for caching.** It's probably left out for simplicity, but I think that's a wrong balance for feeds: they can weigh hundreds of kilobytes and change less often than they're requested. Weird.

2. **self-signed certificates and TOFU** would require control over the TLS layer, which Newsboat defers to curl. Might be a bit tough to implement;

3. **client auth requires per-site certs**, which implies per-site settings, which aren't even fully designed yet: #83;

4. **Gemini defines its own formatting**, which would need a separate parser and renderer, plus some code to actually take the format into account (Newsboat currently stores that info but doesn't act on it, treating everything as HTML).

Sounds doable, but a bit broader than what i described in a previous comment.

**Comment by stevenmos** [comment]
@Minoru, a Gemini implementation, e.g. https://git.sr.ht/~sircmpwn/gmni, might go some way to addressing these concerns.

**Comment by Minoru** [comment]
@stevenmos Reading it made me realize that the TOFU problem is even harder than I thought, so thanks; I updated my above comment. Other than that, not sure which part of the code you wanted me to read.

**Comment by stevenmos** [comment]
It was meant in the vein of a general point of information.  Not knowing much at all about it, I rather naively saw ``CLI utility (like curl)'' and thought it might be a drop in replacement for curl for gemini.

**Comment by Seirdy** [comment]
While curl does not support Gemini, there exist other curl-like programs
that were made for gemini. gmni[0] and gurl[1] are two examples.

[0]: https://sr.ht/~sircmpwn/gmni/
[1]: https://github.com/MasterQ32/gurl/

On the Rust side, @Xe has put together maj[2].

[2]: https://tulpa.dev/cadey/maj

More software is listed at the Gemini project's Gemini space:
gemini://gemini.circumlunar.space/software/

Some example Gemini feeds:

Drew Devault's Gemini space: gemini://drewdevault.com/feed.xml
@Xe's Gemini space: gemini://cetacean.club/journal/atom.xml (seems to be
down)

An alternate solution would be to just use an existing Gemini-to-web
proxy to subscribe to Gemini feeds, like https://portal.mozz.us. Users
can also run a proxy on localhost.

**Comment by Xe** [comment]
It's back up. The lesson of the day is to not set up services with openrc

**Comment by Minoru** [comment]
After thinking about this for a bit more, I think the TOFU and client cert stuff will inevitably make it into the config and/or the TUI. Client certs can be universally useful (as HTTPS uses them too), but TOFU is a purely Gemini thing (unless we add fetching over SSH or something). Since there already exist Gemini<->HTTP proxies, and Newsboat has `exec:` for those who just need to fetch a single feed, I don't think it's warranted to add all of this into Newsboat.

Thus I'm closing this for now. Perhaps the world will change in a few years, and I'll re-consider this.
