### ISSUE TITLE
Filebrowser always starts in $HOME

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#126]
**Newsboat version (copy from `newsboat -v`)**: b66aa5d5

Steps to reproduce the issue:

1. Ensure there's at least one feed loaded in Newsboat.

2. `cd` somewhere other than the home directory.

3. Start Newsboat, open any article, press `s`.

**Actual behaviour**: file browser opens inside Newsboat, showing files and directories in user's home directory.

**Expected behaviour**: file browser shows files and dirs in *current* directory.

**Other info you think is relevant**: not sure if this is really a bug. On one hand, [the code uses `getcwd`](https://github.com/newsboat/newsboat/blob/b66aa5d5a493d38744607b054bbe8f3d2fac8255/src/filebrowser_formaction.cpp#L139), which indicates programmer's intent clearly enough. On the other hand, no user ever complained about that to me, and I'm not sure if I'd ever notice if I didn't read the code.

TODO:
- [x] check if we promise anything regarding this in docs
- [ ] check the history of this piece of code to see if there were any bugs related to it
- [ ] check Newsbeuter's bugtracker to see if there are any bugreports regarding this

**Comment by dennisschagt** [comment]
I think starting in the home directory is intended behavior.

The documentation mentions a setting called `save-path` with a default value of `~/`.
During [FileBrowser initialization](https://github.com/newsboat/newsboat/blob/73a12e1c05c5ffb661609df1d609a48c300b3d50/src/filebrowserformaction.cpp#L235-L244) the working directory is changed according to that config variable.
The `getcwd` call you mention is executed after the initial change of working directory.

**Comment by Minoru** [comment]
> The documentation mentions a setting called save-path with a default value of ~/.

Yeah, that settles it then. Thanks for investigating! Closing this as invalid.
