### ISSUE TITLE
Regression: External Newsreading services now require the urls file to exist and be readable

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#1273]
**Newsboat version**: 6247cea64e860f4a6d77f6f354e1b830440dc8df (current master)

Config file:
```
urls-source "ocnews"
ocnews-url "http://localhost"

ocnews-login <username>
ocnews-password <password>
```

Steps to reproduce the issue:

1. Configure an external newsreading service (e.g. Nextcloud with the provided config)

2. Start Newsboat without creating a `urls` file

3. Observe that Newsboat does not start, even though there are feeds configured in Nextcloud

**Other info you think is relevant**:
This is a regression caused by a PR I submitted (https://github.com/newsboat/newsboat/pull/1245) which introduced checking for errors when opening the `urls` file.
I tried to fix it (https://github.com/newsboat/newsboat/pull/1269) but now realize that I still missed some aspects.
I've added this to milestone 2.22 so this regression gets resolved before the next release (either with a fix or by reverting PRs https://github.com/newsboat/newsboat/pull/1245 and https://github.com/newsboat/newsboat/pull/1269).

**Comment by dennisschagt** [comment]
The UrlReaders for the external newsreading services currently error out when the generic UrlReader cannot open the `urls` file for reading:
https://github.com/newsboat/newsboat/blob/6247cea64e860f4a6d77f6f354e1b830440dc8df/src/ocnewsurlreader.cpp#L25-L28

Previously, before https://github.com/newsboat/newsboat/pull/1245, this was ignored and the external feeds were loaded as usual.
Now they return immediately, resulting in 0 feeds being loaded, which in turn leads to an error in the controller:
https://github.com/newsboat/newsboat/blob/6247cea64e860f4a6d77f6f354e1b830440dc8df/src/controller.cpp#L350-L393

I am thinking about just ignoring the return value of `ur.reload()` in the external UrlReaders (maybe adding it to the log).
If anyone has a better idea, just let me know.

**Comment by Minoru** [comment]
> I am thinking about just ignoring the return value of ur.reload() in the external UrlReaders (maybe adding it to the log).

I think that's the right thing to do. Logging it at `DEBUG` level seems fine; `USERERROR` is not appropriate since it's not really an error to *not* have a urls file.

Thanks for checking all those edge cases! That's what *I* should've done when reviewing #1245 :(
