### ISSUE TITLE
Breaking change in Nextcloud News 15.1.0

### ISSUE THREAD

**Issue by Grotax** [newsboat/newsboat#1277]
With news 15.1.0 we have a change in the feed attribute "folderId", if the feed is in the root folder the id will be "null" instead of 0.

See https://github.com/nextcloud/news/issues/939

Steps to reproduce the issue:

1. Install News 15.1.0-rc2

2. sync with client

3. 0 -> null

**Comment by dennisschagt** [comment]
I just verified that Newsboat works fine when retrieving/reloading feeds from News 15.1.0-rc2.

We use `json_object_get_int()` to get the value of folderId, which handles `null` as if it read `0`:
https://github.com/newsboat/newsboat/blob/28b1be4404a957318d84e6bf894ad29e7bbca4be/src/ocnewsapi.cpp#L126-L132

From https://json-c.github.io/json-c/json-c-0.10/doc/html/json__object_8h.html#ae6cab7d4c7c707b9053035a6405d3891:
> null is equivalent to 0 (no error values set)

**Comment by Minoru** [comment]
@Grotax, thanks for notifying us in advance! Looks like we're well prepared, so I'm closing this issue.

**Comment by Grotax** [comment]
Cool :)
