### ISSUE TITLE
Slow "Loading https://www.youtube.com/feeds/videos.xml?channel_id=..."

### ISSUE THREAD

**Issue by philiprhoades** [newsboat/newsboat#1282]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Fedora newsboat x86_64 2.16.1-2.module_f31+5225+6fde2dc4  

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser				google-chrome
datetime-format		"%F"
color				listfocus			white				blue	bold
color				listfocus_unread	white				blue	bold
color				info				white				blue	bold
highlight			feedlist			"https?://[^ ]+"	white	red bold
```

Steps to reproduce the issue:

1. Open newsboat

2. Use "r" to update a feed

**Other info you think is relevant**:

I have been using newsbeuter for a while and then suddenly refresh on some feeds became very slow.  After a bit of messing around trying to work out where the slowness was introduced, I tried using different readers but found newsboat convenient because it used my existing newsbeuter data but showed that the delay was with loading the feed . . 

Since I have the same problem with newsboat as I did with newsbeuter, I presume the problem is with youtube? - has Google somehow made some changes to drive users like me crazy?  Is there some sort of more debugging that I might do?

Thanks,
Phil.

**Comment by Minoru** [comment]
Hi! I don't have any YouTube feeds, so I don't have any first-hard experience there. I only got two ideas to check:

1. fetch the feed using something else, like curl or wget:

    ````
    $ time curl --user-agent 'newsboat/2.16.1-2.module_f31+5225+6fde2dc4' https://youtube.com/...
    ```

    Is this as slow as Newsboat?

2. if you remember which Newsbeuter version was fast, can you build it from source and check that it's *still* fast? If so, we can try to pinpoint a commit that made it slow.

**Comment by philiprhoades** [comment]
@Minoru ,

Thanks for responding!:

> 1. fetch the feed using something else, like curl or wget:
>    ```
>    $ time curl --user-agent 'newsboat/2.16.1-2.module_f31+5225+6fde2dc4' https://youtube.com/...
>    ```

newsboat time:  32s

curl time: 32s

>    Is this as slow as Newsboat?

Yes - which suggests the problem has nothing to do with newsbeuter / newsboat and has arisen in the last day on YouTube?

> 2. if you remember which Newsbeuter version was fast, can you build it from source and check that it's _still_ fast? If so, we can try to pinpoint a commit that made it slow.

There was no change to the version of newsbeuter from one day when it was working OK, to the next day, when many YT channel feeds were suddenly slow . . hmm, looks like I am stuck with a YT issue . .

**Comment by philiprhoades** [comment]
After having problems with many of the YT feeds yesterday, everything is fine and working properly again today! - after that bit of recommended diagnosis I suspected a YT problem (I did download speed tests on other stuff to check) and it looks like that is what it must have been . . 

Anyway, the upside from getting stuffed around a bit is that I found newsboat which seems to be a nicer update to newsbeuter . .

**Comment by Minoru** [comment]
Regarding the cache site: 23 megabytes is *nothing*. SQLite can handle gigabytes for sure. In fact, Newsboat's code gets slow way before SQLite becomes a bottleneck :)

And I'm sure glad you moved to Newsboat :) Fedora seem to keep Newsbeuter alive, rebuilding it for new releases and apparently applying some patches, but I believe it makes sense for everyone to move to a project that's still maintained upstream — i.e. Newsboat.

Anyway, since YouTube fixed their feeds, I'm closing this issue. Thanks for taking the time to open it — we have zero chance of fixing something we don't know is broken :)
