### ISSUE TITLE
Podboat won't start when run-on-startup is in config file

### ISSUE THREAD

**Issue by h88e22dgpeps56sg** [newsboat/newsboat#1288]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.21.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
run-on-startup next-unread; open
```

Steps to reproduce the issue:

1. have `run-on-startup` in config

2. run podboat

Error message:
```
Loading configuration...unknown command `run-on-startup'
```

**Expected behavior**
Easy fix: Ignore the setting.
IMHO better fix: Have two separate settings for newsboat and podboat.

**Comment by Minoru** [comment]
> IMHO better fix: Have two separate settings for newsboat and podboat.

I agree, but Podboat doesn't have nearly enough operations for this to be useful. So I'll just merge #1289 that implements the easy fix. Thanks for the report!

**Comment by h88e22dgpeps56sg** [comment]
Having a look at it again now, I totally agree with you. Thanks for the fast fix and thanks for this piece of software. :)
