### ISSUE TITLE
Scrolloff ignored when opening article list

### ISSUE THREAD

**Issue by h88e22dgpeps56sg** [newsboat/newsboat#1293]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.21.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```
scrolloff 10
```

Steps to reproduce the issue:

1. Go into feed list

2. Have lots of read articles above an unread article in one feed.

3. Open article list of this feed.

**Description:**
Newsboat will scroll down to the first unread article, but ignore the scrolloff so the selected article is the very last item in the list section.

**Expected behavior**:
Honor scrolloff option and automatically scroll down to the first unread article + *scrolloff* lines (and still select the first unread article of course).

**Comment by Minoru** [comment]
Thanks for the report, @h88e22dgpeps56sg! @dennisschagt just fixed this via #1294. You can build from Git, or just wait a month for Newsboat 2.22 to come out — it will include this fix.

**Comment by h88e22dgpeps56sg** [comment]
Thanks a lot. I really appreciate the lightning fast fixing of my two reported issues.
