### ISSUE TITLE
Browser returned error code 127

### ISSUE THREAD

**Issue by nadrad** [newsboat/newsboat#1295]
My newsboat installation was with apt, which is still version 2.13. To get a newer version, I just installed it using Snap, and now, I have version 2.21. 

I've added my old cache, config file, and URL list, and everything works fine, except that I can't execute anything: When I try to open something in the browser, or run a macro, it gives me the "returned error code 127". Can someone help me with this problem?

**Comment by Minoru** [comment]
Hi! That code is returned by the shell, and means "command not found". I think this is a manifestation of #121. You'll have to change the browser to `xdg-open`, and rewrite your macros to use that somehow, too. Please see #121 for details.

**Comment by nadrad** [comment]
Thanks for the help. 
It seems that I can't run my shell scripts in a setup like this, and since I'm not sophisticated enough to install from source, I'm going back to the old apt version :)

**Comment by user1180** [comment]
I am also having this issue, only not the Snap version.  Running version 2.22.1 from the the Manjaro repos.

**Comment by Minoru** [comment]
@user1180 Do you have a browser configured in ~/.newsboat/config or ~/.config/newsboat/config? If not, the default is `lynx`, see the documentation. Do you have that browser installed?

**Comment by user1180** [comment]
No. I do have lynx installed, but I was trying to get it to open in Brave. I am running a brand new Manjaro installation and Palemoon was the default browser that came with it. Newsboat did initially open with it by default, before I uninstalled it and attempted to configure Newsboat to open with Brave. That's when the trouble started happening.

**Comment by user1180** [comment]
I may have isolated the source of the problem. I run all my applications through a Firejail sandbox and if I run Newsboat independently, browser opens just fine. So I think Firejail is blocking the browser command for some reason.

**Comment by Minoru** [comment]
Ah, got it. Looks like you resolved this via https://github.com/netblue30/firejail/issues/3894; great!

**Comment by chandujr** [comment]
I created the file `~/.newsboat/config` and added the line `browser "firefox %u"` and now links are working.

**Comment by neverdimed** [comment]
version: 2.28. I have this 127 error code appearing but under different circumstances to those described above

i defined a macro to download videos using yt-dlp as he describes here: https://persrex.xyz/tech/rss.html. I have these lines in my config:

```
# externel browser
browser "xdg-open %u"
#map ,d to download video
macro d set browser "yt-dlp %u"; open-in-browser; set browser "xdg-open %u"

```

using 'o' to open in my browser worked no problem at all without the 3rd and 4th lines, but with these lines both o and ,d produce the comment "browser returned error code 127"

Im really hoping to use that guy's macro to download video. Any idea how i can fix this?

**Comment by pedrohgodoys** [comment]
> I created the file `~/.newsboat/config` and added the line `browser "firefox %u"` and now links are working.

I'm using Fedora 37, and it deas work here. Thank you a lot.

**Comment by momja** [comment]
For those who might encounter this issue on macOS, try using `browser "open %u"` Unlike linux, we're not given a nice firefox CLI. `open` will open the link in your default browser.
