### ISSUE TITLE
without a cookies-file newsblur does weird things

### ISSUE THREAD

**Issue by nielsk** [newsboat/newsboat#13]
**Newsboat version (copy from `newsboat -v`)**:
newsboat 2.10.1-r2.10.1-19-gbbfee
System: OpenBSD 6.2 (amd64)
Compiler: g++ 4.9.4
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.55.1 LibreSSL/2.6.1 zlib/1.2.3 nghttp2/1.26.0 (compiled with 7.55.1)
SQLite: 3.20.1 (compiled with 3.20.1)
libxml2: compiled with 2.9.5

Steps to reproduce the issue:

1. Add newsblur as a newssource
```
urls-source "newsblur"
newsblur-login "user"
newsblur-passwordeval "gpg2 -q --for-your-eyes-only --no-tty -d /home/user/.passwd/newsblur.passwd.gpg"

```

2. Add a cookies-cache that doesn't exist
`cookie-cache /home/user/.foobar/cookies.txt
`
3. start newsboat

**Other info you think is relevant
newsboat loads feeds from newsblur but not mine and shows tags that I do not have.

**Expected behavior
Do not start and complain about the non-existent cookies-cache

**Comment by Minoru** [comment]
Thank you for reporting this! I don't know why Newsblur API returns something when the cookie is garbage, but I've added a check on startup and Newsboat shouldn't start if cookie cache doesn't exist and can't be created.
