### ISSUE TITLE
"Error: feed contains no items!" displayed while valid feed contains items

### ISSUE THREAD

**Issue by tardypad** [newsboat/newsboat#131]
I have 2 Atom feeds which items are not displayed within newsboat:
- https://sanctum.geek.nz/arabesque/feed/atom
- https://junegunn.kr/atom.xml

"Error: feed contains no items!" is reported in the status bar

I've checked their validity against https://validator.w3.org/feed/ and they are both reported as valid there

**Newsboat version**: 2.10.2

**Comment by der-lyse** [comment]
This sounds like you didn't load the feeds. By default the key binding to manually fetch a feed is `r` or `R` to reload all feeds. You probably want to put (`refresh-on-startup yes`)[https://newsboat.org/releases/2.10.2/docs/newsboat.html#refresh-on-startup] in your _~/.newsboat/config_ to fetch the feeds automatically when newsboat starts. See also the (`auto-reload`)[https://newsboat.org/releases/2.10.2/docs/newsboat.html#auto-reload] and [`reload-time`](https://newsboat.org/releases/2.10.2/docs/newsboat.html#reload-time) settings.

**Comment by tardypad** [comment]
No I have many other feeds working in my config.
Only those 2 seem not to be parsed properly.
Whether on the startup refresh or via the fetch binding, the result is the same

Could you please add those in your config and test to check if you see their items?

**Comment by tardypad** [comment]
In case it matters, I'm using Arch now
I used to have Ubuntu and a previous version of then newbeuter, those feeds didn't work as well there.
One of those feed used to report a SSL issue, and the other nothing AFAIR.
I waited to report the issue because I hoped it would be different on Arch and a newer newsboat version

**Comment by Minoru** [comment]
Both feeds worked for me. Can you show your config? Can you also try with empty config and just these two feeds in your urls file (don't forget to backup your cache.db beforehands!)

**Comment by Minoru** [comment]
When you run Newsboat with just two feeds, start it like this:

```
$ newsboat --log-level=6 --log-file=newsboat.log
```

reload all feeds and immediately close Newsboat, then post the resulting newsboat.log. It will be a big file, but that's okay.

**Comment by tardypad** [comment]
Argh... nevermind I'm stupid...
I tested a bit more and I have a setting `keep-articles-days 30` indeed
Since those feeds only have old entries, it makes sense none were shown...
Sorry for the noise :/
I was so convinced something was wrong with them given that SSL error I used to have on my old system

However a small thing: if I remove that setting, the feed items still don't show up unless I remove `~/.local/share/newsboat` too.
Not sure if that's normal

**Comment by Minoru** [comment]
No problem, glad you resolved it so fast @tardypad!

> However a small thing: if I remove that setting, the feed items still don't show up unless I remove ~/.local/share/newsboat too.
> Not sure if that's normal

That's expected. Articles older than `keep-articles-days` got deleted, and they will stay deleted no matter how you change the settings. I've updated the docs to reflect that; hope it helps!

**Comment by tardypad** [comment]
Nice, at least something got a bit improved from my noise :stuck_out_tongue: 
Thanks for the help and the quick replies
