### ISSUE TITLE
Is it possible to automatically save all items from all feeds as text files using newsboat?

### ISSUE THREAD

**Issue by bitcoinmeetups** [newsboat/newsboat#1322]
Hi,

This is BM.

Is it possible to automatically save all items from all feeds as text files using newsboat?

This would be a very useful feature.

**Comment by Minoru** [comment]
Hi! Can you describe the end goal? Is this some sort of export, or backup, or what?

**Comment by bitcoinmeetups** [comment]
Use cases:

Notification systems
Reports
Convenient sharing
Other

I have been into RSS for a long time. This would be a killer feature.

**Comment by Minoru** [comment]
No, I mean you specifically: what do you intend to do with this feature? Can you explain in terms like "I'm using <Newsboat's feature X> but it has \<limitation> so I'd like to be able to save all articles of all feeds"?

**Comment by Minoru** [comment]
@bitcoinmeetups, ping?

**Comment by bitcoinmeetups** [comment]
> No, I mean you specifically: what do you intend to do with this feature? Can you explain in terms like "I'm using <Newsboat's feature X> but it has <limitation> so I'd like to be able to save all articles of all feeds"?

Hi,

Here is a concrete example.

Reddit is great. But it has a problem. E-mail notifications don't work properly. I never get an e-mail notification when I get an inbox message, even though it's turned on in the settings.

Workaround using Newsboat:

The Reddit inbox has a notifications feed in RSS format.

If I could get Newsboat to automatically check that feed every x minutes/hour and download all feed items to a folder as text files on my personal device then I could manually make a script that notifies me each time it happens.

Here's another example. I use the Feedly newsreader app on Android. But rarely. It's not customizable enough. And again I'm not getting notifications.

I really want my RSS items as text files in a folder. I want this badly. I want this for many information based updates system that I use on a daily basis.

I hope this clarifies why I want this feature better. I am very interested in RSS technology and have been so for many years. Newsboat could fit my puzzle perfectly as I love working with CLI's rather than GUI's in my data flows.

**Comment by Minoru** [comment]
Yep, that's much clearer, thank you! Unfortunately, I think this kind of automation is out of scope for Newsboat, which is a rather human-driven program. I think you should take a look at [rsstail](https://www.vanheusden.com/rsstail/) instead, or at one of the myriad RSS/Atom libraries that exist for every programming language out there. They'll serve your needs much better than Newsboat could.
