### ISSUE TITLE
Automatically jump to the bottom of article list when opening feed.

### ISSUE THREAD

**Issue by zengbs** [newsboat/newsboat#1334]
Dear developers,

Is it possible to automatically move the cursor to the bottom of article-list when opening a feed? Because the latest article is exactly at the bottom of article-list (i.e. `article-sort-order date-desc` in config file).

Best,
Thanks.

**Comment by Minoru** [comment]
Hi! It's not currently possible, and I don't quite see why you'd even want this. Why not set the order to `date-asc`? Presumably you want to read other articles to, and scanning the list from the bottom up is less natural than going from top down (or is it only so in my culture?) Can you provide a bit more explanation of how this setup is useful?

**Comment by zengbs** [comment]
Dear @Minoru,

Since the article list following `date-desc` is the same as the text flow in terminal on Linux. 
i.e.
```
user@machine:~$ the_old_command
user@machine:~$ the_mid_command
user@machine:~$ the_latest_command
```
If newsboat can do this, then Linux users won't need to spend some time adapting to switch between terminal (bottom-up text flow) and the article list in the newsboat (top-down text flow).

Best,

**Comment by Minoru** [comment]
Sorry, but I don't find this argument convincing at all. Terminal users already spend time adapting when they read the *output* of those commands. They also adapt every time they launch Vim (which displays the first line of the file at the top, not at the bottom) and when they read articles in Newsboat (which too start at the top). Ditto with numerous other applications: pagers, TaskWarrior, Mutt are among those that come to mind.

This feels like a very specific workflow that only you have, so I don't think it's a good idea to add this to Newsboat as a configurable option. I suggest you just press `End` after you've entered the feed (you can remap it to some other key, of course). Once #1165 is implemented, you'll be able to automate that by adding `bind o in feedlist open; end` to your config (the syntax might change by then, but the idea would still hold).

Sorry this isn't the exact response you probably hoped for :broken_heart:

**Comment by zengbs** [comment]
Actually, #1165 is the exact solution I am looking for! Thanks!

**Comment by Minoru** [comment]
Oh, cool! I feel less cruel now :)
