### ISSUE TITLE
mpv --autofit Syntax Help.

### ISSUE THREAD

**Issue by annata83** [newsboat/newsboat#1337]
This is what I am currently using:

`macro y set browser "mpv %u" ; open-in-browser ; set browser "w3m %u"`
 
Wich streams in 1080.

I would like an option to stream in 480 to use When I am on the go like so:

`macro t set browser "mpv --autofit 640x480 %u" ; open-in-browser ; set browser "w3m %u"`

But I dont know how to use the correct syntax.

**Comment by Minoru** [comment]
Hi!

> `macro y set browser "'mpv %u" ; open-in-browser ; set browser "w3m %u"`

This has a single quote in `set browser "'mpv %u"`, are you sure this macro even works?

> `macro t set browser "mpv --autofit 640x480 %u" ; open-in-browser ; set browser "w3m %u"`

This looks correct both from Newsboat's and MPV's point of view (if I'm reading MPV's manpage correctly). Is Newsboat giving you any errors?

**Comment by annata83** [comment]
> Hi!

_Hi and thanks for responding,_


> 
> > `macro y set browser "'mpv %u" ; open-in-browser ; set browser "w3m %u"`
> 
> This has a single quote in `set browser "'mpv %u"`, are you sure this macro even works?

_You are right, I miss type that one. I edit the original question._


> 
> > `macro t set browser "mpv --autofit 640x480 %u" ; open-in-browser ; set browser "w3m %u"`
> 
> This looks correct both from Newsboat's and MPV's point of view (if I'm reading MPV's manpage correctly). Is Newsboat giving you any errors?


_Yes; here:_ 
`Error parsing commandline option autofit: option requires parameter`

**Comment by Minoru** [comment]
I think you need an equals sign between the option and the value: --autofit=640x480. Try it in the terminal, and once you got it working, copy it into the Newsboat's config.

**Comment by Minoru** [comment]
Hey @annata83, did you have any luck with `--autofit=640x480`?

**Comment by annata83** [comment]
> Hey @annata83, did you have any luck with `--autofit=640x480`?

yes it work, Meaning it plays the link given But, still stream in high quality:

`(+) Video --vid=1 (*) (vp9 1280x720 25.000fps)`

**Comment by dennisschagt** [comment]
It is indeed best to try the command in the terminal first.

---

I believe mpv uses youtube-dl for streaming videos from many sites.
You could try to use mpv's `--ytdl-format` flag with the videos you want to watch, e.g.:
`mpv --ytdl-format='bestvideo[height<=?480]+bestaudio/best' https://www.youtube.com/watch?v=ap-BkkrRg-o`

If that works correctly with the URLs you want to use, you could configure that option in Newsboat using:
`macro t set browser "mpv --ytdl-format='bestvideo[height<=?480]+bestaudio/best' %u" ; open-in-browser ; set browser "w3m %u"`

If the above suggestion does not work, it is best to look for other relevant options in the mpv documentation or ask via their support channels.

**Comment by annata83** [comment]
> It is indeed best to try the command in the terminal first.
> 
> I believe mpv uses youtube-dl for streaming videos from many sites.
> You could try to use mpv's `--ytdl-format` flag with the videos you want to watch, e.g.:
> `mpv --ytdl-format='bestvideo[height<=?480]+bestaudio/best' https://www.youtube.com/watch?v=ap-BkkrRg-o`
> 
> If that works correctly with the URLs you want to use, you could configure that option in Newsboat using:
> `macro t set browser "mpv --ytdl-format='bestvideo[height<=?480]+bestaudio/best' %u" ; open-in-browser ; set browser "w3m %u"`
> 
> If the above suggestion does not work, it is best to look for other relevant options in the mpv documentation or ask via their support channels.



_Hey,, I was going thru that secction of the mpv man page more exacly I was reading this:_
**`--ytdl-format=<ytdl|best|worst|mp4|webm|...>`**
_I have no idea  how you come up with_ `bestvideo[height<=?480]` _but that's exacly rigth, it work like a charm!_
_Sorry to have come here for help over mpv syntax! Your guys have help me a lot; hope other people fond it useful some day to!._
 !
