### ISSUE TITLE
Make textwrap in 'save' configurable

### ISSUE THREAD

**Issue by herrsimon** [newsboat/newsboat#1346]
Hello,

when saving articles, lines are wrapped so that the resulting textfile has 80 columns. The same is true when piping an article through a script. While this certainly aids readability, it is not optimal for all users and in particular, when piping an article to a script (which then typically unwraps again to parse the headers). 

Therefore, it would be nice to introduce a 'wrap-on-save-and-pipe' (the name can definitely be improved) configuration option which stores the maximum linewidth. By default it should be 80 and a value of 0 means that wrapping is disabled.

**Comment by Minoru** [comment]
There's an issue about `pipe-to` already: #833.

I'm ok with adding an option for this, but I think `pipe-to` and `save` should have separate ones because there is no inherent connection between those two operations, and I don't think it make sense to couple their settings.

**Comment by herrsimon** [comment]
I agree that pipe-to and save should have sepearate options.

**Comment by Minoru** [comment]
Everything I said in https://github.com/newsboat/newsboat/issues/833#issuecomment-873462365 applies here too.
