### ISSUE TITLE
ignore-mode "display" makes possible to delete invisible articles

### ISSUE THREAD

**Issue by emanruse** [newsboat/newsboat#1360]
```
newsboat 2.21.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.21.0
System: Linux 5.9.12-1-default (i686)
Compiler: g++ 10.2.1 20200825 [revision c0746a1beb1ba073c7981eb09f55b3d993b32e5c]
ncurses: ncurses 6.2.20201031 (compiled with 6.2)
libcurl: libcurl/7.73.0 OpenSSL/1.1.1h-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.41.0 (compiled with 7.73.0)
SQLite: 3.34.0 (compiled with 3.33.0)
libxml2: compiled with 2.9.10
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
*read below
```

Steps to reproduce the issue:

0. Have some articles in a feed with certain url containing some 'keyword' in content body

1. In config set
```
ignore-mode "display"
ignore-article "the url of the feed" "content !~ keyword"
```

2. Run newsboat and open the feed (the killfile works fine)
4. Press CTRL+D to delete all articles visible in the feed
5. Exit newsboat
6. Remove the 'ignore-article' line
7. Run newsboat again and go to the same feed

### Expected:

The articles containing 'keyword' should remain. IOW only the ones *displayed* in step 2 should have been deleted.

### Actual:

All articles in the feed are deleted.

**Comment by Minoru** [comment]
Thank you for the report! I don't have time to reproduce this right now, but I'll get back to you once I did.

**Comment by Minoru** [comment]
Reproduced on 6dc08295efd6bcd31695bb66ec197305695be304.
