### ISSUE TITLE
Performance regression in Podboat

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#1375]
**Newsboat version**: newsboat r2.22

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# Empty
```

Steps to reproduce the issue:

1. Start podboat with a high number of podcasts queued

2. Use mouse-wheel to scroll up and down a few times

3. Press `q`

Expected: The scrolling up/down is handled quickly and podboat will thus quit quickly

Actual: Scrolling takes a (relatively) long time so it might take a few seconds until the next (quit) command is handled

**Other info you think is relevant**:
Git bisect points to https://github.com/newsboat/newsboat/commit/35e56001ceae0475ccc03ee1825000e1fa3d124c

This is definitely not a big issue in Podboat but it would be nice to improve performance.

**Comment by Minoru** [comment]
I did not try to reproduce this because I'm feeling too lazy to create a large enough queue file, but it makes sense looking at the commit that created the regression. I guess the invalidation mechanism from itemlist could be implemented here (provided we tamed it in the itemlist... :)
