### ISSUE TITLE
How to sync two instances of newsboat?

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#1377]
I have newsboat running on the server which pulls new RSS data on regular basis.

I would like to have another instance of newsboat on my laptop and:
1) sync new rss data from the server instance.
2) sync back the new/modifications/deletions of the articles from client to server (after some reading offline).

I know all the data are kept in sqlite database files. I would appreciate any hints how to approach this (what sequence of steps should be done?,  etc.)

Can the databases be updated by external script without exiting the newsboat?

Regards,
Piotr

**Comment by Minoru** [comment]
I believe the most common way is to use [one of the remote APIs we support](https://newsboat.org/releases/2.22/docs/newsboat.html#_newsboat_as_a_client_for_newsreading_services). If you want to just sync files manually, then:

1. close Newsboat (on both ends). You *might* get lucky copying the database while Newsboat is running, but most likely you'll corrupt the database instead;
2. copy at least cache.db and the urls file. Config file should definitely be copied if it contains `ignore-article` settings. Queue and history can be left alone if you don't use Podboat and don't care about missing history in command line and searches;
3. now start Newsboat again.

There is no way to "merge" two caches, even nearly identical ones, so you make sure to only run Newsboat on a single machine at a time.

Note that configs can include paths to other configs and to scripts — make sure those are consistent between machines, or keep per-machine configs and include them with something like ```include `echo ~/.newsboat/config.$HOST` ```.

**Comment by bbigras** [comment]
Does all the remote APIs support two-ways sync? I mean if something is marked as read in newsboat vs in the web ui.

**Comment by Minoru** [comment]
@bbigras I believe they all do. If you find one that doesn't, please open an issue about that.

Since the original question was answered, and there seem to be no follow-up to do, I'm closing this issue.

**Comment by ZaxonXP** [comment]
@Minoru: sorry to come back to this topic after so long, but I wanted to make some cleaning.

I tried to use your suggestion for synchronising two instances of newsboat using API, but I do not see any example that it could be used for this. I only see how one newsboat connects to some specific news services, but not another instance of newsboat.

 How one newsboat can connect to another using api? Could you give some example? Or is this is something which current newsboat cannot support?

**Comment by Minoru** [comment]
Yeah, what I meant is that two Newsboat instances sync to the same remote API, e.g. The Old Reader. There is no way to do a peer-to-peer sync like you describe. There was an attempt to add DecSync support, but it didn't quite fit into Newsboat, and I rejected it. You can subscribe to #381 for updates if it's ever attempted again.
