### ISSUE TITLE
Move existing Rust bindings to cxx crate

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1383]
We recently started using cxx crate which lets us write bindings with no `unsafe` code at all! We're using cxx 0.5 because cxx 1.0 requires Rustc 1.48 which we don't yet have, but 0.5 and 1.0 are largely compatible. The crate has thorough tutorial and reference at https://cxx.rs

Now, let's move our existing bindings to that crate:
- [x] `ConfigPaths` (#1793)
- [x] `Logger` (#1576)
- [x] `History` (#1584)
- [x] `FmtStrFormatter` (#1676)

(`MatcherError` is missing because I expect to work on it separately).

For inspiration and more guidance, see https://github.com/newsboat/newsboat/pull/1327, https://github.com/newsboat/newsboat/pull/1356, https://github.com/newsboat/newsboat/pull/1379, and https://github.com/newsboat/newsboat/pull/1304#discussion_r531671058.

If you start working on one of those, please leave a comment here so we don't duplicate work.

When submitting a PR with your work, please mention this issue so everything gets nicely linked together.

**Comment by dennisschagt** [comment]
> If you start working on one of those, please leave a comment here so we don't duplicate work.

I plan to work on updating the `Logger` soon.

**Comment by dennisschagt** [comment]
I plan to port the `History` bindings to cxx sometime soon.

**Comment by dennisschagt** [comment]
I'm currently porting the `FmtStrFormatter` bindings.

**Comment by dennisschagt** [comment]
Looks like this issue has been resolved now.

**Comment by Minoru** [comment]
Yup, and all thanks to you! :rocket:
