### ISSUE TITLE
Unicode characters with >=2 code points breaks the alignment of format strings

### ISSUE THREAD

**Issue by kutsan** [newsboat/newsboat#139]
<details>
 <summary>newsboat -v</summary>

```
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Darwin 16.7.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.54.0 SecureTransport zlib/1.2.8 (compiled with 7.51.0)
SQLite: 3.16.0 (compiled with 3.16.0)
libxml2: compiled with 2.9.4
```

</details>
<br>

It's rather self-explanatory, see the line with emojis. I believe it's because newsboat is counting the code points of characters, since one emoji contains two 2 code points (a surrogate pair), it breaks the alignment.

```
articlelist-format "  %t %> %L  %D  "
```

![image](https://user-images.githubusercontent.com/10108377/37172202-2fcfb784-2321-11e8-8664-bad00cfcc9e4.png)

**Comment by kutsan** [comment]
I also noticed now, it produces some weird output. See the book emoji.

![](https://i.imgur.com/z0nJnhG.gif)

**Comment by Minoru** [comment]
Thank you for the report! Looks related to akrennmair/newsbeuter#572.

**Comment by kutsan** [comment]
Yeah, you're right. I should have searched better.

**Comment by Minoru** [comment]
Oh, I didn't mean it as a rebuke—you did everything right. I'm just linking this to an older Newsbeuter issue so that when it's fixed here, there's a trace in Newsbeuter issue tracker too.

**Comment by kutsan** [comment]
Ah, if it's the case, thank you!

**Comment by dennisschagt** [comment]
> I believe it's because newsboat is counting the code points of characters

That is almost correct; Newsboat is counting graphemes.
I would expect it to count the actual width as shown on screen.

I'm currently working on a fix for this issue.

Below is a config with some urls to reproduce this.
I'm including this as it shows another, related, issue: Newsboat does not count stfl-quoted angle brackets when rendering a format-string.

An example config + some urls to reproduce this (for feedlist, fix will also work for the itemlist):
- Config:
    ```feedlist-format "%4i %n %11u %-50t<<<"```
- Urls:
    ```
    http://rss.slashdot.org/Slashdot/slashdot
    https://newsboat.org/news.atom
    https://www.ptt.cc/atom/marvel.xml
    https://www.ptt.cc/atom/movie.xml
    https://www.ptt.cc/atom/stupidclown.xml
    http://antirez.com/rss
    ```
- Output:
    a. Expected: `"<<<"` should be starting at the same column for different feeds
    b. Actual: `"<<<"` does not line up for different feeds
        ![image](https://user-images.githubusercontent.com/4629607/77007452-88251880-6964-11ea-9d32-3f00b46426d0.png)
