### ISSUE TITLE
grouping feeds

### ISSUE THREAD

**Issue by ghistes** [newsboat/newsboat#1393]
Hi,

I like to group feeds and use a hack I found somewhere on the internet.
It works like this:

In my urls-file I put entries like this:

```
youtube
https://www.youtube.com/feeds/videos.xml?channel_id=UCMBATpFb--uLNAODOVWvCTA "~PowerPlayChess" y
https://www.youtube.com/feeds/videos.xml?channel_id=UCld68syR8Wi-GY_n4CaoJGA "~Brodie" y
```

The literal string "youtube" here is simply a title and not a feed - note that all the true feeds have a tag.

In my config I then use a "%?T?" expression to make sure that all the feeds without a tag (ie. the headers/titles) are displayed differently, resulting in visually grouping feeds.

This works well enough so far, however when I update all the feeds I get errors like "unsupported URL: youtube" - which is no surprise of course...

So my question is: Would there be a better way to group feeds and if not then would it be an idea that some special syntax could be introduced to tell newsboat that a particular line in the urls-file is not really meant to be a feed but just a string that simply should be printed verbatim but no attempt should be made to fetch articles?

**Comment by dennisschagt** [comment]
This looks similar to https://github.com/newsboat/newsboat/issues/412.

**Comment by Minoru** [comment]
It does look like a duplicate, so I'm closing this. @ghistes, if you're describing a problem different from #412, please explain the difference and we'll re-open this promptly! And thank you for filing an issue in the first place — can't improve Newsboat if we don't know what needs improving!
