### ISSUE TITLE
Segmentation fault when opening URLs in a browser (only with swap-title-and-hints)

### ISSUE THREAD

**Issue by silvercoders** [newsboat/newsboat#1399]
**Newsboat version** 2.22.0

Output of `newsboat -v`:

```
newsboat 2.22.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.22.0
System: Linux 5.10.3-arch1-1 (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.74.0)
SQLite: 3.34.0 (compiled with 3.34.0)
libxml2: compiled with 2.9.10
```

**Config file**

I was able to reproduce the issue with a minimal config file containing only the following line:

```
swap-title-and-hints yes
```

**Steps to reproduce the issue**

1. Ensure `swap-title-and-hints yes` is set in the config file as described above 

1. Open newsboat

1. Select an article and press `o` (`open-in-browser`)

**Other info you think is relevant**

- I have found that the issue goes away if I disable `swap-title-and-hints`, although I would prefer to keep that setting
- I cloned this repo and built it from source, and after performing a `git bisect` I found that the first bad commit was 9aa2e7e

**Comment by dennisschagt** [comment]
Nice bug report, thank you for bisecting and for the clear steps to reproduce!

I've created [a bugfix](https://github.com/newsboat/newsboat/pull/1400) which I expect will be merged by tomorrow.

**Comment by silvercoders** [comment]
I applied your patch locally and it fixes the issue for me. Thanks for the quick response!

As the change is quite simple, I'm happy for you to close this issue once it's merged.
