### ISSUE TITLE
Switch to CMake

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#14]
Newsboat is currently built using a handwritten Makefile with some help from a shell script that finds paths to dependencies. There are some problems with this approach:

* *manual tracking of dependencies between files*, i.e. we have to tell `make` what to rebuild when a file changes. We partially automated that tracking but developers have to remember to re-run a special command from time to time;

* *bad support from tools*. This is related to the previous item, but this time the problem is a bit different: IDEs can't understand how our code hangs together. To work on Newsboat in QtCreator, one has to import all the `.cpp` and `.h` files, then re-create what our Makefiles already do using QMake.

    CLion, a C++ IDE from JetBrains, also can't automatically import Newsboat. This is actually my original motivation to look into CMake, which seem to be widely supported by IDEs;

* *duplication of effort in finding the libraries*. Some platforms and libraries have idiosyncrasies, which we have to work around in `config.sh`. This work is better be done in something popular and useful to everyone, not just us;

* *no universal interface*. There are some conventions on how to name targets and what environment variables to heed, but overall Makefiles can behave any way they want. This leads to inconveniences for some party or another; e.g. Newsbeuter Makefile always enables debugging because it's useful to developers, but [distros have to strip the parameter out](https://github.com/gentoo/gentoo/blob/61b861acd7b49083dab687e133f30f3331cb7480/net-news/newsbeuter/newsbeuter-9999.ebuild#L47).

CMake tracks the deps automatically, is importable to some IDEs, bundles functions that find some libraries, and enforces some structure.

I tried porting Newsboat to CMake; you can find the code in [feature/build-with-cmake branch](https://github.com/newsboat/newsboat/tree/feature/build-with-cmake). Some problems I hit upon:

* CMake [only learned to find ncursesw in 3.10](https://github.com/Kitware/CMake/commit/4b02afc0caf46244f12f87f363ace6c1ab47fae5), which isn't even released yet;

* if I try and copy the upstream FindCurses.cmake into our repo, I have to pull in a handful of support modules, and they require newer CMake than the one we have on Travis. I'm uncomfortable upgrading CMake on Travis because it runs recentish LTS Ubuntu and I view it as an example of what a reasonable user might still have running on their computer;

* CMake uses its own complicated language that, despite its specialization, doesn't add much clarity to configs.

As it stands, I don't think CMake is a good fit for Newsboat yet, and I will lay this aside for now.

**Comment by Earnestly** [comment]
> Newsbeuter Makefile always enables debugging because it's useful to developers, but distros have to strip the parameter out.

This is how it should work.  Upstream's build systems should never strip debug symbols.

**Comment by Minoru** [comment]
> if I try and copy the upstream FindCurses.cmake into our repo, I have to pull in a handful of support modules, and they require newer CMake than the one we have on Travis. I'm uncomfortable upgrading CMake on Travis because it runs recentish LTS Ubuntu and I view it as an example of what a reasonable user might still have running on their computer;

On re-reading this, I realize I didn't explicitly state the following: I am totally okay with vendoring stuff from newer CMake, but I couldn't figure out how to do it so that it works on older versions. If someone solves that problem, I will happily drag around any number of CMake modules, until the majority of users get newer CMake where these modules are built-in.

**Comment by Minoru** [comment]
Closing as outdated: we're moving to Rust (#89), so we shouldn't need CMake anymore.
