### ISSUE TITLE
Insert newlines after divs in html renderer

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#1405]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: `2.22`

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): default config

Steps to reproduce the issue:

1. Open an article from this feed: `https://smb-dep.web.cern.ch/en/private-market-accommodation.xml`

All articles in that feed are displayed as a big jumble of text without any newlines. Other rss readers/html viewers add a newline after each div block.

**Comment by Minoru** [comment]
Confirmed. `div` is [a block element](https://www.w3schools.com/htmL/html_blocks.asp), so it indeed should start on a new line. I'm working on a fix already. Thanks for the report!
