### ISSUE TITLE
spaces at apostrophe signs

### ISSUE THREAD

**Issue by muralikodali** [newsboat/newsboat#141]
**Newsboat version r2.10.2-57-gf5b7a**:

spaces are appearing when a word contain apostrophe.

![20180310t2127-crop](https://user-images.githubusercontent.com/11482766/37244177-10881b06-24ab-11e8-8dd1-cce36696416d.jpg)

**Comment by Minoru** [comment]
Couldn't reproduce. Can you provide the URL for the feed where you observe this?

A wild guess: the text contains Unicode quotes, and your terminal isn't in UTF-8. What does `locale` print out in the terminal where you run Newsboat?

**Comment by muralikodali** [comment]
locale output is like this:

LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by Minoru** [comment]
Okay. What about my other question, the one about URL?

**Comment by muralikodali** [comment]
http://www.tuxmachines.org/node/feed

**Comment by Minoru** [comment]
Nope, doesn't look like that to me:
![2018-03-10-195417_1920x1080_scrot](https://user-images.githubusercontent.com/118875/37244650-2eae4938-249d-11e8-9732-fd477185b4da.png)

I'm especially worried by the fact that the link anchor ("[1]") appears in different places in our screenshots, and you don't have that bug where list items don't start on the same line as list markers. Are you absolutely sure you're running Newsboat and not Newsbeuter? :)

But at least I confirmed that the apostrophe is a Unicode one, [codepoint 2019](https://www.fileformat.info/info/unicode/char/2019/index.htm). What does the following command print out in your terminal?

```
$ echo 'it\xE2\x80\x99s'
```

What operating system are you running?

What does `newsboat --version` print out?

One more test: please run Newsboat like this

```
$ newsboat --log-file=newsboat.log --log-level=6
```
Update that one feed and exit immediately. Then view newsboat.log in two different ways:

1. with any pager, in the same terminal where you run Newsboat. `less newsboat.log` will do;
2. with an editor you trust to support Unicode, preferably in a different terminal or even in GUI mode.

In both cases, search for "This Android" and check if the apostrophes are there.

Also try running Newsboat without a config (e.g. `--config-file=/dev/null`). You'll probably want to change the cache file for that, too: `--cache-file=/path/to/temporary/cache.db`.

**Comment by muralikodali** [comment]
I forgot to mention that these feeds are sourced from **nextcloud news** app.
I am using **UBUNTU MATE 16.04** and compiled newsboat from source.

- output for command: echo 'it\xE2\x80\x99s':
it\xE2\x80\x99s

- newsboat version output with command: newsboat --version
newsboat r2.10.2-57-gf5b7a - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat r2.10.2-57-gf5b7a
System: Linux 4.4.0-116-generic (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libcurl: libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.11.0 (compiled with 3.11.0)
libxml2: compiled with 2.9.3

- In vim and less pager , apostrophe's are looking good.
  I am attaching log file for your reference.
[newboatlog.zip](https://github.com/newsboat/newsboat/files/1800032/new.boatlog.zip)

I have not observed this problem in newsbeuter (with tt-rss)

- command output for: newsboat --config-file=/dev/null --cache-db=/tmp/testcache.db
loaded url's from default configuration. when we press enter on feed , it shows **"Error:feed contains no items"**

**Comment by Minoru** [comment]
Thanks! From your log, I learned that you use `w3m` to render articles. Does the bug persist if you comment out the `html-renderer` line in your config? (Though I just tried out w3m for rendering, and it rendered apostrophes just fine).

Re "feed contains no items": you have to *update* the feed. Select it and press `r`.

**Comment by muralikodali** [comment]
this problem is not appearing when i comment out the line as suggested by you.
i.e: html-renderer "w3m -dump -T text/html"

**Comment by Minoru** [comment]
Given w3m works for me, I doubt this bug has anything to do with Newsboat—it's probably your version of w3m. I'm running this one: "w3m/0.5.3+git20161120, options lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,w3mmailer,nntp,ipv6,alarm,mark" Hope you'll figure it out from here.
