### ISSUE TITLE
Is it possible to have multiple urls files?

### ISSUE THREAD

**Issue by f6ADt** [newsboat/newsboat#1420]
I would like to separate some feeds in their own urls file, to generate a mobile and a desktop feed list.

So far, I only found `include`- but that is for splitting up configs. There is also an example with a file scheme in the documentation (`file:///my/path/to/feed`) and first I thought, this would be the equivalent of the include directive for urls. The option seems to be rather for a local feed file (not sure, what that is).

Note: I have installed newsboat with snap, so I may have messed up something with the home path, if `file:///` was really intended for this case.

**Comment by Minoru** [comment]
It isn't, but we will consider adding it in the future. Closing in favour of #118.

> There is also an example with a file scheme in the documentation (file:///my/path/to/feed) and first I thought, this would be the equivalent of the include directive for urls. The option seems to be rather for a local feed file (not sure, what that is).

http:// feeds are fetched using HTTP, https:// ones are fetched using HTTPS, and file:// ones are just read off the disk directly. It's mostly useful for testing, but you might also employ file:// if you have some tool generating a feed and storing it into a file — you'd just point Newsboat at that file then.

**Comment by f6ADt** [comment]
@Minoru thanks for the issue hint - good to know, this idea is already considered.
