### ISSUE TITLE
UI issues on FreeBSD with st and Ncurses 5.9.20140222

### ISSUE THREAD

**Issue by christosmarg** [newsboat/newsboat#1428]
## Newsboat version:

newsboat 2.21.0
System: FreeBSD 12.2-RELEASE-p2 (amd64)
Compiler: g++ 4.2.1 Compatible FreeBSD Clang 8.0.1 (tags/RELEASE_801/final 366581)
ncurses: ncurses 5.9.20140222 (compiled with 5.9)
libcurl: libcurl/7.74.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.42.0 (compiled with 7.74.0)
SQLite: 3.34.0 (compiled with 3.34.0)
libxml2: compiled with 2.9.10

## Issue

On startup, `newsboat` randomly hides (i.e makes the whole line black) feeds and it only shows them if you hover over them. It might also apply wrong colors to a feed. If the feed happens to be unread, it highlights it even if you're not hovering over it, so you end up with several highlighted feeds at the same time. The highlighting goes away if you hover over it again.

Colors also get messed up when reading an article too.

## Config file (only the following lines *are* part of the issue):

```
highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default
```

Without these lines in the config, some of the issues still persist.

## Steps to reproduce the issue:

1. Add the lines I've included above in the `config` file.
2. Open `newsboat`.
3. Make sure there are unread feeds.

### Startup (notice the yellow feeds as well)
![2021-01-13-230834_1854x1035_scrot](https://user-images.githubusercontent.com/54286563/104511035-07669580-55e4-11eb-9529-6e9af1607930.png)

### Hovering over the "blacked out" feeds
![2021-01-13-230938_1854x1035_scrot](https://user-images.githubusercontent.com/54286563/104511051-13525780-55e4-11eb-93aa-5bf421435204.png)

### Unread feeds

![2021-01-13-231011_1854x1035_scrot](https://user-images.githubusercontent.com/54286563/104511125-2d8c3580-55e4-11eb-922f-337fe5425d70.png)

### Hovering over the unread feeds (if you hover back, they'll get highlighted again)
![2021-01-13-231018_1854x1035_scrot](https://user-images.githubusercontent.com/54286563/104511154-3846ca80-55e4-11eb-8494-d361b6a6cab7.png)

**Comment by Minoru** [comment]
Thanks! Does pressing `^L` make the issue go away?

**Comment by Minoru** [comment]
Also, what version of STFL is Newsboat built against?

**Comment by christosmarg** [comment]
> Thanks! Does pressing `^L` make the issue go away?

Quite the opposite, it created even more issues. :-)

`^L` either does nothing or it has very weird behaviour. After scrolling a bit back and forth and then pressing `^L`, the highlighting of all the feeds got reversed. Then I kept scrolling down and every time I pressed `^L`, all the feeds above the selected one got  either black or yellow.

**Comment by christosmarg** [comment]
> Also, what version of STFL is Newsboat built against?

```
$ pkg info | grep stfl

stfl-0.24_1                    Structured Terminal Forms Language/Library
```

**Comment by Minoru** [comment]
Okay. I don't see a way for Newsboat to mess this up: ^L gets propagated straight to STFL and then Ncurses. You already have the latest version of the former; is there any chance you can build Newsboat against a newer version of Ncurses?

Another angle of attack would be the terminal.
- Are you running Newsboat in a TTY, or is it a terminal emulator?
- What does `echo $TERM` print out?
- Can you please run in e.g. `xterm` and see if the problem persists there?

**Comment by christosmarg** [comment]
> Is there any chance you can build Newsboat against a newer version of Ncurses?

I might try it later but I'll post the results here.

>   Are you running Newsboat in a TTY, or is it a terminal emulator?

It's a terminal emulator.

>   What does `echo $TERM` print out?

`st-256color`
 
>   Can you please run in e.g. `xterm` and see if the problem persists there?

`xterm` seems to be rendering colors properly, so it might not be `newsboat` related.

**Comment by Minoru** [comment]
Got it! FWIW, on Debian testing with st 0.8.4 and STFL 0.22, the rendering looks correct to me — no gaps like in your screenshots.

```
newsboat r2.22.1-130-gc7cf-dirty
System: Linux 5.10.0-1-amd64 (x86_64)
Compiler: g++ 10.2.1 20201224
ncurses: ncurses 6.2.20201114 (compiled with 6.2)
libcurl: libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.42.0 librtmp/2.3 (compiled with 7.74.0)
SQLite: 3.34.0 (compiled with 3.34.0)
libxml2: compiled with 2.9.10
```

(The build is "dirty" due to unrelated changes to the docs, no code changes were made relative to c7cf0a3beadca44af19b168382f72f9a74fd9831)

It might also be a problem with st itself, so if you aren't running the latest version (or at least 0.8.4 that I did), it might be worth updating that one too. Looking forward to those results!

**Comment by christosmarg** [comment]
Compiling from `/usr/ports/www/newsboat` with the most recent version of `ncurses` fixed the issue. Thanks a lot!

**Comment by Minoru** [comment]
Ah, awesome! Let's close this then.
