### ISSUE TITLE
eBay Search RSS Feed Times Out 

### ISSUE THREAD

**Issue by matteqa** [newsboat/newsboat#1438]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

newsboat 2.22.1
System: Linux 5.10.7-arch1-1 (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0 (compiled with 7.74.0)
SQLite: 3.34.0 (compiled with 3.34.0)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser ~/scripts/linkhandler
reload-threads 100
download-timeout 60
error-log "~/.config/newsboat/error.log"
```

**Other info you think is relevant**:

Steps to reproduce the issue:

1. Add https://www.ebay.com/sch/i.xml?_from=R40&_nkw=remarkable+tablet&_sacat=0&_sop=15&_blrs=recall_filtering&rt=nc&_rss=1 to newsboat urls

2. Try to load the feed

**Other info you think is relevant**:

The feeds load almost instantaneously in other news readers, but time out in newsboat even after increasing download-timeout to 60.

**Comment by Minoru** [comment]
Hi! It worked fine for me just now, even with an empty config. Are you sure it wasn't just a transient problem? Did it still not work?

**Comment by Minoru** [comment]
I checked again just now, and I still can't reproduce this. I have to assume this was a spurious problem that already resolved itself.

Please drop a comment if it still persists for you.

**Comment by matteqa** [comment]
Hi, sorry forgot to respond to this. The issue still persists for me however I have worked around it using an exec scrip that uses wget to download the feed instead.

My guess is that all the special characters are causing libcurl to fail to respond.

**Comment by matteqa** [comment]
Actually this might not be a newsboat issue at all. Using a URL from ebay.com.au (my country) works fine, however ebay.com and ebay.co.uk urls fail. It works fine on other RSS readers so maybe eBay is blocking curl requests from foreign IP addresses?

**Comment by Minoru** [comment]
For me, www.ebay.com.au, www.ebay.co.uk, and www.ebay.com all work both in Newsboat and with curl. ebay.eu (note: without www.) works with curl, but gives an SSL error in Newsboat (their SSL certificate seem to belong to but.ly?) So no, I still can't observe the original problem.

One thing you could try is set a user-agent: `user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"`. This will make Ebay (and all other servers) think that the request is coming from Firefox, not Newsboat.
