### ISSUE TITLE
'T' identifier in articlelist-format should display first tag of feed instead of feed title 

### ISSUE THREAD

**Issue by herrsimon** [newsboat/newsboat#1439]
Hello,

when displaying articles from different feeds in an article list, I think it would be very useful to have the possibility of also including the first tag of a feed in articlelist-format instead of the full feed title (as is possible in feedlist-format using the 'T' identifier). For example, the behavior of the 'T' identifier in articlelist-format could be changed to either show the first tag of the feed the article belongs to, or the feed title if no tag is present. If that's not wanted, please think about introducing a new identifier in articlelist-format which shows the first tag of a feed.

The reason I'm asking for this feature is that a lot of feeds contain long and cumbersome titles, such as 'The super cool news feed - your best news source reporting 24/7 from the area'. It is much more reasonable to tag such a feed with '[NF]' or similar instead of cluttering every article line with the long title.

Thanks in advance!

**Comment by Minoru** [comment]
Note that you can change the title of the feed using a special tag that starts with tilde:

```
https://example.com/news.xml "~A shorter title"
```

Is that a satisfactory solution, @herrsimon? If not, why not?

**Comment by herrsimon** [comment]
Hi @Minoru,

thanks for the quick reply (as always!). I already gave all my feeds short titles using tags which start with a tilde. The issue is with query feeds which gather articles from multiple feeds. There, the `%T' identifier yields the original feed title, even if a tilde-tag is present. Here is a sample urls file:

``
filter:~/bin/some_filter_script1 !~tag1 common_tag
filter:~/bin/some_filter_script2 !~tag2 common_tag
"query:some_query:tags # \"common_tag\""
``
Now if you use '%T' in the value of `articlelist-format` in your config file (in my case, I have `articlelist-format "%4i %f %D %-70a %t %T"`) and open the 'some_query' feed, the full feed titles of the two filter feeds appear in each article line, instead of tag1/tag2. I hope this explanation was clear.

**Comment by herrsimon** [comment]
Sorry, some new lines were swallowed in my last comment and I can't edit it. In the urls file there are of course three separate lines, two filter feeds and one query feed.

**Comment by herrsimon** [comment]
...and of course, in my actual filter lines there are also urls appended after the script (separated by a colon).

**Comment by Minoru** [comment]
Ah, I guess I see the problem: `!~tag1` is not a tilde tag, because it doesn't start with a tilde. It does start with an exclamation mark, so it's a "hidden" tag, but it doesn't change the title of the feed.

Try splitting that in two `!hidden ~tag1`, that should resolve the problem. And please tell me how that goes :)

**Comment by herrsimon** [comment]
works like a charm, thanks a lot for your help (and the great software), I really appreciate it!

**Comment by Minoru** [comment]
Excellent! Let's close this issue then :)
