### ISSUE TITLE
`cookie-cache` should have a reasonable default value

### ISSUE THREAD

**Issue by dertuxmalwieder** [newsboat/newsboat#145]
**Newsboat version (copy from `newsboat -v`)**:

    newsboat 2.10.2 - https://newsboat.org/
    Copyright (C) 2006-2015 Andreas Krennmair
    Copyright (C) 2015-2017 Alexander Batischev
    Copyright (C) 2006-2017 Newsbeuter contributors
    Copyright (C) 2017 Newsboat contributors
    
    newsboat ist Freie Software und steht unter der MIT-Lizenz.
    Für mehr Information `newsboat -vv' eingeben.
    
    newsboat 2.10.2
    System: Linux 4.9.76-gentoo-r1 (x86_64)
    Compiler: g++ 6.4.0
    ncurses: ncurses 6.0.20150808 (compiled with 6.0)
    libcurl: libcurl/7.58.0 OpenSSL/1.0.2n zlib/1.2.11 (compiled with 7.58.0)
    SQLite: 3.22.0 (compiled with 3.22.0)
    libxml2: compiled with 2.9.7

Steps to reproduce the issue:

1. Set `urls-source` to "newsblur"

2. Add your Newsblur `login` and `password` (and nothing else) to your config file

3. Try to start `newsboat`, be greeted with an error that says that the file "" (actually, here's just a second space character) can neither be read nor created. Set a useful value for the cookie path to make this error go away.

**Other info you think is relevant**:

As there is no reason to *not* preset the cookie path to `~/.newsboat/cookies.txt`, I suggest to do exactly that.

**Comment by Minoru** [comment]
I agree. In XDG mode that should probably be `~/.local/share/newsboat/cookies.txt`

**Comment by Minoru** [comment]
Now that I think a bit more about this, I do see a reason not to preset this setting: privacy. RSS and Atom are "stateless" in a sense that the server doesn't have to know who's asking for the feed. And even if it does, there are better mechanisms in place:
- private feeds can embed a token into the feed URL itself, or require HTTP authentication;
- caching can be implemented with `Last-Modified` and `ETag` headers and their request counterparts.

Newsboat already supports all of the above.

So far, the only people who need a cookie cache are NewsBlur users, which are a fraction of Newsboat users; an important fraction, but a fraction still.

I'll hold off adding a default for `cookie-cache` for now.
