### ISSUE TITLE
Replace Text Regex in comfig

### ISSUE THREAD

**Issue by hussein-esmail7** [newsboat/newsboat#1457]
It would be nice to be able to define replacing text in the config file. For example, it could be based on a certain feed or all feeds in a tag (or even all feeds). 

For example:
`<tag_name> "old_string" "new_string"`
`<tag_name> "regex string" "new_string"`
`"Reddit" "/u/" "u/"`

This could also be useful for people who may not appreciate offensive language, and they can block whichever words they wish.

**Comment by Minoru** [comment]
Newsboat already provide a couple features that intersect with this:

1. if the user doesn't want to see some content, they [can ignore articles that match a particular filter expression](https://newsboat.org/releases/2.22.1/docs/newsboat.html#_killfiles). Filter expressions can match the content of the article with a regex (and much more!);
2. if the user wishes to "censor" the feed, e.g. by replacing some words, they can use `filter:` to e.g. pipe the feed through `sed`: `filter:sed 's#offensive#safe#:https://example.com/feed` (keeping in mind that it operates directly on the feed's XML). More docs on that here: https://newsboat.org/releases/2.22.1/docs/newsboat.html#_scripts_and_filters_snownews_extensions
3. if the user doesn't want to operate on the XML of the feed, they can operate on the HTML of the article instead, by setting [`html-renderer`](https://newsboat.org/releases/2.22.1/docs/newsboat.html#html-renderer) to a script that would run `w3m -dump -T text/html | sed 's#offsensive#safe#'`;
4. if XML and HTML are not suitable, the user can set the [`pager`](https://newsboat.org/releases/2.22.1/docs/newsboat.html#pager) setting, and operate on the rendered text.

I think with that, Newsboat covers the use-case of offensive words quite thoroughly, and so I don't think we need any new features. @hussein-esmail7, do you yourself have some use-cases that can't be covered by these facilities?

**Comment by Minoru** [comment]
Since there are no counter-arguments, I'll assume that Newsboat's feature set is sufficient. Please drop a comment if something is still missing ;)
