### ISSUE TITLE
[feature request] option to show only sites with unread feeds

### ISSUE THREAD

**Issue by nsklaus** [newsboat/newsboat#1458]
just a quick suggestion, 
would it be possible to have an option to get newsboat to show only sites with unread feeds ?
i mean, at this moment i have so many subscriptions to various sites that i have to scroll a few pages up and down just to check if there is something new. if newsboat could have such an option, only sites that have unread feeds would be displayed and users wouldn't have to continuously scroll up and down all the time just to check for updates. so yes, either display only sites with unread feeds, or at least place them at the top of the list. if this is made as an option folks can choose wether to use it or not depending if they prefer current behaviour, or the one i'm describing here. would be great to also have a hotkey to toggle it on and off at will.

**Comment by nsklaus** [comment]
the feature request i suggested already exists. in config do:
```
show-read-feeds no
...
bind-key U toggle-show-read-feeds
bind-key u show-urls
```

**Comment by Minoru** [comment]
Sorry I didn't reply in time. Glad you resolve it yourself! :+1:
