### ISSUE TITLE
Help messages are not localised

### ISSUE THREAD

**Issue by bitigchi** [newsboat/newsboat#1471]
newsboat 2.22.1
System: Darwin 19.6.0 (x86_64)
Compiler: g++ Apple LLVM 12.0.0 (clang-1200.0.32.28)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2 (compiled with 7.64.1)
SQLite: 3.34.0 (compiled with 3.34.0)
libxml2: compiled with 2.9.4

Newsboat help messages are in English. Users should get localised help messages upon pressing ? by default.

**Comment by Minoru** [comment]
You're right! I admit I don't know what's up with that: the messages are marked up for translation:

https://github.com/newsboat/newsboat/blob/550932bb26cc9c07d1e3655f59bb91e1324b6ad3/src/keymap.cpp#L37

...and these messages *are* used:

https://github.com/newsboat/newsboat/blob/550932bb26cc9c07d1e3655f59bb91e1324b6ad3/src/keymap.cpp#L549

And yet they all appear in English in the help dialog. No idea yet :thinking:

**Comment by scompo** [comment]
Can confirm this too.

**Comment by scompo** [comment]
I've used git bisect to find the first bad commit, here's the result:

```
73399760f987d2cdc6636792bcef95629fd83272 is the first bad commit
commit 73399760f987d2cdc6636792bcef95629fd83272
Author: Dennis van der Schagt <dennisschagt@gmail.com>
Date:   Mon Apr 20 15:30:49 2020 +0200

    Remove duplicate calls to gettext()

    gettext is already called via the `_(s)` macro when assigning to
    `.help_text`.

 src/keymap.cpp | 13 ++++++-------
 1 file changed, 6 insertions(+), 7 deletions(-)
```
I'll take a look if changing this back fixes the code now.

**Comment by scompo** [comment]
Not really sure why but `opdesc.help_text` is still in English when pushed.

``` diff
diff --git a/src/keymap.cpp b/src/keymap.cpp
index 407896ef..f7e65a63 100644
--- a/src/keymap.cpp
+++ b/src/keymap.cpp
@@ -546,7 +546,7 @@ std::vector<KeyMapDesc> KeyMap::get_keymap_descriptions(std::string context)
                        const std::string& key = keymap.first;
                        const Operation op = keymap.second;
                        if (opdesc.op == op) {
-                               descs.push_back({key, opdesc.opstr, opdesc.help_text, context, opdesc.flags});
+                               descs.push_back({key, opdesc.opstr, _(opdesc.help_text.c_str()), context, opdesc.flags});
                                bound_to_key = true;
                        }
                }
```
Converting it to a c string and applying the translation macro again like this fixes it..

It's weird because, as you said previously, it should be already translated at the beginning in the `opdescs` declaration.

**Comment by scompo** [comment]
I guess that's related to what's described [here](https://www.gnu.org/software/gettext/manual/html_node/Special-cases.html).

**Comment by Minoru** [comment]
Thanks for the link! It's indeed very much related, and I understand the root cause now.

Our strings are stored in a top-level constant in keywords.cpp. This means that the constant had a "static storage"; in other words, it exists the whole time the program is running, *even before the call to `main()`*. That implies that it gets initialized *before* the call to `main()`, too. This is an important detail, since `main()` is responsible for configuring gettext. Prior to that configuration, `gettext()` simply returns the string unchanged.

And thank you for the pull request too, I'll go take a look now :)

**Comment by bitigchi** [comment]
Thank you!
