### ISSUE TITLE
Ask for confirmation before deleting all articles

### ISSUE THREAD

**Issue by rumwerfer** [newsboat/newsboat#1490]
Similar to #1006, marking all articles in a feed as deleted (and thus lose their read/unread-status) can't be undone easily. Thus, asking for confirmation would be nice to have. In general, this would solve the same problem as #1096 for a different shortcut.

Since a lot of users are used to the behavior without confirmation, a setting `confirm-delete-all-articles` similar to #1214 would serve all users best.

**Comment by Minoru** [comment]
Yep, good idea, thanks! If someone wants to implement this, you can follow https://github.com/newsboat/newsboat/issues/1214#issuecomment-703266082 and https://github.com/newsboat/newsboat/pull/1215 as templates, except you'd look for `OP_DELETE_ALL`.
