### ISSUE TITLE
Setting toggle syntax broken

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#1491]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: cd9d777 (also broken in 2.22.1, 2.22)

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```
macro m set mark-as-read-on-hover!
```

Steps to reproduce the issue:

1. Open any feed

2. Run the provided macro

Instead of toggling `mark-as-read-on-hover` it displays an invalid syntax error.
Bisect points to 0fb0c28fb974a1a4f3030de2350e7bb6bcc0cf6a, which makes sense.

**Comment by dennisschagt** [comment]
I somehow overlooked that feature, thanks for the report!
I'm working on a fix now.
