### ISSUE TITLE
Making the pager accessible outside of Newsboat

### ISSUE THREAD

**Issue by kentdobias** [newsboat/newsboat#1498]
The Newsboat pager is the best tool I have ever used for reading HTML in the terminal. I would love to be able to use it to read HTML email in mutt, among other things. If it were easy, this would be a very nice feature.

**Comment by Minoru** [comment]
Hey, thanks for the kind words!

I think it's doable, but I don't want to take on the maintenance work it would incur. If you're willing to maintain it, though, I'm open for further discussions. But you'll probably want to look at the code first, and take into account that it's being gradually ported to Rust.

If all you want is rendering and scrolling, it's way easier to write a script like `w3m -dump -T text/html | less` and use that. If you want features like key bindings, macros, and URL view, you can take Newsboat's repo, look at `ItemViewFormAction` class, and strip away anything that you don't need.

**Comment by kentdobias** [comment]
The winning features for me are the ANSI touches (which would work in a 'dump' scenario but have no parallel in w3m, elinks, or lynx) and the URL treatment (which is necessarily interactive). I will take a look at the code as you suggest – thank you for pointing out the appropriate class!

**Comment by Minoru** [comment]
Hmm, what's "ANSI touches"? :)

**Comment by kentdobias** [comment]
Bold and underline.

**Comment by Minoru** [comment]
@kentdobias, did you take a look at the code? What's your plan around this issue?

**Comment by Minoru** [comment]
It doesn't look like Newsboat needs to do anything about this, so I'm closing the issue. Please drop a comment here if there's new information!
