### ISSUE TITLE
Mark unread command

### ISSUE THREAD

**Issue by cedricpim** [newsboat/newsboat#15]
Great work here!

One thing I didn't find out anywhere and I was wondering why is: ability to mark a feed back as unread, is it possible? In my flow, it is the simplest way to keep track of feeds that I want to read in the future.

**Comment by polyzen** [comment]
Perhaps we could deprecate `mark-feed-read` with `toggle-feed-read`, complimenting `toggle-article-read`.

I (and others presumably) have just been mashing `N` for this, heh.

**Comment by cedricpim** [comment]
I was actually searching for the `toggle-article-read`. I think I searched for unread in documentation, that's why I didn't find this option. Thanks @polyzen!

**Comment by giannigdev** [comment]
is this feature still in progress ?

**Comment by Minoru** [comment]
Hi! No work is being done on it. We didn't even settle on a final design, hence the "to consider" label.

I'm open to discuss the design and TODO if you (or someone else) is willing to work on this.

**Comment by allanwind** [comment]
The normal case is probably a feed with a mix of read and unread articles and toggle isn't the right action.  Can you define a macro that (`set-filter unread`, `toggle-article-read`, `clear-filter`)?

**Comment by chromer030** [comment]
+1 for this feature , it's vital.

**Comment by Minoru** [comment]
@in-plaintext, it's about entire feeds. I believe `toggle-article-read` already covers individual articles. Do you have an example where it doesn't work properly? I can imagine issues in macros, but I'd prefer an actual user with an actual problem.

@GreyStinger, no work has been done on this, but as you can see, there was some feedback and thoughts. Would you like to pull it all together and implement this?

**Comment by Minoru** [comment]
Internal help only shows operations that are available in the current context, so `toggle-article-read` can only be seen if you're inside a feed or reading an article. Also, the bound and unbound keys are in different sections — have you checked both? If it's still missing, please file an issue, we'll figure it out there ;)
