### ISSUE TITLE
[minor] folder .newsboat still in message/manual

### ISSUE THREAD

**Issue by pirate486743186** [newsboat/newsboat#1504]
in the man pages (FIRST STEPS) and the error message if the file urls is empty.
It still mentions the .newsboat folder, instead of .config/newsboat.

**Comment by Minoru** [comment]
Newsboat supports both, so the messages aren't wrong. However, you're right that the message should mention both directories. We already have an issue for this, #3, so I'll close this one. Thanks for filing it though, these paper cuts should be addressed too!

**Comment by pirate486743186** [comment]
???
XDG is meant to be the standard. The folder ".newsbeuter" remained for backwards compatibility.

**Comment by Minoru** [comment]
As I said, Newsboat supports both, equally. None of them is for backwards compatibility.

This might change in some future major version of Newsboat, but for now, it supports both.
