### ISSUE TITLE
alt attribute of <img> is not displayed

### ISSUE THREAD

**Issue by markmatney** [newsboat/newsboat#1505]
**Newsboat version**: commit c783cb454622e75b1d9bb1bf6401bcb7cd37618c

Config file: n/a

I would expect Newsboat to display the `alt` attribute of images (as it does for `title`) in article view, but it does not.

Steps to reproduce the issue:

1. Checkout the branch `bugfix/img-alt-rendering` from https://github.com/markmatney/newsboat.git

2. Run `TMPDIR=/dev/shm make -j5 PROFILE=1 check` and observe the test that fails

**Comment by Minoru** [comment]
Thanks for the report, and for the test as well!
