### ISSUE TITLE
Rendering of <img> is inconsistent with other media types

### ISSUE THREAD

**Issue by markmatney** [newsboat/newsboat#1506]
**Newsboat version**: commit c783cb454622e75b1d9bb1bf6401bcb7cd37618c

Config file: n/a

I would expect Newsboat to render, for example, the first image placeholder in an article, which appears after a single `<a>`, as `[image 1 (link #2)]` rather than `[image 2]`, similar to how `<audio>`, `<video>`, etc. are rendered. In general, I would expect all image placeholders to display an index between 1 and `image_count` (inclusive), but currently it [displays the `linknum`](https://github.com/newsboat/newsboat/blob/c783cb454622e75b1d9bb1bf6401bcb7cd37618c/src/htmlrenderer.cpp#L341) instead (which will fall outside that range if there are any other links before any images). Since the current behavior is inconsistent with other media types, I believe it is confusing.

Steps to reproduce the issue:

1. Checkout the branch `bugfix/img-numbering` from https://github.com/markmatney/newsboat.git

2. Run `TMPDIR=/dev/shm make -j5 PROFILE=1 check` and observe the test that fails

**Comment by markmatney** [comment]
(Please ignore the branch name on this and #1505 -- my sense is that these are bugs, but I should probably leave the classification to maintainers)

**Comment by Minoru** [comment]
I agree that it's a bug and it's confusing. I'm not sure why we number media at all — need to dive into Git history to see if it was that way from the beginning, or was added later.

Thanks for the report and the test case!
