### ISSUE TITLE
Ability to highlight in feedlist using filter language

### ISSUE THREAD

**Issue by lbatalha** [newsboat/newsboat#1510]
Related to #1104 

The behaviour of highlight-article does not seem to apply to the feedlist, so for example I cannot highlight a whole feed based on tags using filter language.

Example:
`highlight-article "tags # \"important\" and unread_count > 0" red default reverse bold`

With that all feeds deemed `important` would receive a major highlight when any new articles exist.

This has other obvious uses like being able to change the look of all feeds tagged `youtube` etc...

**Comment by Minoru** [comment]
Makes sense! Although I think it should be a separate setting, because filter expressions for feedlist might not make sense for the article list.

**Comment by lbatalha** [comment]
Agree, I was thinking something like `highlight-feed`
