### ISSUE TITLE
Don't use backticks in -title-format defaults

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1520]
A user on IRC just ran into a problem: they copy-pasted the default for `feedlist-title-format` from the documentation, and hilarity ensued:

```
> I'm trying to configure title dialogs, and I stuck.
> when I added default string for feedlist-title-format to my config newsboat stopped working properly
> feedlist-title-format "%N %V - %?F?Feeds&Your feeds? (%u unread, %t total)%?F? matching filter `%F'&?%?T? - tag `%T'&?"
> when I hit "t" and choose tag, there's no "- tag `%T'&?" part in the title
> but if I remove this line from my config, it works
> strange thing is that it is default string... so I'm confused
> additionoaly when I hit F for "filter" I only have:
> newsboat 2.22.1 - Feeds (3 unread, 3 total) matching filter '
> but when I remove this line from my config, it works properly:
> newsboat 2.22.1 - Feeds (3 unread, 3 total) matching filter `unread_count > 0'
> do you have any ideas why default string doesn't work (for me)?
```

This is caused by backticks: the stuff in between them is interpreted as a shell command.

I think we should use something else, but I'm not sure what. Double quotes are not very good because they have to be escaped. Single quotes look a bit odd in this context, but we are already using them for e.g. `itemview-title-format`.

Similar issue for error messages: #901.

**Comment by demure** [comment]
What about removing backtick substitution and requiring the more resent (and less error prone) `$()` style for command pre evaluation?

**Comment by Minoru** [comment]
@demure Removing backticks would be a breaking change, and I want a more quick fix.

Meanwhile, the same user on IRC suggests removing quotes entirely, and using a format like this:

```
> Maybe not use them, like: feedlist-title-format   " Feeds: %u unread, %t total.%?F?Filter: %F&?%?T? Tag: %T&?"
> it gives me this (for tag):  Feeds: 0 unread, 9 total. Tag: OpenBSD
```

**Comment by Minoru** [comment]
Oh, and JFTR the reason I assigned this to 2.24 release is because:

1. 2.23 is in two weeks and I just made a call for translators to update their translations — any changes to translatable strings is now forbidden until after the release;
2. this is a simple bug, should be fixed quickly, so I added it to the milestone for the next next release.

**Comment by Minoru** [comment]
> Meanwhile, the same user on IRC suggests removing quotes entirely

I think it's not a very good idea, since it makes entirely unclear there a filter/tag ends.

Let's use single quotes. Double quotes would be my first choice, but filters often end with a double quote, and the resulting title would look a bit weird. Single quotes avoid this problem.
