### ISSUE TITLE
Article background always black

### ISSUE THREAD

**Issue by thentoorglan-x** [newsboat/newsboat#1527]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: newsboat r2.22.1

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): default

I installed newsboat through snap. I've tried using the default config and changing colors, but the article colors don't change. I have verified the config was loaded as all other colors were changed.

![](https://i.imgur.com/TGr2KjW.png)

**Comment by Minoru** [comment]
Without seeing your config (i.e. `color` commands), it's impossible to tell what's wrong. I just tried [the "commander" colorscheme](https://github.com/newsboat/newsboat/blob/f08b758de331b624be2b3005394b991d6d1dccf0/contrib/colorschemes/commander) and the article background is blue, so apparently something *does* work:

![newsboat](https://user-images.githubusercontent.com/118875/110647236-b8467680-81c8-11eb-84e6-a3bb17a81043.png)

Note though that this was with a locally built Newsboat, not Snap. If you supply more details, I might try installing Snap instead and checking if it works there.

**Comment by thentoorglan-x** [comment]
Sorry I had messed up my config. Closing this (non-)issue and thank you for this great project

**Comment by Minoru** [comment]
Ah, okay. Glad you resolved it! :+1:
