### ISSUE TITLE
Version 2.11 binary reports as version 2.10.2

### ISSUE THREAD

**Issue by ryantm** [newsboat/newsboat#154]
Hi.

When packaging newsboat 2.11 for NixOS, we noticed that `newsboat -v` reports the version number to be 2.10.2. Also the case for Arch's AUR packaging. More details are available here: https://github.com/NixOS/nixpkgs/pull/37979#issuecomment-377344356

Are we packaging it wrong? Can you confirm this issue?

**Comment by Minoru** [comment]
Yes, that was an error on my part—for whatever reason, I packed the tarball *before* the commit that updated the version. Sorry about that. I've just pushed out a hotfix release, 2.11.1, that addresses this problem.

Thank you for packaging Newsboat for NixOS, by the way—I'm a happy user when I'm not running my own build from Git.
