### ISSUE TITLE
Add FreshRSS/Fever API support

### ISSUE THREAD

**Issue by PetraOleum** [newsboat/newsboat#1544]
What would it take to add FreshRSS support? I've enjoyed using newsboat in the past, but my feeds are on my freshrss instance these days.

**Comment by Minoru** [comment]
Hi! https://freshrss.github.io/FreshRSS/en/ says they implement a "“Google Reader”-like API", and Newsboat already supports a number of such services. Can you please try [our instructions for Bazqux](https://newsboat.org/releases/2.23/docs/newsboat.html#_bazqux) and report how well they work for FreshRSS? If they work, then supporting FreshRSS is just a matter of adding a new section to the docs.

(Perhaps in the future we'll add separate settings for all services, even if they all use the same API, but I haven't decided on this yet. Any thoughts on that are welcome too!)

**Comment by PetraOleum** [comment]
Hi!

Pointing the `feedhq-url` field at `https://[u.r.l]/api/greader.php` does successfully allow a log in and for the titles of the feeds to be loaded (though not the tags/folders), which is better than I expected, however no feed contents load when refreshing individual or the entire set of feeds. 

Specifically I get errors along the lines of `Error while retrieving https://[u.r.l]/api/greader.php/reader/atom/feed%2F14?n=20: HTTP response code said error 400`, which is the same error I get when navigating to that link via browser - even when removing the "reader" and the "atom" portions. It seems clear that freshrss and feedhq have a different idea of what a greader api is, unfortunately!

As a much less severe error, the feedhq setup adds spurious "people you follow", "starred items", and "shared items" feeds at the  top of the feed list, which give errors along the lines of `Error while retrieving http://feedhq.org/reader/atom/user/-/state/com.google/starred: HTTP response code said error 403`.

**Comment by Minoru** [comment]
Yup, it looks like [FreshRSS doesn't implement `reader/atom` endpoint](https://github.com/FreshRSS/FreshRSS/blob/master/p/api/greader.php), so none of Newsboat's existing integrations will work.

Well then, someone would have to write a new integration, taking FeedHQ as example, but replacing the HTTP calls with something that FreshRSS implements. And then commit to maintaining it, i.e. respond to user questions and fix any bugs that crop up. I'll of course handle the general questions.

Or if that's easier, add support for `reader/atom` on the FreshRSS side, and document how to use FeedHQ integration with it (or some other, that doesn't add the tree special feeds).

**Comment by PetraOleum** [comment]
It looks like the call needs to be along the lines of `https://[u.r.l]/api/greader.php/reader/api/0/stream/contents/feed/14`, however this produces json output and it looks like newsboat wants xml/the raw rss feed?

**Comment by PetraOleum** [comment]
By cannibalising code from some of the other integrations that do use json I've [got to the point](https://github.com/PetraOleum/newsboat/tree/freshrss) where I can at least load and parse feeds. I'll come back to it later and see what I can do to improve that.

**Comment by PetraOleum** [comment]
I've implemented read status, categories/tags, starred/favourited articles, and podcast enclosures, along with a bit of basic documentation. Should I make a pull request? I can probably fix bugs going forward, at least so long as it's still C++ (I need to learn Rust someday, but that's another story).

Also, from poking around I expect the feedhq starred articles feed is broken for standalone instances, but I don't have one to test.

**Comment by Minoru** [comment]
Awesome! Yeah, sounds like a great time to send a pull request :)

> Also, from poking around I expect the feedhq starred articles feed is broken for standalone instances

What makes you suspect that? I don't have an instance to test on either, but I can at least double-check your findings.

**Comment by PetraOleum** [comment]
In [src/feedhqurlreader.cpp Line 22-28](https://github.com/newsboat/newsboat/blob/master/src/feedhqurlreader.cpp#L22) the urls for the "people you follow", "starred items", and "shared items" feeds I mentioned earlier are hardcoded to the feedhq.org url:

```
#define BROADCAST_FRIENDS_URL                                    \
	"http://feedhq.org/reader/atom/user/-/state/com.google/" \
	"broadcast-friends"
#define STARRED_ITEMS_URL \
	"http://feedhq.org/reader/atom/user/-/state/com.google/starred"
#define SHARED_ITEMS_URL \
	"http://feedhq.org/reader/atom/user/-/state/com.google/broadcast"
```

 In my freshrss code I've removed the domain part and used `cfg->get_configvalue("freshrss-url") + STARRED_ITEMS_URL`, though I don't know if that's the safe way to do it.

**Comment by PetraOleum** [comment]
> Awesome! Yeah, sounds like a great time to send a pull request :)

I'll submit it then :)

**Comment by Minoru** [comment]
Yeah, these URLs look suspicious. I filed #1562 about this. Thanks for spotting the issue!
