### ISSUE TITLE
Improve the message that nudges users towards `cleanup-on-quit yes`/`newsboat --cleanup`

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1548]
> Would it be possible to improve this by also stating, which feed the unreachable items belong to? Or more generally, the general reason?
> 
> I encountered this message the first time today and did not know whether this is to be expected or if this is a critical error.
Searching for "unreachable" in the log file didn't reveal anything either, so I think at least some kind about how to find out more about the issue would be good.
As it is now (from a pure user perspective), this is well-intended but I had to find this issue first.

_Originally posted by @mbwgh in https://github.com/newsboat/newsboat/issues/1359#issuecomment-805977514_

**Comment by Minoru** [comment]
@mbwgh, thanks for reporting this!

> Would it be possible to improve this by also stating, which feed the unreachable items belong to?

Yes, I think that's pretty simple to do: we're already running a query to count the feeds, so we can change that to collect the URLs of the feeds, and list them after the message. I'll take a PR adding that :)

> Or more generally, the general reason?

Well, I guess, but it's hard for me to imagine what we have to say. From my point of view, if a user disabled `cleanup-on-quit`, they knew why, so when this message warns them of consequences, they should just go "oh, right, so let's run `--cleanup` then" or "oh, right, I don't need this anymore, let's re-enable `cleanup-on-quit`".

If you can suggest what we should actually add to the message, that'd be great!

**Comment by mbwgh** [comment]
> Yes, I think that's pretty simple to do: we're already running a query to count the feeds, so we can change that to collect the URLs of the feeds, and list them after the message. I'll take a PR adding that :)

Sounds great. I might even give it a shot, since this doesn't sound terribly complicated.

> Well, I guess, but it's hard for me to imagine what we have to say. From my point of view, if a user disabled cleanup-on-quit, they knew why, so when this message warns them of consequences, they should just go "oh, right, so let's run --cleanup then" or "oh, right, I don't need this anymore, let's re-enable cleanup-on-quit".

I did indeed disable cleanup-on-quit, originally as a workaround for #685. But even after this issue was presumably fixed, I decided against re-enabling it, just in case either something like the aforementioned issue happens again, or I decide to add a previously removed url to my feed list again, in which case I would like to still see the old entries.

But to be honest, I totally forgot about that, since I don't tend to mess with configs that work :)

So, assuming that this is the only way this situation can occur, I think it could look something like this:

```
There are items belonging to the following feeds which are no longer reachable:
  1. https://some/feed.xml
  2. https://another/feed

Did you set 'cleanup-on-quit no'?
Consider setting ... (the message we already have).
Alternatively, you may set 'notify-unreachable-feeds no'.
```

What do you think?

**Comment by Minoru** [comment]
I agree with the "list the feeds" part, but I have concerns about other changes.

> Did you set 'cleanup-on-quit no'?

This question seems superfluous. Newsboat already knows what the config value is, so why ask the user? Shouldn't the message explain what's "wrong" with having unreachable items instead?

> Alternatively, you may set 'notify-unreachable-feeds no'.

That's a good point. I didn't consider what should people do if they are okay with the situation, but don't want to see the message. I feel like an additional option doesn't quite cut it; I can almost feel like someone is already asking for an option to suppress the message *unless* the set of unreachable feeds changes (or some other condition).

**Comment by mbwgh** [comment]
> That's a good point. I didn't consider what should people do if they are okay with the situation, but don't want to see the message. I feel like an additional option doesn't quite cut it; I can almost feel like someone is already asking for an option to suppress the message unless the set of unreachable feeds changes (or some other condition).

It surely wouldn't be too hard to make it `notify-unreachable-feeds (yes|no|on-change)` or something, but isn't this kind of an edge case already? I don't know how many people use the `cleanup-on-quit` option, but if there are unreachable feeds because of it, there isn't something inherently "wrong" about it, but the feature is rather working as intended.

Even if not all possible use cases are covered yet, this should not preclude the possibility to silence this warning I think.

**Comment by Minoru** [comment]
What worries me is that people will disable `cleanup-on-quit` and suppress the warning, and then we're back to pre-2.23 situation which prodded us to add a warning in the first place. So I'm trying to think what new misunderstandings and bugs this might cause.

Also, new options are practically impossible to take out, so it always puts me on edge when one is proposed :)

Perhaps instead of suppressing the warning, we should make it *less* wordy? For example, just one line saying "There are N unreachable feeds in the database. See `cleanup-on-quit` in newsboat(1) for details.". This won't be very obtrusive, but will keep the user in the loop, and will also explain where to find additional info.

**Comment by mbwgh** [comment]
> Perhaps instead of suppressing the warning, we should make it less wordy? For example, just one line saying "There are N unreachable feeds in the database. See cleanup-on-quit in newsboat(1) for details.". This won't be very obtrusive, but will keep the user in the loop, and will also explain where to find additional info.

This would probably suffice, yes. And it would still be possible to emit the affected feeds in a logfile.
