### ISSUE TITLE
Replace rand crate with fastrand

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1550]
We're only using `rand` crate in a single place in the "production" part of our Rust code:

https://github.com/newsboat/newsboat/blob/f2a9fd644946d1a64a40c50919b7b749e8934063/rust/libnewsboat/src/utils.rs#L249-L251

(And also in tests, but those are only compiled by developers and, sometimes, package maintainers, so are less of an issue.)

Yet this crate is quite heavy: according to cargo -Z timings, it accounts for 8.9 seconds of CPU time on my machine (including `getrandom`).

We should replace it with https://crates.io/crates/fastrand, which is smaller. It's not a cryptographically secure RNG, but since we're using it for shuffling items, it's fine.

We also transitively depend on `rand` via `gettext-sys` because `tempfile` depends on `rand`. So if you're feeling adventurous, go push https://github.com/Stebalien/tempfile/pull/118 to the completion too :)

The Newsboat part of the work sounds simple enough, so this is a "good first issue". Please drop a comment here if you need more advice or run into some trouble!

**Comment by Minoru** [comment]
Stebalien/tempfile#118 got replaced by https://github.com/Stebalien/tempfile/pull/141, which only enabled a couple features on the rand crate. We could do the same here.

**Comment by amritbrar** [comment]
> (And also in tests, but those are only compiled by developers and, sometimes, package maintainers, so are less of an issue.)
Should `fastrand` also be used in tests so that `rand` can be completely removed?
