### ISSUE TITLE
Default for 'article-sort-order' is actually 'date-asc' (yet sorts in descending order anyway)

### ISSUE THREAD

**Issue by PetraOleum** [newsboat/newsboat#1560]
I was trying to figure out how to set the default ordering of articles to ascending by date (just to try it out, since in that order 'n' moves forward in time). I tried `article-sort-order "date-asc"` as implied by the man page, but this didn't work.

> article-sort-order (parameters: <sortfield>[-<direction>]; default value: date)
> The <sortfield> specifies which article property shall be used for sorting, currently available are: `date`, `title`, `flags`, `author`, `link`, `guid` and `random`. The optional <direction> specifies the sort direction. `asc` specifies ascending sorting, `desc` specifies descending sorting. Note that direction does not affect `random` sort order. For `date`, `desc` is default, for all others, `asc` is default.

In fact, the code gives "date-asc" as the default, and in practice both "date" and "date-desc" reverses the order to ascending.

```
// src/configcontainer.cpp line 26-28
	{
		"article-sort-order",
		ConfigData("date-asc", ConfigDataType::STR)},
```

**Newsboat version**:

```
newsboat r2.23-22-g3bdab - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat r2.23-22-g3bdab
System: Linux 5.10.23-1-MANJARO (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.75.0 OpenSSL/1.1.1j zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 (compiled with 7.75.0)
SQLite: 3.35.1 (compiled with 3.35.1)
libxml2: compiled with 2.9.10
```

Config file:

```
article-sort-order "date-asc"
```

This is very minor and I don't know if you even want to bother fixing it, but I thought I'd best mention it.

**Comment by Minoru** [comment]
> This is very minor and I don't know if you even want to bother fixing it, but I thought I'd best mention it.

No, no, thank you! Even minor bugs are worth fixing. Also, [I promised to look into this 4 years ago](https://github.com/akrennmair/newsbeuter/issues/76)… Oops!

I wouldn't risk changing the default, or even the behaviour of `date-asc`/`date-desc`. Instead, I'll update the docs to better explain the situation. I'll submit a PR shortly.
