### ISSUE TITLE
open-in-browser-noninteractively causes newsboat's terminal to stop rendering

### ISSUE THREAD

**Issue by samhh** [newsboat/newsboat#1568]
Version: 2.23.0

Config:

```
browser xdg-open %u
confirm-exit yes
text-width 80

bind-key j down feedlist
bind-key k up feedlist
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key j down article
bind-key k up article
bind-key g home
bind-key G end
bind-key o open-in-browser-noninteractively
bind-key ESC quit
```

Steps to reproduce the issue:

1. Enter any article.

2. Type "o" to trigger `open-in-browser-noninteractively`.

3. Focus newsboat/its terminal again and run some commands, for example "q q q y" to quit. It will quit, but you won't see that rendered until the browser process has ended. You can continue to enter arbitary input to the underlying terminal, for example "notify-send x<Enter>", and this will all be processed once the browser process has ended and newsboat has quit.

I've tried a few variations on the `browser` config value, including appending `&` and `& disown`, removing `%u`, and directly opening different browsers (vimb, firefox-developer-edition).

This is on Arch Linux with everything up to date. I can reproduce this behaviour in both Alacritty and xterm and each of fish and bash.

**Comment by Minoru** [comment]
I didn't try to reproduce, but I think I see the problem already: this line

```
browser xdg-open %u
```

tells Newsboat that the "browser" is "xdg-open". The "%u" is ignored. I guess that's what tripped you up when you added `&` and other stuff — all of that was ignored.

The correct incantation is `browser "xdg-open %u &"` — note the double quotes around the setting's value. Can you please try that and confirm that it does work?

Of course, the proper fix on Newsboat's side is to add a check for this situation (settings stored in the `ConfigContainer` have exactly one value, so it should fail if the config provides more than one value.)

**Comment by samhh** [comment]
[Success!](https://github.com/samhh/dotfiles/commit/5472b9c91118e821e28418b9dbf9fc8eaf21f693) Cheers :slightly_smiling_face:

**Comment by Minoru** [comment]
Excellent! I submitted a pull request that adds an error for such cases: #1571. You would be the last person to fall into this pitfall, hopefully ^_^
