### ISSUE TITLE
turses

### ISSUE THREAD

**Issue by annata83** [newsboat/newsboat#1591]
newsboat 2.23.0

Hey newsboat;
Trying to achive twitter acces thru turses just like I use TUIR for reddit;

Here are the macros:

* Reddit TUI (Working good)
macro r set browser "tuir" ; open-in-browser; set browser "w3m %u"
* Twitter TUI (error code 2)
macro f set browser "turses" ; open-in-browser ; set browser "w3m %u"

And I get this error at the bottom of the newsboat UI:

`Browser returned error code 2`

How can I go about Debugging for this?

Thanks.

**Comment by Minoru** [comment]
Hi! Well, if Turses returns an error code, why do you ask *us* about it? :) Turses issue tracker would be a better place to ask.

From what I see in their code, this error can mean either:

1. turses couldn't generate a config: https://github.com/louipc/turses/blob/6c3c7befbdb2defa786caabae2c7443c324d06db/turses/config.py#L685
2. turses couldn't authorize with Twitter: https://github.com/louipc/turses/blob/6c3c7befbdb2defa786caabae2c7443c324d06db/turses/config.py#L782

So the first step in debugging this is to make sure that something like `turses https://twitter.com/icfpcontest2020/status/1285233054705950721` starts without errors and displays the tweet. Then you can go back to Newsboat macro and see if it still fails.
