### ISSUE TITLE
Decide if we should drop support for "common but unknown entities" in TagSoupPullParser

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1602]
`TagSoupPullParser::decode_entity()` contains a curious `switch` statement which "convert(s) some common but unknown numeric entities":

https://github.com/newsboat/newsboat/blob/357af21d80a296d1b05c6285eb2321be41f303ea/src/tagsouppullparser.cpp#L453-L479

As far as I understand, these entities come from the dawn of Web, when Windows folks tended to include codepoints specific to Windows codepages: https://jkorpela.fi/www/windows-chars.html#list I'm not sure how relevant this is today, and I'm slightly worried that we're stamping over the perfectly valid Unicode codepoints with this `switch`.

**Comment by the-blank-x** [comment]
Seems like the standard says to convert those codepoints: https://html.spec.whatwg.org/multipage/parsing.html#numeric-character-reference-end-state

**Comment by Minoru** [comment]
That's a great find, thank you! I think the best way to close this issue, then, is to make our `switch` match the spec exactly, i.e. add all the missing `case`s. Would you send a PR so you get credited for all the work? ;)
