### ISSUE TITLE
snownews mentions in documentation need update

### ISSUE THREAD

**Issue by msharov** [newsboat/newsboat#1607]
The snownews project no longer bundles sample filter scripts in contrib. Your website [links to them directly](https://github.com/kouya/snownews/tree/master/contrib) and to [the webpage explaining them](https://web.archive.org/web/20090724045314/http://kiza.kcore.de/software/snownews/snowscripts/writing). If you want to keep these scripts and the writing doc, I would encourage you to copy them to your own repository.

The current version of snownews (now at https://github.com/msharov/snownews ; I've taken over as maintainer) still supports both filters and execurls, and does explain (but not encourage) their use in the README. Previously these were required to support Atom feeds and https. Because snownews now natively reads Atom and does https via curl, the need for external apps has been greatly diminished.

Your webpage also mentions the snow2opml script in [section 3.5.2](https://newsboat.org/releases/2.23/docs/newsboat.html#_other_readers_via_opml), for migrating from "Other Readers". snow2opml was removed because since v1.7, snownews stores its subscription list natively in OPML, in `~/.config/snownews/urls.opml`. You may want to either update the instructions or have both.

**Comment by Minoru** [comment]
Thanks for the heads-up! I opted to update the links for now (see #1612), using older commits where the scripts are still present. Perhaps one day we'll write our own docs for this stuff, but until then, it'll have to do :)
