### ISSUE TITLE
Search using regexp?

### ISSUE THREAD

**Issue by Boruch-Baum** [newsboat/newsboat#1610]
newsboat 2.13.0 - https://newsboat.org/
System: Linux 5.4.0-4-amd64 (x86_64)
Compiler: g++ 8.3.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.7.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.43.0 librtmp/2.3 (compiled with 7.64.0)
SQLite: 3.34.1 (compiled with 3.27.2)
libxml2: compiled with 2.9.4

Is it possible to search articles using regexp? I've tried using the '/' command, and that doesn't work. For example:

    /20[0-9][0-9],

**Comment by Minoru** [comment]
`/` can't do this, but you can use a filter instead: press `F` and type something like `content =~ "20[0-9][0-9]"`.

**Comment by Boruch-Baum** [comment]
Thank you. The method works.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
