### ISSUE TITLE
Weird colouring of unread items using dark solarized and Alacritty terminal 

### ISSUE THREAD

**Issue by sandersantema** [newsboat/newsboat#163]
newsboat 2.11.1
System: Darwin 16.7.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
*I actually discovered I had a very old version of ncurses but after many tries I still can't get brew to build newsboat with ncurses 6.1*
libcurl: libcurl/7.54.0 SecureTransport zlib/1.2.8 (compiled with 7.51.0)
SQLite: 3.16.0 (compiled with 3.16.0)
libxml2: compiled with 2.9.4
Steps to reproduce the issue:

1. Add the solarized dark config, or as far as I know it could be any other colour-scheme

2.  Unread items look weird as seen here:
https://asciinema.org/a/YJxmXYRSgZwMztfmzTJp7XdNV

Asciinema doesn't record the colour-scheme of my terminal but the effect stays the same. 

3. I fixed this by adding this to my config:
```
color listfocus_unread  black     yellow
```

Is this caused by my old ncurses version? And is there any way to build against the newer ncurses? 

I've tried adding this to my config.fish but these environment variables don't seem to make a difference:
```
set -g fish_user_paths "/usr/local/opt/ncurses/bin" $fish_user_paths
set -Ux PKG_CONFIG_PATH /usr/local/opt/ncurses/lib/pkgconfig
set -Ux LDFLAGS "-L/usr/local/opt/ncurses/lib"
set -Ux CPPFLAGS "-I/usr/local/opt/ncurses/include"
```

Brew does let you edit the formula but I couldn't figure out how that would work. Compiling newsboat myself and editing the make file leads to all sorts of other troubles.

**Comment by Minoru** [comment]
Hi!

> Is this caused by my old ncurses version?

No, it's just stale files. `listfocus_unread` have been added a few months after the colorscheme has been updated, and changed its look. I'm surprised no-one reported this over the last five years. Thank you for reporting it and providing the fix!

> And is there any way to build against the newer ncurses?

It should be as simple as installing ncurses along with its header files, and then compiling Newsboat. It'll find the headers and the library, and use it. I'm not sure where the files are being put on MacOS, so I can't help you much there. Newsboat uses pkg-config to figure everything out, so make sure that command works.
