### ISSUE TITLE
toggle-article-read "read" marks as unread when viewing an article

### ISSUE THREAD

**Issue by ysh16** [newsboat/newsboat#1637]
**Newsboat version**: newsboat 2.23.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
macro x toggle-article-read "read"
```

Steps to reproduce the issue:

1. View an article
2. Run the above macro

I am then dropped back to the article list view with the article being marked unread.

While this feature does not seem to be documented (#1336), I expect it is meant to leave the article marked as read in this case.

After limited inspection, the following seems to be the culprit of this:
https://github.com/newsboat/newsboat/blob/master/src/itemlistformaction.cpp#L215
https://github.com/newsboat/newsboat/blob/master/src/itemviewformaction.cpp#L408
Looks like arguments are only considered in the item view.

**Comment by Minoru** [comment]
Thank you for the report! I didn't try to reproduce, but it's obvious from the code that you're right. I agree that this should behave the same across the dialogs. Since you've already identified the place in the code, would you like to send a pull request fixing it? ;)
