### ISSUE TITLE
Migrate our IRC channel off Freenode

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1643]
[Freenode is being taken over](https://blog.bofh.it/debian/id_461) by some for-profit organization. Most (all?) of the staff resigned, and some of them stood up a new network, [libera.chat](https://libera.chat). The motives and goals of new Freenode owners are unclear; the new owner certainly can't be trusted to keep their promises (they promised to not interfere with operations, but that's what they're doing now). I think we should move elsewhere.

We already discussed this on IRC, and have something of a requirements list:
- there must be a way for us to register the channel and ensure that we can recover access if something happens (this means ChanServ and, preferably, project registration);
- the new network should be somewhat popular, so as many people as possible can join in with little hassle;
- there should be a webchat, for those who have a one-off question and don't want to learn IRC;
- it'd be nice if the network has documented its governance, so we can tell if they're susceptible to the same problem as Freenode;
- it'd be nice if the network has a bridge with matrix.org, so Matrix users can join the discussion.

Does anyone see more requirements to add?

## Current candidates

1. [**OFTC**](https://oftc.net/):
    - has ChanServ, but [channels are registered on the first-come-first-serve basis](https://oftc.net/Network_Policy/). If we lose it and don't recover in time, it'll be up for grabs;
    - [fourth most popular IRC network](https://netsplit.de/networks/top10.php?year=2021) (second and third place, IRCnet and Undernet, don't seem to be targeted toward FLOSS);
    - has webchat.oftc.net ([it was broken, but promptly fixed](https://github.com/oftc/oftc/issues/4));
    - has [a constitution](https://oftc.net/constitution/). The domain is managed by a well-known American non-profit, SPI, which enforces the Constitution;
    - matrix.org has a bridge.
2. [**Libera.chat**](https://libera.chat/):
    - has ChanServ, [the rules](https://libera.chat/chanreg) say that we can get #newsboat (and all channels starting with `#newsboat-`) simply by asking. We'll provide contacts, and even if we lose everything, I expect we can regain the channel just as easily — as long "we" are the project named "Newsboat";
    - not very popular at the moment, but as a successor to Freenode, ran by former Freenode staff, IMHO it's poised to grow rapidly;
    - has no webchat, but [I asked for it to be added](https://github.com/Libera-Chat/libera-chat.github.io/issues/19);
    - only has a privacy policy, doesn't even have a list of people involved. Managed by a Swedish non-profit established just for this. [I asked for them to better document their governance](https://github.com/Libera-Chat/libera-chat.github.io/issues/18);
    - *vanity bonus*: since we're a registered project, we can provide cloaks, so e.g. I can appear to connect from ~minoru@newsboat/minoru rather than ~minoru@1.2.3.4 (not my real IP);
    - there is no matrix.org bridge, but [I asked them for one](https://github.com/Libera-Chat/libera-chat.github.io/issues/20).

Are there any other networks that fulfil the above requirements?

## Timeline

Let's reach the decision by June 5th.

Libre.chat will take unknown amount of time to gain popularity, update docs, and add webchat. Freenode will not burn down today or tomorrow, but might become unstable soon (it's unclear if there are any competent people running it now). Our next release, 2.24, is scheduled for June 20th. If we decide by June 5th, that gives me a day to prepare, submit, and merge a PR to update the channel address in the docs and in `--version`. On June 6th, I'll re-generate POT files and ask translators to update their PO files; those updates must include the new address.

## The elephant in the room

Should we migrate to [Matrix](https://matrix.org/) instead? It grows in popularity as a more modern protocol, and it works, but there are also concerns about it being too dependent on Vector (a company that spearheads the development), and I haven't found a client that lets me pretend that Matrix is IRC :) I think migrating to it would be premature, but I'd like to hear your thoughts. (2 out of 68 people currently in the IRC channel joined via a Matrix bridge).

**Comment by Minoru** [comment]
IRC discussion so far: three persons spoke up; two of them are already on OFTC, the other one is at on hacking, libera and ircnet. All three are okay with whatever open network we choose.

**Comment by demure** [comment]
Personally I don't find matrix to be an IRC replacement. Perhaps if there more clients (including CLI) that actually worked...
Anyway, just my 2cents.

**Comment by Minoru** [comment]
My two cents: if Freenode died without a successor, OFTC would be a no-brainer. I like that they have formal governance document and are managed by a non-profit. They're also been doing this for over 10 years, and still exist, and are used by projects like Debian. They appear to be a reliable network.

However, Freenode — or, more precisely, former Freenode staff that now runs Libera.chat — served Newsboat fine over the years, and I've been on their network even longer than that. Now that they've been burned by this governance and ownership problem, they're bound to improve even further. The only way Libera.chat could die now is if people decided not to migrate there, or if (undocumented) hardware sponsors pulled support. It feels a bit like betrayal not to choose them :)

**Comment by Minoru** [comment]
On IRC, two more votes against Matrix.

**Comment by Minoru** [comment]
I squatted our channel both on Libera.chat and OFTC. The former required talking to an op, and now it'll feel even more of a betrayal if we don't go with them >_<

**Comment by Minoru** [comment]
Updated top post to mention that Libera.chat lets us provide cloaks, so e.g. I can appear to connect from ~minoru@newsboat/minoru rather than ~minoru@1.2.3.4 (not my real IP). There are gotchas with how this is applied, so it's no good as a security thing, but could sway the decision for some :)

**Comment by mrrcollins** [comment]
I can go with either, so take that vote as you want. :-) But, I would vote against Matrix.

As for a web client, Kiwiirc offers one that connects to any, without any registration required. For example:
https://kiwiirc.com/nextclient/irc.libera.chat/#newsboat

**Comment by demure** [comment]
> I can go with either, so take that vote as you want. :-) But, I would vote against Matrix.
> 
> As for a web client, Kiwiirc offers one that connects to any, without any registration required. For example:
> https://kiwiirc.com/nextclient/irc.libera.chat/#newsboat

Re Miscellaneous web irc clients (non irc Network provided):
As an IRC Oper, free tier web irc clients frequently earn server/network wide bans due to abuse.
At least some of these web irc services make the free accounts distinct from registered/paying users, but it might not be a good idea to count on a third party web UI that is public opened for free.

**Comment by Minoru** [comment]
Meanwhile, a user popped into chat to ask a question (this really happens!), I asked them about their preferences, and they're already on hackint and quakenet.

**Comment by amritbrar** [comment]
Even though I haven't participated on IRC, it's probably best sticking with it and switching to OFTC. If in the future you want to use Matrix/Element, you can always bridge to IRC (many Matrix rooms do this).

**Comment by Minoru** [comment]
I added a soft requirement for a Matrix bridge, because we do have two users who join from Matrix, and one of them spoke up asking me to look into this. matrix.org has a bridge for OFTC but not Libera.chat. (As far as I understand, users on different homeservers can use the bridge on matrix.org, too, but I didn't test this.)

In fact, I got asked to look at room bridging, i.e. joining an IRC channel with a Matrix room. My findings (some of which are just confirmations of what was already mentioned in IRC discussion about this):
- messages longer than three lines are sent from Matrix to IRC as links;
- Matrix stickers are not propagated at all. This won't be a problem if we don't add any sticker packs to the Matrix room (AIUI users can't bring their own packs?);
- formatting (`*bold*`, `_italics_`, ``` `code` ```) works okay: IRC and Matrix exchange plain text. On the Matrix side, Matrix messages are formatted, while IRC messages stay as plain text;
- actions (/me) are propagated fine;
- nick  highlighting works;
- file uploads in Matrix are sent to IRC as links, too, and mention the upload type (e.g. "image") and size;
- I do sometimes see a couple seconds of delay between me saying something via webchat or Irssi, and the message appearing in Element;
- it appears you have to be on IRC to kick IRC users. Kicking IRC user from Matrix only kicks their "puppet", which does nothing on the IRC side; on Matrix side, the puppet re-joins when the IRC user says something. Kicking IRC user from IRC of course works, and the message is propagated to Matrix. I don't have a second Matrix account to test how the equivalent action on Matrix works, but it's probably the same. The upshot of this is that mods have to be present on *both* sides of the bridge;
- topics are propagated from Matrix to IRC, but not the other way round. If the room topic is multi-line, only the first line is used on IRC.

My conclusion so far is that I would rather see Matrix users connect on a per-user basis, by joining #_freenode#newsboat:matrix.org. That way, Matrix users are aware they're talking to a different network, which should prepare them for the aforementioned quirks with multi-line messages and formatting.

**Comment by Minoru** [comment]
On IRC, a vote for Libera.chat over OFTC.

**Comment by Minoru** [comment]
Filed a couple issues with OFTC and Libera.chat:
- https://github.com/oftc/oftc/issues/4 to report OFTC webchat is broken;
- https://github.com/Libera-Chat/libera-chat.github.io/issues/18 to ask Libera.chat to better document their governance;
- https://github.com/Libera-Chat/libera-chat.github.io/issues/19 to ask Libera.chat for a webchat;
- https://github.com/Libera-Chat/libera-chat.github.io/issues/20 to ask Libera.chat for a Matrix.bridge.

**Comment by Minoru** [comment]
For the record: I considered emailing our list about this, and posting an entry in our Atom feed, but decided against. I think the people who are actually *using* our IRC channel have the voice; others might have an opinion, but it's less relevant. I realize this excludes people who never joined our channel because it's hosted on Freenode, but since they never mentioned it via other communication channels, it's probably not *that* important.

**Comment by Minoru** [comment]
Another vote of indifference on IRC.

**Comment by PopeRigby** [comment]
I'm voting on at least having an native Matrix room bridged with IRC, because I know some people don't want to leave IRC.

**Comment by Minoru** [comment]
@PopeRigby See https://github.com/newsboat/newsboat/issues/1643#issuecomment-845107556 above (which is mostly a copy-paste from the IRC). Matrix.org has a bridge for OFTC, but not Libera.chat; [I asked the latter to add it](https://github.com/Libera-Chat/libera-chat.github.io/issues/20).

**Comment by Minoru** [comment]
On IRC, one more vote for Libera over OFTC.

**Comment by PopeRigby** [comment]
> As far as I understand, users on different homeservers can use the bridge on matrix.org, too, but I didn't test this.

This is correct.

**Comment by Minoru** [comment]
Libera.chat [published](https://libera.chat/bylaws) their bylaws, and even though they haven't yet responded to my issue about the webchat, I'm now confident they'll be a good network to stick around. So my vote goes to Libera.chat. (But I'll still wait until the promised deadline to see what others think — not that many people spoke up).

**Comment by Seirdy** [comment]
Freenode staff is automatically shutting down any channel with the word "libera" in the topic and replacing the topic. `#newsboat` just got shut down an hour ago, and the topic now reads `This channel has been reopened with respect to the communities and new users. The topic is in violation of freenode policy: https://freenode.net/policies`. Nobody can speak in `#newsboat` anymore.

Wikimedia, Frosted, and other channels have shared a similar fate.

So yeah, a move needs to happen ASAP now since currently the Newsboat Freenode channel is closed, directing users to another channel being operated by a hostile party.

**Comment by Minoru** [comment]
Okay. So far:
* we've got 31 nicks on Libera.chat compared to 4 on OFTC
* Libera.Chat is now almost as big as OFTC: average of 13,511 users compared to OFTC's 16,583 users. Peaks at 16,713 users on Libera and 17,967 on OFTC (all stats according to netsplit.de)
* votes are 3 for Libera, 5 indifferent, plus a few mentions of other IRC networks which I discarded as too small (hackint) or not topical (quakenet)

Let's migrate to Libera.Chat then.

Libera still doesn't have a Matrix bridge, but both parties had a meeting and things are afoot. Meanwhile, @PopeRigby can join #newsboat:matrix.org; it's not bridged anywhere, but we can use it to coordinate. I'm not ready to make Matrix one of our primary channels, so don't spread the word too far please :)

#newsboat on OFTC is still registered to me. If any of you wants to build a community channel, I'll hand the registration over to you. Otherwise I'll just drop it in a few weeks.

I'll now make a PR to update the docs, and write an email and Atom entry about this. I also intend to go through all docs for all versions on newsboat.org and update the network name there.

Anything else I forget?

**Comment by Minoru** [comment]
For posterity:

```
<Minoru> info #newsboat
-ChanServ(ChanServ@services.)- Information on #newsboat:
-ChanServ(ChanServ@services.)- Founder    : Minoru, nikos
-ChanServ(ChanServ@services.)- Successor  : freenode-placeholder-account
-ChanServ(ChanServ@services.)- Registered : Sep 12 19:35:02 2017 (3y 21w 4d ago)
-ChanServ(ChanServ@services.)- Mode lock  : +ntc-slk
```

And now:

```
<Minoru> info #newsboat
-ChanServ(ChanServ@services.)- Information on #newsboat:
-ChanServ(ChanServ@services.)- Founder    : freenode-placeholder-account
-ChanServ(ChanServ@services.)- Registered : May 26 03:05:48 2021 (9h 59m 24s ago)
```
