### ISSUE TITLE
open in browser opens in text based terminal application

### ISSUE THREAD

**Issue by nawtrobar** [newsboat/newsboat#165]
newsboat 2.11.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.11.1
System: Linux 4.16.0-999-lowlatency (x86_64)
Compiler: g++ 5.4.0 20160609
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libcurl: libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.23.1 (compiled with 3.23.1)
libxml2: compiled with 2.9.3

Steps to reproduce the issue:

1. select article with <enter>

2. select open in browser with <o>

Rather than open in a browser window, the article is displayed in the terminal with an application that uses text highlighting.

**Comment by Minoru** [comment]
Hi! That behaviour is expected—the default browser is lynx, since it's quite wide-spread. You can change it via [`browser` setting](https://newsboat.org/releases/2.11.1/docs/newsboat.html#browser) in your config.

**Comment by nawtrobar** [comment]
lol oops. Now I feel silly. I didn't know I could configure because it didn't say anything about that in the help page.

**Comment by Minoru** [comment]
You mean the man page? The option should be listed there in the "Configuration Commands" section.

Either way, don't beat yourself up over it—Newsboat is quite big, it's easy to become disoriented because of all the options and multiple ways to do stuff. ;)

**Comment by nawtrobar** [comment]
Funny enough I configured it fore firefox read a couple articles and switched back to lynx. lol.

**Comment by nawtrobar** [comment]
Is there a way to configure the reader to organize the feeds by topic?

**Comment by Minoru** [comment]
>Is there a way to configure the reader to organize the feeds by topic?

More than one! :)

You can add tags to your URLs file. When you start Newsboat, you'll go 
to the tags dialog and select the topic you want to view right now.

Alternatively, you can hide all your feeds (search for "hidden" in the 
docs) and add query feeds that aggregate individual feeds into topics. 
This way, you'll have your list of topics (query feeds) right upon 
startup—no need to open any additional dialogs.

**Comment by iknownothingaboutcomputers** [comment]
@nawtrobar Hi. I'd like to know how you configured Newsboat to launch Firefox. I want NB to do this for me, but, being a Linux newb, I don't know how to.

**Comment by Minoru** [comment]
@iknownothingaboutcomputers You need to put the following into your config (~/.newsboat/config or ~/.config/newsboat/config, depending on where your urls file is stored):
```
browser "/usr/bin/firefox"
```

If that doesn't work, you might need another path to Firefox. Use `whereis`:
```
$ whereis firefox
firefox: /nix/store/ass4dyg465wdmhw997k6bzqnjnxn8rcf-user-environment/bin/firefox
```

(I'm on NixOS, paths here are scary, yours will probably be much different.)

**Comment by nawtrobar** [comment]
Memory: 2114MiB / 7435MiB 
                                                                                                    Users: nawtrobar 
 
                                                                                                                            
 

Firefox should already be in their path though. So browser "firefox" should suffice.
