### ISSUE TITLE
Constant segfaults in view_dialogs

### ISSUE THREAD

**Issue by glacambre** [newsboat/newsboat#168]
**Newsboat version (copy from `newsboat -v`)**: newsboat r2.11.1-12-gcf845

Steps to reproduce the issue:

1. Set `swap-title-and-hints` to `yes` in your config

2. Start newsbeuter and press `v`

**Other info you think is relevant**:
A year ago I found that this was caused by a null pointer in the STFL. The dereference happens in STFL's `mydump()`, in dump.c:90 and can be prevented by adding `if (w == NULL) return;` on line 89. The null pointer is obtained in STFL'S `stfl_dump()` in public.c:200. I sent a patch to prevent this null dereference to the STFL mailing list a year ago but didn't hear back. Hopefully this bug is due to newsboat incorrectly using the STFL rather than the STFL incorrectly doing something and this can be fixed on newsboat's end :).

**Comment by Minoru** [comment]
Hi, thank you for the report! Indeed, it was us using the library incorrectly: we didn't name widgets that display title and hints. When Newsboat tried to swap them, it couldn't find them, and crashed. This error was present only in dialogs view.

I've fixed it now. Please build from commit a86eddde86ae3e881bfbc72f6cc68e3a6f1791a5 (which is current `master`).

**Comment by glacambre** [comment]
Wow, this was fast! I can confirm this bug doesn't happen anymore on `a86eddd`, thanks fixing this.
