### ISSUE TITLE
Passing additional arguments with notify-program

### ISSUE THREAD

**Issue by diskotechjam** [newsboat/newsboat#170]
**Newsboat version (copy from `newsboat -v`)**: newsboat 2.11.1

I'm trying to pass an icon to my notification daemon via notify-send. I placed this in my config but it doesn't seem to work...

notify-program "notify-send -i ~/.newsboat/rss.png"

**Comment by Minoru** [comment]
You should set `notify-program` to program's name or path, not a command. If you need additional arguments, put the whole thing into a script and use *that* as your `notify-program`. I think the setting is made this way to prevent shell escaping issues.

@diskotechjam, any suggestions on how we could update the documentation to make this point clearer?

**Comment by Minoru** [comment]
Hope #171 addressed the documentation problem. if not, and you have suggestions for better phrasing or whatnot—please shout!
