### ISSUE TITLE
Newsboat resetting gnome-terminal color palette

### ISSUE THREAD

**Issue by michaelhaaf** [newsboat/newsboat#1701]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

newsboat 2.18.0
System: Linux 5.4.0-77-generic (x86_64)
Compiler: g++ 9.3.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.68.0 GnuTLS/3.6.13 zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 (compiled with 7.68.0)
SQLite: 3.31.1 (compiled with 3.31.1)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# a comment
browser          lynx

```

Steps to reproduce the issue:

1. Precondition: have a nonstandard colour palette for gnome-terminal. For example, a theme chosen through [Pywal](https://github.com/dylanaraps/pywal)

2. Open newsboat in a terminal window

3. Close newsboat

4. Observe that the terminal color palette has been reset (see below)

![colourbug1](https://user-images.githubusercontent.com/8232471/125108817-8975d980-e0b0-11eb-88f8-ee5a3744e6f2.jpg)
![colourbug2](https://user-images.githubusercontent.com/8232471/125108814-8975d980-e0b0-11eb-8185-155cf230b7a2.jpg)

**Other info you think is relevant**:

- Only the terminal tab where newsboat opens is affected (other simultaneously open terminal windows and tabs are not affected)

I have so far not observed this behavior in any other text-based programs that make use of my terminal for display (lynx, htop, etc.) My current hypothesis is that newsboat silently sources a system wide bash configuration file that overrides my colour palette, but I'm having a difficult time proving this.

Edit:

I have experimented with alternate color configurations in the config file per the [documentation](https://newsboat.org/releases/2.24/docs/newsboat.html#_configuring_colors), however none of these configurations address the underlying problem that the palette used by the ANSI escape sequences itself has been changed.

**Comment by michaelhaaf** [comment]
I raised this issue too hastily. Alas, Github is preventing me from stealthily deleting it, so instead I'll provide a justification.

After a bit more experimentation, I think the issue is with gnome-terminal, not with newsboat. Newsboat appears to have the reasonable behavior of using gnome-terminal's "Profile" setting for display, which Pywal (or similar theme editors) cannot programmatically edit. So whatever "Profile" setting is chosen (regardless of Pywal configurations) will determine the color palette for newsboat. (you may notice in my screenshots that the color scheme displayed in the terminal after newsboat is Tango, I experimented with selecting the other default color schemes and observed that the terminal color scheme would match these after running newsboat).

I think I'll just switch to a terminal emulator that uses a programmatic configuration file like .Xresources. Hope this is helpful for someone else in the future.

**Comment by Minoru** [comment]
Hey, sorry for the late response! I'm glad you figured it out, since I probably wouldn't be able to :) And thanks for writing a detailed explanation, too!

**Comment by holmescharles** [comment]
I am also experiencing this issue. It occurs with GNOME terminal and alacritty.

```
newsboat 2.21.0
System: Linux 5.15.0-88-generic (x86_64)
Compiler: g++ 10.2.1 20201207
ncurses: ncurses 6.3.20211021 (compiled with 6.2)
libcurl: libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16 (compiled with 7.72.0)
SQLite: 3.37.2 (compiled with 3.34.0)
libxml2: compiled with 2.9.10
```

The best solution I can think of is something like a wrapper script like this:

```
#!/bin/sh
newsboat "$@"
cat ~/.cache/wal/sequences
```

...but this would still have the "wrong" colors while newsboat is running. Is there anyway to keep colors from updating to use the terminal defaults?
