### ISSUE TITLE
Is it possible to execute a script after auto-reloading?

### ISSUE THREAD

**Issue by ablearthy** [newsboat/newsboat#1703]
`Newsboat 2.24.0`

Config file:
```
auto-reload yes
reload-time 1
```

Is it possible to execute a script after reloading/auto-reloading? I want to download new articles in a specific way. `Newsboat` is running in background. 

How can I run custom script for a new articles after auto-reloading?

**Comment by Minoru** [comment]
It's not possible at the moment. What do you mean by "download new articles in a specific way"? Are you sure you can't achieve that by pre-processing the feed using `filter:`?

**Comment by ablearthy** [comment]
Here's an example.
urls:
```
https://news.ycombinator.com/rss
https://www.youtube.com/feeds/videos.xml?channel_id=UCBmwzQnSoj9b6HzNmFrg_yw "~Google Workspace (YouTube)"
```
After reloading I want to download new videos from YouTube via `youtube-dl` and download new articles from HackerNews via my custom script that downloads html + all media content.

**Comment by Minoru** [comment]
Okay. The YouTube feed is better processed outside of Newsboat: you'll be using `youtube-dl` to get videos and some media player to view them, so Newsboat will be just a glorified `wget`. Take a look at `rsstail`, or RSS parser libraries for your favourite programming language. I don't plan to make it possible to extend Newsboat in that direction.

The HN feed sounds like a perfect case for `filter:`, have you looked at that yet?

**Comment by ablearthy** [comment]
Hm, I think `filter:` is good thing for all my tasks. In YouTube case, the script can download videos and then return same output. 
```bash
CONTENT="$(cat -)"
download_videos "$CONTENT"
echo "$CONTENT"
```
What do you think about that?

**Comment by Minoru** [comment]
Well, `$CONTENT` would be an RSS/Atom feed, and you'll have to parse it. `rsstail` might be easier since it does the parsing for you, so all that's left is `grep` for enclosures and pass their URLs into `youtube-dl`.

**Comment by Minoru** [comment]
BTW, if you write a filter for Hacker News, please consider adding it to our contrib directory. I think it'll be a useful to those people whose feeds are too complicated for Newsboat's `download-full-page` setting (as HN feed seems to be).

**Comment by ablearthy** [comment]
Oh, I can parse "$CONTENT" with python so that's not a big problem. The main goal is to integrate this scripts with newsboat. Therefore, there will no additional services. I can easily modify `urls` file and that's all (like everything in one place)

**Comment by ablearthy** [comment]
> BTW, if you write a filter for Hacker News, please consider adding it to our contrib directory. I think it'll be a useful to those people whose feeds are too complicated for Newsboat's `download-full-page` setting (as HN feed seems to be).

I'm not good at writing scripts but I'll try my best!

**Comment by Minoru** [comment]
Cool, I guess this resolves the issue then.
