### ISSUE TITLE
Move configuration folder to XDG_CONFIG_HOME?

### ISSUE THREAD

**Issue by Kabouik** [newsboat/newsboat#1705]
Is there any reason to store configuration files directly in `~/.newsboat` instead of `~/.config/newsboat`? My understanding is the latter would be more standard and it would help users who get anxious when their `~/` gets cluttered by individual programs (like me!).

**Comment by ifohancroft** [comment]
Newsboat respects and uses the XDG Basedir spec if the variables $XDG_CONFIG_HOME and $XDG_DATA_HOME are set, however, unlike what the manual says, you have to have the newsboat folder created in those places or it will try to use your home dir directly.

**Comment by Kabouik** [comment]
Oh, that's excellent news. Thanks. I was just misled by the help and message when first running newsboat!

**Comment by Minoru** [comment]
@Kabouik, you will probably want to move your files, see [this section in the docs](https://newsboat.org/releases/2.24/docs/newsboat.html#_files) for how to do that.

@ifohancroft, thanks for answering this! Can you quote the part of the docs that's wrong or unclear on this? I'd like to improve the wording if possible. If you have specific ideas, you can just submit a PR and we'll discuss there :)

**Comment by ifohancroft** [comment]
@Minoru No problem.
Sure! I'd argue that Newsboat is wrong, not the documentation as I believe what the documentation states makes sense and should be how it works (I'd open a PR about that), but here is the part of the documentation and man page, that is not representative of what actually happens:

"If the XDG config directory exists, Newsboat will use XDG directories, creating the data directory if necessary."

In my case $XDG_CONFIG_HOME exists and is set to a folder that exists and is readable/writable by my user. In the terminal I executed newsboat I executed `echo $XDG_CONFIG_HOME` to make sure it's not the variable that's the problem, and I got `/home/ifohancroft/.config`

I executed newsboat and I was expecting that it would create a folder called 'newsboat' under $XDG_CONFIG_HOME, but instead and then complain about the missing urls file in there, but instead, it complained about missing urls file in /home/ifohancroft/.newsboat/urls

**Comment by Kabouik** [comment]
Note that on my end, both `XDG_CONFIG_HOME` and `XDG_DATA_HOME` are empty (but somehow most programs seem to have no issue to place their subfolders in `~/.config/` and `~/.local/share/`), but creating `~/.config/newsboat/` and `~/.local/share/newsboat` as @ifohancroft mentioned above worked: `newsboat` did not create a `~/.newsboat` when those folders existed prior to launch.

What got me confused is that when executing `newsboat` for the first time with no pre-existing configuration, it returns that URLs need to be added in the configuration file in `~/.newsboat/`.

**Comment by ifohancroft** [comment]
Yeah, I got confused about that as well. I was like: What?! I thought it uses XDG dirs? then I checked the manual, deleted the ~/.newsboat/ folder and ran it again. It again asked me for urls in ~/.newsboat/urls, then I have no idea how I got the idea to try and create the Newsboat folder to see if that would work and it did.

What you said about most dirs creating their own dirs in $XDG_CONFIG_HOME and $XDG_DATA_HOME - same on my end. This is the usual behavior. To be honest, software wanting its folder to already exist is the exception. If there is a configuration present in either the home directory or the XDG dirs, I can understand that it would use that for fallback.

Even with it being implemented a bit weird, I am still very happy that Newsboat at least somewhat implements and uses the XDG Basedir Specification.

**Comment by Kabouik** [comment]
I'm also very happy that it supports XDG standards as well, it really helps keeping my home tidy. I am just surprised to realize that my XDG env variables are actually empty, I didn't check before, but probably that's no issue for most programs anyway. Even for `newsboat`, it doesn't actually seem to be a requirement; that the `newsboat/` subdirectories exist in `~/.local/share/` and `~/.config/` is, but indeed this may be a bit unusual.

The manual says "If the XDG config directory exists, Newsboat will use XDG directories, creating the data directory if necessary. Otherwise, it will default to ~/.newsboat." This is where the opposite behaviour would be more relevant to me, *i.e.*, default to **creating** the XDG subdirs on first launch, but first check if `~/.newsboat` exist and use it if yes, as it would allow retrocompatibility with old configurations without user manipulation.

**Comment by Minoru** [comment]
> What got me confused is that when executing newsboat for the first time with no pre-existing configuration, it returns that URLs need to be added in ~/.newsboat/urls.

Yeah, we even have an issue about it: #3. I tried to fix it once and broke other stuff >_< I should try again sometime.

I started collecting file-related ideas in #1711, feel free to add more there.

**Comment by ifohancroft** [comment]
@Kabouik 

> I am just surprised to realize that my XDG env variables are actually empty

I think they are empty by default. I set them myself but only because there are apps that don't follow the XDG spec, but have workarounds like letting you pass a specific folder path via a command line parameter, so I set the XDG envs so I can later re-use them in aliases, aliasing commands to the same command but with the path options and so on. It seems some desktop environments set some XDG envs but only the ones they personally need.

> Even for `newsboat`, it doesn't actually seem to be a requirement; that the `newsboat/` subdirectory exists in `~/.config/` is, but indeed this may be a bit unusual.

Wait! Can you ellaborate on that? I am confused by that a bit. Do you mean becuase you can just use the homedir directly or?

> The manual says "If the XDG config directory exists, Newsboat will use XDG directories, creating the data directory if necessary. Otherwise, it will default to ~/.newsboat." This is where the opposite behaviour would be more relevant to me, _i.e._, default to **creating** the XDG config subdir on first launch, unless `~/.newsboat` already exists, in which case this dotdir is used instead. And the warning message on first launch should reflect the XDG path as default too. This would allow backward compatibility with old configurations without user manipulation, while promoting XDG standards for new users.

I totally agree with you on this one.

@Minoru

> Yeah, we even have an issue about it: #3. I tried to fix it once and broke other stuff >_< I should try again sometime.

Unfortunately, I know that feeling too well.

> I started collecting file-related ideas in #1711, feel free to add more there.

Lovely! I'd check it out.

**Comment by ifohancroft** [comment]
P.S. I just re-read the old documentation sentence. It is saying that it will create the DATA directory automatically. I mean yeah, it was unclear that the _newsboat_ directory needs to be created under $XDG_CONFIG_HOME, but when I asked what happens if $XDG_DATA_HOME/newsboat/ is not created - well the documentation says so. I guess I was just reading on auto pilot :D

**Comment by Kabouik** [comment]
> Wait! Can you ellaborate on that? I am confused by that a bit. Do you mean becuase you can just use the homedir directly or?

What I meant here is having env variables `XDG_CONFIG_HOME` and `XDG_DATA_HOME` exported is not actually required to make `newsboat` use them, the only condition seems to be that `~/.config/newsboat` must exist (and if so, then `~/.local/share/newsboat` will be created automatically). That's why it works for me even if I didn't manually set the env variables and my distribution doesn't automatically do it either.

**Comment by ifohancroft** [comment]
> > Wait! Can you ellaborate on that? I am confused by that a bit. Do you mean becuase you can just use the homedir directly or?
> 
> What I meant here is having env variables `XDG_CONFIG_HOME` and `XDG_DATA_HOME` exported is not actually required to make `newsboat` use them, the only condition seems to be that `~/.config/newsboat` must exist (and if so, then `~/.local/share/newsboat` will be created automatically). That's why it works for me even if I didn't manually set the env variables and my distribution doesn't automatically do it either.

Oh! Hm.. I didn't know that. Although, according to the specification if $XDG_CACHE_HOME is empty or not set or not readable, it should just default to ~/.config/ so perhaps Newsboat is just adhering to the specification in that regard

**Comment by Minoru** [comment]
> so perhaps Newsboat is just adhering to the specification in that regard

It does.
