### ISSUE TITLE
Pass feed's title and the link's title to `open-in-browser`

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#1727]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.23.0
System: Linux 5.4.0-80-generic (x86_64)
Compiler: g++ 5.5.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.9.0 nghttp2/1.44.0 librtmp/2.3 OpenLDAP/2.5.5 (compiled with 7.77.0)
SQLite: 3.36.0 (compiled with 3.35.5)
libxml2: compiled with 2.9.12

----

In my config file:

```bash
macro m set browser "Youtube %u"; open-in-browser ; set browser "firefox %u"
```

Here, Youtube is a  shell script available in PATH. I use this to make a log of the Url that I am seeing. And it then opens the file with mpv. But I would also like to log the name of the feed and the title of the url. Just like `%u` designates Url. Can we use something like `%f` for the name of the feed and `%t` for title? 

So, I could write macro like this 

```bash
macro m set browser "Youtube %u %f %t"; open-in-browser ; set browser "firefox %u"
```
And then process it using my script?

**Comment by Minoru** [comment]
Hi! Please try [bookmarking](https://newsboat.org/releases/2.24/docs/newsboat.html#_bookmarking) instead, and tell me if that resolves the issue.

Instead of adding new specifiers to `browser`, we'll probably [unify a lot of commands](https://github.com/newsboat/newsboat/issues/1691) and provide as much info as possible to all of them.

**Comment by anishmittal2020** [comment]
I use bookmarking to have a record of stuff which I want to watch later. My request is to pass this information to be stored in a log file, when I want to watch a video..

**Comment by Minoru** [comment]
I understand, I'm just pointing out that you can *already* do this via bookmarking:

```
macro m set bookmark-cmd "youtube-wrapper"; set bookmark-autopilot yes; bookmark; ...reset bookmark-{cmd,autopilot} here...
```

**Comment by Minoru** [comment]
@anishmittal2020, did you get a chance to try bookmarking? Did it resolve this issue?

**Comment by kohane27** [comment]
I have the following macro to append the youtube filename then its url into a file:

```bash
macro s set browser "setsid -f echo '%u\n%T' >> ~/Videos/video-list/pending_videos.txt" ; open-in-browser ; set browser linkhandler
```
