### ISSUE TITLE
Can't open link with lynx in new terminal.

### ISSUE THREAD

**Issue by nawtrobar** [newsboat/newsboat#173]
**Newsboat version (copy from `newsboat -v`)**:
newsboat 2.11.1 - https://newsboat.org/

Steps to reproduce the issue:

1.  include in config: `browser "xfce4-terminal -e "bash -c \"lynx %u; exec bash\"""`  

2. select article

3. press o

new terminal opens with the following error message: failed to exectue child process "`url`" (no such file or directory)
I'm not sure if I'm passing the `%u` argument correctly, but it doesn't appear to be running the lynx command at all. When I run the command `xfce4-terminal -e "bash -c \"lynx guardian.com; exec bash\""`in my terminal it executes successfully. 

I'm basically posting here to see if people have succesfully gotten newsboat to open lynx with a link as parameter in a new terminal from newsboat.

**Comment by Minoru** [comment]
Try running Newsboat like that: `newsboat --log-file=newsboat.log --log-level=6`, and look for a line mentioning "browser" in the beginning where it parses your config. Is the command parsed completely? I suspect you need to escape double quotes inside double quotes.

**Comment by nawtrobar** [comment]
Actually just noticed somehting! the command is output in the terminal it doesn't include the \s that are escaping the internal quotes. So when it runs the command in bash, bash doesn't escape those quotes. Does that sound right? Unfortunately, when I use double slashes there, it doesn't open anything.

**Comment by Minoru** [comment]
You need to escape the inner slashes like this: `browser "xfce4-terminal -e \"bash -c \\"lynx %u; exec bash\\"""`. Then Newsboat will read it as `xfce4-terminal -e "bash -c \"lynx %u; exec bash\""`, and pass it to the shell that way.

Rather than dealing with all that escaping stuff, you could put your command into a script (replacing `%u` with `$1` or maybe `$*`) and use that script as your `browser`.

**Comment by nawtrobar** [comment]
I've solved the problem. This is the correct command:
```
browser "xfce4-terminal -e \"zsh -c \\\"lynx %u; exec zsh\\\"\""  
```
Note I changed the shell to zsh, as that is my preferred shell.

**Comment by Minoru** [comment]
Oh, right, three backslashes, not two, because you need to escape the inner double quote too.

Glad you've solved it, @nawtrobar! I'll close the issue then.

**Comment by nawtrobar** [comment]
thanks so much for your help.
