### ISSUE TITLE
Exported OPML should contain infromation about tags

### ISSUE THREAD

**Issue by s-kaczmarek** [newsboat/newsboat#1735]
Hi, I would like to be able to import OPML from newsboat to another RSS reader (Feeder and Feedly) and have all the feeds categorized instead of one list.

When we export OPML from FreshRSS all feeds have attached tag which becomes a tag in newsboat after importing. I would like to have similar functionality while exporting OPML from newsboat.

**Comment by Minoru** [comment]
Hi! Please see https://github.com/newsboat/newsboat/issues/871 and https://github.com/newsboat/newsboat/pull/1243.
