### ISSUE TITLE
Fedora 28 build exist immediatly

### ISSUE THREAD

**Issue by Harnish** [newsboat/newsboat#176]
newsboat r2.11.1-62-gfa4d
System: Linux 4.16.5-300.fc28.x86_64 (x86_64)
Compiler: g++ 8.0.1 20180324 (Red Hat 8.0.1-0.20)
ncurses: ncurses 6.1.20180224 (compiled with 6.1)
libcurl: libcurl/7.59.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.4 libpsl/0.20.1 (+libidn2/2.0.4) libssh/0.7.5/openssl/zlib nghttp2/1.31.1 (compiled with 7.59.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.7
Steps to reproduce the issue:

1. Upgrade Fedora 27 to 28. 
2. Recompiled for Fedora28 due to updated libraries.  Also updated to HEAD.
3. Execute `newsboat` or `newsboat --log-level 6 --log-file logtest.log` and it immediately exits.
4. log complains about ~/.config/newsboat already existing.
5. I moved that directory out of the way `mv ~/.config/newsboat ~/.config/newsboat.orig`
6. Executed again
7. Log now shows: [2018-05-02 09:17:50] CRITICAL: Couldn't create `/home/<username>/.newsboat': (17) File exists
8. Moved that directory out of the way `mv ~/.newsboat ~/.newsboat.orig`
9. Executed again
10. ~/.newsboat comes back and the error pops up again.

The configs worked with previous versions of newsboat and were migrated from newsbeuter.  I have tried it with and without my configs and such.  

config:
```
auto-reload yes
max-items        100 # such comments are possible, too
browser          links
show-read-feeds  no
notify-beep yes
confirm-exit yes
```

**Comment by Minoru** [comment]
Sorry, I broke it recently while fixing issues found by Coverity Scan. I just pushed a fix, can you try it please?

**Comment by Harnish** [comment]
Fixed.  Thanks
