### ISSUE TITLE
Launch Newsboat in 'Tag' view

### ISSUE THREAD

**Issue by cargaona** [newsboat/newsboat#1761]
Hi all!

I couldn't find a way to do this so I'm opening this issue/feature request.

Is there a possibility to configure newsboat to start the application in 'select tag' view? 

This could be really useful since I have a lot of feeds in my main view and always have to press 't' to switch to the tag view to start browsing my feeds. 

I'm open to contribute with code if it's needed.

**Comment by dennisschagt** [comment]
This might be possible using the [`run-on-startup`](https://newsboat.org/releases/2.24/docs/newsboat.html#run-on-startup) configuration, e.g.:
```
run-on-startup select-tag
```

**Comment by cargaona** [comment]
I didn't see it in the documentation. But now that you mention I found it. 
Thank you! 
Closing issue.
