### ISSUE TITLE
Invalid URL error for enquing Atom Feeds

### ISSUE THREAD

**Issue by sebastianrakel** [newsboat/newsboat#177]
newsboat r2.11.1-63-g414d
System: Linux 4.16.5-1-ARCH (x86_64)
Compiler: g++ 7.3.1 20180406
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.59.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.4 libpsl/0.20.1 (+libidn2/2.0.4) nghttp2/1.31.1 (compiled with 7.59.0)
SQLite: 3.23.1 (compiled with 3.23.1)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. Subscribe to Atom Feed with some Audio files or something like that (Podcasts)

2. Try to enque

Additonal Infos:

I use ttrss as backend

I posted this issue first on irc and @noctux said, that the lookup for audio files is on the link nodes, but atom feeds have an enclosure tag, which should also be matched

**Comment by sebastianrakel** [comment]
It seams, that ttrs didn't provide attachments, i will look deeper in this issue and keep you up2date

**Comment by Minoru** [comment]
As already pointed out on our IRC channel, this bug should be reproducible regardless of feed type: in your setup, both Atom and RSS go through src/ttrss_api.cpp, and *never* go through our Atom and RSS parsers.

**Comment by sebastianrakel** [comment]
So the ttrss api is working fine, i got the same typo at my curl tests...
