### ISSUE TITLE
Error while retrieving https://gbatemp.net/forums/280/index.rss: HTTP response code said error 403

### ISSUE THREAD

**Issue by minusfourty** [newsboat/newsboat#1780]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Newsboat 2.24.0
System: Linux 5.10.61-1-MANJARO (x86_64)
Compiler: g++ 11.1.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.78.0 OpenSSL/1.1.1l zlib/1.2.11 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.44.0 (compiled with 7.78.0)
SQLite: 3.36.0 (compiled with 3.36.0)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

# general settings
auto-reload yes
max-items 500

# externel browser
browser "/usr/bin/w3m %u"
macro m set browser "/usr/bin/mpv %u"; open-in-browser ; set browser "/usr/bin/w3m %u"
macro l set browser "/usr/bin/brave %u"; open-in-browser ; set browser "/usr/bin/w3m %u"

# unbind keys
unbind-key ENTER
unbind-key j
unbind-key k
unbind-key J
unbind-key K
unbind-key n
unbind-key p
unbind-key l

# bind keys - vim style

bind-key j down
bind-key k up
bind-key l open
bind-key h quit
bind-key n next
bind-key u prev
bind-key N next-unread
bind-key U prev-unread

# solarized
color background         default   default
color listnormal         default   default
color listnormal_unread  default   default
color listfocus          black     cyan
color listfocus_unread   black     cyan
color info               default   black
color article            default   default

# highlights
highlight article "^(Title):.*$" blue default
highlight article "https?://[^ ]+" red default
highlight article "\\[image\\ [0-9]+\\]" green default

Steps to reproduce the issue:

1.  Add https://gbatemp.net/forums/computer-hardware-devices-and-accessories.270/index.rss or other github RSS to urls

2. Load newsboat

3. it prints "Error while retrieving https://gbatemp.net/forums/280/index.rss: HTTP response code said error 403"

**Other info you think is relevant**:
It is not an issue with the site, as it works with other RSS apps. It has worked in the past.

**Comment by Minoru** [comment]
Hi! I just tried both links with Newsboat compiled from b76911029d5df7b6e8443cebaa5221181b2fb38b, and they both work for me.

HTTP code 403 means "not authorized". I have no idea why the server might respond with this — perhaps you're fetching the feed too often?

If the error persists, I suggest you contact the forum's admins and ask them why the server could return this error. I don't see anything we could do on Newsboat's side to fix this, so I'm closing the issue.

**Comment by der-lyse** [comment]
Maybe changing the [`user-agent`](https://newsboat.org/releases/2.24/docs/newsboat.html#user-agent) helps.

**Comment by Minoru** [comment]
@der-lyse I don't have it in my config, so I don't expect it to help, but it's worth trying anyway I guess :)
