### ISSUE TITLE
Add a config variable for to confirm marking all articles as read

### ISSUE THREAD

**Issue by aflyingpumpkin** [newsboat/newsboat#1781]
Currently, if the user accidentally presses whatever key is bound the keybind to mark all articles as read it will do so with no confirmation. This would allow the user to toggle on confirmation for this so the user can avoid accidental activation.

**EX:**
``confirm-mark-all-articles-read yes``

**Comment by Minoru** [comment]
Good point, thanks! Should be pretty easy to do, just look at how `confirm-mark-all-feeds-read` is implemented.
