### ISSUE TITLE
Add URL command

### ISSUE THREAD

**Issue by rememberYou** [newsboat/newsboat#179]
First of all, a big thank you for `newsboat`, I appreciate it every day.

In order to increase the ergonomics of `newsboat`, I had thought to add the command _URLs_ to the existing commands (_h:Quit ENTER:Open n:Next Unread r:Reload ... U: URLs ..._)
This will avoid opening a new terminal or quitting `newsboat` in order to modify the `~/.newsboat/urls` file.

Maybe this addition can be visually heavy, what do you think?

**Comment by der-lyse** [comment]
There is [`edit-urls`](https://newsboat.org/releases/2.10.2/docs/newsboat.html#edit-urls), to do exactly that. Using [`reload-urls`](https://newsboat.org/releases/2.10.2/docs/newsboat.html#reload-urls) you can just reload the *urls* configuration file.

**Comment by rememberYou** [comment]
I didn't know about it. Thank you!
