### ISSUE TITLE
Error when fetching local generated feeds using sock5 proxy

### ISSUE THREAD

**Issue by Vinfall** [newsboat/newsboat#1794]
Newsboat version:

```
newsboat 2.21.0
System: Linux 5.10.0-8-amd64 (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20201114 (compiled with 6.2)
libcurl: libcurl/7.74.0 GnuTLS/3.7.2 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 (compiled with 7.72.0)
SQLite: 3.36.0 (compiled with 3.33.0)
libxml2: compiled with 2.9.10
```

Newsboat config:

```
proxy-type socks5h
proxy localhost:{{my_local_proxy_port}}
use-proxy yes
user-agent "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"
```
PS: I don't use `download-timeout` and `always-download` as changing them do not solve the issue last time I tried when reading #1291 .

My RSS flow:

- I use socks5 proxy with [Clash](https://github.com/Dreamacro/clash) and proxy DNS requests when using newsboat.
- The feeds in question are generated by a locally running docker container of [RSSHub](https://github.com/DIYgod/RSSHub), so the feeds are like `http://127.0.0.1:1200/appsales/highlights/`.

Steps to reproduce the issue:

1. Use the version and config above and open newsboat
2. Press `r` to fetch RSS feed
3. Newsboat shows `Error while retrieving {{feed_url}}: Server returned nothing (no headers, no data)`

Additional Info:

- The RSS feed works fine when I directly browse it via Firefox ESR private mode and Chromium incognito mode.

I'am able to solve the issue when set `use-proxy` to `no` in config, but I prefer to fetch feeds via proxy. 

Edit: Typo fix.

**Comment by dennisschagt** [comment]
It looks like there is a typo in your config (`socsk5h` -> `socks5h`).
Is that typo also present in your actual configuration file?

Apparently newsboat does not show an error if the proxy type is unknown:
https://github.com/newsboat/newsboat/blob/7830c1a51e9b8151682c3c5acc5ec93b631adc6b/src/utils.cpp#L686-L712

**Comment by Vinfall** [comment]
>  Is that typo also present in your actual configuration file?

Humm, actually no, I typed the config instead of copy-paste, the config file itself is correct.

**Comment by Vinfall** [comment]
In case you want to dig it furthur, you can set up a socks5 proxy (tor works) and pull the docker image `diygod/rsshub` from DockerHub, then use the sample feed `http://127.0.0.1:1200/appsales/highlights/`.

**Comment by Minoru** [comment]
@Vinfall does it work if you set `proxy-type socks5` (i.e. the version that doesn't proxy the DNS requests)?

**Comment by Vinfall** [comment]
> @Vinfall does it work if you set `proxy-type socks5` (i.e. the version that doesn't proxy the DNS requests)?

No, I've tried that and it didn't work. BTW if I set `proxy-type` to `socks5`, some feeds will time out due to poisoned DNS. I have to use `socks5h` to proxy DNS requests.

**Comment by Minoru** [comment]
Okay, What if you run `NO_PROXY=127.0.0.1 newsboat`?

**Comment by Vinfall** [comment]
It seems to act as if I set `use-proxy` to `no` in the config, i.e., the locally generated RSS feeds work but those feeds with poisoned DNS got `timeout was reached`.

**Comment by Vinfall** [comment]
Yes, I switch back to `socks5h`. FYI, I'll list the behavior of two feeds `A`(locally generated RSS), `B`(unreachable without proxy):

|  Config  |    A    |    B    |
|-----------|---------|--------|
|set `use_proxy` to `yes` and `proxy_type` to `socks5` |no header, no data|timeout|
| set `use_proxy` to `yes` and `proxy_type` to `socks5h`|no header, no data| works|
| set `use_proxy` to `no`| works | timeout|
| run `NO_PROXY=127.0.0.1 newsboat`| works | timeout|

**Comment by Vinfall** [comment]
@Minoru  Sorry, I misread your comment. Run `NO_PROXY=127.0.0.1 newsboat` partially solves the problem. But the source sites of some locally generated feeds are DNS-poisoned, by running the previous command, those feeds become unreachable. Is there a way to solve that?

PS: The feed `A` in my previous comment means a local feed that is *not* DNS-poisoned.

**Comment by Minoru** [comment]
I managed to resolve the original problem by setting `use-proxy yes`, with an `socks5h` proxy, and running `NO_PROXY=127.0.0.1 newsboat`. I used `ssh -vD` for the proxy, and saw that Newsboat uses the proxy for non-local feeds. Please double-check that you didn't accidentally set `use-proxy` to `no` or used `socks5` proxy — feed `B` shouldn't timeout in the last line of your table.

> But the source sites of some locally generated feeds are DNS-poisoned, by running the previous command, those feeds become unreachable.

Can you give steps to reproduce this? If a feed is locally generated, it means Newsboat would be fetching the feed from 127.0.0.1, and it shouldn't matter (to Newsboat) if the source site is DNS-poisoned or not. The program that generates the feed would probably need to use a proxy, but that's unrelated to Newsboat.

**Comment by Vinfall** [comment]
Yes, feed `B` works if I run `NO_PROXY=127.0.0.1 newsboat`. Sorry for the mistake.

> ...it shouldn't matter (to Newsboat) if the source site is DNS-poisoned or not. The program that generates the feed would probably need to use a proxy, but that's unrelated to Newsboat.

That's right. Such feeds are acutally non-existent as RSSHub (the local RSS generator) throws an error even when accessing from the browser.

Closing the issue as the remaining problem is unrelated. Thanks for your patience and solution!
