### ISSUE TITLE
pagedown and pageup doesn't scroll as expected

### ISSUE THREAD

**Issue by allanwind** [newsboat/newsboat#1802]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: e3c4c28cde9c244adfdaaedaa7b91a4083058ab5

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
article-sort-order title
articlelist-title-format "%U"
bind-key J next-feed
bind-key K prev-feed
bind-key j next
bind-key k prev
bind-key o open-in-browser-and-mark-read articlelist
datetime-format "%F %T"
error-log ~/.local/share/newsboat/error.log
feedlist-format "%4i %n %11u %L - %t"
# ignore-article 
ignore-mode display
keep-articles-days 365
prepopulate-query-feeds yes
reload-threads 32
run-on-startup reload-all
show-read-articles no
show-read-feeds no
unbind-key C

```

Steps to reproduce the issue:

1. Ensure you have more than a full page of feeds.  Note the last feed id range  (in my case it's 1 t o 63).
2. Press pagedown.  List scrolled by 1 line (2 to 64) and move cursor to last line
3. Press pagedown.  List scrolled by full page (65 to 127).

In step 2, only 1 line is being scrolled, so you kinda need to hit it twice to get the desired effect but it means you missed the last line in step 2 (64).  I would like pagedown or pageup to scroll a full page irregardless of cursor position (expect for start or end of list where scroll may be partial).

I did see the enhancement #1682 but it was not clear if this talked about full page scrolls, also current behavior doesn't seem to fit original scenario described.

As an aside neovim on pagedown seems to scroll a full page - 2 lines on my setup irregardless of cursor position, then move cursor to first line, and on pageup moves cursor to last line but moves a page up. vim's cursor movement doesn't make sense to me, you press pagedown and the cursor moves _up_ (and pageup moves cursor down), also and pagedown + pageup is not inverse.

**Comment by Minoru** [comment]
> I did see the enhancement #1682 but it was not clear if this talked about full page scrolls

It talks both of scrolling inside the page (i.e. jumping between the first and last items) and between pages.

> also current behavior doesn't seem to fit original scenario described.

Dunno, it seem to match as far as I can tell. That issue uses "space" for pagedown and "backspace" for pageup though, perhaps that confused you?

This issue provides some new arguments and insights though, so that's for filing it! I'm closing in favour of #1682 though.
