### ISSUE TITLE
Save a list of titles and URLs?

### ISSUE THREAD

**Issue by geomoetric** [newsboat/newsboat#1805]
Nothing wrong with my Newsboat config, just wanted to ask whether it was possible to get Newsboat to export a list of titles and URLS? 

My scenario is that I have a custom query feed that I've used the String Format to get the Article title, Publication Date, and Feed Title in the Article List, then export the terminal output to a CSV manually. If the Article List format supported the URL parameter I think that would solve my problem—for now, I'm just copying URLs manually.

I've tried using some other scripts like RSSTail which are more designed to interpret and reformat RSS Data, but no other program has the caching or sophisticated filters like Newsboat! 

Speaking as a lover of the program but not an adept programmer, I would hope that this is something not that intensive to add to the functionality. Perhaps an extension of the string formatting and save functionality that's already present in the program. A `save-list` option perhaps?

But if I'm totally off please let me know! I mean maybe the solution is some sort of custom piping command that has totally eluded me so far. Thanks!

**Comment by Minoru** [comment]
I don't think a URL parameter and a `save-list` would be hard to implement, but I also don't see how they'd fit into Newsboat. A URL is hardly informative; I don't expect it to be useful when scanning the list. The `save-list` doesn't really provide any new capabilities within Newsboat, so it doesn't sound appealing either.

Have you tried `save-all` operation? It exports all the articles into plain text files, which you can then process to extract title, feed title, and URL. Another approach would be to work with Newsboat's cache.db (its schema is not stable and is not guaranteed, but it's good enough if you just want to hack on it). But the best course of action IMHO is to write a script that's totally separate from Newsboat.

**Comment by geomoetric** [comment]
Thanks @Minoru this is helpful. I'll close this issue as I can't argue alone these features fit into Newsboat's use case. Perhaps in the future, someone else will make a case for a URL parameter or a `save-list` feature and can reference my issue. In the meantime I'll go the route of processing the files after using the `save-all` command.  If it amounts to anything I'll post my solution here and if I just end up modifying Newsboat in a meaningful way I'll make a PR. Thanks!

**Comment by clappo143** [comment]
@geomoetric Did you happen to have any luck processing the files after using the save-all command?

**Comment by geomoetric** [comment]
@clappo143 Still doing it by hand alas!

Sincerely,
Eric Moe

--

Phone: 512-914-4921
Social: @geomoetric
Portfolio: ericmoe.co
