### ISSUE TITLE
I can't change "urls" file path

### ISSUE THREAD

**Issue by NikodemCelinski** [newsboat/newsboat#1808]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Newsboat r2.25 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `/snap/newsboat/5003/usr/local/bin/newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat r2.25
System: Linux 5.11.0-37-generic (x86_64)
Compiler: g++ 7.5.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

config is nowhere to be found as it installs itself in a weird place - namely : $HOME/snap/newsboat/
From there we have : 
```
$ cd ~/snap/newsboat/
~/snap/newsboat$ ls
5003  common  current
~/snap/newsboat$ ls -l
total 8
drwxr-xr-x 3 cypher cypher 4096 paź  5 20:16 5003
drwxr-xr-x 2 cypher cypher 4096 paź  5 20:16 common
lrwxrwxrwx 1 cypher cypher    4 paź  5 15:52 current -> 5003
~/snap/newsboat$ cd 5003/
~/snap/newsboat/5003$ ls
~/snap/newsboat/5003$ ls -l
total 0
~/snap/newsboat/5003$ cd ../common/
~/snap/newsboat/common$ ls
~/snap/newsboat/common$ ls -l
total 0
~/snap/newsboat/common$ 
```

Steps to reproduce the issue:

1. install newsboat with snap

2. try to change urls path with "-u"

3. EFFECT : 
`~/.newsboat$ newsboat -u '$HOME/.newsboat/urls' 
Starting Newsboat r2.25...
Loading configuration...done.
Opening cache...done.
Loading URLs from $HOME/.newsboat/urls...Error: failed to read URLs from file "$HOME/.newsboat/urls": Failed to open file: Permission denied (os error 13)`

**Other info you think is relevant**:

The dafault path is : $HOME/snap/newsboat/5003/.newsboat/urls
Which does not exist, but the program works once I manually create it. 
EDIT: 
My new file has all needed permissions ofc. I even tried with 777 to be sure.

**Comment by Minoru** [comment]
Our Snap is sandboxed and can't access the rest of the system, so the error with `-u` is the correct behaviour. It's also right that you have to create the file manually (for reasons unrelated to Snap).

I admit that I treat Snap as a bit of a second-class platform, and no-one stepped up to patch the app to support Snap better, so there we are. Patches welcome!
