### ISSUE TITLE
How do I filter by Unread?

### ISSUE THREAD

**Issue by winteriscariot** [newsboat/newsboat#1813]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: Newsboat 2.25.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
article-sort-order date-desc

download-full-page yes

external-url-viewer "urlscan"

browser "librewolf %u"

reload-threads 100

freshrss-min-items 500

macro y set browser "/home/-/.bin/newsboat-archive.sh" ; open-in-browser ; set browser "librewolf %u"

#show-read-articles no
show-read-feeds no
```

My goal is to create a filter so I can press ctrl-F to show/hide read articles in a feed. This helps, because if I have "show-read-articles" set to 'no' then articles disappear in the article list the moment I open them.

However, the documentation doesn't make it clear how to do this, despite 'unread' being a viable attribute. If i'm in the filter list I can do something like, "unread_count > 10" and it'll show me only feeds with more than 10 unread items. So this seems to work.

But what's the format to only show unread articles in the article list? pressing F, 'unread = true' doesn't seem to do anything and gives an error:

    couldn't parse filter expression `unread = true': invalid stringlit

putting a number instead of 'true' -- such as 'unread = 1' -- doesn't produce an error, but it doesn't show me any articles (there are 3 unread in the feed i'm looking at).

what am i doing wrong here? how can I achieve this result?

**Comment by Minoru** [comment]
No need to be so hard on yourself ;) And I'm glad you figured it out!

For the sake of whoever stumbles on this in the future: `unread = 1` is correct, but it doesn't work here because the filter can't "bring back" the articles that were hidden by `show-read-articles no`.

**Comment by ArshadSiddiqui** [comment]
I got in to same kind of issue; I needed to show only read articles in the list, the following expression worked for me after pressing F:
`unread="no"`

If you want to show only unread articles, try: `unread="yes"`
