### ISSUE TITLE
Add Miniflux support for min-items

### ISSUE THREAD

**Issue by Tokariew** [newsboat/newsboat#1814]
Currently the number of articles which are being synced from miniflux is using default value for miniflux api.
With using `limit` option in query is possible to ask for non default value of articles to sync.

**Comment by Tokariew** [comment]
ok, I adding it…
but i have a question about default value. Currently other sources have `min-items` set at 20, but with current without specifying limit value, miniflux will return 100.

Should i make it consistent with current behaviour or in line with other sources?

**Comment by Minoru** [comment]
Good question! I think it's better to make it consistent with current behaviour, so the existing users don't have to go and change it.
