### ISSUE TITLE
[Question] Miniflux Api and enclosures support

### ISSUE THREAD

**Issue by Tokariew** [newsboat/newsboat#1822]
Hi,
I somewhat started patching miniflux to return enclosures, when using [get-feed-entries](https://miniflux.app/docs/api.html#endpoint-get-feed-entries), but it seems that newsboat doesn't know, what to do with it…
Do I get it right that miniflux api in newsboat should be extended to add support to enclosures similiar like is done in ttrs, ocnews and freshrss?

**Comment by Minoru** [comment]
Correct :+1: Google Reader-like APIs piggyback on Atom, and get support for enclosures automatically. All other APIs have to implement it manually, because each API has its own format.
