### ISSUE TITLE
podboat file naming

### ISSUE THREAD

**Issue by npreiber** [newsboat/newsboat#183]
**Newsboat version (copy from `newsboat -v`)**:
podboat 2.11.1

Steps to reproduce the issue:

1. standard podboat configuration

2.enqueue a podcast in newsboat (e.g. WTF with Marc Maron)

3. download file with podboat

**Other info you think is relevant**:

Some podcasts have poor naming conventions- rather than end with the file extension, they will often end with ?<some number>. I'm not sure why they're named this way, and it's not a podboat bug, however, it would be useful to add a feature which enables the user to name the files themselves when Downloading somehow (like a pattern  "<name>-<date>.mp3" if this feature doesn't already exist

**Comment by Minoru** [comment]
Thanks for the report. Unfortunately, Podboat doesn't get much attention, so it's hard to tell when we'll get around to fixing this.
