### ISSUE TITLE
Man page references section that does not exist

### ISSUE THREAD

**Issue by bartenbach** [newsboat/newsboat#1830]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.25.0

The man page for Newsboat tells you that you will learn about highlighting in the highlighting chapter.

There is no highlighting chapter.

**Comment by Minoru** [comment]
Right ._. It's only in the HTML doc. I'll remove the references then.

**Comment by Minoru** [comment]
Yeah, https://github.com/newsboat/newsboat/pull/1831#issuecomment-943595817. It could be done but then the manpage won't look like a manpage, so I don't think that'll work.
