### ISSUE TITLE
Add configuration option to automatically set xterm title

### ISSUE THREAD

**Issue by aflyingpumpkin** [newsboat/newsboat#1859]
Currently the xterm title cannot be automatically set via a config option, the closest newsboat currently has is by using `notify-xterm` but this set's the xterm title to the `notify-format` which the user may not always desire, it also does not apply until all feeds are loaded. Two options should be added to alleviate these issues:
- `set-xterm-title` to toggle whether the user want's to automatically set the xterm title. and
- `xterm-title` to define the title if the previous option is set to `yes`

**Comment by Minoru** [comment]
Thanks for the suggestion! Since you also opened a PR that implements it, [I commented there](https://github.com/newsboat/newsboat/pull/1860#issuecomment-956519143).

**Comment by Minoru** [comment]
Please see https://github.com/newsboat/newsboat/pull/1860#issuecomment-959156686 for why I'm closing this.
