### ISSUE TITLE
rss for "google trend"

### ISSUE THREAD

**Issue by al-hub** [newsboat/newsboat#1861]
I've added google trend rss as  
https://trends.google.com/trends/trendingsearches/daily/rss?geo=US 

But I could not see contents properly.

I hope to see the first
\<ht:news_item_title\>
\<ht:news_item_snippet\>
\<ht:news_item_url\>

tags  for each \<item\>.

Is it  possible?

**Comment by Minoru** [comment]
You could write [a filter](https://newsboat.org/releases/2.25/docs/newsboat.html#_scripts_and_filters_snownews_extensions) that turns those `ht` tags into separate RSS `item`s.

The `ht` namespace points [here](https://trends.google.com/trends/trendingsearches/daily), but I couldn't get an XML schema from there and assess the scope. Right now it doesn't look like a schema we should support in Newsboat proper. Do you happen to know where Google hosts a description for this namespace?

**Comment by al-hub** [comment]
Thank you for your reply.

I've found the similar problem and It was replied as below,
https://groups.google.com/g/Google-AJAX-Search-API/c/NCW5L_QU8iE

Unfortunately, we can not get the official information from Google for ht tag.

However, some projects have tried to solve it like this:
https://github.com/Antrikshy/node-google-search-trends

I hope this information helps.

**Comment by Minoru** [comment]
Sorry, I still think that Newsboat proper shouldn't support such niche schemas. Please write a filter as suggested above, or use one of those libraries you found and write something you could use with `exec:`.

**Comment by al-hub** [comment]
I did solve it as your recommendation using by simple script

remove and parsing <ht:> tag  
lynx -source $url | sed '/ht:/!d' | sed 's|ht:news_item_||g' | sed 's|ht:news_||g' | sed 's|snippet|description|g' | sed 's|url|link|g' | sed '/ht:/d' | sed 's|[^&]*;||g' 

And
[newsboat#1157](https://github.com/newsboat/newsboat/issues/1157)
[newsboat_custom_stuff](https://github.com/graysky2/newsboat_custom_stuff)
It helps me. 

Thanks!
