### ISSUE TITLE
Newsboat shows only the first 50 items/articles of feed

### ISSUE THREAD

**Issue by arnoro** [newsboat/newsboat#1865]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.21.0

Steps to reproduce the issue:

1. Add url to ~/.newsboat/urls: https://feeds.br.de/eins-zu-eins-der-talk/feed.xml
2. Open newsboat
3. Select new feed
4. Reload
5. 50 Items are shown (but feed contains more then 280 items)

**Comment by Minoru** [comment]
Hi! I can't reproduce. Are you certain that your config is empty, and you haven't set [`max-items`](https://newsboat.org/releases/2.25/docs/newsboat.html#max-items) to 50 or something like that?

Also, if you've been subscribed to this feed before and deleted some items, it's possible that Newsboat "remembers" that and don't show the deleted items.

**Comment by arnoro** [comment]
Sorry, it was my fault. I actually had an entry for max-items. I copied the config file from someone else and did not check it.
