### ISSUE TITLE
Newsboat doesn't seem to support url's that download a .rss file

### ISSUE THREAD

**Issue by heagan01** [newsboat/newsboat#1872]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
Newsboat 2.25.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.25.0
System: Linux 5.14.16-zen1-1-zen (x86_64)
Compiler: g++ 11.1.0
ncurses: ncurses 6.3.20211021 (compiled with 6.2)
libcurl: libcurl/7.80.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0 (compiled with 7.79.0)
SQLite: 3.36.0 (compiled with 3.36.0)
libxml2: compiled with 2.9.12

```

Steps to reproduce the issue:

1. Put dev.to/feed to .newsboat/urls

2. Press r

3. And it shows invalid url

**Other info you think is relevant**:
Error while retrieving dev.to/feed: Error: unsupported URL: dev.to/feed

oh yeah I tried curling it, it doesn't return anything, but when I visit the link, it downloads an .rss file

**Comment by dennisschagt** [comment]
It looks like the `http://` or `https://` part is missing in that URL. Browsers will automatically add it, so that would explain why visiting it does work while it does not work with curl and newsboat.

I can't test at the moment, but I expect that adding the following URL will work: `https://dev.to/feed`

**Comment by heagan01** [comment]
> It looks like the `http://` or `https://` part is missing in that URL. Browsers will automatically add it, so that would explain why visiting it does work while it does not work with curl and newsboat.
> 
> I can't test at the moment, but I expect that adding the following URL will work: `https://dev.to/feed`

It works! Thanks
