### ISSUE TITLE
Add remoteapi_secret-passwordeval functionality

### ISSUE THREAD

**Issue by jottr** [newsboat/newsboat#1877]
It is possible to safely evaluate passwords for external services.  

Some services, like Inoreader, require not only a password but also an API secret.  
It is possible to retrieve the password from the keychain via `inoreader-passwordeval`:
```
#~/.newsboat/config
inoreader-passwordeval "security find-generic-password -s Inoreader -w"
```

Currently, it is not possible to safely retrieve API secrets via `remoteapi_secret-passwordeval`. 
The only method to define an API secret is via `inoreader-app-key`, but not `inoreader-app-key-eval`.

The `*eval`-functionality should not only exist for passwords, but also for api keys, usernames, app-ids etc. so that no sensitive data will be leaked.

To make things less complicated, maybe it is possible to extend the config API to something like this:

```
inoreader-app-id secure-eval "<script to retrieve app-id>"
inoreader-app-key secure-eval "<script to retrieve app-key>"
inoreader-login secure-eval "<script to retrieve login>"
inoreader-password  secure-eval "<script to retrieve app-key>"
```

**Comment by Minoru** [comment]
Thanks for opening the issue! You can already do this using backticks:

```
inoreader-app-id "`<script to retrieve app-id>`"
```

I'm not sure what I was thinking when `-passwordfile` and `-passwordeval` were introduced. Perhaps I just forgot about backticks? Need to check that (maybe later).

**Comment by jottr** [comment]
Thank @Minoru I will try it out.  
It would probably be useful to add info about the backticks to the documentation.

**Comment by Minoru** [comment]
They're already described in the [First Steps](https://newsboat.org/releases/2.25/docs/newsboat.html#_first_steps) section.

**Comment by jottr** [comment]
Ah. Haven't that. Thx.
