### ISSUE TITLE
libstfl dependency looks unmaintained

### ISSUE THREAD

**Issue by iMichka** [newsboat/newsboat#1881]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Newsboat 2.25.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.25.0
System: Darwin 20.6.0 (x86_64)
Compiler: g++ Apple LLVM 12.0.5 (clang-1205.0.22.9)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0 (compiled with 7.64.1)
SQLite: 3.32.3 (compiled with 3.32.3)
libxml2: compiled with 2.9.4

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

Not applicable

Steps to reproduce the issue:

1. Compile newsboat from source: it requires the `libstfl` dependency

2. The `libstfl` package seems not maintained anymore, and the upstream website is gone: http://www.clifford.at/stfl/

**Other info you think is relevant**:

I am a maintainer of Homebrew, the missing package manager for MacOS (and Linux).
We might need to drop support for newsboat in the future if no alternative to `libstfl` is found.
See https://github.com/Homebrew/homebrew-core/pull/89981 for reference.

**Comment by Minoru** [comment]
Thanks for opening an issue! We'll maintain our own fork for now: https://github.com/newsboat/stfl We intend to move to some Rust crate eventually, see #232, but there's no plan or timeline for that just yet.

I guess this resolves the situation for now, so closing.
