### ISSUE TITLE
Make dependency on Asciidoctor optional

### ISSUE THREAD

**Issue by mortezadadgar** [newsboat/newsboat#1885]
It would be nice to not have to compile ruby as a build dependency

**Comment by Minoru** [comment]
If you can live without manpages and the HTML doc, you can install *just Newsboat* with:

```
$ make newsboat && sudo make install-newsboat
```

Ditto for `podboat`.

[I briefly considered](https://github.com/newsboat/newsboat/issues/645) to migrate from AsciiDoc format to something else, but the experience of migrating from `asciidoc` (the program) to `asciidoctor` dissuaded me from that. No-one was very eager in offering their help either, so it kind of died down. I'm open to discussion, but only if it's in the practical vein, not just discussing alternatives and expecting unnamed someone to do the migration.

Does this resolve the issue, @mortezadadgar?

**Comment by mortezadadgar** [comment]
@Minoru I get it, thanks for your quick response!
