### ISSUE TITLE
replace `&apos;` with single quote in title

### ISSUE THREAD

**Issue by stxyang** [newsboat/newsboat#1890]
35 N  Dec 08   203   Charlottesville&apos;s Robert E. Lee statue to be melted down into new public artwork

Is it possible to replace `&apos;` with single quote in title? Fox news like to use single quote :)

**Comment by Minoru** [comment]
FoxNews feed is RSS 2.0, and it's unclear if their titles should be interpreted as HTML or not. Please see #202.
