### ISSUE TITLE
Deduplicate items by title

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1891]
> Hello, I am also looking to deduplicate items in Newsboat – specifically, automatically hide them from display or ignore/delete them in the first place. Any means of achieving this would be helpful. 
>
> In my case, duplicate items (mostly news articles) will have identical Titles but do not necessarily come from the same source, meaning they will generally have entirely different URLs. 
> 
> I am almost entirely illiterate when it comes to this stuff, so apologies if the above does not make sense or would be better posted elsewhere. Any advice/suggestions or updates on this would be much appreciated. :)

_Originally posted by @clappo143 in https://github.com/newsboat/newsboat/issues/1729#issuecomment-988708233_

**Comment by Minoru** [comment]
I think the best way to achieve this with Newsboat is to write a script that can be used with as a filter (see ["Scripts and Filters"](https://newsboat.org/releases/2.25/docs/newsboat.html#_scripts_and_filters_snownews_extensions) in the docs). This filter would remember all the item titles it sees, and if it sees it again, it will just remove the item from the XML. That way, Newsboat will only see the first item with a given title.

I don't want to build this into Newsboa itself because the criteria is quite arbitrary. What if you only want this for particular feeds? What if different subsets of feeds have to be processed separately? It's much easier to implement this as a separate tool that's used together with Newsboat.

Does that answer the question?

**Comment by clappo143** [comment]
Thanks @Minoru, yes that answers my question; also makes good sense in terms of the issues that would be associated with building such a function into Newsboat - no worries there. Looks I need to learn how to write a script to be used as a filter!  

Out of [these examples](https://github.com/msharov/snownews/tree/de3bd8b28191c4d4bc1be18275786613bcbc0c94/docs/untested), could you suggest any of them as even vaguely suitable to be used as a base template/for broad guidance with what I'm trying to do, however crude (I assume the answer is none of them,  but seemed worth a shot!)  

Thank you again for your response, much appreciated.

**Comment by Minoru** [comment]
I'd say [rss-tag-filter](https://github.com/msharov/snownews/blob/de3bd8b28191c4d4bc1be18275786613bcbc0c94/docs/untested/rss-tag-filter) is the closest of them all. You'll have to change the condition on lines 62-64, and figure out a way to store titles.

**Comment by clappo143** [comment]
Brilliant, many thanks!
