### ISSUE TITLE
Allow regexes to select URLs in ignore-article

### ISSUE THREAD

**Issue by duarm** [newsboat/newsboat#1913]
Newsboat r2.23-227-g86600 
reopening https://github.com/akrennmair/newsbeuter/issues/500 here,
as per https://github.com/newsboat/newsboat/issues/31

I would like this feature for the same reason as ghost in https://github.com/akrennmair/newsbeuter/issues/500, quoting him:

> Could you please make the selectivity filter for ignore-article a regex for multiple feeds? Currently it appears that one can use either "*" or the full path of the feed one wants to censor. Being able to use regex would make it possible to censor all feeds except for a few.

I made a patch as a workaround (1b7b48a) which does regex matches with the feed url, I just used the built-in c++ regex which differs from newsboat one, it uses ECMAScript style by default I think. It's working for me, at least for now.
I do something like this
`
ignore-article "https://nitter.net/.*" "title =~ \"RT by\" or title =~ \"R to\""
`

**Comment by Minoru** [comment]
I'm still in favour of implementing this. I guess the main question here is: how to distinguish between regex and "verbatim" URL? Dot, asterisk, question mark, parentheses, square brackets are all allowed in URLs.

Couple ideas:
1. match by equality first, use regex match if that fails. So `https://example.com/page?foo` will match `https://example.com/page?foo` and `https://example.com/pagfoo`, but not `https://example.com/page?bar` or `https://example.com/`. This approach has a downside that exiting `ignore-article` rules can change their meaning and start matching more feeds than the user intended.
2. explicitly prefix regexes with something, e.g. `ignore-article "regex:https://nitter.net/.*" "…"`. Are there any downsides here?

Also, `highlight` uses POSIX extended regexes, and I think it'd be better to use them for this new syntax too, for consistency.

I'm not going to work on this myself, but I'd love to collaborate with someone who wants to think through the design and then implement it.

**Comment by duarm** [comment]
2 with "regex:" seems perfect, making regex opt-in should protect current configs. I don't think this feature needs anything else (except changing from ecma to posix).

**Comment by Minoru** [comment]
Good point about `highlight`, but yeah, it's sufficiently different that it doesn't have to be consistent with `ignore-article`.

Would you like to polish your commit a bit more and send a pull request? I think the following needs to be done for it to be mergeable:

1. switch to POSIX ERE (we have a `Regex` wrapper for it, see _include/regexowner.h_);
2. add tests for this new functionality (_test/regexmanager.cpp_ is probably the best place);
3. document this (_doc/newsboat.asciidoc_).

**Comment by duarm** [comment]
Working on it, thanks for maintaining newsboat, merry christmas.

**Comment by Minoru** [comment]
Cool! I'm more of a New Years person, so you are not late at all ;) Happy holidays to you too!

**Comment by duarm** [comment]
the feature (247604e9bb312167e5d981eb77ca601da32c085a) and the docs(2e0ca29d602aa609c5123b21e8825cdc2345939d) are already on my fork, just a question about the tests, test/rssignores.cpp wouldn't  be a better place, together with the "*" test?

**Comment by Minoru** [comment]
You're right, test/rssignores.cpp is the better place. Just adding a new `SECTION` to that test should be fine I think.
