### ISSUE TITLE
delete-read-articles-on-quit is not working on MacOs Monterey

### ISSUE THREAD

**Issue by farukara** [newsboat/newsboat#1917]
```
delete-read-articles-on-quit yes
history-limit 0
#show-read-articles no
```
Newsboat 2.25.0 
I'm using MacBookPro. Since updating to Monterey, newsboat is not deleting the read articles on quit. I don't know if that's a known issue or has been reported before. But would be glad to a find solution.

**Comment by Minoru** [comment]
Hi! I don't have a macOS machine, so I tested on Linux (Newsboat r2.26-10-g52e2) and the read articles are deleted as they should. Perhaps it *is* related to macOS somehow, although I doubt it.

Can you please run `newsboat --log-file=newsboat.log --log-level=6`, enter any feed, mark a single article as read, then quit Newsboat? After that, please post the "newsboat.log" here (you can attach a file by dragging it onto a little strip in between the comment field and the "Comment" button).

Happy holidays! Don't take it amiss if I don't have time to respond to you in the next few days ;)

**Comment by farukara** [comment]
I did as you described. It turns out that database file was corrupted. I just deleted the file and that fixed the problem.
