### ISSUE TITLE
Organising urls file directly in newsboat

### ISSUE THREAD

**Issue by T3SQ8** [newsboat/newsboat#1918]
Many services have very indescriptive feed URLs. Youtube for example,
`https://www.youtube.com/feeds/videos.xml?channel_id=UCS0N5baNlQWJCUrhCEo8WlA`.
Looking at the url it's impossible to figure out its contents unless one opens
it, making it indistinguishable from other feeds from the same domain. Having
many feeds like this in a row in newsboat's `urls` can make it cumbersome to
reorganise the feeds, since one has to either open up each feed individually or
use the line numbering in newsboat to figure out which feed is which. (The
latter approach doesn't work if there are any comments in the `urls` file.)

A nice solution would be to have keybinding in newsboat that would that can
move lines up and down inside of the `urls` file.

**Comment by Minoru** [comment]
Ah, this is an interesting alternative to #1262. I can see two downsides here:

1. in order to be as powerful as #1262, this feature would also have to provide an operation to edit the feed's tags. If we ever implement per-feed settings, we'll have to provide an op to edit those, too. In other words, this is less modular and maintainable than #1262;
2. it's unclear how comments should be moved, and *if* they should be moved. Consider this:

    ```
    https://example.com/feed1.xml
    # just a comment here
    https://example.com/feed2.xml
    ````

    If I move the second feed up, should the comment stay in place, or should it be moved too? I guess the answer will depend on whether the comment is a note about feed2 (in which case it should be moved), or if it's a commented-out URL (in which case it probably shouldn't be moved).

So at a glance, I'm in favour of #1262 rather than this, but I'm open to discuss this further if you think this proposal is better.

**Comment by T3SQ8** [comment]
As far as I can tell, each one has different uses.

[#1262](https://github.com/newsboat/newsboat/issues/1262) would be useful to
edit a feed's tags, but would be cumbersome to move around feeds inside the
file. For instance...

```
56         (0/24) Foo's youtube channel #1
57         (0/56) Bar's blog
58         (0/34) Baz's news
59         (0/13) Foo's youtube channel #2
```

If I would want to move Foo's second channel underneath the first one using
[#1262](https://github.com/newsboat/newsboat/issues/1262), I would have to keep
in mind which line I need to move the feed to. In practise this would mean:

1. Memorize that the destination is line 57.
2. Open the `urls` file in my text editor using
   [#1262](https://github.com/newsboat/newsboat/issues/1262).
3. Delete line 59 (the one my cursor would be on).
4. Paste the line I just deleted at line 57.

This would get the desired result:

```
56         (0/24) Foo's youtube channel #1
57         (0/13) Foo's youtube channel #2
58         (0/56) Bar's blog
59         (0/34) Baz's news
```

This would only become more cumbersome if Foo had more channels, or if I wanted
to group together feeds on the same topic. I would also have to jump through
the same hoops if I add any more feeds to the `urls` file.

As for the comments, this is the best solution that I've come up with as of now
that hits both birds with one stone (addressing both this issue and
[#1262](https://github.com/newsboat/newsboat/issues/1262)) is: Making a
function inside newsboat that...

1. Prepends the feeds titles to the feeds URLs in the `urls` file with a
   delimiter between them. (Not actually overwriting `urls` yet.)
2. Opens up the file in the users preferred text editor.
3. After the user is done editing, the previously added titles and delimiters
   are removed and the edits are written to the `urls` file.

It could look something like this when edited by the user (arrows with
clarification only for illustration):

```
Bar's blog %%% https://example.org/rss.xml "tag1" "tag2"
^~~~ Title     ^~~~ URL                     ^~~~ Tags
           ^~~~ Delimiter
```

(Obviously pick a better delimiter than `%%%`.)

This way, it's possible to both manage both tags and the feeds order at once.

**Comment by Minoru** [comment]
Hmm, right. Now I see how #1262 would be inconvenient for this when managing a lot of feeds.

Your proposal with a temporary, annotated file sounds great to me! I would avoid introducing new syntax though, and rely on comments instead; here's your example. rewritten the way I see it:

```
https://example.org/rss.xml "tag1" "tag2" #NB Bar's blog
^~~~ URL                    ^~~~ Tags     ^   ^~~~ Title
                                          `~~~ Delimiter (starts with "#", so it's just a comment)
```

Newsboat would add those "#NB" comments before starting the editor, and remove them before writing to the urls file.

Would you like to implement this? I think you'd want to start with `OP_EDIT_URLS` (invoked by `edit-urls` which is bound to <key>E</key> by default), and enhance it. I'd create a new op for now (`edit-annotated-urls`?), so we can experiment with this before making it the default.

**Comment by T3SQ8** [comment]
I don't actually know any C++ so i couldn't figure out how to do it. [This](https://github.com/T3SQ8/newsboat/commit/b00041cb0e926f27ba976c90c128b425fced46ed) is as far as I've come.

**Comment by Minoru** [comment]
That's a good start! The next step would be copying the urls file into a temporary location and editing *that*. Then, you got to work with `urlcfg` to read the URLs, and with `FeedContainer` to figure out their titles.

**Comment by T3SQ8** [comment]
I almost got it to work. The last piece of the puzzle is extracting the titles from a given url.

https://github.com/T3SQ8/newsboat/commit/7803d11b9c6bef7b8ad6b1dbcd62537e196660a4

**Comment by Minoru** [comment]
Sorry for the slow reply! (Realistically, I'll probably be slow for at least a few more weeks, so please don't get grumpy about that.)

At a glance, the code does the following:

1. write the URLs and their titles into a temporary file;
2. read the temporary file and copy its lines into the urls file;
3. launch the editor to edit the temporary file.

I think the last two steps are in the wrong order ;)

Other than that, the code looks ready to be submitted as a PR, so I can check it out locally, test and maybe find some more things to nitpick on :) Good job!

**Comment by T3SQ8** [comment]
See PR #2123.
