### ISSUE TITLE
Clarify error when importaing OPML and the urls file doesn't exist

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1919]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.26-10-g52e2

Steps to reproduce the issue:

1. create a new home directory to make sure that no Newsboat files exist: `export HOME=$(mktemp -d)`

2. get some OPML file, e.g. Gwern's: `wget https://www.gwern.net/docs/personal/rss-subscriptions.opml`

3. attempt to import the file into Newsboat: `newsboat --import-from-opml rss-subscriptions.opml`

The expected result is something like running `newsboat` without arguments: it should ask the user to create a urls file. What actually happens is this:

```
Error: failed to read URLs from file "/tmp/tmp.pLLp2GXrAf/.newsboat/urls": Failed to open file: No such file or directory (os error 2)
```

To a user, this doesn't look like creating a urls file is the correct thing to do (but it is!) We should improve this error message, making it explain that the file should be created.

This was reported by ghostbuster on IRC.

**Comment by bogdasar1985** [comment]
`Error: failed to read URLs from file "/tmp/tmp.pLLp2GXrAf/.newsboat/urls": Failed to open file: No such file or directory (os error 2) Please, make sure file was created by you and have a read permissions.`
How about it? I will make a pull request if that's variant is OK.
Or the second one is `Please, make sure you created urls file and have a read permissions.`

**Comment by Minoru** [comment]
"Please make sure the file exists and you have write permissions" would be good, thanks ;) (Write permissions are necessary to write the URLs from the OPML file into the urls file)

**Comment by bogdasar1985** [comment]
@Minoru But it's not about importing the opml file. The thing is, the url file doesn't exist. And it will give the same message even if we just open the newsboat without importing.
For example in my PC:
```
bogdasar@bogdasar-Aspire-V3-571G:/home/bogdasar/Документы/Programming/C++_Programming/newsboat$ newsboat 
Запускаю Newsboat r2.26-13-g98214...
Загружаю настройки...сделано.
Открываю кэш...сделано.
Загружаю ссылки из /tmp/tmp.MYezAEreKw/.newsboat/urls...Ошибка: не удалось прочесть адреса лент из файла "/tmp/tmp.MYezAEreKw/.newsboat/urls": Не удалось открыть файл: Нет такого файла или каталога (os error 2). Пожалуйста убедитесь, что файл существует и у вас есть права на запись.

```

And the error message forming here https://github.com/bogdasar1985/newsboat/blob/98214100d29858e02134d7cfaacbfc44e95471f1/src/fileurlreader.cpp#L28
In `FileUrlReader` method.

How about "read/write permissions"? Or that's too generalized?

----------------------
Of course, I'm not very familiar with the codebase, but probably if we want to achieve more accurate error messages, we will probably have to change the error handling directly in the code.
But this is just my guess.

**Comment by Minoru** [comment]
Oh, interesting! Starting Newsboat without a urls file should display a different error message, and also show the help: https://newsboat.org/releases/2.26/docs/newsboat.html#_first_steps

It does sound like the error handling should be changed. Perhaps FileUrlReader should return an enum rather than a string? Then we can show different error messages depending on what the user is trying to do. I believe this is done in Controller.

**Comment by bogdasar1985** [comment]
@Minoru so, how about stop at `read` permission and continue working with error handling in other issue? (I already change message in all other `.po` files. Should I do it?)

**Comment by Minoru** [comment]
If like to restore the behaviour that is described in the linked doc, because it's nicer than a simple "couldn't open the file". That *is* a different issue, but I suspect that fixing it is entangled with this one, so I view them as a single issue.

IMHO just adding "create file and give read permissions" to the current message is not a sufficiently user-friendly fix for this.

There's no need to change files in po directory; this will be done automatically at the end of the development cycle, two weeks before the release.

**Comment by bogdasar1985** [comment]
@Minoru I think you can close this issue
