### ISSUE TITLE
Ignoring articles not working as expected

### ISSUE THREAD

**Issue by decibyte** [newsboat/newsboat#193]
I have a rule like the following in my `config`:

```ignore-article "https://example.com/*" "title !~ \"interesting thing\""```

I'd expect this to ignore any articles from any feed from `https://example.com/` that does not have the string `"interesting thing" ` in the title. But I see articles slip past this rule anyway :(

I think there could be 3 causes for this:

 1) I'm an idiot and this rule does not do what I expect it to do.
 2) `*` doesn't work as a wildcard in feed URLs, but only as a standalone wildcard for _all_ feeds.
 3) There's an actual bug!

Is anyone able to tell me what's going on? :)

**Edit:** I just realised that there's a #newsboat channel on Freenode, which might have been a better place for something questionish like this, but I'll leave it here, to avoid causing too much commotion.

**Comment by tsipinakis** [comment]
Looks like your second assumption is correct, only wildcard for all feeds is recognized and it isn't doing any actual parsing on the url.

The relevant codebit is the following:

https://github.com/newsboat/newsboat/blob/6f3c0ccc037576bf069206f6628925ea5174b375/src/rss.cpp#L408-L419

**Comment by decibyte** [comment]
Thanks, both of you!

@Minoru, I _did_ read the docs, and _did_ understand what it said. I guess I was just hoping for a little bit of additional magic :)

> can we make the documentation better?

That would be to explicitly say that `*` _only_ works to match _all_ feeds, not as a wildcard in feed URLs.

> Second, maybe this should lead to a feature request for globs or regexes

Oh yes, that would be sweet! Would you prefer to open a new issue for this yourself or do you want me to do it?

> Both will conflict with URL's use of question mark, though

Yeah. Let's save that discussion for the issue for the actual feature request.

I'll close this one, as I consider my question answered. Thansk again.

**Comment by Minoru** [comment]
@decibyte, turns out we already have an issue for that over at Newsbeuter tracker: akrennmair/newsbeuter#500. But if you have more thoughts on the matter, please do open an issue here, and we'll discuss it further.

(My stance regarding Newsbeuter issues and how they apply to Newsboat is outlined in #31.)

**Comment by duarm** [comment]
a patch 1b7b48adf69c9d0e0fa251ceb252671daf429c3f which does regex matches with the feed url. I don't like c++ codebases so I just took the quick route and used the built-in regex match, which uses ECMAScript style I think.

and I'm using this
`
ignore-article "https://nitter.net/.*" "title =~ \"RT by\" or title =~ \"R to\"" 
`
