### ISSUE TITLE
Hidden feeds cause 'mark-read' to move cursor too far

### ISSUE THREAD

**Issue by tejing1** [newsboat/newsboat#1934]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
$ newsboat -v
Newsboat 2.25.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.25.0
System: Linux 5.10.81 (x86_64)
Compiler: g++ 10.3.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.79.1 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libssh2/1.10.0 nghttp2/1.43.0 (compiled with 7.79.1)
SQLite: 3.36.0 (compiled with 3.36.0)
libxml2: compiled with 2.9.12
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser "mybrowser %u"
auto-reload yes
reload-time 30
```
(plus some `ignore-article` lines which are personal)

Steps to reproduce the issue:

1. Create a hidden feed partway through your urls list (with a tag starting with `!`)

2. Try 'mark-read' (`A` by default) from the feed list above your hidden feed. Observe that the next feed is now selected. Reasonable.

3. Try 'mark-read' (`A` by default) from the feed list below your hidden feed. Observe that the selected feed moved 2 feeds down. Oops.

**Other info you think is relevant**:
I was confused about the source of this behavior until I added a second hidden feed and suddenly the number of lines moved went up. Light bulb moment.

Presumably the new cursor position is being calculated based on the order of feeds in the list, and doesn't take account of hidden feeds.

**Comment by dennisschagt** [comment]
I can reproduce this.
It looks like this issue is already present since at least r2.10.
I might have some time later today to look for a fix.
