### ISSUE TITLE
text/plain parser does not unescape escaped XML chars

### ISSUE THREAD

**Issue by alexwennerberg** [newsboat/newsboat#1938]
#1500

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

v3.15.0_alpha20210804-4411-g6ef8a4

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
(default config)
```

Steps to reproduce the issue:

1. Load a feed that has type text/plain and xml-escaped chars (e.g. `&lt;`, `&gt;`), such as https://lists.flounder.online/test/threads/20220113231935.kfjdqfwr3ov3hlbu@minty.xml
2. Notice that these chars are not unescaped in newsboat

**Comment by Minoru** [comment]
Thanks for the report! I don't think the issue is with #1500; ideally, XML entities should be decoded by the XML parser. I think `get_xml_content()` from rss/xmlutilities.cpp is to blame; it should process entities but preserve whitespace.

**Comment by bogdasar1985** [comment]
@Minoru I take this issue, it seems I found what the problem is.
