### ISSUE TITLE
Loading feeds from onion sites

### ISSUE THREAD

**Issue by kjk11** [newsboat/newsboat#1945]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.26.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
#show-read-feeds no
auto-reload yes
external-url-viewer "urlscan -dc -r 'linkhandler {}'"

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key l open
bind-key h quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread blue default bold
color listfocus_unread yellow default bold
color info red black bold
color article white default bold

browser linkhandler
macro , open-in-browser
macro t set browser "qndl" ; open-in-browser ; set browser linkhandler
macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best" ; open-in-browser ; set browser linkhandler
macro v set browser "setsid -f mpv" ; open-in-browser ; set browser linkhandler
macro w set browser "lynx" ; open-in-browser ; set browser linkhandler
macro d set browser "dmenuhandler" ; open-in-browser ; set browser linkhandler
macro c set browser "echo %u | xclip -r -sel c" ; open-in-browser ; set browser linkhandler
macro C set browser "youtube-viewer --comments=%u" ; open-in-browser ; set browser linkhandler
macro p set browser "peertubetorrent %u 480" ; open-in-browser ; set browser linkhandler
macro P set browser "peertubetorrent %u 1080" ; open-in-browser ; set browser linkhandler

highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default

# Proxy settings
use-proxy yes
proxy-type socks5
proxy localhost:9060
#download-timeout 200
#download-retries 5

```

**Other info you think is relevant**:

Until a few months ago I was able to load RSS feeds from onion services through newsboat when it was configured to route through a tor proxy. However, this ability was lost with one update (unfortunately I did not track with which version change this happened) and since then I get a proxy handshake error when trying to load from an Tor v3 address. (Random example: http://c7hqkpkpemu6e7emz5b4vyz7idjgdvgaaa3dyimmeojqbgpea3xqjoid.onion/feed/channel/UCoxcjq-8xIDTYp3uz647V5A ) The tor-proxy configuration per se still works fine but I can only load feeds from clearnet websites, not from hidden services. It would be cool to have this ability back. 

Best, 

kjk11

**Comment by Minoru** [comment]
Please try `proxy-type socks5h` (note the "h"). This will force Newsboat to proxy DNS queries too, which I think will make Tor resolve onion addresses.

**Comment by kjk11** [comment]
Did the trick, thank you! Also, apologies if this was in the documentation (I assume it is)

**Comment by Minoru** [comment]
No problem ;) Yeah, [it's documented](https://newsboat.org/releases/2.26/docs/newsboat.html#proxy-type), but it takes a bit of knowledge to see that the problem with Tor can be caused by the proxy type, so I don't blame you for not spotting it yourself.
