### ISSUE TITLE
Invalid Atom version for `degoes.net` 

### ISSUE THREAD

**Issue by machinedgod** [newsboat/newsboat#1960]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload yes
refresh-on-startup yes
```

Steps to reproduce the issue:

1. add `https://degoes.net/feed.xml` to url list
2. try to reload

Observe it doesn't load, but newsboat reports "Invalid Atom version"

**Comment by Minoru** [comment]
Thanks for the report! This feed is using an HTTPS URI to identify its namespace:

```xml
<feed xmlns="https://www.w3.org/2005/Atom" xml:lang="en">
```

The URI works in the browser, but [the Atom specification only mentions the HTTP URI](https://datatracker.ietf.org/doc/html/rfc4287#section-1.2). Thus, this feed can't be considered an Atom feed, and is rightfully rejected.

Please contact the site admin and tell them to fix it ;)

**Comment by machinedgod** [comment]
Ah, excellent, thank you sir! I am not knowledgeable about Atom protocol, so I figured better to ask!
Cheers
