### ISSUE TITLE
Having multiple newsboat instances (with separated caches) while setting cache directory

### ISSUE THREAD

**Issue by mizhozan** [newsboat/newsboat#1963]
I have two kind of feeds, one curated list of feeds which I use newsboat and another is another list which I like to again use newsboat for but in separate instance. It's possible to achieve this by `-u`, `-c` and `-C` options for url, cache and config. However, it would be great if I could have set the cache directory to completely separate two instances. As far as I've read the manual these three switches are the only options to separate the two.

Currently, I've a bash file which export `XDG_CONFIG_HOME` and `XDG_DATA_HOME`  variables, but having such option immensely improve newsboat usage. I think newsboat become even more powerful when it handles different instances cleanly.

p.s. I also find #1706 discussion, relevant here. But still I think it can be possible to just set the cache directory.

**Comment by Minoru** [comment]
Do I understand correctly that you'd like a single option that makes Newsboat use a directory different from _~/.newsboat_? So instead of:

```
$ newsboat -u foobar/urls -c foobar/cache.db -C foobar/config
```

(or setting XDG variables to achieve a similar effect) you'd write:

```
$ newsboat --directory foobar
```

**Comment by mizhozan** [comment]
Yes. Right now, I export the XDG variables in a bash script (set for child precess) and run newsboat. This works fine.

```bash (new_instance_newsboat)
#!/bin/bash

export XDG_CONFIG_HOME=/path/to/config/dir
export XDG_DATA_HOME=/path/to/cache/dir
newsboat
```

The better would be something like this `newsboat --config-dir /path/to/config --cache-dir /path/to/cache`. It basically the same mechanism to `-u,-c,-C` currently implemented. But this is I think more neat. To just guide newsboat use differnt config/cache directory for that instance. This way it's easy to launch multiple instances of it.

**Comment by Minoru** [comment]
Sorry, I don't see how our own custom flags would be better than a standardized set of variables in this case. Newsboat already has a ton of flags and settings, so I think it's better to re-use what's already there, rather than create a separate option for each situation. Hope you'll agree :heart:

**Comment by mizhozan** [comment]
I agree on your argument regarding re-use what already available. However, the concern is about having two independent instants. I had this concern so I force newsboat use two different directories for each. If `-u <url_file>`, `-c <cachefile>` and `-C config-file` is enough for such separation, then right there is no need for another option.

**Comment by Minoru** [comment]
`-u`/`-c`/`-C` are almost enough, see #57; it can still be sufficient sometimes, e.g. I use it when reproducing bugs. Your approach with XDG variables is actually the best one, because it provides the full separation.
