### ISSUE TITLE
only show items that contain keyword, ignore the rest

### ISSUE THREAD

**Issue by runlow** [newsboat/newsboat#1967]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.26.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
bind-key        d delete-article
bind-key        j down
bind-key        k up
browser         "firefox %u"
cache-file      "~/.cache/newsboat/cache.db"
history-limit   0
text-width      72
```

Steps to reproduce the issue:

1. append `http://feeds.bbci.co.uk/news/rss.xml` to `~/.newsboat/urls`

2. start `newsboat`, press `r` on the feed you added

3. press `Enter` to check the articles, it shows **all** of them

**Expected**:
show only articles containing specific keywords, for example - "energy" "electricity" "coal" and treat all other items as if they didn't exist

**Other info you think is relevant:**
Also wishing for this when:
* a youtuber does letsplays of multiple games and I'm only interested in a specific game
* forum has many posts but I'm only interested in posts with a specific keyword

I've read the FAQ but didn't see this mentioned. Searched through Issues here. Checked the documentation but couldn't find anything relevant - other than the two below that I didn't get to work yet

**Solutions considered:**
* maybe somehow applying `ignore-article` config on a feed but in such a way that it blocks everything **except** items that contain a word (not sure if possible)
* writing a "filter script" that would parse the XML and only let through items with a keyword (thought I'd check here first if there's a simpler solution)

**Comment by Minoru** [comment]
Indeed this can be achieved with `ignore-article`:

```
ignore-article "http://feeds.bbci.co.uk/news/rss.xml" "content !~ \"(energy|electricity|coal)\""
```

It could check the `title` as well; alas, the regular expression would have to be repeated. See also `ignore-mode` setting. I hope this answers the question, but please drop a comment here if it doesn't (or open a new issue for a different question).

**Comment by runlow** [comment]
@Minoru Thanks for the answer but it doesn't seem to be doing anything for me (it displays all articles the same way it did before)

I'm troubleshooting this to try to see if I can get `ignore-article` to do something first with a simpler query.

**Comment by runlow** [comment]
I've set `ignore-mode` to `display` and it started working as expected. thank you
