### ISSUE TITLE
Last unread->read feed issue

### ISSUE THREAD

**Issue by Bfgeshka** [newsboat/newsboat#197]
newsboat r2.11.1-73-g3434-dirty

Steps to reproduce the issue:

1. Go to "unread only" mode.

2. Have several feeds, ex.:
```
aaa
bbb
ccc
```

3. Open last one (i.e. `ccc`) and mark it all read.

4. Go back to feed list, `ccc` is gone from here now.

5. Open current last feed. Instead of expected `bbb`, `ccc` is opened.

**Comment by Minoru** [comment]
Thank you for the report, but I believe this issue is already fined under #72.
