### ISSUE TITLE
Remove old articles

### ISSUE THREAD

**Issue by SirCipherz** [newsboat/newsboat#1972]
i've been using newsboat for over a year now and it's an amazing software but i follow some prolific feeds and now the articles database is hitting some high numbers in term of size, is there a way to auto delete articles from a source if they are more than N of them ? if not consider this a feature request :)

**Comment by Minoru** [comment]
Perhaps [`max-items`](https://newsboat.org/releases/2.26/docs/newsboat.html#max-items) is what you're looking for?

**Comment by SirCipherz** [comment]
Thanks a lot
