### ISSUE TITLE
Newsboat crashes when trying to open specific feed item

### ISSUE THREAD

**Issue by mbwgh** [newsboat/newsboat#1974]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Newsboat 2.26.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.26.0
System: Linux 5.16.10-arch1-1 (x86_64)
Compiler: g++ 11.1.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0 (compiled with 7.80.0)
SQLite: 3.37.2 (compiled with 3.37.0)
libxml2: compiled with 2.9.12
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
Tested with an empty config file

Steps to reproduce the issue:

1. ~~Use urls file containing the single entry `https://css-tricks.com/rss`~~ Use the provided xml file and create an urls file containing the single entry `file:///path/to/css-tricks.xml` 
[css-tricks.zip](https://github.com/newsboat/newsboat/files/8114830/css-tricks.zip)

2. Create empty config / cache.db files

3. Open newsboat via `newsboat -c cache.db -C config -u urls`

4. Press R to download feed items

5. Open feed entry `A Complete Guide to CSS Cascade Layers` (if someone could tell me how to make this not dependent on remote data, I can modify this)

The following assertion then triggers:

```
/usr/include/c++/11.1.0/bits/stl_vector.h:1227: void std::vector<_Tp, _Alloc>::pop_back() [with _Tp = newsboat::HtmlTag; _Alloc = std::allocator<newsboat::HtmlTag>]: Assertion '!this->empty()' failed.
```

and the application will abort.

**Comment by dennisschagt** [comment]
I can reproduce this issue, looks like we try to remove an item from an empty vector.
In my case the crash happens at a later moment (when adding a new item to the corrupted vector), but the root cause is the same.

> Open feed entry A Complete Guide to CSS Cascade Layers (if someone could tell me how to make this not dependent on remote data, I can modify this)

I think the root cause is clear enough, so I think the current steps to reproduce are fine.
However, if you ever want to make this independent from remote data, you could download the feed xml and link to it from the newsboat urls file e.g.: `file:///home/dennis/css-tricks.xml`
(and then attach/include the feed's xml file in the Github issue)

**Comment by mbwgh** [comment]
Although a PR already exists, I added the xml file at fault for completeness' sake.
