### ISSUE TITLE
text-width does not wrap long URLs and links

### ISSUE THREAD

**Issue by gmarmstrong** [newsboat/newsboat#20]
**Newsboat version (copy from `newsboat -v`)**: `newsboat 2.10.1-r2.10.1-28-gad51`

Steps to reproduce the issue: 

1.  Set `text-width` to `80`

2. Open an article with a URL or link longer than 80 characters

**Comment by gmarmstrong** [comment]
I see that this was actually an implementation to fix https://github.com/akrennmair/newsbeuter/issues/282

**Comment by Minoru** [comment]
Yes, this was conscious decision on my part, and I still stand behind it. But maybe i just didn't consider enough (noone chimed in for a discussion in that issue, as you can see.) Can you describe why you want the URLs wrapped at `text-width`?

**Comment by gmarmstrong** [comment]
I had just assumed this was an error when I reported it. But since I see that the documentation for `text-width` at `newsboat/doc/configcommands.dsv` does mention this behavior and nothing is broken by it, it should be fine to close this issue.
