### ISSUE TITLE
Sync with phone

### ISSUE THREAD

**Issue by timsofteng** [newsboat/newsboat#2019]
Hello.
It's not bug report. It's question from nubile in rss.

First of all thanks for the great program. I start to use rss reader.
Just have one small question. Is it any way to  automatically sync my urls and news cache with all news state (read/unread) between PC and smartphone?

**Comment by Minoru** [comment]
Hi! Newbies are very much welcome! RSS is a bit out of fashion right now, so it's nice to see new people coming to this old technology :)

There is no smartphone app that can understand Newsboat's urls and cache, so there is no point syncing those files. Instead, you could use [one of the many newsreading services](https://newsboat.org/releases/2.27/docs/newsboat.html#_newsboat_as_a_client_for_newsreading_services): on PC you'd read it in Newsboat, and on the smartphone you'd read it with the service's app.

Does that answer your question?

**Comment by timsofteng** [comment]
Cool!
Is `feedly` supported?

Can I use my passwords-manager like a pass to put it instead of real password?

**Comment by Minoru** [comment]
Unfortunately, Feedly is not supported; see #61 for technical details.

> Can I use my passwords-manager like a pass to put it instead of real password?

Sure: https://newsboat.org/releases/2.27/docs/newsboat.html#_passwords_for_external_apis

**Comment by Minoru** [comment]
Looks like I've answered all the questions, so I'll close the issue. Please comment and/or open new ones if you have more questions! (Preferably one question per issue, so we can reference them later when we answer similar questions.)

**Comment by timsofteng** [comment]
> Looks like I've answered all the questions, so I'll close the issue. Please comment and/or open new ones if you have more questions! (Preferably one question per issue, so we can reference them later when we answer similar questions.)

Sorry for the delay. I'm waiting for inoreader support response to give me api key:)
