### ISSUE TITLE
Queueing podcasts with `e` is unreliable (sometimes it fails to enqueue)

### ISSUE THREAD

**Issue by cipriancraciun** [newsboat/newsboat#2020]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

~~~~
Newsboat 2.26.0
System: Linux 5.16.1-1-default (x86_64)
Compiler: g++ 11.2.1 20220103 [revision d4a1d3c4b377f1d4acb34fe1b55b5088a3f293f6]
ncurses: ncurses 6.3.20220312 (compiled with 6.3)
libcurl: libcurl/7.82.0 OpenSSL/1.1.1n-fips zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.47.0 OpenLDAP/2.4.59 (compiled with 7.81.0)
SQLite: 3.38.1 (compiled with 3.37.2)
libxml2: compiled with 2.9.12
~~~~

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

~~~~
[...]

podcast-auto-enqueue no
podlist-format " %8t / %-6p | %-20S | %b"
download-path "~/.../podcasts/%N"
download-filename-format "%N ~~ %F ~~ %t.%e"
max-downloads 2
~~~~

Steps to reproduce the issue:

1. find a podcast item,
2. either open it (i.e. press `Enter` to read its details), either mark it as read, either leave it unread,
3. press `e` in any of the previous three states;

Sometimes it enqueues to the `queue` file, sometimes it doesn't, sometimes it works only when one is in an item, sometimes it works only if it is unread.  I couldn't find a pattern yet.  No amount of restarting of `newsboat` seems to make it work.

**Comment by Minoru** [comment]
`e` only works in the item view, i.e. when you open an item. It does nothing in the feed list and article list. Are you sure you ever managed to enqueue something without opening it?

Also, `e` should always produce a message, even if it fails. Do you see any messages when `e` fails? If so, can you please quote them?

**Comment by cipriancraciun** [comment]
> `e` only works in the item view, i.e. when you open an item. It does nothing in the feed list and article list. Are you sure you ever managed to enqueue something without opening it?

I can't be 100% certain about this...  Perhaps you are right?  (I've only recently started using the podcast feature.)

(Although, having `e` work only when in the item view is quite unexpected...  Is there a technical limitation of not having it work also in the item list?)


> Also, `e` should always produce a message, even if it fails. Do you see any messages when `e` fails? If so, can you please quote them?

No, I didn't see any error messages (or in the log).  However, now that you've mentioned that `e` works only in the item view, I do see the `Added...` message in there and I have never seen it while the item list view.


> (Marking as "cannot-reproduce" for now, because it's unclear how to reproduce this just yet.)

I think it's correct to label it as `cannot-reproduce`, because it might be that I had the wrong expectations about `e`.

I'll keep using the podcast feature and report back any findings.  (If I don't actually find an issue, we can close it in a few days.)

----

Again, having `e` work only in the item view is an "unexpected behaviour", because all other commands work either on the list or in the view, and in order to improve usability such unexpected behaviours should be minimized...

**Comment by Minoru** [comment]
I don't see any technical limitation for supporting <kbd>e</kbd> in the item list, so I filed #2023.

**Comment by cipriancraciun** [comment]
Since I've initially opened this ticket, and since always using `e` in the article view, I haven't encountered any issue.

Thus I'm closing this as it seems I was confused, as discussed in previous comments.
