### ISSUE TITLE
Adding JSON feed capability 

### ISSUE THREAD

**Issue by Lucas-mother3** [newsboat/newsboat#2022]
So hi, but I wanted to suggest something. I just wanted JSON feed compatibility with Newsboat.

So first off here's the things I wanted:

1. Support for both JSON Feed 1.0 and JSON Feed 1.1
2. Proper rendering of text (rendering via ```content_html```) 

I recently made a JSON feed too if you want to test it: https://alexisgaming95.neocities.org/deepest%20mistakes/my/brain/just/committed%20/suicide%20/feed.json

Ciao!

**Comment by Minoru** [comment]
In case someone else stumbles onto this: this is a duplicate of #426. Pull requests welcome!
