### ISSUE TITLE
Consider camel case for class names

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#203]
Newsbeuter code used snake case both for classes and methods, but I started violating this convention by writing FSLock, CLIArgsParser, and ConfigPaths in camel case instead. I didn't do it on purpose—just didn't think about it, and did whatever is "natural" to me.

Now, I don't want this to be the new default just because I like it, but I also don't see a reason to keep a convention that no-one likes.

A question to people who contributed code in the last, say, 2 years: would you like classes to use CamelCase while methods use snake_case?

**Comment by der-lyse** [comment]
I personally love this naming convention (probably because I'm a Python guy) and welcome such a change. But I'm also totally fine with underscores for everything.

**Comment by Minoru** [comment]
All newly created classes are getting CamelCase names now: FeedHandler, SortStrategy, Reloader, OPML. Therefore, this issue is de-facto resolved in favour of using CamelCase.
