### ISSUE TITLE
SSH into remote where newsboat lives: possible to open links in browser on my local machine?

### ISSUE THREAD

**Issue by stianmandarin** [newsboat/newsboat#2034]
**Question**
I keep newsboat installed on a server i frequently SSH into. When trying to open links in browser, newsboat obviously tries to open a browser on the SSH host. Is there a way to tell newsboat to the browser client-side, that is, on the machine I'm physically using?

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.18.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
** Not really relevant, but here goes**

```
# general settings
auto-reload yes
max-items 9999
download-full-page yes
history-limit 0
# browser firefox
browser brave-browser

# unbind keys
unbind-key ENTER
unbind-key j
unbind-key k
unbind-key J
unbind-key K

# bind keys - vim style
bind-key j down
bind-key k up
bind-key l open
bind-key h quit

# Newsboat colour scheme to work with the Nord palette
# from Arctic Studios - https://github.com/arcticicestudio/nord
# Tested with the Nord kitty terminal colour palette
# Though should work with any terminal using the palette

color background          color15    default
color listnormal          color248   default
color listnormal_unread   color4     default
color listfocus           color0     color4
color listfocus_unread    color0     color4   bold
color info                color12    color0
color article             color248   default

# highlights
highlight article "^(Feed|Link):.*$" color6 default bold
highlight article "^(Title|Date|Author):.*$" color6 default bold
highlight article "https?://[^ ]+" color10 default underline
highlight article "\\[[0-9]+\\]" color10 default bold
highlight article "\\[image\\ [0-9]+\\]" color10 default bold
highlight feedlist "^─.*$" color6 color0 bold

```

**Comment by Minoru** [comment]
I don't have a worked solution for this, but I think you could use reverse port forwarding in SSH to create a "channel" from the remote to the local machine, and then write the URL into that channel on the remote side and read it and run Firefox on the local side.

**Comment by Minoru** [comment]
BTW you might wish to grab a newer Nord colorscheme from https://github.com/newsboat/newsboat/pull/1996, because the old one had invisible prompts which is confusing.

**Comment by stianmandarin** [comment]
@Minoru Thank you! I will look into that idea when i get a chance (and thanks for the Nord tip)

**Comment by Minoru** [comment]
I think the question was answered; at least there is nothing to be done in Newsboat proper.

**Comment by jeromecst** [comment]
Hi, I invite you to look at my script https://gist.github.com/jeromecst/8fa6ed18bfbf43ed2c7d14a4d94bcb60

Just ask newsboat to write its commands to a pipe on the ssh server
```
browser "echo firefox %u > ~/fifo"
```

Then launch newsboat using the script, it will read the fifo using ssh and execute the commands
