### ISSUE TITLE
Move all search-related stuff from `ItemListFormAction` into `SearchResultsListFormAction`

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#2036]
Before #2031, `ItemListFormAction` was used to display both the ordinary feeds and the search results. With #2031, we now have a separate class for search results, `SearchResultsListFormAction`. I now wonder if there's tuff we could move from the former to the latter.

TODO:

- [ ] move `show_searchresult` (or maybe remove it entirely, if it's not needed)
- [ ] see if there's more search-related stuff in `ItemListFormAction`, and move it to the new class

(This is obviously blocked on #2031, which is not merged yet.)

**Comment by bogdasar1985** [comment]
Ok, when #2031 gonna be merge, I'll get down to it issue.

**Comment by bogdasar1985** [comment]
I think if we just simply move search related stuff from `ItemListFormAction` to `SearchResultFormAction`, we, as you can see, got much code duplication, escpecially in `SearchResultsListFormAction::set_head` and `OP_OPEN` section of `SearchResultsListFormAction::process_operation`.
