### ISSUE TITLE
Sometimes you need to press `z` several times to return to the previous search result

### ISSUE THREAD

**Issue by bogdasar1985** [newsboat/newsboat#2043]
Newsboat r2.26-160-gb277-dirty

First scenario to reproduce the issue:

1. Search string `A` in feed
2. Search string `B` in feed for `x` times
3. Now you should press `z` `x` times for return to `A` feed

Second scenario to reproduce the issue:

1. Search string `A` in feed
2. Search string `B` in feed, which return same result as after `A` (just nothing to change)
3. Now if you return to `A` feed by pressing `z`, Newsboat won't let you know about it. Just nothing will change on the screen

**Comment by Minoru** [comment]
Oh, it didn't occur to me to search for the same thing multiple times :)

I have two thoughts on this:

1. we could display the search phrase in the title, so the user is aware at what results they're looking at;
2. we could make it so searching for the same thing again does nothing, i.e. it doesn't add a new feed to the history. That way, the user doesn't have to press <kbd>z</kbd> multiple times.

**Comment by bogdasar1985** [comment]
@Minoru I made a PR, which implement your second suggestion, but I think that your first suggestion could be implemented too in the next PR.

**Comment by Minoru** [comment]
Whoops, this shouldn't have been closed because the first point is not implemented yet.

**Comment by bogdasar1985** [comment]
@Minoru The title of the Search Results FormAction is highly configurable via the `searchresult-title-format` parameter in config file, if we want to display `search_phrase` in the title, then we need to add a modifier to the configuration of this parameter (for example, `%s`). You can, of course, just add `search_phrase` to an already configured line, but this is a crutch, not pretty and most importantly, users won't like it. To implement that, you need to get into Rust, inside `do_format` function. I don't know Rust, so I won't do it, let someone else do it.

**Comment by bogdasar1985** [comment]
@Minoru Oh, no. It seems I could fix this problem by adding a new format format parameter for `searchresult-title-format`: `%s` which represent `search_phrase`. I will make a PR.

**Comment by bogdasar1985** [comment]
We also could add this new parameter into default value here 
https://github.com/newsboat/newsboat/blob/78506f2fbb5c1c6af8ff8405781a79d7c645d703/src/configcontainer.cpp#L315
