### ISSUE TITLE
Termux package outdated

### ISSUE THREAD

**Issue by scompo** [newsboat/newsboat#2048]
Hi I'm getting random crashes in podboat while downloading multiple feeds, can't understand why figure it just crushes sometimes and exit to the command prompt.

Downloading just some feed at a time works, but I wanted to see if the last version still does this but it looks like the package has not been updated lately.

Who is maintaining the termux version?
I've found this https://repology.org/maintainer/termux%40github and cannot figure out who to contact about this, so I opened this issue to ask to update the build.

The termux version of newsboat is `2.24.0` it looks like it's from June 2021.

This is the version output:

```
~ $ newsboat --version
Newsboat 2.24.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.24.0
System: Linux 4.14.180-perf-ge2a1322887a5 (aarch64)
Compiler: g++ Android (7714059, based on r416183c1) Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.83.0 OpenSSL/3.0.2 zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.81.0)
SQLite: 3.38.2 (compiled with 3.38.0)
libxml2: compiled with 2.9.13
```

**Comment by Minoru** [comment]
I believe it's maintained by the community over at https://github.com/termux/termux-packages, so please report this over there.

If you know how to get a coredump or a stacktrace out of Termux though, please post it here. It might give me an idea of what's going wrong.

Also, podboat doesn't download feeds, it downloads podcasts. I guess you mistyped either "podboat" or "feeds"; meant "newsboat" or "files"? Right now I'm not entirely sure which one crashes :)

**Comment by scompo** [comment]
Thanks for the info, I'll open an issue over there and ask them if they can update the package.

Sorry about the confusion, I meant downloading "files" from the dowload queue with "podboat".

I have no clue on how to do a coredump or stacktrace on termux but I'll take a look at the docs or online and learn how to do it next time it happens. Thanks for the suggestion.

I would also prefer to use the last version to see if it persist with the latest version, maybe it was just something that's already fixed.

Maybe we can close this and I'll open a new issue when (and if) it happens again and I'll have more info.

**Comment by Minoru** [comment]
Sounds good!
