### ISSUE TITLE
Can't get proxy to work

### ISSUE THREAD

**Issue by chromer030** [newsboat/newsboat#2053]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Newsboat 2.27.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2022 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2022 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.27.0
System: Linux 5.17.5-arch1-1 (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.83.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.82.0)
SQLite: 3.38.3 (compiled with 3.38.1)
libxml2: compiled with 2.9.13
```

Please implement Socks/HTTP proxy support.

**Comment by dennisschagt** [comment]
It looks like there is support fox a proxy already, from [the documentation](https://newsboat.org/releases/2.27/docs/newsboat.html#proxy):
![image](https://user-images.githubusercontent.com/4629607/166420518-e5cfcb1d-49db-4539-bceb-e7f266be469d.png)

Does that work for you?

**Comment by chromer030** [comment]
Options stated in documentation doesn't work in command line !

**Comment by Minoru** [comment]
@chromer030, these settings should be specified in the config file, not command line.

`HTTPS_PROXY` only works with HTTPS, so it won't work with e.g. HTTP, `filter:` and `exec:`. Also, it's an environment variable from a library that Newsboat uses, so I'd advise against relying on it; please use Newsboat's settings instead.

**Comment by chromer030** [comment]
thanks for explanation
