### ISSUE TITLE
Error opening terminal from kitty (snap version)

### ISSUE THREAD

**Issue by gdv** [newsboat/newsboat#2058]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat r2.27
System: Linux 5.15.0-27-generic (x86_64)
Compiler: g++ 7.5.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key l open
bind-key h quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete
bind-key u goto-url

color listnormal white black
color listfocus black cyan
color info yellow blue bold
color background white black
color article green black
color listfocus_unread black cyan
color listnormal_unread   white black

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread white default
color listfocus_unread yellow default bold
color info red black bold
color article white default

browser linkhandler
macro o open-in-browser
macro t set browser "qndl"; open-in-browser ; set browser linkhandler
macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best"; open-in-browser ; set browser linkhandler
macro v set browser "setsid nohup mpv"; open-in-browser ; set browser linkhandler
macro w set browser "lynx"; open-in-browser ; set browser linkhandler
macro p set browser "dmenuhandler"; open-in-browser ; set browser linkhandler
macro c set browser "xsel -b <<<" ; open-in-browser ; set browser linkhandler

highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default

always-display-description no
articlelist-format "%4i | %40T| %80t | %f %D %6L"
article-sort-order asc
auto-reload yes
browser "xdg-open %u"
delete-read-articles-on-quit yes
download-retries 2
download-timeout 10
error-log "~/tmp/newsboat-error.log"
#external-url-viewer "urlscan -dc -r 'linkhandler {}'"
feed-sort-order unreadarticlecount-desc
#html-renderer "w3m -dump -T text/html"
keep-articles-days 50
max-items 3000
prepopulate-query-feeds yes
refresh-on-startup yes
reload-time 60
reload-threads 5
save-path ~/Downloads
show-keymap-hint yes
show-read-feeds no
show-read-articles no
text-width 0
use-proxy no
```

Steps to reproduce the issue:

1. invoke the newsboat inside the kitty terminal

```
gianluca@Dell-7290 ~/tmp> /snap/bin/newsboat                                                       
Starting Newsboat r2.27...
Loading configuration...Couldn't open `/home/gianluca/snap/newsboat/5807/tmp/newsboat-error.log' as a user error logfile: No such file or directory (os error 2)
done.
Opening cache...done.
Loading URLs from /home/gianluca/snap/newsboat/5807/.newsboat/urls...done.
Loading articles from cache...done.
Prepopulating query feeds...done.
Error opening terminal: xterm-kitty.
```

**Other info you think is relevant**:

I think that the problem should be solved by adding the package `kitty-terminfo` to the build or the required packages, but I haven't been able to build the snap from source.

If I run newsboat from the deb package everything works fine (but it's the 2.21 version)

**Comment by Minoru** [comment]
Hey, sorry for the slow response!

Installing `kitty-terminfo` makes sense to me, but our snap is based on `core18`, i.e. Ubuntu 18.04, which [doesn't ship kitty-terminfo](https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=terminfo). Ubuntu 20.04 [has it](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=terminfo), but Snapcraft docs [give contradictory advice](https://snapcraft.io/docs/base-snaps) on which one of `core18` and `core20` is the recommended one, so I'm not sure if we should upgrade to `core20` yet. [I asked on the Snapcraft forum](https://forum.snapcraft.io/t/which-base-snap-is-the-recommended-one/29945) about this.

**Comment by Minoru** [comment]
A Snapcraft developer answered that `core20` is preferred. I switched to it, added `kitty-terminfo` to `stage-packages`, and just uploaded a fresh build to the "beta" channel on the Snap store. @gdv, can you please give it a try and tell if it works fine for you? If it does, I'll add this to `master` and start pushing the corresponding builds to "edge", and when Newsboat 2.28 comes out in June, this will become the default (i.e. available from the "stable" channel).

**Comment by gdv** [comment]
Thanks for your work, that's amazing.
Unfortunately the error is still the same.
```
gianluca@Dell-7290 ~ (master)> snap list newsboat                                                         
Name      Version      Rev   Tracking     Publisher  Notes
newsboat  r2.27-dirty  5853  latest/beta  minoru     -
gianluca@Dell-7290 ~ (master)> /snap/bin/newsboat                                              
Starting Newsboat r2.27-dirty...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/gianluca/snap/newsboat/5853/.newsboat/urls...done.
Loading articles from cache...done.
Prepopulating query feeds...done.
Error opening terminal: xterm-kitty.
```

I'll try to figure out if kitty is doing something weird.
Thanks again

**Comment by elliot0319** [comment]
I'm using the same version. I tried it on foot, and it doesn't work. Any suggestions?

**Comment by gdv** [comment]
> I'm using the same version. I tried it on foot, and it doesn't work. Any suggestions?

If you are in a hurry, the following command seems to work
```
TERM=xterm-256color /snap/bin/newsboat
```

It's a horrible hack and I am afraid it might bite you.

**Comment by gdv** [comment]
It looks like adding `kitty` to `build-packages` suffices. 
I have uploaded the snapcraft that I have used as a [gist](https://gist.github.com/gdv/3d0b21dc54d7a9a5f5e7a45a71a9cd77)

**Comment by Minoru** [comment]
Cool! I added `kitty` to `build-packages` and `kitty-terminfo` to `stage-packages`, and released that to the "beta" channel. (The build for s390x is missing just now because there is no "kitty" package for it; I'll resolve that. The build for i386 is missing because `core20` doesn't support i386). @gdv, can you please install from the Snap Store and tell me if that version works?

**Comment by gdv** [comment]
Unfortunately, it does not work.

I have investigated the issue a bit more, it looks like the snap I have built works on my computer only because (1) I used the devmode containment and (2) I have a local installation of kitty in my home directory. If I change any of those, even my build fails.
Apparently, newsboat is unable to find the terminfo installed with kitty-terminfo, but I don't know how to further debug the snap.

**Comment by Minoru** [comment]
It finally occurred to me to look up this exact problem, and sure enough, [people ran into it before](https://forum.snapcraft.io/t/handling-of-alternative-terminfo-settings-kitty-term/19256). I applied htop's solution and pushed another build to the "beta" channel (still without i386). @gdv, can you test that please?

**Comment by gdv** [comment]
Amazing, it worked!

Thanks again for your work. 
Take care
