### ISSUE TITLE
manpage generation leaving markup syntax in output

### ISSUE THREAD

**Issue by mfiano** [newsboat/newsboat#2062]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.27.0
System: Linux 5.17.6-arch1-1 (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.82.0)
SQLite: 3.38.5 (compiled with 3.38.1)
libxml2: compiled with 2.9.13

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): No config file (yet)

Steps to reproduce the issue:

1. `man newsboat`

**Other info you think is relevant**: 

Here's a screenshot of what I see on Arch Linux:

![](https://img.mfiano.net/pcZOoH.png)

**Comment by der-lyse** [comment]
Hi @mfiano, I reckon this is fixed with #2026, that is already in current master.

**Comment by der-lyse** [comment]
No worries, thanks for taking the time and reporting it anyways. :-)
