### ISSUE TITLE
reload-only-visible-feeds conflicts with reload-threads

### ISSUE THREAD

**Issue by danieldoof** [newsboat/newsboat#2067]
First of all, I really enjoy using newsboat!

It seems like the option `reload-only-visible-feeds yes` has a conflict with `reload-threads 30`.
When using `reload-all`, newsboat loads all visible feeds sequentially and NOT in parallel.
Obviously, this slows down operation considerably.

After commenting out `reload-only-visible-feeds yes`, all feeds are reloaded again in parallel.

Is this known and/or desired behaviour?
I could not find any information on that in the documentation.

The tag feature is a really useful one, especially when combining it with `reload-only-visible-feeds` and `reload-threads`.
Although read feeds are still excluded from being reloaded with `reload-all` when `show-read-feeds no` is used.

The absolutely best version in my opinion would be the following:
- tags are used
- `reload-only-visible-feeds` with `reload-all` reloads ALL feeds under the current tag, not just feeds with unread articles
- `reload-threads` plays nicely with `reload-only-visible-feeds` and reloads in parallel

And again: thank you very much for your work on this useful piece of software.

_Originally posted by @danieldoof in https://github.com/newsboat/newsboat/issues/207#issuecomment-1129699495_

**Comment by danieldoof** [comment]
Here the output of `newsboat -v`

Newsboat r2.27-28-g746eb
System: Linux 5.15.0-30-generic (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.2)
libcurl: libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11 (compiled with 7.74.0)
SQLite: 3.37.2 (compiled with 3.35.5)
libxml2: compiled with 2.9.12

**Comment by Minoru** [comment]
Sorry, I lost a browser tab with this issue among the others!

> When using reload-all, newsboat loads all visible feeds sequentially and NOT in parallel.

Reproduced. For whatever reason, `Reload::reload_indexes()` doesn't use parallelism, but it can certainly be fixed :)

> reload-only-visible-feeds with reload-all reloads ALL feeds under the current tag, not just feeds with unread articles

I don't think this is a good idea. There are a number of ways to hide feeds; you mentioned two of them, the third one is filtering. Making `reload-all` behave differently for tags would be pretty confusing, I think. I suggest you write a macro instead, which shows unread feeds, reloads everything, then hides them back again.
