### ISSUE TITLE
Querying multiple tags; how to change the width of the "unread/total" field in the feedlist

### ISSUE THREAD

**Issue by bambirombi** [newsboat/newsboat#2081]
Currently I have a query for one tag "query:Journal:tags # \"(Journal)\"" meta
I want to add more tags to that same query but I do not know how to do it.

**Comment by Minoru** [comment]
You can use operators "and" and "or" to combine filters. For example, if you want articles from feeds that are tagged with "Journal" or "News", you should write:

    query:Example1:tags # \"Journal\" or tags # \"News\""

Similarly, if you want articles from feeds that are tagged *both* with "News" and "Asia", you should write:

    query:Example2:tags # \"News\" and tags # \"Asia\""

You can find a few more examples in https://newsboat.org/releases/2.27/docs/newsboat.html#_filter_language

Does that answer your question?

**Comment by bambirombi** [comment]
It works, but there is a problem.
I put "query:Example:tags # \"tag1\" and tags # \"tag2\"" and as you say it only presents feeds that contain both tags. 

The problem is with how it looks when opening newsboat:
![Example](https://user-images.githubusercontent.com/87095035/170969084-8705d0a8-d1e0-4083-b9e9-58ff80aebf45.png)

So I want the query to look as "Example 2". The problem I have is that "Example 2" does not do what the first query does (I mean to retrieve feeds that have both tags, it retrieves feeds as it would have and "or" instead of an "and").
The "Example 2" query is this: "query:Example2:unread = \"yes\" and tags # \"tag1\"" and tags # \"tag2\""
-----
Other little thing: Do you know how to do in config to increase the parenthesis in the right part? As you can see in the image, it does not have any parenthesis on the right side. It only happens when it is more than 100.

**Comment by Minoru** [comment]
> The problem is with how it looks when opening newsboat:

Looks like your configuration is different from the default. Can you tell me what Newsboat version you use, and show your config file? The lines in the urls file that surround the query would help too.

> it retrieves feeds as it would have and "or" instead of an "and"

I couldn't reproduce this with Newsboat 2.27. Perhaps it'd become clear once I find out what Newsboat version you're running.

> Do you know how to do in config to increase the parenthesis in the right part?

Yes. You have to change the width dedicated to those numbers. It's configured via [`feedlist-format`](https://newsboat.org/releases/2.27/docs/newsboat.html#feedlist-format). Apparently you already configured it to decrease the width (the default is 11 columns, you seem to have 8), so just increase it back by replacing `%8u` with `%11u` (or any other number bigger than 8).

**Comment by bambirombi** [comment]
Newsboat version (latest): 2.27-1 (from arch linux official repository).

Config file:
[config.txt](https://github.com/newsboat/newsboat/files/8805935/config.txt)

And url lines:
#starred articles a shift-a mark all as read, alt-l 
# ctrl-e to flag, s-enter to star it, to remove, ctrl-e delete flag s 
"query:Unread:unread = \"yes\"" ~Unread (Unread)
"query:Starred:flags # \"s\"" ~Starred (Starred)
"query:(Other)(tag)+Word:tags # \"(tag1)\"
"query:Other:unread = \"yes\" and tags # \"strenght\"" and tags # \"(Journal)\""
"query:Example2:unread = \"yes\" and tags # \"tag1\"" and tags # \"tag2\""
"query:Example:tags # \"tag1\" and tags # \"tag2\""
#macro ,,

Then I start with the urls (that work fine). That is the first part of the urls file.

And thanks for your help.

**Comment by bambirombi** [comment]
When I quit that double quotes the results offered are correct, but the looks are wrong.

So, what should I put in feedlist-format?

**Comment by bambirombi** [comment]
This is also why "Example" and "Example2" look differently. You configured feedlist-format to display feeds without tags the way "Example" is displayed, and feeds with tags as "Example2" is displayed.

I do not understand that. I had tags in both of them (in "Example" and "Example2") so I am not being able to figure out what is the trouble. The only thing I know is what already said. That when changing that double quote the results are correct, but the looks change (to worse). Do you have the same queries format?

**Comment by Minoru** [comment]
> I had tags in both of them (in "Example" and "Example2")

True, you have tags in filter expressions for these feeds, but there are no tags on feeds themselves. From your urls file:

```
"query:Starred:flags # \"s\"" ~Starred (Starred)
"query:Example:tags # \"tag1\" and tags # \"tag2\""
```

Here, the first feed has two tags ("~Starred" and "(Starred)"), and the second one has none. You should add a tag to the second feed like so:

```
"query:Example:tags # \"tag1\" and tags # \"tag2\"" "just a tag"
```

**Comment by bambirombi** [comment]
Well, maybe I expalined wrong. I said, "That is the first part of the urls file". Meaning that is only the first part. I have also lots of feeds tagged, but I did not want to publish them here. So, there are actually feeds with tags, that are included in my queries.

**Comment by Minoru** [comment]
So, did tagging *the query itself* work?

**Comment by bambirombi** [comment]
Yes, i simply put a tag called query after the query. so "query:Example:tags # \"tag1\" and tags # \"tag2\"" "query"
