### ISSUE TITLE
MacOS: Switch shortcuts from Ctrl to Command Key

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#2082]
As MacOS uses Command for most shortcuts that are use with Ctrl in Linux and Windowes, I suggest that we could have ability to switch shortcuts from Ctrl to Command Key, if desired.

**Comment by Minoru** [comment]
I'd accept a PR that makes this possible. One would probably have to change https://github.com/newsboat/stfl first, as that's the library we use to draw our UI.

By the way, how do other apps handle this difference? Do they create a setting that simply converts all mentions of "Ctrl" into "Conrol", or do they support Control as an additional key that can only be used on macOS?

**Comment by DominikRusso** [comment]
the command key on macos is the equivalent of the super key on linux, and both of them are not used by terminal applications.

remapping command to control should be the terminal emulator's job. @lamyergeier if apple's default terminal can't do that (which --- knowing apple --- it probably can't) i think iterm2 is capable of it.
