### ISSUE TITLE
Open in browser and mark as read not working

### ISSUE THREAD

**Issue by cedricpim** [newsboat/newsboat#21]
**Newsboat version (copy from `newsboat -v`)**: `newsboat 2.10.1`

Steps to reproduce the issue:

1. Add `openbrowser-and-mark-jumps-to-next-unread yes` to the config file.

2. Open a feed list, and `open-in-browser` from the articles list.

3. The article is open in the browser but it is not marked as read

**Other info you think is relevant**: The way I see it, what this means is that the article should be open, marked as read and the highlight row should jump to the next unread article.

**Comment by Minoru** [comment]
`open-in-browser` doesn't mark the article read; for that, you'll have to use `open-in-browser-and-mark-read` (bound to `O` by default). Then the setting will be heeded and Newsboat will jump to the next unread article.

**Comment by cedricpim** [comment]
Ah, you are right, of course. My oversight, sorry and thanks :+1:
