### ISSUE TITLE
Scroll position in article lost when a configuration option is set on-the-fly

### ISSUE THREAD

**Issue by the-blank-x** [newsboat/newsboat#2100]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Newsboat 2.27.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2022 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2022 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.27.0
System: Linux 5.15.41-1-lts (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.82.0)
SQLite: 3.38.5 (compiled with 3.38.1)
libxml2: compiled with 2.9.13
```

**Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):**

```
browser false
macro o set browser true; open-in-browser; set browser false
```

**Steps to reproduce the issue:**

1. Open an article
2. Run `:set browser true` or run macro `o`

**Other info you think is relevant**:
Seems to be caused by [formaction.cpp:279](https://github.com/newsboat/newsboat/blob/4db46a08c662c291997b2c90cd5593f8b2aab457/src/formaction.cpp#L279) (and in some more places, search for `set_redraw` in formaction.cpp), perhaps could be solved by storing a list of configuration options that are UI-related and only redrawing if the option is in the list.

**Comment by Minoru** [comment]
For itemview, this got fixed in f9e616b7c4ee90911c154242d980f4d404346344. At a glance, I don't think this behaviour is an issue for any other dialog, so I'll consider this one resolved; but if you find a similar problem with another dialog, please create another issue and let's take a look.
