### ISSUE TITLE
Segmentation fault (Core dumping) loading feeds after updating Nextcloud News to 18.1.0

### ISSUE THREAD

**Issue by psa-anddev** [newsboat/newsboat#2102]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat 2.27.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2022 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2022 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.27.0
System: Linux 5.18.3-arch1-1 (x86_64)
Compiler: g++ 11.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 (compiled with 7.82.0)
SQLite: 3.38.5 (compiled with 3.38.1)
libxml2: compiled with 2.9.13

```
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser qutebrowser
# Key Bindings
unbind-key j
bind-key J next-feed
unbind-key k
bind-key K prev-feed
unbind-key DOWN
bind-key j down
unbind-key UP
bind-key k up
unbind-key ENTER
bind-key l open
unbind-key q
bind-key h quit
unbind-key PPAGE
bind-key ^B pageup
unbind-key NPAGE
bind-key ^F pagedown
unbind-key g
bind-key s sort
unbind-key G
bind-key S rev-sort
unbind-key HOME
bind-key g home
unbind-key END
bind-key G end
unbind-key Q
bind-key q hard-quit
bind-key ^S save
bind-key ^U toggle-show-read-feeds

macro v set browser "mpv"; open-in-browser ; set browser "qutebrowser"
macro V set browser "ytdl-mpv"; open-in-browser; set browser "qutebrowser"
download-path "~/podcasts/%n"
download-filename-format "%t_%F.%e"
player "podcast_player"

include dracula
reload-threads 100
auto-reload yes

urls-source "ocnews"
ocnews-url "https://nextcloud.tansanchez.net"
ocnews-login "<redacted>"
ocnews-passwordeval "<redacted>"

```

Steps to reproduce the issue:

1. Update Nextcloud News to 18.1.0

2.Open Newsboat and refresh a feed with new articles

3.Application hangs and kills with a segmentation fault with this message
```
156028 segmentation fault (core dumped)
```

**Other info you think is relevant**:
The application was working fine this morning but stopped failing the moment I updated Nextcloud News to 18.1.0. 
I have tried in 2 different machines both with the same version of Newsboat and the same config. I have tried in my phone as well using the Nextcloud News mobile app and it works as expected. This application had an update a couple days ago where one of the items in the change log was to adapt for this specific version of Nextcloud News. My hunch is that there has been some changes made to the API that break Newsboat. I have my own instance of Nextcloud so if you need any logs, I can assist.

**Comment by psa-anddev** [comment]
And I think I might have found what the problem is. in the change log for Nextcloud News for 18.1.0 this item appears

> Due to #1766 some Feeds might now have items that have null set as author instead of "" clients need to handle this.

I think it is highly likely that this is the problem that is causing the segmentation fault.

**Comment by Minoru** [comment]
Thanks! I think they could have avoided API breakage, so I commented to that effect on https://github.com/nextcloud/news/pull/1766. But I also think we should add explicit type checks to all our APIs, just in case.

**Comment by psa-anddev** [comment]
I just tried compiling the linked PR from source and it does the job. I'll keep the issue open until the PR goes in master. Thanks for addressing the problem so quickly.
