### ISSUE TITLE
Image, video and audio tags don't have new lines if back-to-back

### ISSUE THREAD

**Issue by the-blank-x** [newsboat/newsboat#2103]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: `commit 4db46a08c662c291997b2c90cd5593f8b2aab457`

**Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):** empty

**Steps to reproduce the issue:**
1. Add [vc.xml.gz](https://github.com/newsboat/newsboat/files/8924291/vc.xml.gz) as a feed
2. Open the article

**Comment by Minoru** [comment]
Thanks for the report (and the fix!), but why do you consider the existing behaviour wrong?

**Comment by the-blank-x** [comment]
It looks a bit odd, but on second thought, perhaps I should've asked before opening.

**Comment by Minoru** [comment]
No, no, it's fine, issues are meant to be opened :) It's just unclear what's bad about the current behaviour.

I think we could add spacing for video and audio, but images seem risky to me. Before emojis became a part of Unicode, emoticons were small images, and it's easy to imagine someone putting a few such emoticons in a row — that's one example where we should render them all in one line. So how about doing this just for video and audio?

**Comment by the-blank-x** [comment]
I suppose that works

**Comment by Minoru** [comment]
Cool! If you could amend #2104, I'd merge it first thing after the 2.28 release ^_^
