### ISSUE TITLE
Adding a feed should auto mark as read

### ISSUE THREAD

**Issue by shabbs15** [newsboat/newsboat#2108]
Hi, is it possible to make feeds marked as read when added?

Useful since person has likely read the older articles of the person so no need to appear unread

**Comment by Minoru** [comment]
No, and it doesn't seem worthwhile to me. This feature would have some interesting interactions with some others:

- users of remote APIs won't appreciate that Newsboat marks everything read the first time they connect to the remote service;
- when `cleanup-on-quit` is disabled, Newsboat will remember all previously added feeds, so adding, removing, then re-adding a feed won't mark that feed as read;
- if `delete-read-articles-on-quit` is enabled together with this feature, the user might think that no articles were fetched for the feed at all;
- (perhaps more that I didn't think of).

Doing it manually seems easy enough though: press one key to mark feed read, and another to confirm. Don't you agree?

**Comment by Minoru** [comment]
I'll assume you agree and close this, but if you have more points to discuss, please share — this can always be re-opened!
