### ISSUE TITLE
Ability to filter articles by arbitrary xml fields

### ISSUE THREAD

**Issue by gordon-quad** [newsboat/newsboat#2111]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.23.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```
auto-reload yes
reload-time 30
ignore-article "*" "title =~ \"#shorts\""
ignore-mode "display"
```

**Info**: So, I am trying to filter out YouTube's premiers out of my feeds. Unfortunately YouTube does not want you to do that, so virtually only way to determine if the video is definitely not a premiere is to check its view count, which for real videos is >0.
This statistics is supplied in an extra Atom tag "media:group" -> "media:community" -> "media:statistics" with attribute "views", e.g.

```
<entry>
    <id>yt:video:EP4Hf63zR6w</id>
    <yt:videoId>EP4Hf63zR6w</yt:videoId>
    <yt:channelId>UCVSHXNNBitaPd5lYz48--yg</yt:channelId>
    <title>WHAT ELSE CAN A JET ENGINE AFTERBURNER DO?!</title>
    <link rel="alternate" href="https://www.youtube.com/watch?v=EP4Hf63zR6w"/>
    <author>
        <name>Tech Ingredients</name>
        <uri>https://www.youtube.com/channel/UCVSHXNNBitaPd5lYz48--yg</uri>
    </author>
    <published>2022-06-28T21:30:12+00:00</published>
    <updated>2022-06-28T22:11:30+00:00</updated>
    <media:group>
        <media:title>WHAT ELSE CAN A JET ENGINE AFTERBURNER DO?!</media:title>
        <media:content url="https://www.youtube.com/v/EP4Hf63zR6w?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
        <media:thumbnail url="https://i2.ytimg.com/vi/EP4Hf63zR6w/hqdefault.jpg" width="480" height="360"/>
        <media:description>Today we show you our new jet engine design using a new afterburner setup. We start with how you can build it yourself and then run through some demos. We end with a fun show of fog juice (glycerin) running through the turbojet to create huge clouds of smoke. Find us on Patreon and our website: https://www.patreon.com/techingredients https://www.techingredients.com/</media:description>
        <media:community>
            <media:starRating count="5408" average="5.00" min="1" max="5"/>
            <media:statistics views="68820"/>
        </media:community>
    </media:group>
</entry>
```

So idea is to hide this video from feed unless views become non-zero. But it looks like newsboat cannot filter by arbitrary XML data/XPath query, or, possibly I am being stupid and just cannot find it in docs. If that is the former is there a workaround maybe?

**Comment by Minoru** [comment]
Newsboat doesn't store `media:group`s in its database, so `ignore-article` can't do this; please use [`filter:`](https://newsboat.org/releases/2.28/docs/newsboat.html#_scripts_and_filters_snownews_extensions) instead. You'll have to write a script that reads XML from stdin, cuts out the items you don't want to see, and prints the result to stdout.

**Comment by gordon-quad** [comment]
I see, thanks!
