### ISSUE TITLE
error code 127 with yt-dlp

### ISSUE THREAD

**Issue by neverdimed** [newsboat/newsboat#2117]
version 2.28 (snap), ubuntu 18.04

I have this 127 error code appearing but under different circumstances to those described previously (#1295 ). I'm trying to download video using yt-dlp, as follows

Config file:

```
# general settings
auto-reload yes
max-items 50 
reload-time 30 # update all feeds every x minutes
reload-threads 100
prepopulate-query-feeds yes
cleanup-on-quit yes
confirm-mark-feed-read no
wrap-scroll no

# externel browser
browser "xdg-open %u"

#map ,d to download video
#comma used as prefix by default: https://newsboat.org/releases/2.10.1/docs/newsboat.html
macro d set browser "yt-dlp %u"; open-in-browser; set browser "xdg-open %u"

unbind-key ENTER
unbind-key j
unbind-key k
unbind-key J
unbind-key K


bind-key j down
bind-key k up
bind-key l open
bind-key h quit
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key ENTER open-in-browser
bind-key a toggle-article-read

# colours
color info default default reverse
color listnormal_unread cyan default
color listfocus blue default reverse bold
color listfocus_unread blue default reverse bold
color article cyan default
color listnormal yellow default

text-width 80

articlelist-format "%4i %f %D  %?T?|%-17T| ?%t"

```

Steps to reproduce the issue:

1. add this line to config: `macro d set browser "yt-dlp %u"; open-in-browser; set browser "xdg-open %u"`

2. in newsboat go to any item with a url to a video

3. type: ,d

the macro is suggested by a guy here: https://persrex.xyz/tech/rss.html. Using 'o' to open in my browser worked no problem before adding the macro, but with the macro in the config both o and ,d produce the comment "browser returned error code 127" (if i quit newsboat and run yt-dlp for the same weblink in the terminal it runs no problem at all)

**Comment by neverdimed** [comment]
i ran newsboat with the same config and url files in an xfce terminal on mx linux 21.1 and the macro above works as it should. it's an older version of newsboat on the mx computer tho

**Comment by insane-dreamer** [comment]
I still get this error with Newsboat 2.31 even though the FAQ says to upgrade to > 2.18

**Comment by Minoru** [comment]
@insane-dreamer, the error could be legitimate. The FAQ says to upgrade because with 2.18 it's impossible to tell if the browser is really failing or it's just Newsboat making stuff up.

Please create a separate issue with all the details (like your config and steps to reproduce) so we can take a closer look at your situation (if you observe it still — I'm *a tad* slow to respond lately, sorry about that!)
