### ISSUE TITLE
Does not fetch full article even with download-full-page "yes"

### ISSUE THREAD

**Issue by j605** [newsboat/newsboat#212]
**Newsboat version (copy from `newsboat -v`)**:
newsboat r2.11.1-73-g3434 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat r2.11.1-73-g3434
System: Linux 4.16.0-pf7 (x86_64)
Compiler: g++ 8.1.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.31.1 (compiled with 7.59.0)
SQLite: 3.23.1 (compiled with 3.23.1)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. Add http://tamil.thehindu.com/tamilnadu/rss to urls file

2. Notice that newsboat does not download full article even though the link opened with a browser produces the article.

3. Changing user-agent did not change the outcome.

**Comment by sanaptejas** [comment]
Any update on this issue? I am experiencing the same problem.

**Comment by Minoru** [comment]
Sorry, this issue fallen through the cracks. I meant to reproduce it (hence "to check" tag), but apparently never got around to it.

If I download the page with CURL, I don't see its body in the HTML either. Apparently the body of the article is fetched using JavaScript. Newsboat doesn't support JS, and there are no plans to add that support.

For sites like that, you have two options:
1. read it in the browser;
2. write a script or program that can be used with ["filter:" or "exec:" in Newsboat](https://newsboat.org/releases/2.13/docs/newsboat.html#_scripts_and_filters_snownews_extensions).

**Comment by momo286** [comment]
Hello,

I have the same problem and i wonder, is there anyway to put a python script through the extension system?

With an extension like readability ( https://pypi.org/project/readability-lxml/) it can be done.

**Comment by Minoru** [comment]
Hi, @momo286!

`filter:` in Newsboat feeds the whole feed to the program, so you'll need a wrapper script that:
1. parses RSS/Atom as read from stdin
2. extracts links from items
3. puts each link through readability-lxml
4. re-constructs the feed using readability's output as item descriptions
5. prints out the resulting feed (it doesn't have to be in the same format as the input, just something Newsboat supports. So e.g. you can read anything but only print out Atom)

I don't have anything like that already implemented, but it looks like [feedparser](https://github.com/kurtmckee/feedparser) is a good Python library that will let you do all of the above.

**Comment by momo286** [comment]
> Hi, @momo286!
> 
> `filter:` in Newsboat feeds the whole feed to the program, so you'll need a wrapper script that:
> 
> 1. parses RSS/Atom as read from stdin
> 2. extracts links from items
> 3. puts each link through readability-lxml
> 4. re-constructs the feed using readability's output as item descriptions
> 5. prints out the resulting feed (it doesn't have to be in the same format as the input, just something Newsboat supports. So e.g. you can read anything but only print out Atom)
> 
> I don't have anything like that already implemented, but it looks like [feedparser](https://github.com/kurtmckee/feedparser) is a good Python library that will let you do all of the above.

Many thanks for your answer and for providing me the steps. I will look into it, and thanks for your work
