### ISSUE TITLE
Support API keys for Miniflux integration

### ISSUE THREAD

**Issue by 00dani** [newsboat/newsboat#2122]
Miniflux's API supports authorising your request in two ways: either with HTTP Basic auth, using your regular Miniflux username and password, or [as of Miniflux 2.0.21 using an application-specific API key](https://miniflux.app/docs/api.html#authentication), which is the preferred method according to the documentation.

API key functionality was [added to Miniflux in March 2020](https://miniflux.app/releases.html), several months before [Newsboat added support for Miniflux](https://github.com/newsboat/newsboat/blob/master/CHANGELOG.md#221---2020-09-20)! However, Newsboat 2.28.0 still only appears to be capable of integrating with Miniflux using the legacy Basic auth method.

In order to support Miniflux API tokens, Newsboat must be able to make its requests in this form:
```http
GET /v1/me HTTP/1.1
X-Auth-Token: your-api-key-goes-here
```
A separate username is not required.

I've dug through the codebase a little and it looks like Newsboat's integration with external APIs is pretty heavily designed around the assumption that you have a username/password pair for your service, so it might be easiest to implement a "special" username to access this new behaviour. For example, you might write something like this in your configuration:
```shell
miniflux-username "<Miniflux:X-Auth-Token>"
miniflux-password "your-api-key-goes-here"
# and you can still do things like this of course
miniflux-passwordeval "gpg --decrypt ~/.newsboat/miniflux-api-key.gpg"
```
It would probably be nicer to have `miniflux-token` and corresponding `miniflux-tokeneval` configuration options instead, but that might be more complicated to work into the current codebase. 🤷‍♀️

**Comment by Minoru** [comment]
I wasn't aware of the token authentication in Miniflux; thanks for the pointer! I like the `miniflux-token`/`miniflux-tokenfile`/`miniflux-tokeneval` approach better, because it makes the config easier to understand. PRs welcome :)

**Comment by dennisschagt** [comment]
Sounds like a good idea.
Thank you for providing the concrete information (header example, links)
Implemented in https://github.com/newsboat/newsboat/pull/2219.

> I like the `miniflux-token`/`miniflux-tokenfile`/`miniflux-tokeneval` approach better, because it makes the config easier to understand. PRs welcome :)

I think adding just `miniflux-token` should be enough. I expect the other options can be easily emulated using backtick-evaluation in the config file: https://newsboat.org/releases/2.29/docs/newsboat.html#_shell_evaluation
