### ISSUE TITLE
How to specify different pagers for different feeds?

### ISSUE THREAD

**Issue by patricorgi** [newsboat/newsboat#2127]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.28.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
pager "path/to/mypager.sh"
```

Steps to reproduce the issue:

1. Create the pager to display xkcd images `mypager.sh`

```bash
#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

if grep -qE "xkcd" "${1}"; then
    image=$(grep -E -o "https?://[a-zA-Z0-9./?=_%:-]*.(jpg|png|JPG|PNG)" < "${1}" | tail -1)
    cd /private/tmp/
    imagepath="${image/https:\///private/tmp}" 
    imagepath=$(urldecode "$imagepath")  
    # download image to /tmp (will skip if image downloaded earlier)
    if [[ ! -f "$imagepath" ]]; then    
        echo "downloading..."
        nohup wget -q -m "$image" &>/dev/null
    fi
    kitty +kitten icat --hold "${imagepath}"
else
    # Hoping to use newsboat built-in pager instead of `less` <----
    less "${1}"
fi
```

2. Put this line in your `~/.newsboat/config` file

```
pager "path/to/mypager.sh"
```

https://user-images.githubusercontent.com/15998986/179735833-255f7857-8455-4c37-9a9e-f5164b80a55a.mp4

**Other info you think is relevant**:

My environment:

OS: macOS Monterey 12.4
Terminal emulator: kitty

`w3m` on macOS does NOT support image preview (lacking `w3mimgdisplay` functionality). This also prevents me from using this method https://github.com/newsboat/newsboat/issues/480#issuecomment-481045578. I started with the existing one pager `kitty-img-pager.sh` in the `contrib` dir to make my own pager.

However, not all my feeds are image based, only the feeds like xkcd; for other text-based feeds I want to use the built-in newsboat pager; is there a way to realize this by changing the line, indicated by `<----`, in the `mypager.sh` file?

**Comment by patricorgi** [comment]
Found a workaround: 
1. Modify newsboat article to tinker all image links into markdown images, i.e. `![](image link)`
2. Save modified article content into a markdown file
3. Use [mdcat](https://codeberg.org/flausch/mdcat/) in kitty to preview this markdown file

So that all articles can be parsed & viewed the same way. The result is decent (see the video below) but I think it can be improved in many aspects...

Uploading newsboat.mp4…

**Comment by Minoru** [comment]
> is there a way to realize this by changing the line, indicated by <----, in the mypager.sh file?

No, because there is no way to use Newsboat's pager as a separate command (i.e. you can't call it from a shell script).

What I'd do instead in your case is write [a macro](https://newsboat.org/releases/2.28/docs/newsboat.html#_macro_support) that changes the `pager` setting, calls `open`, then restores the setting. You could then use that macro to open articles from the XKCD feed.

Would that work for you?

**Comment by Minoru** [comment]
> it will be tedious to press the macro-prefix + key on every single one of them.

Yeah. We're thinking of unifying macros and ordinary keys though (#1165), so hopefully sometime in the future it won't be tedious anymore.

**Comment by Minoru** [comment]
Cool! I guess the original question is answered, then. Please open more issues if you've got more questions or suggestions!
