### ISSUE TITLE
Types of feeds where each "article" opens the same link and marks-as-read everything

### ISSUE THREAD

**Issue by shabbs15** [newsboat/newsboat#2128]
You have a twitter feed and you don't have to open each tweet individually. 

When you open one "article/tweet", it opens up to the persons twitter account rather than the tweet

All other articles are marked as read.

You don't have to open a large amount of tabs and you can read the persons tweets more quickly

Is this viable?

**Comment by Minoru** [comment]
This is already possible:

- to open the Twitter profile, put the cursor onto the feed in the feedlist and press <kbd>o</kbd> (default key for `open-in-browser`). If it doesn't open the page you want, try a different source for Twitter feeds; e.g. Nitter opens a Nitter page for the user. Alternatively, look if you can get your current source to add a `<link href="…">` attribute to the RSS channel or `<link rel="alternate" href="…">` to the Atom feed;
- to mark all articles in a feed read, press <kbd>A</kbd> (default key for `mark-feed-read`).

Does that cover your use-case sufficiently well?

**Comment by shabbs15** [comment]
Wow, this is perfect, thanks
