### ISSUE TITLE
Question about: "NewsBlur’s folders are converted into Newsboat tags"

### ISSUE THREAD

**Issue by shmup** [newsboat/newsboat#2132]
I've tried to parse the docs before opening a ticket. I've set up minimal configuration to used newsboat for Newsblur.

```
urls-source "newsblur"
newsblur-login "<censored>"
newsblur-password "<censored>"
newsblur-url "https://newsblur.com"
cookie-cache "~/.newsboat/cookies.txt"
newsblur-min-items 20
```
That's pr much it, nothing configured in `urls`.

However, this is what renders, and I'm wondering if there's some configuration I need to do in Newsblur itself. My setup on that service is, most feeds are just in the root, and a variety I've put into root/\<folder\>. Additionally, when working, will newsboat treat root as a folder itself? re: the title "newsblur foldres are converted into newsboat tags"

![image](https://user-images.githubusercontent.com/118710/181035747-82c35954-26f9-4f32-a852-9374f7dee40a.png)

**Comment by Minoru** [comment]
Newsboat doesn't reload feeds by default. You have to press R to do that, or configure auto-reload. That will fetch the proper feed titles, and populate feeds with items.

I don't think tags or folders have anything to do with this, but if you press R and something still looks wrong, please comment and let's figure it out!

**Comment by shmup** [comment]
Appreciate the quick reply, and especially appreciate that it was the thing I needed to do :) 

Thanks!
