### ISSUE TITLE
Question: Can a filter be applied by default?

### ISSUE THREAD

**Issue by shmup** [newsboat/newsboat#2133]
I run newsboat, `f`, and select `unread`.

I always do this, so I was wondering: can I just make it a default? 

Would love to be pointed to a relevant bit in the docs, if so.

Thanks!

**Comment by der-lyse** [comment]
I didn't try it, but with [`run-on-startup`](https://newsboat.org/releases/2.28/docs/newsboat.html#run-on-startup), you should be able to define either [`set-filter`](https://newsboat.org/releases/2.28/docs/newsboat.html#set-filter) or [`select-filter`](https://newsboat.org/releases/2.28/docs/newsboat.html#select-filter). Not sure what the difference between both is, can't try I right now.

**Comment by shmup** [comment]
Well I got it, but weirdly I had to specify the query, not the query name. This just means if I want to change both the `unread` saved filter, and the `run-on-startup`, I need to edit in 2 places. But at least I got it, so thank you!

```
run-on-startup select-filter "unread_count > 0"
```

Though, if I had defined tags, I could do this:

`run-on-startup set-tag "space"` https://github.com/newsboat/newsboat/issues/93

Even in a ticket about predefined-filters, the answer is leveraging tags: https://github.com/newsboat/newsboat/issues/93#issuecomment-720143222

**Comment by dennisschagt** [comment]
> Well I got it, but weirdly I had to specify the query, not the query name

I can reproduce this. It is strange that `select-filter` with an argument behaves exactly the same as `set-filter` with a single argument.
I think it makes sense to change that by letting `select-filter` select by name.

Regarding your initial question:
> I run newsboat, f, and select unread.
> I always do this, so I was wondering: can I just make it a default?

Newsboat already has some functionality to only show unread feeds/items.
By default, [toggle-show-read-feeds](https://newsboat.org/releases/2.28/docs/newsboat.html#toggle-show-read-feeds) is bound to the `l` key (lower-case L)
Even though the name only mentions feeds, this also works in lists of articles (to show/hide read articles)

This can be applied by default using regular configuration options [show-read-feeds](https://newsboat.org/releases/2.28/docs/newsboat.html#show-read-feeds) and [show-read-articles](https://newsboat.org/releases/2.28/docs/newsboat.html#show-read-articles)
For example: `show-read-feeds no`

**Comment by shmup** [comment]
@dennisschagt this is prefect, thanks. 

Setting `show-read-feeds no` and learning about `l` is a much better situation. 

Nice job getting a PR up quickly to allow `select-filter` to accept a `name`, also!
