### ISSUE TITLE
Question: can I define/customize behavior such that I get 2 commands in 1?

### ISSUE THREAD

**Issue by shmup** [newsboat/newsboat#2134]
Example:

I go into a feed and often end up doing a `A` to mark 'em all read, then immediately do a `q` to go back to the list of feeds. So I was wondering if I can define this behavior myself, such that when I `A`, it will then go back to the list of feeds.

If it's possible, I'd love being pointed to the relevant section in the docs.

(Sort of related, I thought I saw a setting for this I cannot currently find. When I `o` to open a feed in the browser, I would actually like to mark the feed as read, too. Possible?)

Thanks!

**Comment by shmup** [comment]
Well, I got the "sort of related" question.

Simply use `O` instead of `o`: https://newsboat.org/releases/2.28/docs/newsboat.html#open-in-browser-and-mark-read

**Comment by shmup** [comment]
I'm ok with this going unanswered because it's a pretty poorly worded question :)

**Comment by Minoru** [comment]
Sorry for the late reply! The answer to your question should be [macros](https://newsboat.org/releases/2.28/docs/newsboat.html#_macro_support), but they require two keypresses too, so it doesn't save you any typing here. We have ideas for a new design that won't require two keypresses (#1165), but that haven't been finalized and implemented yet.

I guess this answers the question?

**Comment by shmup** [comment]
Better late than never. I could open the issue until that's implemented if you tag this one in a comment? Your call, if you do just reopen!

**Comment by Minoru** [comment]
The design and implementation is already tracked by #1165, so let's keep this closed.
