### ISSUE TITLE
View is scrolled too much when toggling `show-read-feeds`

### ISSUE THREAD

**Issue by shmup** [newsboat/newsboat#2138]
**Newsboat r2.28-35-gcc4a**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
urls-source "newsblur"
newsblur-login "foo"
newsblur-password "changeme"
newsblur-url "https://newsblur.com"
cookie-cache "~/.newsboat/cookies.txt"
newsblur-min-items 20
browser xdg-open
define-filter "unread" "unread_count > 0"
feed-sort-order "title"

unbind-key j
unbind-key k

bind-key j down
bind-key k up

unbind-key g # bound to `sort` by default
bind-key g home
unbind-key G # bound to `rev-sort` by default
bind-key G end

confirm-mark-all-feeds-read no

show-read-feeds no
```

Steps to reproduce the issue:

Easiest to just see the attached mp4, but..

1. Toggle to your unread feeds so you get a tinier list

2. Focus the last feed

3. Toggle back to the full list4. 

4. Notice the list is scrolled off (to the top) and you have to cursor up to see it

**Other info you think is relevant**:

https://user-images.githubusercontent.com/118710/182013406-79dd7647-6b8b-4091-87ee-f15a20420ed3.mp4

**Comment by shmup** [comment]
You likely got a push notification with this full initial open Issue, containing my config's password, because I'm tired. Have no fear, I have changed it :sweat_smile:

**Comment by Minoru** [comment]
I can't reproduce this exactly, but I get a similar effect if I do the following:

1. start Newsboat with empty config;
2. press <kbd>l</kbd> to hide read feeds;
3. press <kbd>End</kbd> to go to the end of the list;
4. press <kbd>l</kbd> twice to show and then hide the read feeds

then only one item is shown, and the cursor is at the top of the list, just like in your video.

Thanks for the report!
