### ISSUE TITLE
Feature request: accept brotli encoding

### ISSUE THREAD

**Issue by Seirdy** [newsboat/newsboat#2152]
Full-text feeds can get pretty massive, especially when authors don't use paginated feeds. Most distros build libcurl with support for Brotli compression; this could help save some bandwidth, esp. since many Newsboat users fetch feeds from static sites with static compression enabled.

I'm not a C++ developer, but it looks like this could be implemented by a simple change to `curl_easy_setopt` calls.

Newsboat version:

```
Newsboat 2.28.0
System: Linux 5.18.16-200.fc36.x86_64 (x86_64)
Compiler: g++ 12.1.1 20220507 (Red Hat 12.1.1-1)
ncurses: ncurses 6.2.20210508 (compiled with 6.2)
libcurl: libcurl/7.82.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.46.0 OpenLDAP/2.6.2 (compiled with 7.82.0)
SQLite: 3.36.0 (compiled with 3.36.0)
libxml2: compiled with 2.9.14
```

**Comment by dennisschagt** [comment]
> … it looks like this could be implemented by a simple change to curl_easy_setopt calls.

Yes, it looks like that is possible and quite easy, from https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html:
> To aid applications not having to bother about what specific algorithms this particular libcurl build supports, libcurl allows a zero-length string to be set ("") to ask for an Accept-Encoding: header to be used that contains all built-in supported encodings.

and
> Four encodings are supported: identity, meaning non-compressed, deflate which requests the server to compress its response using the zlib algorithm, gzip which requests the gzip algorithm, (since curl 7.57.0) br which is brotli and (since curl 7.72.0) zstd which is zstd.
