### ISSUE TITLE
Newsboat to tt-rss on OpenBSD: ttrss-flag-star & ttrss-flag-publish not working.

### ISSUE THREAD

**Issue by Entheonautic** [newsboat/newsboat#2163]
> Newsboat 2.26.0
> System: OpenBSD 7.1 (amd64)
> Compiler: g++ OpenBSD Clang 13.0.0
> ncurses: ncurses 5.7.20081102 (compiled with 5.7)
> libcurl: libcurl/7.84.0 LibreSSL/3.5.2 zlib/1.2.11 nghttp2/1.47.0 (compiled with 7.82.0)
> SQLite: 3.38.3 (compiled with 3.38.2)
> libxml2: compiled with 2.9.13

Config file:

```
ttrss-flag-publish "b"
ttrss-flag-star "a"
ttrss-login "<user>"
ttrss-mode "multi"
ttrss-password "<password>
ttrss-url "https://..."
urls-source "ttrss"
custom macros
[...]
key-bindings
[...]
external-url-viewer "urlview"
prepopulate-query-feeds yes
reload-threads 15
feedlist-format "%4i %n %11u %t"
articlelist-format "%4i %f%F %D %6L %?T?|%-17T|  ?%t"
```

Steps to reproduce the issue:
1. Pressing 'a' to start an article doesn't star it and no errors seen.
2. Pressing 'b' also doesn't mark them as published.

I am not sure where else to look if there are errors that would explain why it's not working.

**Comment by dennisschagt** [comment]
I expect the `a` and `b` flags can be added to an article by editing the article flags (by default bound to Ctrl+E)
See [editing flags](https://newsboat.org/releases/2.26/docs/newsboat.html#_flagging_articles) and [the operation which starts it](https://newsboat.org/releases/2.26/docs/newsboat.html#edit-flags)

**Comment by Entheonautic** [comment]
Wonderful, that works. I misunderstood how the flagging works. Thanks for the reply!
