### ISSUE TITLE
Make `FeedHandler::sort_feeds` accept a structure not a string

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#217]
Once #216 is merged, `FeedHandler::sort_feeds` should be changed to accept a structure that describes the sorting order, as outlined in [this discussion](https://github.com/newsboat/newsboat/pull/216#discussion_r194252861).

**Comment by kmws** [comment]
Who should handle tokenizing the config value and creating this struct? 
The caller before every call? some helper funtion?

**Comment by Minoru** [comment]
I think it makes the most sense to put the tokenizing part in `configparser`, and `configcontainer` would store the structure. Clients will call a special method on `configcontainer` 

In general: the container is just a glorified `std::map` right now; I'll be happy if that changed to something more strictly typed. Eventually we'll end up with a lot of special methods (one for each kind of value), which is fine by me.
