### ISSUE TITLE
[Feature Request] Disable feed

### ISSUE THREAD

**Issue by lonix1** [newsboat/newsboat#2171]
2.21.0

I have many feeds, and some I don't want to update for a while. But I don't want to remove them from my list, just to disable temporarily.

Would be nice to be able to do this:
````
https://www.example.com/rss/ "tag" disable
````

**Comment by Minoru** [comment]
Sorry for the delayed response! My next one might be delayed too because I'm down with COVID ._.

This feature sound similar to #1844 and #445. Just like in #1844, my question is: can't this be achieved by hiding the feed?

**Comment by Minoru** [comment]
I meant "hidden" tags (the ones that start with exclamation mark):

```
https://www.example.com/rss/ !disabled
```

But commenting out works fine too. There are important differences between the approaches though:

- if you have `cleanup-on-quit` enabled (which is the default), commenting out a feed will remove its articles from the cache. When you uncomment the feed, it would be empty. This doesn't happen with hidden feeds. Also, the default will be changed sometime in the future (#1183), to prevent data loss;
- hidden feeds are still reloaded with `reload-all`. If you want to ignore them, you could enable `reload-only-visible-feeds`
- commented-out feeds are unreachable from query feeds, while hidden feeds can be reached just fine

I don't think Newsboat needs a separate feature for this. It's easy enough to press <kbd>E</kbd> and edit the urls file, or edit it in an editor in a different window and then press <kbd>^R</kbd> to reload the file in Newsboat. So I'll close this.

And thanks for the kind words! I'm over the worst part already, happy to return to my usual life of quietly putting out the code ^_^
