### ISSUE TITLE
Any ways to exclude and filter the articles with certain keywords?

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2189]
I know that we can search for certain articles by pressing `/` and typing the keywords.
But any way to filter and exclude the articles with certain keywords?

Thanks.

**Comment by Minoru** [comment]
The following filter should do the trick:

```
content !# "keyword"
```

If the keyword contains spaces, try regexes instead:

```
content !~ "multiple words"
```

You can type apply these interactively by pressing <kbd>F</kbd> and typing them in, then pressing <kbd>Enter</kbd> to apply them. Does that answer the question?

**Comment by amalgame21** [comment]
Yes! Thank you very much!!!
