### ISSUE TITLE
Mark All Read doesn't work in (ocnews) query feeds

### ISSUE THREAD

**Issue by arjan-s** [newsboat/newsboat#220]
**Newsboat version (copy from `newsboat -v`)**: 2.11.1

Steps to reproduce the issue:

1. Create a query feed, for instance:
`"query:Category - Tech:tags =~ \"Tech\""`
2. Open the query feed with unread articles in Newsboat
3. Press 'A' for 'Mark All Read'
4. Newsboat (correctly) marks all articles as read in the interface
5. Go back to the main screen and press 'R' for 'Reload All'
6. All feeds are reloaded and all articles that were marked as read are back and unread

**Other info you think is relevant**:
My config options related to read/unread articles:
```
show-read-feeds         no
show-read-articles      no
mark-as-read-on-hover   yes
```
Also, marking all articles as read in an actual feed works fine.

**Comment by Minoru** [comment]
Thank you for the report! I think I found the cause—Newsboat marked the feed read in its database, but didn't send that info to remote API (ocnews in your case). Can you pull down `bugfix/220` branch and check if it fixes the issue for you?

**Comment by arjan-s** [comment]
Sorry, I tested the branch, but I get the same behaviour.

**Comment by Minoru** [comment]
I don't have ocnews, so I had to test with The Old Reader instead, and it works there. Can you check again with a minimal config that contains just `urls-source`, `ocnews-login` and `ocnews-password`?

**Comment by arjan-s** [comment]
Of course. I did that right now and found the same issue. After "A" for reload all, the articles previously marked as read were marked unread again.

**Comment by nononomen** [comment]
Same issue here. I can make you an ocnews account if it helps.

**Comment by Minoru** [comment]
Thank you for the offer, @nononomen, but I don't know when—and if—I'll be getting back to this.

**Comment by Minoru** [comment]
@arjan-s, @nononomen: can you try out #1275 and tell us if this fixes the bug?

**Comment by arjan-s** [comment]
Hi, thank you for notifying me.
Essentially, it does fix the bug, but I'm afraid the implementation is not useful yet.
When marking a query feed read-all, the current implementation performs an API call to mark each and every article in the feed as read. There is one bug in the current code: it also performs the API call for articles that were already marked read. Changing this to only mark unread articles as read would improve the performance a lot.
Then there is a higher level performance question: is marking every article individually the way to go? Performance-wise it would be much better to use the single API call to mark an entire feed read, like when marking a single feed read. That would make the current PR more difficult though, I imagine.

**Comment by Minoru** [comment]
Okay, thanks! Since the bug is *technically* fixed, I'll merge that PR.

As for performance, we do have a couple issues about it, e.g. https://github.com/newsboat/newsboat/issues/123 and https://github.com/newsboat/newsboat/issues/682. Improving that requires pretty drastic changes to how Newsboat works with remote APIs. I personally won't work on that until after the move to Rust, but #123 has some instructions if anyone's itching to help.
