### ISSUE TITLE
History: Option to store, search and tag

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#2200]
May be we could have an option to enable history of all the visited sites with other Metadata like Feedname, date, time. 

This might be useful as it might be nice to be able to search through already consumed content when needed in future. It's quite likely as we often need to recall something which we consumed, but was not very important at the time of consumption abd that we didn't paid enough attention to make a note of it. But later, when we hear something related we might want to go back to the website, which is possible only through history... 

May be storing this information as a text file might be good as one can use standard terminal tools to search, sort, filter..

Also, it would be interesting if one could add tag (if desired), after consuming the content, so that it can help in finding the content later.

**Comment by Minoru** [comment]
Hi, sorry for the delayed response!

It sounds like all you need is to create a script like this:

```sh
#!/bin/sh
feed_url="$1"
article_url="$2"
echo "$(date)\t${feed_url}\t${article_url}" >> ~/history.txt
firefox "${article_url}"
```

Save it as e.g. "browser.sh", make it executable, and configure Newsboat with `browser "/path/to/browser.sh %F %u"`. Does that cover your use-case?

As for tagging items, please take a look at [flagging](https://newsboat.org/releases/2.29/docs/newsboat.html#_flagging_articles) and tell me if that works for you.

**Comment by Minoru** [comment]
https://github.com/newsboat/newsboat/issues/1396 is related, but asks for a history of articles that have been read within Newsboat. This is impossible to do externally when using internal HTML rederer and pager, which is why the answer there is different.

**Comment by Minoru** [comment]
I think this is answered. Please comment if you disagree — the issue can always be re-opened.
