### ISSUE TITLE
Error while retrieving: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by tapyu** [newsboat/newsboat#2210]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.21.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.21.0
System: Linux 5.15.0-48-generic (x86_64)
Compiler: g++ 10.2.1 20201207
ncurses: ncurses 6.3.20211021 (compiled with 6.2)
libcurl: libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13 (compiled with 7.72.0)
SQLite: 3.37.2 (compiled with 3.34.0)
libxml2: compiled with 2.9.10
```
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
ignore-mode "display" # download the items, but do not show them
ignore-article "http://portal.utfpr.edu.br/noticias/ultimas-noticias/@@RSS" "title !~ \"(vaga|bolsa|resultado|seleção|concurso)\""
```
I am trying to set up `newsboat` with my feed readers, but one in particular does not want to work (https://ifce.edu.br/rss.xml). However, this feeder does work properly in other RSS readers. I am trying to understand why it is happening.

Steps to reproduce the issue:

1. Add `https://ifce.edu.br/rss.xml` to your `urls` file.

2. Try to reload.

3. You will get `Error while retrieving https://ifce.edu.br/rss.xml: SSL peer certificate or SSH remote key was not OK`.

**Comment by hiltjo** [comment]
Looks like a certificate issue. newsboat uses libcurl. When using the command-line cURL:

I see the following message:

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by tapyu** [comment]
It seems to be a certificate issue, indeed. I have no knowledge about SSL, but the code `curl --insecure 'https://ifce.edu.br/rss.xml'` returns the `.xml` file that is supposed to feed the `newsboat`. How to modify `newsboat` in order to use this command?

**Comment by tapyu** [comment]
I could solve it by using the `execurl:` option to get the `.xml` file. My final config becomes
```
"exec:/usr/bin/curl --insecure 'https://ifce.edu.br/rss.xml'" "~IFCE"
```
Is the way I used correct?

**Comment by hiltjo** [comment]
It looks OK, it can be a way to workaround the issue. Of course this can be insecure (no certificate/peer vertification and validation etc).
Another way could be retrieving the certificate and using a local trusted certificate bundle and specifying the curl --cacert option. This is useful for self-signed certificates too.

Hope this helps,

**Comment by josx** [comment]
BTW you can config newsboat to avoid some ssl checks.

ADD this to **.newsboat/config** file

```
ssl-verifyhost no
ssl-verifypeer no
```
