### ISSUE TITLE
Allow splitting a config command into multiple lines

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2212]
I created a very long filter macro in the `config` file like this:

`macro F set-filter " content !~ \"keyword1\" and title !~ \"keyword1\" and content !~ \"keyword2\" and title !~ \"keyword2\" and ...........................and title !~ \"keywordN\" "`

I would like to split it into multiple lines that I can easily edit and manage the list of filter.
But those are inside a pair of double quotes, I don't know how to break into new lines with `\`.
Any way to split the filter languages to multiple lines??? Thanks!

**Comment by Minoru** [comment]
Hi, sorry for the delayed response!

This isn't possible yet, but seems like a good feature to have. I think the most common way to support this is to allow backslash at the end of the line, so one could write:

```
macro F set-filter " \
  content !~ \"keyword1\" \
  and title !~ \"keyword1\" \
  and content !~ \"keyword2\" \
  and title !~ \"keyword2\" \
  and ........................... \
  and title !~ \"keywordN\" "
```

Looks like this is fairly simple to implement. The relevant files are _include/configparser.h_, _src/configparser.cpp_, and _test/configparser.cpp_.

**Comment by amalgame21** [comment]
Thanks for your explanation! 
I agree with your suggestion, that's also what I think of!
