### ISSUE TITLE
Access title article in external browser script

### ISSUE THREAD

**Issue by isak102** [newsboat/newsboat#2224]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat 2.29.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2022 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2022 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.29.0
System: Linux 6.0.2-arch1-1 (x86_64)
Compiler: g++ 12.2.0
ncurses: ncurses 6.3.20211021 (compiled with 6.3)
libcurl: libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0 (compiled with 7.85.0)
SQLite: 3.39.4 (compiled with 3.39.3)
libxml2: compiled with 2.10.2
```
It would be useful to be able to pass the title to a external script along with the URL. Right now I have for example: `set browser "/home/isak102/.config/newsboat/newsboat-mpv -u %u" ; open-in-browser ; set browser /home/isak102/.config/newsboat/linkhandler`, passing in the title could be something like `%t`. Is this something that could be done?

**Comment by Minoru** [comment]
Sure! But the passed string would be empty if browser is invoked from the feedlist (e.g. one starts Newsboat and presses <kbd>o</kbd> to open the selected feed). Also, [`%t` is already taken](https://newsboat.org/releases/2.29/docs/newsboat.html#_using_browser), but we could use `%T` I guess.

This is fairly simple to implement: look at https://github.com/newsboat/newsboat/pull/2096 which added `%t`. This issue should be even easier to implement I think. And don't hesitate to ask questions!
