### ISSUE TITLE
Encoding conversion errors when fetching feeds

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#2230]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 117ea16977de9dbb7c148aa4a1887ba7cb006303

Config file is empty. Urls file is:

```
http://practicaltypography.com/feed.xml
https://www.roscosmos.ru/rss/102/
https://www.roscosmos.ru/rss/22356/
```

Steps to reproduce the issue:

1. start an older version of Newsboat and reload these feeds;
2. start Newsboat 117ea16977de9dbb7c148aa4a1887ba7cb006303 and reload the feeds. Observe that:

    - the first feed's title changes
    - the second and third feeds cause an error to be printed to the terminal, breaking Newsboat's UI: "encoding error : input conversion failed due to input error, bytes 0x98 0xD0 0xBD 0xD1" and "encoding error : input conversion failed due to input error, bytes 0x98 0xD0 0x90 0x20"

**Other info you think is relevant**:

I haven't bisected, but I think this is caused by https://github.com/newsboat/newsboat/pull/2214. I guess these sites return an incorrect encoding in the HTTP headers, which causes Newsboat to convert the feed into that encoding, which breaks the text. All three feeds worked fine when we didn't have the conversion, which implies that libxml managed to process them correctly based on the encoding specified in the XML.

**Comment by dennisschagt** [comment]
I cannot access the roscosmos.ru feeds (might be blocked in my country).

Regarding http://practicaltypography.com/feed.xml
It redirects to https://practicaltypography.com/feed.xml

The HTTP to HTTPS redirect response contains a header specifying a non-utf-8 charset: `Content-Type: text/html; charset=iso-8859-1`
The HTTPS response does not specify a charset: `Content-Type: application/xml`

If we don't detect a charset, we assume utf-8,which would be correct for this feed.
However, we already store the charset of the original redirect response, causing us to incorrectly try to convert from iso-8859-1.

It looks like it is our own responsibility to clear header data from the non-final responses.
From [the libcurl documentation](https://curl.se/libcurl/c/CURLOPT_HEADERFUNCTION.html):
> It's important to note that the callback will be invoked for the headers of all responses received after initiating a request and not just the final response. This includes all responses which occur during authentication negotiation. If you need to operate on only the headers from the final response, you will need to collect headers in the callback yourself and use HTTP status lines, for example, to delimit response boundaries.

**Comment by Minoru** [comment]
#2243 indeed fixes practicaltypography.com, but doesn't affect the roscosmos issue.

**Comment by Minoru** [comment]
Roscosmos feeds declare their encoding both in the `Content-Type` HTTP header and the XML document itself:

```
$ curl --head https://www.roscosmos.ru/rss/102/ --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0'
HTTP/1.1 200 OK
Content-Type: text/xml; charset=windows-1251
Connection: keep-alive
Date: Mon, 19 Dec 2022 19:00:10 GMT
Vary: Accept-Encoding
Cache-Control: max-age=0
Expires: Mon, 19 Dec 2022 19:00:10 GMT
Content-Security-Policy-Report-Only: script-src 'self' 127.0.0.1:8182 127.0.0.1:8888 127.0.0.1:5005; frame-src 'self'; object-src 'self'; report-uri /cspreportonly;
Set-Cookie: session-cookie=173246f086e6c0953891f55bb4819f5bc48515c93a3501e421431bb28fcd68788acbd28365b4dd62e11915fbf3beb520; Max-Age=86400; Path=/; secure; HttpOnly
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
```

```xml
<?xml version="1.0" encoding="windows-1251" ?>
<rss version="2.0">
<channel>
...
```

(You can see for yourself: [roscosmos_102.rss.gz](https://github.com/newsboat/newsboat/files/10261985/roscosmos_102.rss.gz))

`utils::retrieve_url` converts the text from Windows-1251 to UTF-8, but keeps the header of the XML document intact. As a result, libxml2 tries to parse the incoming UTF-8 as Windows-1251, and fails.

I tried to force libxml2 to use UTF-8 with the following patch:

```patch
diff --git a/rss/parser.cpp b/rss/parser.cpp
index d370befc..982c745a 100644
--- a/rss/parser.cpp
+++ b/rss/parser.cpp
@@ -285,7 +285,7 @@ Feed Parser::parse_buffer(const std::string& buffer, const std::string& url)
        doc = xmlReadMemory(buffer.c_str(),
                        buffer.length(),
                        url.c_str(),
-                       nullptr,
+                       "UTF-8",
                        XML_PARSE_RECOVER | XML_PARSE_NOERROR | XML_PARSE_NOWARNING);
        if (doc == nullptr) {
                throw Exception(_("could not parse buffer"));
diff --git a/src/opmlurlreader.cpp b/src/opmlurlreader.cpp
index b6acf467..8d9599a4 100644
--- a/src/opmlurlreader.cpp
+++ b/src/opmlurlreader.cpp
@@ -27,7 +27,13 @@ nonstd::optional<utils::ReadTextFileError> OpmlUrlReader::reload()
                std::string urlcontent = utils::retrieve_url(url, cfg);
 
                xmlDoc* doc =
-                       xmlParseMemory(urlcontent.c_str(), urlcontent.length());
+                       xmlReadMemory(
+                                       urlcontent.c_str(),
+                                       urlcontent.length(),
+                                       url.c_str(), // base URL for the document
+                                       "UTF-8",
+                                       0 // parsing options
+                                       );
 
                if (doc == nullptr) {
                        LOG(Level::ERROR,
```

This works, i.e. I don't get conversion errors on the Roscosmos feed anymore, but I suspect that it will create new problems: if encoding is declared in XML but *not* in the Content-Type, then `utils::retrieve_url` won't do any conversion, and the input to libxml would not be in UTF-8.

I wish I could describe a satisfactory solution here, but I haven't come up with one because I ran out of time for today. Will carry on tomorrow. If worst come to worst, I'll have to revert the two PRs above, because mangling data is worse then outright crashing (in my opinion at least).

**Comment by Minoru** [comment]
Closing in favour of #1436.
