### ISSUE TITLE
Allow flagging / starring articles with Miniflux

### ISSUE THREAD

**Issue by sonor3000** [newsboat/newsboat#2235]
Is there really no possebility to flag / star an article wheen miniflux is used as backend? Or did I miss something? Using current newsboat version on Debian unstable.

**Comment by Minoru** [comment]
It's not implemented yet. If anyone is interested, take a look at `MinifluxApi::update_article_flags` in src/minifluxapi.cpp This method is implemented for other APIs, so one can take inspiration from them.

That would handle the Newbsboat-to-Miniflux flagging/starring. The other direction is not implemented for any API at all; the issue for that is #1130.

**Comment by Minoru** [comment]
Fixed by https://github.com/newsboat/newsboat/pull/2693.
