### ISSUE TITLE
wrap-scroll doesn't respect a value of "no"

### ISSUE THREAD

**Issue by Pound-Hash** [newsboat/newsboat#2238]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.29.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
wrap-scroll no
```

Steps to reproduce the issue:

1. Set `wrap-scroll` to `no`

2. Scroll up/down list with `next-unread`/`prev-unread`

3. When list reaches end, it wraps

**Comment by Minoru** [comment]
`wrap-scroll` doesn't affect `next-unread`, `prev-unread` and `random-unread` operations. If you don't want these operations to switch between feeds, set [`goto-next-feed`](https://newsboat.org/releases/2.29/docs/newsboat.html#goto-next-feed) to `no` or `false`.
