### ISSUE TITLE
build system relies on unstable implementation details of Cargo

### ISSUE THREAD

**Issue by Be-ing** [newsboat/newsboat#2239]
Hi there. I'm working on [CXX-Qt](https://github.com/KDAB/cxx-qt) and have been advocating for a [better way for cxx to work with C++ build systems besides Bazel](https://github.com/dtolnay/cxx/issues/462). In discussing packaging cxx with @decathorpe, he let me know that newsboat is using cxx and is packaged in Fedora. So I took a look at how you're using cxx.

I see you're [adding the `target/cxxbridge` directory to your include paths](https://github.com/newsboat/newsboat/blob/1fc27253bd7d6c7b4739bdd139116370ea590fc5/Makefile#L53) in a manually written Makefile. This is problematic because that cxxbridge directory is [only a development tool](https://github.com/dtolnay/cxx/blob/c7060d40361c4d955fc64adf35f67b28b5c75299/gen/build/src/lib.rs#L151) and [relies on unstable implementation details of Cargo](https://github.com/dtolnay/cxx/blob/c7060d40361c4d955fc64adf35f67b28b5c75299/gen/build/src/target.rs#L10).

The currently recommend way to handle this is to use the CLI cxxbridge tool, which is written in Rust, to generate the C++ code and compile that with the C++ build system. However, this is cumbersome because it adds another dependency which you somehow need to install (nobody has packaged it AFAICT) or build. It's also problematic because the CLI tool's version needs to precisely match the version of the cxx proc_macro crate and these could easily get out of sync with each other.

Neither of those are problems when the C++ code is generated and compiled by cxx-build in build.rs. The problem with cxx-build currently is that there isn't a reliable way for the headers it generates to get added to the include paths by the C++ build system. My proposal in https://github.com/dtolnay/cxx/issues/462 / https://github.com/dtolnay/cxx/pull/1120 is to create a way for the C++ build system to tell cxx-bridge where to symlink the generated headers via an environment variable. This way the C++ build system can reliably add that path to its include paths without relying on unstable implementation details of Cargo.

I'd appreciate your input on https://github.com/dtolnay/cxx/issues/462 to emphasize that this issue applies to all C++ build systems that invoke Cargo, not only CMake.

**Comment by Minoru** [comment]
Hi, sorry it took me so long to dive into this! It's a lot to read. Also thanks for bringing this to my attention.

We don't depend on Cargo implementation details because we set `CARGO_TARGET_DIR` ourselves, but we do depend on the existence of "cxxbridge" directory. The approach you proposed in the PR looks fine to me, but dtolnay locked all the relevant discussions, so I won't pester him about this. Maybe someday he'll change his mind, or maybe he'll break the cxxbridge directory and thus force me to open a new issue about this.

I'm closing this because it's not actionable (anymore — sorry once again!)

**Comment by Be-ing** [comment]
> We don't depend on Cargo implementation details because we set CARGO_TARGET_DIR ourselves, but we do depend on the existence of "cxxbridge" directory.

To be clear, the existence of the `cxxbridge` directory inside CARGO_TARGET_DIR is what relies on implementation details of Cargo. It could easily break when Cargo changes.
