### ISSUE TITLE
Auto-refresh query feeds on startup, regardless reload or not

### ISSUE THREAD

**Issue by gulliver-4qd** [newsboat/newsboat#2247]
Query-feeds represent already existing state from other feeds, they don't need to (re)load any external data.
Hence it makes sense to auto-refresh all query feeds on newsboat app startup, regardless if auto-reload is enabled or not.

Use case:
I manually reload all feeds a couple times a day. The machine with newsboat then is offline for a longer period. 
After having closed Newsboat, if I reopen the app offline to read some articles (there is no reload), all query feeds behave, as if they had zero entries. 
I need to manually search for their entries in the feeds' list amongst other feeds without entries. After opening them, they update to have  the correct amount of unread/read articles (according to referenced feeds).
This is quite cumbersome and non-intuitive behavior. Instead it would be cool to just have the query feeds with their current state ready to be read at startup.

**Comment by dennisschagt** [comment]
(I never used it myself but) I expect that configuring [`prepopulate-query-feeds yes`](https://newsboat.org/releases/2.29/docs/newsboat.html#prepopulate-query-feeds) will work for your use-case.

**Comment by gulliver-4qd** [comment]
Awesome, thank you! I must have overlooked that entry in the docs.
