### ISSUE TITLE
Feature request: Filter by current title

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#225]
**Newsboat version (copy from `newsboat -v`)**: 2.12.0

Steps to reproduce the issue:

I do not see how to do it in an easy way to filter messages by currently selected title.

I have RSS channel where all the user comments are retreived for articles. If I want to read only these  related to specific topic I do the following:

Shift+F then type `title =~ "<part of current title here>"`

This is rather annoying and it would be nice to have at least possibility to make a macro for it. But I do not see how can I get currently selected title to put this into a macro for the filter definition.
(By "currently selected" I meant that the cursor is placed on the article in the article list.)

Can this be done in a current version of newsboat or it has to be developed?

Regards,
Piotr

**Comment by Minoru** [comment]
Hi! Thank you for taking the time to write this up.

If you don't use bookmarking, you can abuse it to automate all this: write a script that creates the filter expression you want and copies it into your X clipboard, then press `F` and paste with Shift+ins. That's about as good as you can do without modifying Newsboat.

As for adding this functionality into Newsboat itself, I'm doubtful. It doesn't make sense to limit this to just titles, so it'll have to be implemented for everything else: author's name, feed title, flags, tags, etc. The added complexity just isn't worth it in my opinion. Sorry, but you'll have to stick with your current approach, maybe with some little automation I described above.

**Comment by ZaxonXP** [comment]
Thanks for pointing out for the bookmarking. In fact I currently use bookmark script to do some stuff, but because I use the newsboat from remote machine trough tmux, I could write tmux macro and assign it to some key combination. That could also work with the current version of newsboat.

**Comment by jcul** [comment]
Try a query feed:
https://newsboat.org/releases/2.14.1/docs/newsboat.html#_query_feeds
You can create a new feed by filtering an existing one.
