### ISSUE TITLE
[question] cache.db growing bigger over time, and newsboat become slower and slower

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2254]
After a year or so, my `cache.db` become bigger and bigger, and now it is over 1GB.
Some of the feeds containing about 7XXXX articles. When I open those feeds, the cursor (up and down) become very slow and not very responsive.
And `newsboat` now takes about 15 seconds to launch.
But I really want to keep ALL those cache, so I can search for the articles in later time, maybe after a year.

What I am doing now is manually creating backups over a period of time.
For example, creating a monthly backup by renaming of `cache.db` into maybe `cache.db.OCT` for October and start a new `cache.db` for November.
However if I want to search for an old article, I have to rename the backup back into `cache.db`, then use `newsboat` to search for the articles.
If I want to search for 1 years of old cache.db, I have to do the rename process 12 times since those are monthly backups.

I do not know any other practical and more elegant way to make newsboat faster while keeping all the records.

Are there any commands that allow `newsboat` to limit reading the `cache.db` for maybe most recent month, so that it become more responsive, and launch faster?? 

Or are there any ways to split the `cache.db` by a period of date (a month/ half a year), and later we can merge it back into one single big `cache.db` when performing and old article search?

Or any options to launch `newsboat` by loading multiple cache files, say `cache.db.SEP` `cache.db.OCT` at once by multiple `--cache-file=` flag??

Thanks.

**Comment by hiltjo** [comment]
Hi,

Just curious, can you try out this shellscript, it adds 2 indices to the database and in my use-case improves start-up time much:

#!/bin/sh
sqlite3 ~/.newsboat/cache.db <<!
CREATE INDEX idx_feedurl_deleted ON rss_item(feedurl, deleted);
CREATE INDEX idx_unread ON rss_item(unread);
!

See also:
https://github.com/newsboat/newsboat/pull/2057
https://github.com/newsboat/newsboat/pull/2057/commits/3cc6bbc80a1addd71d3c6f1592348682393df49a

Of course make sure to backup your cache.db file (just in case).

Thanks,

**Comment by amalgame21** [comment]
> Hi,
> 
> Just curious, can you try out this shellscript, it adds 2 indices to the database and in my use-case improves start-up time much:
> 
> #!/bin/sh sqlite3 ~/.newsboat/cache.db <<! CREATE INDEX idx_feedurl_deleted ON rss_item(feedurl, deleted); CREATE INDEX idx_unread ON rss_item(unread); !
> 
> See also: #2057 and: [3cc6bbc](https://github.com/newsboat/newsboat/commit/3cc6bbc80a1addd71d3c6f1592348682393df49a)
> 
> Of course make sure to backup your cache.db file (just in case).
> 
> Thanks,


I tested your script on my fastest destop.
It use about `5s` to startup the script before your script.
After using your script, the startup time reduced to only `1s`

I did not test on my old laptop, should be huge difference.

However, it did not improve the speed when opening the feeds containing 7XXXX articles, slow as usual.



What the script actually do?
Do you have another script to reverse that??
Thanks.

**Comment by hiltjo** [comment]
It adds table indices on some of the fields to check for items marked as deleted or unread. This allows newsboat/sqlite3 it to look them up faster basically.

To reverse the script you can drop the indices by replacing "CREATE INDEX" with "DROP INDEX".

Opening the feeds with many articles might need different indices or a different solution altogether,

Thanks for testing it,

**Comment by Minoru** [comment]
Hi! Slow startup is tracked by #766, and slow feed navigation by #229, so please subscribe there for updates.

I'm glad that the indices help. Should do a bit more work on that and finally merge them, that's be nice.
