### ISSUE TITLE
Unsupported <author> on <feed> level

### ISSUE THREAD

**Issue by der-lyse** [newsboat/newsboat#2256]
#### Newsboat versions

* `r2.26-8-gaaab-dirty` (This is what I'm running locally. Yes, it's an old version and also contains some dirty stuff that, unfortunately, I cannot remember anymore. Probably documentation or translation changes, most certainly no code changes, though. Doesn't matter, because, also…)
* 89df1fdf679f14fbb75d9a251e82c83cd7bf86f8 (current master; manually verified by looking at the source code)

#### Description

I recently reread the Atom feed specification and noticed that an `<author>` is not required in `<entry>` elements, if there is an `<author>` at `<feed>` level. [Section 4.2.1 on _The "atom:author" Element_](https://www.rfc-editor.org/rfc/rfc4287#section-4.2.1) says:

> If an atom:entry element does not contain atom:author elements, then
> the atom:author elements of the contained atom:source element are
> considered to apply.  In an Atom Feed Document, the atom:author
> elements of the containing atom:feed element are considered to apply
> to the entry if there are no atom:author elements in the locations
> described above.

I didn't know that before, so I happily went ahead fixed all my own Atom feeds to move the `<author>` elements from the `<entry>`s to `<feed>` in order to avoid unnecessary duplication and reduce feed size a tiny bit. After reloading the updated feeds I noticed:

1. In Newsboat's article view there's no "Author" header field displayed anymore.
2. That's not too surprising, because in the cache file, the `author` column of the `rss_item` table is now empty for all those adapted feeds.
3. Looking at the source code of the _atomparser.cpp_, the [`AtomParser::parse_feed(…)` simply does **not** check for a `<feed>` level `<author>`](https://github.com/newsboat/newsboat/blob/r2.29/rss/atomparser.cpp#L40). [`<author>`s are only considered in `<entry>`s in `AtomParser::parse_entry(…)`](https://github.com/newsboat/newsboat/blob/r2.29/rss/atomparser.cpp#L78).

#### Feature or Bug?

I'm fully okay with that behavior, especially since my feed titles and author names are basically the same for most of my feeds. So, previously, the "Feed" and "Author" header fields in the article view were showing the same information. I'm kind of glad, that this redundant information is now gone. But I still want to address this and ask about your opinions. Would it be better if an item's author would not be empty but rather take the value of the feed's author? Basically, is this a real feature or rather a bug? What's your take on that?

In case you all agree to change that, I'm happy to contribute a fix. Although, I'm currently not able to build from source because my system seems to be broken (running into very weird  ```/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: unknown type [0x13] section `.relr.dyn'``` errors for yet to be determined reasons). So I would have to sort that out first.

If implemented, the next question would be how deal with backwards-compatibility. Introduce a setting, that disables the new behavior or just treat it as a bugfix?

And maybe I could also add support for the `<source>` element, as stated by the specification. I've never run across `<source>` in the wild (but I also don't look at the raw XML, so take that statement with a grain of salt). So maybe it's not that relevant. Any thoughts on that matter?

**Comment by Minoru** [comment]
I think this is a bug. Just fix it, no need to introduce more settings for this.

`atom:source` is nifty! Looks like it was added to aid blog planets and other aggregators. I'd love to see that implemented too, but it should probably be a separate pull request.

Thanks for digging all of this up :)

**Comment by Minoru** [comment]
Re-opening because #2259 only fixed the bug — the support for `<source>` is yet to be implemented.
