### ISSUE TITLE
Filter is removed when quiting from article

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#227]
**Newsboat version (copy from `newsboat -v`)**: 2.12.0

Steps to reproduce the issue:

1. Define some filter in the configuration file. Mine was like this
`define-filter "Age 20" "age = 20"``

2. Open the RSS channel to see articles, then press `f` and `enter` on defined filter (subset of articles will open).

3. Open one article by pressing `enter`.

4. go back to the article list (press `q`).

**Expected**:
The filter will be in place showing only subset of articles.

**Actual**:
Filter was removed, all articles were shown.

How can I have `expected` behaviour?

Regards,
Piotr

**Comment by ZaxonXP** [comment]
I noticed that this happen when the whole list of articles are displayed.

When first I try to show only unread ones (by pressing `l` key) then the issue is not there.

Hope this help with reproducing the issue.

**Comment by Minoru** [comment]
Reproduced with e6386794feb42f8a18667b98c848473453110c0f.

**Comment by xelkarin** [comment]
> I noticed that this happen when the whole list of articles are displayed.
> When first I try to show only unread ones (by pressing `l` key) then the issue is not there.

I'm seeing this issue when both unread articles and all articles are displayed. I did find, though, that it only occurs when the internal pager is used. If an external pager is configured, then the filter remains set after exiting the article.

**Comment by xelkarin** [comment]
My distro has included newsboat-2.19 and as of that version this bug appears to have been fixed.

**Comment by ZaxonXP** [comment]
Indeed it is working now as I was expecting. :)
Tested on version 2.19

**Comment by Minoru** [comment]
Oh right, it's been fixed since 2.17 (by #615). I've updated the changelog to reflect that.

Thanks for being so vigilant, @xelkarin! :+1:
