### ISSUE TITLE
List macros

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#228]
2.12.0

When you press `,` the `macro-` is displayed in the status bar. What if you do not remember which key should you press next? Look in the configuration file. Not so nice.

Would it be possible to implement such feature that if you press `,` then `TAB` the overlay window will display all the macros (first column = key, second column = macro) and user could press the key or select macro using arrows up/down and enter.

This feature would really help finding right macro when you might forget one.

Regards,
Piotr

**Comment by Minoru** [comment]
I don't believe STFL (our "graphics" library) provides any sort of autocompletion menu, so it'll be a chunk of work. Will you settle for additional entries in the help dialog? If you forget the key, you will:
1. press `Esc` to abandon the macro invocation;
2. press `?` to show the help list;
3. scroll to the section that lists all your macros, find your key there;
4. press `q` to get back to your previous dialog;
5. press `,` again and then the key you wanted in the first place.

It's 3+ more keypresses compared to Tab, but it has an additional benefit of being easily discoverable by the user—it's logical to take a look at the help if you forgot something. What do you think?

**Comment by ZaxonXP** [comment]
Maybe it does not have to be autocomplete, but something like screen where you can see all the macros and select one (similar to the filter screen selected by `f` key). The screen should appear only when you press `, <TAB>` combination (the `, + letter` should be unaffected).

If the above is for some reason not feasible, then putting macros on the help is also better than opening a config file and look for it there.

**Comment by Minoru** [comment]
Oh, a separate dialog is certainly doable! I'd accept a PR implementing that.

**Comment by Jorval** [comment]
Hey,
is the help screen editable? or is it build from the bindkey in config?

a editable helpscreen would be nice so someone could also add his flags to the screen (i know someone who has an additional file for this. )

**Comment by Minoru** [comment]
It's generated automatically from the key bindings in the config, plus the defaults. How do you envision the config syntax to add info to the help screen, @Jorval?

**Comment by Jorval** [comment]
a simple file say _flags.md_ that is attached after the generation at the bottom ?
maybe that leads to scrolling

or maybe a seperate dialog that shows the content of such a file ?

its not a big deal. but falgs are very versatile and individual. i have a md file for that.
the most obviously (R)eadLater is in a header before the query.

**Comment by Minoru** [comment]
That sounds okay. Let's discuss this further in #1363, @Jorval.
