### ISSUE TITLE
Feeds with many items are slow to open and navigate

### ISSUE THREAD

**Issue by hjek** [newsboat/newsboat#229]
**Newsboat version 2.12.0**:

Steps to reproduce the issue:

1. Add an RSS URL to `.newsboat/urls`

2. Open Newsboat and reload RSS feed (over some time) until it has about 15000 items

3. In the **Your feeds** section, select the feed and press enter. *<- Newsboat will take about a minute to respond to this*

4. Press down to select the next item within the feed. *<- Newsboat will take a few seconds to respond to this*

It looks to me like Newsboat loads *all* the entries in a feed when that feed is opened. Perhaps it should only load the ones that it will actually display?

**Comment by Minoru** [comment]
> It looks to me like Newsboat loads all the entries in a feed when that feed is opened. Perhaps it should only load the ones that it will actually display?

Correct. There are a few reasons for that:
- the obvious one: this wasn't prematurely optimized, but now we have the rest of Newsboat on top of this, and optimization is complicated;
- you can't do sorting unless you load the whole feed;
- you can't apply `ignore`s (when in `ignore-mode "display"`) without loading the whole feed.

There are two possible workarounds:
- limit the size of your feeds with [`max-items`](https://newsboat.org/releases/2.12/docs/newsboat.html#max-items);
- upgrade to faster storage (will only help with 3).

As for 4: do you have `mark-as-read-on-hover` enabled? Does Newsboat use a lot of CPU time after you press the key?

**Comment by hjek** [comment]
`max-items` works great. Thanks.

**Comment by Minoru** [comment]
I still consider this a problem—Newsboat shouldn't slow down no matter how big the cache file. So I'll keep this issue open.

I will be grateful if you could answer the questions I asked earlier, @hjek:

> As for 4: do you have mark-as-read-on-hover enabled? Does Newsboat use a lot of CPU time after you press the key?

**Comment by hjek** [comment]
> I still consider this a problem

Cool that you consider it within the scope of this program to handle feeds with >10000 entries. I like that.

> I will be grateful if you could answer the questions I asked earlier

No problem. Sorry I forgot.

> do you have mark-as-read-on-hover enabled?

No, I don't have mark-as-read-on-hover enabled.

> Does Newsboat use a lot of CPU time after you press the key?

Yes, Newsboat maxes out the CPU for a few seconds after pressing up or down key in the feed entry list.

**Comment by Eucyon** [comment]
Something new here ;-)?

**Comment by Minoru** [comment]
@Eucyon, nope. Blocked on #232 right now; need to move to a UI library that doesn't require us to format the whole list at once.

**Comment by Minoru** [comment]
@dennisschagt has proven me wrong by fixing this within the constraints of our current UI library: #2357.

Query feeds might still be slow to open though; this is tracked in #1730. The rest should be fast now.

**Comment by Minoru** [comment]
(Had to re-open this in order to link the PR to this issue.)
