### ISSUE TITLE
Enable set browser macros in URL view

### ISSUE THREAD

**Issue by diskotechjam** [newsboat/newsboat#23]
First of all, Congratulations! I'm so excited to see that newsbeuter was finally forked for active development. This continues to be one of my favourite applications, looking forward to the improvements that come with newsboat.

One improvement that would be helpful is enabling macros commands in the URL view. Currently, the URL view only supports opening links in the default browser by pressing return, but enabling the macros commands could eliminate a step for viewing some links. For example, if I'm reading an article with a youtube link, I'd like to be able to open the link directly in mpv, or if I'm reading an article with an image link, I'd like to be able to open the link directly in an image viewer.

**Comment by Minoru** [comment]
Thank you for filling this (and the other ones)! Don't have anything to say offhand, will comment once I took a look at the relevant code and have something to say.

**Comment by cirrusUK** [comment]
@diskotechjam  see my [config](http://ix.io/Bzb) for enabling macros
this [video](https://www.youtube.com/watch?v=mRnMg2V9n-E) is worth watching.

**Comment by aleprovencio** [comment]
Can't we have newsboat work with mailcap which is the approach softwares like mutt and rtv have taken for this kind of issue?

**Comment by Minoru** [comment]
I admit I don't have any experience with mailcap even though I've been using Mutt for almost a decade now. Luckily [the relevant section of their docs](http://www.mutt.org/doc/manual/#using-mime) is concise and descriptive enough. I'll create a separate issue for that feature. Thanks for bringing it up, @aleprovencio!

**Comment by diskotechjam** [comment]
Mailcap would be a nice feature, but from what I understand it sets defaults for certain file types. Personally, I use a lot of alternative browsers to open links in newsboat, so I wouldn't want to be locked into any defaults by mailcap. 

By the way, something else which is missing from the URL view is the Podcast Download URL. Including the podcast link along with macros support would effectively eliminate the need to que podcasts to podbeuter in order to play or download.

**Comment by aleprovencio** [comment]
@diskotechjam, I did not intend to propose mailcap as a substitute for the macros system, but as an additional feature for these cases where we try to hack the macros system to perform mailcap duties.

**Comment by Minoru** [comment]
Fixed by #194.
