### ISSUE TITLE
Provide default configuration file showing all default keybindings

### ISSUE THREAD

**Issue by Soundtoxin** [newsboat/newsboat#2312]
I can't find a list of default keybindings so I can't see the names of actions in order to rebind them. I strongly believe that the functionality of jk and JK should be swapped around and I thought this would be a quick change, but I can't seem to find anywhere what their actions are called. Other people seem to be figuring out rebinding things, so I must just be missing it somewhere.

**Comment by der-lyse** [comment]
Check out the [Newsboat](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_newsboat_operations) and [Podboat Operations sections in the documentation](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_podboat_operations). For a more compact view have a look at the [raw DSV file](https://github.com/newsboat/newsboat/blob/master/doc/keycmds.dsv). In particular, you're interested in:
* [`next`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#next) (<kbd>Shift</kbd>+<kbd>J</kbd>)
* [`prev`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#prev) (<kbd>Shift</kbd>+<kbd>K</kbd>)
* [`next-feed`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#next-feed) (<kbd>J</kbd>)
* [`prev-feed`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#prev-feed) (<kbd>K</kbd>)

**Comment by Soundtoxin** [comment]
Thank you very much! Hopefully the next person who gets stuck can find this issue now.

**Comment by dennisschagt** [comment]
Another place where you can find the available operations is in the help dialog.
It can be opened in Newsboat itself with the `?` key and shows the operations which are available/bound in the opened view.
