### ISSUE TITLE
how to AUTOMATICALLY save all articles to files, and quit?

### ISSUE THREAD

**Issue by mfioretti** [newsboat/newsboat#2320]
**newsboat 2.21.0**:

_I already posted this one week ago on the google group , but seeing no answer, I'm trying here now:_

Greetings,

I just started using newsboat and it's great, but there must be something basic that I don't understand, or recognize, in the documentation. I would like to run newsboat from a bash script, so that it:

1. downloads ONE feed
2. downloads all the articles in that feed
3. saves each of those articles in a separate, plain text file that I can parse later
4. quits

Is this possible? If yes, how? As I said, I have already read the documentation and tried several combinations of options, but they are either invalid, or not doing what I need, so I must miss something (again, assuming what I want to do is possible to begin with, which I am not sure of)

thanks,
Marcoo

**Comment by der-lyse** [comment]
Hi Marcoo,

Newsboat is designed to be operated by humans, not so much by scripts. Hence, it's probably not possible. Let me suggest to use [`rsstail`](https://python-rsstail.readthedocs.io/en/latest/) or something along those lines instead. Some feed parser library for your favorite programming language should do the trick. To me, Newsboat doesn't sound like the right tool for your job.

However, if you still want to try your luck with Newsboat, have a look at the [`--execute`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_first_steps) flag and [`save-all`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#save-all) operation as a start.

**Comment by hiltjo** [comment]
It's definitely possible, one idea maybe is you could write a query on the cache sqlite3 database using an external script. Just a starting point to expand your script to dump it to a file:

```
#!/bin/sh
# dump data, .mode ascii: Columns/rows delimited by 0x1F and 0x1E

sqlite3 ~/.newsboat/cache.db <<!EOF |
.headers off
.mode ascii
.output
SELECT
        i.pubDate, i.title, i.url, i.content, i.content_mime_type,
        i.guid, i.author, i.enclosure_url,
        f.rssurl AS rssurl, f.title AS feedtitle, i.unread
        -- i.id, i.enclosure_type, i.enqueued, i.flags, i.deleted, i.base
FROM rss_feed f
INNER JOIN rss_item i ON i.feedurl = f.rssurl
ORDER BY
        i.feedurl ASC, i.pubDate DESC;
.quit
!EOF
LC_ALL=C awk '
BEGIN {
        FS = "\x1f";
        RS = "\x1e";
}
{
        print $9 ": " $2 " " $3;
}'
```

**Comment by mfioretti** [comment]
Hi @hiltjo , and thanks a lot for the great tip, I'm almost there thanks to it.

As is, your sample code gave me an error because sqlite3 says that there is no column like i.content_mime_type in the database. But if I just remove that column from the query, it runs and produces output lines like:

FEEDNAME: TITLE URL
FEEDNAME: TITLE URL
...

that are just fine for the postprocessing I want to do 

so the only missing piece is how to launch newsboat from a shell script so it just starts, reloads ALL the feeds listed in a rsslist.txt file and quits.

I tried this:

newsboat -u rsslist.txt -c temporary-cache.db -r -x quit

but it says "quit: unknown command"

so I am surely missing something obvious here. What?

Again, thanks for pointing me in the right direction!

**Comment by juntuu** [comment]
> I tried this:
>
> newsboat -u rsslist.txt -c temporary-cache.db -r -x quit

It would seem that [`-x reload`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_commandline_commands) is the command you are looking for, instead of `-r -x quit`.

Although, that does not reload *just one* feed, but *all the feeds*. Of course you could work around that by having only one feed at a time in the `rsslist.txt`.

**Comment by mfioretti** [comment]
> It would seem that [`-x reload`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_commandline_commands) is the command you are looking for, instead of `-r -x quit`.

YES, this is it, thanks. It loads, fills the sqlite3DB that can later be queried as @hiltjo said, and then quits. Just what I need.

And doing once per feed, with a different 1-line rsslist.txt every time is what I need to do anyway, because it makes easier the postprocessing I want to do.

Again, thanks a lot!

**Comment by dennisschagt** [comment]
It looks like the the question got fully answered, so I'm closing as resolved.
If there are any other issues, feel free to reopen or open a new issue.
