### ISSUE TITLE
Request: Ability to group feeds together

### ISSUE THREAD

**Issue by BurnyBoi** [newsboat/newsboat#233]
As far as I can tell, each feed URL always shows as its own entry. It would be nice to be able to put feeds into groups such that when a group is selected, all the items for those feeds show under 1 list. In this grouped list, there should be an extra column to show the name of the feed each item came from. 

Example use case: What I do in Thunderbird is group all my YouTube feeds together under 1 list. The "From" column shows me the channel name where each item is coming from.

**Comment by BurnyBoi** [comment]
Whoops. I neglected to read the part of the documentation about query feeds. For those also looking for the same thing:

https://newsboat.org/releases/2.12/docs/newsboat.html#_query_feeds

Should have finished reading the manual first. My bad.

**Comment by Minoru** [comment]
No worries; glad you've figured it out ;)
