### ISSUE TITLE
How to search for feed name instead of all articles?

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2338]
I have a lot of RSS feed urls in the `urls` files,
I find it not very convenient to navigate through them.
When I press `/` to search the feeds name, the result contains the feed articles, but mixed with articles from other feed.
Do newsboat have some feature to search only feeds names?
Something like `nnn`'s type-on-nav function, to filter out the unmatched feeds name?

Thanks!

**Comment by dennisschagt** [comment]
I don't think Newsboat has that feature at the moment.
However, it does have 2 features which might come close enough:

1. The [goto-title operation](https://newsboat.org/releases/2.30.1/docs/newsboat.html#goto-title) allows you to go to the next feed which contains the entered text as a part of the title.
    By default, it is not bound to any key combination, so you will have to add a bind-key line in your config, e.g.:
    ```
    bind-key g goto-title
    ```
2. The filter language allows you to filter the list of feeds based on attributes like [`feedtitle`](https://newsboat.org/releases/2.30.1/docs/newsboat.html#attr-feedtitle).
    To use it, press shift+F to open the filter editor, enter `feedtitle =~ "part of the title"`, and press ENTER.
    This will filter the feeds by title, based on the entered regex.
    If you want to get back to the full list of feeds, press ctrl+f to clear the filter.
    For move filter options, see [the filter documentation](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_filter_language)

**Comment by amalgame21** [comment]
Both options are really great!!
Did not know newsboat have the goto-title key!
Thank you very much!!!
