### ISSUE TITLE
Only ESC, Up, Down, and ENTER work since #2337 was merged

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#2351]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.30.1-60-gceacb

Config file is empty.

```
bind-key ESC quit
```

Steps to reproduce the issue:

1. start Newsboat

2. enter any feed

3. observe that you can't quit it with <kbd>q</kbd>, or do anything else (except scrolling through it with Up and Down keys). Quit the dialog with <kbd>ESC</kbd>, which does work.

**Other info you think is relevant**: this regression is caused by #2337, because it's not present in b53c4f25. I didn't dig deeper.

**Comment by Minoru** [comment]
@dennisschagt, can you please take a look at this? If the problem is not obvious, I think it'd be best to revert #2337 so people who build from Git are not stranded with a broken program.

**Comment by dennisschagt** [comment]
@Minoru I cannot reproduce the issue.
Is there anything special in your setup? (I did try with my usual newsboat environment and separately with the given config: `bind-key ESC quit`)

Strange request, but could you retry reproducing after a clean build?
I see some strange build failures whenever switching between branches which contain the changes from https://github.com/newsboat/newsboat/pull/2324 (the logging PR, specifically commit https://github.com/newsboat/newsboat/commit/5d724acdd957), and branches which do not

**Comment by carno** [comment]
I can reproduce the same behaviour as @Minoru, what is strange, when viewing feed content it does not highlight which feed entry is chosen so my first impression was that even up/down arrows don't work

```
Newsboat r2.30.1-60-gceacb - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2022 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2022 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat r2.30.1-60-gceacb
System: Linux 6.1.14-1-siduction-amd64 (x86_64)
Compiler: g++ 12.2.0
ncurses: ncurses 6.4.20221231 (compiled with 6.4)
libcurl: libcurl/7.88.1 GnuTLS/3.7.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 (compiled with 7.88.1)
SQLite: 3.40.1 (compiled with 3.40.1)
libxml2: compiled with 2.9.14
```

Compiled with

```
export CARGO_HOME=.cargo; prefix=/home/carno/.local make clean && prefix=/home/carno/.local make -j5 && prefix=/home/carno/.local make install
```

**Comment by carno** [comment]
Looks like Debian (I'm using Siduction based on Debian unstable) is stuck with 0.22 https://tracker.debian.org/pkg/stfl
