### ISSUE TITLE
Is asciidoctor really optional?

### ISSUE THREAD

**Issue by michelboaventura** [newsboat/newsboat#2353]
**commit ceacb52ff506c297f2e4c8e8a1ea3078869ef520 (HEAD -> master, origin/master, origin/HEAD)**:

Hey. Looking at https://github.com/newsboat/newsboat/issues/1885 it seems `asciidoctor` is an optional dependency and if I just do a `make newsboat` it should work. But instead I got an error:

```
$ make newsboat
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for command asciidoctor... not found

You need package asciidoctor in order to compile this program.
Please make sure it is installed.
Checking for command cargo... found
Checking for package json... not found
Checking for package json-c... found
Checking for package ncursesw... found
curl was built with static libraries disabled
curl was built with static libraries disabled

One or more dependencies couldn't be found. Please install
these packages and retry compilation.
Makefile:37: config.mk: No such file or directory
make: *** [Makefile:455: config.mk] Error 1
```

If I comment [this line](https://github.com/newsboat/newsboat/blob/master/config.sh#L116) it works fine and I can compile `newsboat`.

Steps to reproduce the issue:

1. Clone the repo

2. Try to run `make newsboard` without having `asciidoctor` installed

3. You should see an error

**Comment by mortezadadgar** [comment]
yeah it's a hard dependency @Minoru any thought?

**Comment by michelboaventura** [comment]
Thank you!
