### ISSUE TITLE
Images in Mastodon Feeds are recognized as Podcast and get auto-enqueued

### ISSUE THREAD

**Issue by dorsiflexion** [newsboat/newsboat#2367]
**Newsboat version**:

```
Newsboat 2.30.1
System: Linux 6.1.15-hardened1-1-hardened (x86_64)
Compiler: g++ 12.2.0
ncurses: ncurses 6.4.20221231 (compiled with 6.3)
libcurl: libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0 (compiled with 7.87.0)
SQLite: 3.41.1 (compiled with 3.40.0)
libxml2: compiled with 2.10.3
```

**Config file**:

```
urls-source "ocnews"
ocnews-url ***
ocnews-login ***
ocnews-password ***
ssl-verifypeer no
ssl-verifyhost no
podcast-auto-enqueue yes
```

**Steps to reproduce the issue**:

1. Add a Mastodon feed to Nectcloud news.
2. The article must not be in Newsboat cache. Retrieve Nextcloud news with Newsboat – i. e. open Newsboat and reload feed.
3. Auto-enqueue should already have enqueued the image to the podboat podcast queue.

**Other info you think is relevant**:

Feed URL: https://social.tchncs.de/@kuketzblog.rss
Toot URL: https://social.tchncs.de/@kuketzblog/109975086360478784

The full article as shown by newsboat:

```
Feed: Kuketz IT-Security » Mastodon
Title: 109975086360478784
Date: Mon, 06 Mar 2023 08:10:44 +0100
Link: https://social.tchncs.de/@kuketzblog/109975086360478784
Podcast Download URL:
https://f2.tchncs.de/media_attachments/files/109/975/078/545/360/548/original/5d55b6d57093f18a.png (type:
image/png)

Nachdem das neueste Update von GrapheneOS eingespielt ist, kann man unter
"Einstellungen -> Standort" nun den SUPL-Proxy-Server auswählen. 👇
```

**Comment**:

What is the logic behind auto-enqueueing? Does every attachment get enqueued, no matter what?

I think newsboat should at least check if the file is an audio file.

**Comment by dennisschagt** [comment]
> What is the logic behind auto-enqueueing? Does every attachment get enqueued, no matter what?

Good point, I think I overlooked this behavior in https://github.com/newsboat/newsboat/pull/2218.
Will be fixed by https://github.com/newsboat/newsboat/pull/2378.

**Comment by dorsiflexion** [comment]
A big thanks for this fix. I can confirm that images indeed don't get auto-enqueued anymore in 2.32.

The images are still displayed as *Podcast Download URL* though, which is not the intended behavior, I reckon.
![newsboat](https://github.com/newsboat/newsboat/assets/52240714/f225c077-5666-4af8-a323-04178919d557)
