### ISSUE TITLE
Check if we can use new DYNAMIC_SECTION macro in our tests

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#237]
I just updated our test framework to its latest version, 2.3.0, in which new `DYNAMIC_SECTION` macro was introduced. The only documentation for it is [a sentence in the changelog](https://github.com/catchorg/Catch2/blob/15cf3caaceb21172ea42a24e595a2eb58c3ec960/docs/release-notes.md#improvements), so we'll have to do our own experiments to find out what useful things we can do with it.

**Comment by Minoru** [comment]
I no longer think it's worth anyone's time to go hunting for use-cases like this, so I'm closing it.

**Comment by dennisschagt** [comment]
A bit more information on when to use `DYNAMIC_SECTION` is provided at [1].

> I no longer think it's worth anyone's time to go hunting for use-cases like this, so I'm closing it.

I agree, it's just useful to know that it exists in case you want to use `SECTION`s in a loop [1].

[1] https://github.com/catchorg/Catch2/blob/master/docs/limitations.md#user-content-sections-nested-in-loops
