### ISSUE TITLE
can you make appimage

### ISSUE THREAD

**Issue by newyorkthink** [newsboat/newsboat#2387]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
INSERT COPY HERE
```

Steps to reproduce the issue:

1.

2.

3.

**Other info you think is relevant**:

**Comment by Minoru** [comment]
Please see https://github.com/newsboat/newsboat/issues/1116 for the answer.
