### ISSUE TITLE
[question] `json` dependency package

### ISSUE THREAD

**Issue by azinsharaf** [newsboat/newsboat#2404]
Newsboat version:`2.30.1`

can someone help me to find the `json` package so i can build newsboat from the source? I am using Ubuntu 22.04.

`
> ./config/sh
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for command asciidoctor... found
Checking for command cargo... found
/home/azin-wsl/.cargo/bin/cargo
**_Checking for package json... not found_**
Checking for package json-c... found
Checking for package ncursesw... found
`

**Comment by dennisschagt** [comment]
It looks like the config.sh has alternatives configured for some of the dependencies.
For a json library, apparent, it looks like it can work with either the `json` package or the `json-c` package.
From your pasted output, it looks like it successfully found `json-c` (and so, you can safely ignore the `json not found` line).

If there are no other errors in later output of the config.sh script, I would expect a build with `make` to be successful.
Do you see any other errors? (either running `config.sh` stand-alone, or when running `make`)

**Comment by azinsharaf** [comment]
yes it wokred with `json` package. Thnaks!

**Comment by iampi31415** [comment]
I had a similar issue; just adding for others that may find useful. From [the docs, section 2](https://newsboat.org/releases/2.10/docs/newsboat.html) (bold mine)

> To compile newsboat, simply run "make" in the source tree. After a short time, this should complete successfully, and **you can go on with** installation by running "make install". 

So it should work if only one of the `json` is missing. I had another issue when running `make install` with `stfl` being missing and didnt know how to install it, this solved it:

```
sudo apt-get install libstfl-dev
```

I dont remember if I had to install `libstfl0` as well, so you may need to add it in the command above.

Finally, it exist with this error (but note, it's not a real error and build succeeds)

```
mkdir -p /usr/local/bin
install newsboat /usr/local/bin
install: cannot create regular file '/usr/local/bin/newsboat': Permission denied
make: *** [Makefile:353: install-newsboat] Error 1
```

Just couldn't make the directory for the bin. So the `newsboat` bin is simply in the directory we built on, and `./newsboat` should run it.
