### ISSUE TITLE
Navigate newsfeed with `h / j / k / l`?

### ISSUE THREAD

**Issue by alichtman** [newsboat/newsboat#2412]
I see the `bind-key` functionality. I figured that a set of bindings like:

```
bind-key h LEFT
bind-key j RIGHT
bind-key k DOWN
bind-key l UP
```

would add this functionality, however, I get errors like:

```
Error while processing command `bind-key h LEFT' (/home/alichtman/.config/newsboat/config line 1): `LEFT' is not a valid key command
```

The docs say:

```
The following identifiers for special keys are supported:

...
- `LEFT` (left cursor)
- `RIGHT` (right cursor)
- `UP` (up cursor)
- `DOWN` (down cursor)
...
```

Am I doing something wrong?

**Comment by alichtman** [comment]
Also, in `chapter-configurations.asciidoc`, it says:

```
For a complete list of available operations see <<_newsboat_operations>> and <<_podboat_operations>>.
```

Neither anchor seems to exist.

**Comment by juntuu** [comment]
The key bindings bind a _key_ to an _operation_.

You are trying to remap one key to another key, which is not supported.

Instead you could check the current bindings and duplicate those for the new keys. For example, the default binding for `UP` is `bind-key UP up`, so you could just add a new binding with the same operation `bind-key k up`.

You can also see the currently active bindings from the help dialog with <kbd>?</kbd> (by default).

Also, the anchors work fine in the rendered web version: https://newsboat.org/releases/2.31/docs/newsboat.html#_configuration. I think there's a compilation step that "fixes" the anchor targets.

**Comment by alichtman** [comment]
Thanks!

```
bind-key l open
bind-key h quit
bind-key k down
bind-key j up
```

adds the behavior I'm looking for.

> I think there's a compilation step that "fixes" the anchor targets.

Ah, interesting.

**Comment by Minoru** [comment]
I believe the question has been answered, so I'm closing this. Please leave a comment if something's still unclear!
