### ISSUE TITLE
Question: name in the group/query

### ISSUE THREAD

**Issue by OlegPQ** [newsboat/newsboat#2420]
Hello all! I have the following basic configuration:
```
"query:YouTube:tags # \"youtube\""
https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw ! "abc" "youtube"
https://www.youtube.com/feeds/videos.xml?channel_id=UCUyeluBRhGPCW4rPe_UvBZQ ! "qwerty" "youtube"
```
This works fine; but I am looking for a way to have the ability to mark the channels if they are in the group, so that I can visually identify the individual channel. I.e. when you open the "YouTube" groups, it would be nice to see something similar to the following:

> abc: video
> qwerty: video
> abc: video2
> abc: video3
> qwerty: video2

or

> feed/author name: video
> feed/ name: video
> feed/author name: video2
> feed/author name: video3
> feed/author name: video2

so you can immediately see from which channels the update was received.

I know it is possible to write a separate script that will first add the name of the channel to the titles and only then save them to the database. But I wonder if it is possible to achieve this by the standard configuration, without additional scripts. Is it possible?

Newsboat version - 2.31.

Thx!

**Comment by juntuu** [comment]
There is a format specifier for the feed title: `%T` (https://newsboat.org/releases/2.31/docs/newsboat.html#articlelist-format-T)

I think that might fit your use case.

I personally use with the conditional format. For example the following

```
articlelist-format "%?T?%T: &?%t"
```

gives

```
One feed title: Article title A
Another feed title: Article title B
```

when there are articles from multiple feeds.

For a single feed's articles, the conditional omits the feed title and the separating `: `.

**Comment by dennisschagt** [comment]
@juntuu Thanks! Looks like a good option.

@OlegPQ I assume this configuration option does what you were looking for.
if not, feel free to reopen the issue.
