### ISSUE TITLE
Redundant names in list from urls with the same name.

### ISSUE THREAD

**Issue by Scary-Guy** [newsboat/newsboat#2421]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.21.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): Irrelivant

Steps to reproduce the issue:

1. Go to Meetup.com and join some groups?
2. Copy the URLs of the "RSVPs" into the urls file. (format is always https://www.meetup.com/$group/rsvps/rss/ where $group is the actual group's name.)
3. Open newsboat and try to not be confused.

**Other info you think is relevant**: So this is a combination bug/feature request.  The bug is as described.  The RSS feeds display new RSVPs for events for the groups you're in.  However you can't really tell what the group is easily unless you open it, or remember the order you put them in.

My idea to fix this is an override after the URL that would look something like:
https://www.meetup.com/*group*/rsvps/rss/ $new RSS name  (with whatever syntax actually works, maybe just a space.)

(Note: If this functionality already exists I did not see it in the documentation.  I also did a search for any similar issues opened or closed.  If it does exist then I'm sorry for making a redundant issue/post.)

**Comment by dennisschagt** [comment]
> Note: If this functionality already exists I did not see it in the documentation. I also did a search for any similar issues opened or closed.

I think this functionality exists, but it is not very easy to find in the documentation.
This can be done by adding a "renaming" tag after the URL, e.g. `https://www.meetup.com/040coders-nl/rsvps/rss/ "~whatever name you want to use as a feed title"` 

Newsboat 2.21.0 is already quite old, but based on the documentation, it looks like it already supports this feature:
https://newsboat.org/releases/2.21/docs/newsboat.html#_tagging
Relevant part:
> A special type of tag are tags that start with the tilde character (~). When such a tag is found, the feed title is set to the tag name (excluding the ~ character). These type of tags are ignored when any kind of "first tag" property is used. With this feature, you can give feeds any title you want in your feed list:

> `https://rss.orf.at/news.xml "~ORF News"`

Does that do what you want it to do?

**Comment by Scary-Guy** [comment]
Yes, that works great!  Interesting to note that if there's a space then the quotes are necessary or else the rest doesn't parse (or would parse as something else like a tag instead of a name change.  I must have skimmed over that part but I guess I didn't think it would be considered an advanced option.

I'd consider redoing the documentation to make that a little clearer.  Maybe put a link to section 5.1 somewhere under section 3.  Also maybe change the name to "Tagging, Custom Names, and Hidden Feeds" or something.

Anyway, thanks for the clarity!

**Comment by dennisschagt** [comment]
I think this will also become a bit nicer to setup (and to find in the documentation) when we switch to a new urls file format with support for per-feed settings: https://github.com/newsboat/newsboat/issues/83
