### ISSUE TITLE
Percentage text should be localisable

### ISSUE THREAD

**Issue by bitigchi** [newsboat/newsboat#2441]
Percentage sign usage differs from language to language. Most languages use a basic 100% format, that immediately follows the number; however [some languages](https://en.wikipedia.org/wiki/Percent_sign) use different notations, and even different percent signs.

In newsboat code, it looks like there are two instances of percent sign use; one in [itemviewformaction.cpp](https://github.com/newsboat/newsboat/blob/c0ed70475ddf50ade51479d16fd3395d42231144/src/itemviewformaction.cpp#L679), and the other one in [configcontainer.cpp](https://github.com/newsboat/newsboat/blob/c0ed70475ddf50ade51479d16fd3395d42231144/src/configcontainer.cpp#L189). Ideally, these strings should be marked as translatable and follow the 100% format for the C locale.

**Comment by dennisschagt** [comment]
I wasn't aware of the different notations, thanks! (and thank you for the direct links to the relevant sources)
Will be fixed by https://github.com/newsboat/newsboat/pull/2444

**Comment by bitigchi** [comment]
Thanks for the quick fix. There is a slight issue though, since there is padding attached to the placeholder, in my case it will lead to output like `%  1`, when it has to be `%1` (I need to put the sign before the number). 

I have a similar [patch](https://salsa.debian.org/apt-team/apt/-/merge_requests/294/diffs) for apt, that addresses this. Might be useful.

**Comment by dennisschagt** [comment]
I think it is okay for different translations to have different padding.
The only important part is that the types of specifiers are still the same (so `%3u` can be changed to `%u` or `%-2u` in translations)

In your case, you could choose to add a few spaces in front, and then show the percentage without padding, e.g.: `  %%%u`
Does that resolve your issue?

I think the percentage field is 6 characters wide: https://github.com/newsboat/newsboat/blob/c0ed70475ddf50ade51479d16fd3395d42231144/stfl/itemview.stfl#L38
It might expand if the translated content is bigger than 6 characters, but it is best not to depend on that (behavior could change when we switch to a different terminal UI library)

**Comment by bitigchi** [comment]
If we can change the padding in the translations, then it's all good, thank you for the clarification. I will submit new translations accordingly. So is it okay if I push `  %%%p` and `  %%%u` respectively?

My language is the rare one out here, if I ascertain this, I think the rest of the languages will be fine. :)

**Comment by dennisschagt** [comment]
Yes, that should be fine.

In the case of the `podlist-format` translation, you could choose to use negative padding on the `%p`. (e.g. `%%%-5p`)
That results in padding to the right of the number (making sure that the total width is constant, irrespective of the exact percentage number).
However, I'm not sure if that is what you want in your language (or preference).
