### ISSUE TITLE
`--import-from-opml` should support OPML 2.0

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#2448]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.31-48-g343ad

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
empty
```

Steps to reproduce the issue:

1. download [category.opml.gz](https://github.com/newsboat/newsboat/files/11714965/category.opml.gz) and unzip it somewhere

2. run:

    ```
    $ touch /dev/shm/urls
    $ newsboat --url-file /dev/shm/urls --cache-file /dev/shm/cache.db --import-from-opml category.opml
    ```

3. Observe that the resulting _/dev/shm/urls_ file only contains the URL of the feed. The expectation is that it would also contain the tags "tag one", "tag_two" and "tag/three".

See also https://github.com/newsboat/newsboat/pull/2402.

**Comment by bogdasar1985** [comment]
@Minoru I take this issue
