### ISSUE TITLE
Incorrect grammatical form in po/sv.po

### ISSUE THREAD

**Issue by deob83** [newsboat/newsboat#246]
The msgstr for msgid "Call a macro", i.e.  https://github.com/newsboat/newsboat/blob/f924b62b05f07585adc0c4a1d2ec6eb14132a9e6/po/sv.po#L1260 should say "Anropa ett makro". See for example the last paragraph of http://www.termado.com/DatatermSearch/?ss=makro, from the [Joint Group for Swedish Computer Terminology](http://dataterm.termado.net/in-english/).

**Comment by Minoru** [comment]
Hi! You are welcome to make a pull request that fixes all the errors you found :) I don't know Swedish (and most other languages Newsboat is translated into), so I rely entirely on users like you who have the knowledge to correct everything.

**Comment by deob83** [comment]
@Minoru Great, I will do so during this weekend!

**Comment by Minoru** [comment]
Cool, thank you!

**Comment by Minoru** [comment]
Fixed by #247.
