### ISSUE TITLE
Turn `std::vector<LinkPair>` into a class

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#2464]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2596ea1c52b2ebde3dffc9e871063c5a0718d4f0

While reviewing https://github.com/newsboat/newsboat/pull/2399 I noticed that `item_renderer` adds URLs to the `std::vector<LinkPair>` that `htmlrenderer` also populates. That vector is later used in `UrlViewFormAction` to let the user pick the links, and in `ItemViewFormAction` to let the user open a link by its number.

The `std::vector<LinkPair>` also has a couple invariants:
1. URLs in it are deduplicated (each URL exists only once);
2. URLs are censored (username and password are replaced by asterisks).

It'd be good to encapsulate the vector in a class of its own to guarantee that these invariants are always upheld. Also, it'd be nice to turn `LinkPair` into a structure with named fields, which will help avoid cryptic code such as `links[idx].second`.

At a minimum, the new class should provide an `add_link` method (copy it from `htmlrenderer::add_link`) and some way to iterate over the links (probably `size()` and `operator[]()`). Also, there should be unit tests to check that the invariants are upheld.

**Comment by bogdasar1985** [comment]
@Minoru I will try to do this issue
