### ISSUE TITLE
"Corrupted double-linked list" after adding a flag to an item

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#249]
**Newsboat version (copy from `newsboat -v`)**:

Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.12.0
System: Linux 3.16.0-4-686-pae (i686)
Compiler: g++ 4.9.2
ncurses: ncurses 5.9.20140913 (compiled with 5.9)
libcurl: libcurl/7.38.0 GnuTLS/3.3.8 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 (compiled with 7.38.0)
SQLite: 3.8.7.1 (compiled with 3.8.7.1)
libxml2: compiled with 2.9.1

Steps to reproduce the issue:

I have subscribed to following RSS channel:

`https://www.youtube.com/feeds/videos.xml?channel_id=UCi8e0iOVk1fEOogdfu4YgfA "~YT - Trailers"`

1) open newsboat
2) press `l` on feed list
3) open the Trailers feed
4) press `l` to see only new items
5) Go to last article
6) Press Enter to open it and open the url to the trailer
7) (about ~2 min later) Add a flag to the article
8) Press `q` and then `N`

Crash occurs:
  *** Error in `newsboat': double free or corruption (!prev): 0x08c19d90 ***ers

**Comment by Minoru** [comment]
Reproduced, even without waiting for 2 minutes before adding a flag. Thank you for the report!

**Comment by Minoru** [comment]
It's been a while, and I can't fully reproduce this anymore: with GCC 10.2.0 and Rust 1.44, I don't get a crash; instead, the item list gets slightly borked.

On master (be89592ff6a10243d09ca109f4733049973617af), though, everything works just fine — no crash, no borking. The bisect points to 2f74873bc611f90b996293986cc2126db4b9aa27, but I don't see how it could fix anything here.

Anyway, bug's gone as far as I can see, so I'm closing this. Please comment if you're still experiencing this with a newer Newsboat version.
