### ISSUE TITLE
Images in Mastodon feeds are recognized as Podcast

### ISSUE THREAD

**Issue by dorsiflexion** [newsboat/newsboat#2495]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat 2.32.0
System: Linux 6.1.38-hardened1-1-hardened (x86_64)
Compiler: g++ 13.1.1 20230429
ncurses: ncurses 6.4.20230520 (compiled with 6.4)
libcurl: libcurl/8.1.2 OpenSSL/3.1.1 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.54.0 (compiled with 8.1.2)
SQLite: 3.42.0 (compiled with 3.42.0)
libxml2: compiled with 2.10.4
```

**Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):**

Probably irrelevant. Anyway:
```
urls-source "ocnews"
ocnews-url ***
ocnews-login ***
ocnews-password ***
ssl-verifypeer no
ssl-verifyhost no
```

**Steps to reproduce the issue:**

1. Add a Mastodon feed to Nextcloud news (e. g. `https://social.tchncs.de/@kuketzblog.rss`).
2. Open an article with an image in newsboat.

Newsboat thinks the image is a podcast and displays the image link as a *Podcast Download URL*. I would expect it to be in the link section just like images in other feeds/articles.

This is a follow-up to #2367. The images do not get auto-enqueued any more, but this behavior does not seem as expected to me.

**Other info you think is relevant**:

Actual example:
```
Feed: Kuketz IT-Security » Mastodon
Title: 110710796185051319
Date: Fri, 14 Jul 2023 07:31:26 +0200
Link: https://social.tchncs.de/@kuketzblog/110710796185051319
Podcast Download URL:
https://f2.tchncs.de/media_attachments/files/110/705/619/697/645/288/original/928cc96aa82a9a51.png (type:
image/png)
```

What I expect:
```
Feed: Kuketz IT-Security » Mastodon
Title: 110710796185051319
Date: Fri, 14 Jul 2023 07:31:26 +0200
Link: https://social.tchncs.de/@kuketzblog/110710796185051319

[… article content …]

Links:
[1]: https://f2.tchncs.de/media_attachments/files/110/705/619/697/645/288/original/928cc96aa82a9a51.png (image)
```

---

Thanks a lot for this nice piece of software btw. :)

**Comment by dennisschagt** [comment]
Makes sense.
I already have a PR open for this requested change: https://github.com/newsboat/newsboat/pull/2399
However, I have had quite some distractions lately so might still take a little bit longer for me to get that finished.
