### ISSUE TITLE
Allow temporary directory to be modified

### ISSUE THREAD

**Issue by chiraag-nataraj** [newsboat/newsboat#250]
**Newsboat version (copy from `newsboat -v`)**: 2.12.0

Steps to reproduce the issue:

1. Edit the config file to point to an external pager (any one will do).

2. Use software like [firejail](https://github.com/netblue30/firejail) or systemd to prevent the pager from accessing `/tmp/`. However, _do_ allow access to a subdirectory - for example, since I have `pam_tmpdir` enabled, I give my pager access to `/tmp/user/1000`.

3. Note that `newsboat` doesn't pick up on the `$TMPDIR`, `$TMP`, `$TEMPDIR`, or `$TEMP` variables, which should be set to a directory that your pager _can_ access (`/tmp/user/1000/` in my case).

4. The pager is unable to display the file.

**Other info you think is relevant**:

Maybe I missed something, but it seems that I cannot customize the temporary directory location, which would fix this issue.

**Comment by Minoru** [comment]
Thanks both for the report and the PR!
