### ISSUE TITLE
How do I refresh feeds without opening the UI?

### ISSUE THREAD

**Issue by makerio90** [newsboat/newsboat#2520]
add a flag to just refresh feeds without opening the ui, this way you could set up a script to auto reload on a cron schedule, or whenever a ping command success, ect.

**Comment by juntuu** [comment]
Take a look at the [commandline commands](https://newsboat.org/releases/2.31/docs/newsboat.html#_commandline_commands). Would `reload` work for you?

```sh
newsboat -x reload
```

**Comment by makerio90** [comment]
yes.. i should have paid more attention to the docs, sorry
