### ISSUE TITLE
Can article dialog be configured?

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#255]
**Newsboat version (copy from `newsboat -v`)**:

newsboat 2.12.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.12.0
System: Linux 3.16.0-4-686-pae (i686)
Compiler: g++ 4.9.2
ncurses: ncurses 5.9.20140913 (compiled with 5.9)
libcurl: libcurl/7.38.0 GnuTLS/3.3.8 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 (compiled with 7.38.0)
SQLite: 3.8.7.1 (compiled with 3.8.7.1)
libxml2: compiled with 2.9.1

Steps to reproduce the issue:

Can the content of the article be configured/changed other than changing a source code and recompile? If not, then is there a plan to implement this?

It would be nice to have a template in the config folder where you caould create the layout (text + variables).

**Other info you think is relevant**:

**Comment by Minoru** [comment]
Hi! I think this is a duplicate of #68; can you read that other issue and close this one if it's indeed so?

In short: there is a wish to do it, but no concrete plans yet.

**Comment by ZaxonXP** [comment]
Look similar. I will close this one and add some ideas to the other.
