### ISSUE TITLE
[Feature request] Statically compiled binary

### ISSUE THREAD

**Issue by kenderipa** [newsboat/newsboat#2585]
Hello,

I've searched a bit and found out, that you wouldn't make an AppImage. Would you perhaps compromise on a statically compiled binary, that would include all dependencies? I would love to eliminate an additional (and pretty slow) link, which is repositories.

**Comment by Minoru** [comment]
Hi! The arguments I gave in https://github.com/newsboat/newsboat/issues/1116 apply to the statically compiled binary too.
