### ISSUE TITLE
Lock consistency violation in controller (uri.user)

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#260]
As reported in https://github.com/newsboat/newsboat/issues/254#issuecomment-415651046, Infer static analyzer found a ton of issues with accesses to `uri.user` in `controller`:

1. src/controller.cpp:965: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_edit_urls_file` indirectly reads with synchronization from `uri.user`. Potentially races with unsynchronized write in method `run`.

29. src/itemlist_formaction.cpp:719: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::itemlist_formaction_finished_qna` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `prepare`. [wob].

30. src/itemlist_formaction.cpp:1207: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::itemlist_formaction_handle_cmdline` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `prepare`. [wob].

36. src/view.cpp:553: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::view_push_itemview` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `set_feedlist`. [wob].

37. src/view.cpp:553: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::view_push_itemview` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `prepare`. [wob].

38. src/reloader.cpp:76: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `reload_urls_file`. [wob].

39. src/reloader.cpp:76: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `reload_indexes`. [wob].

40. src/reloader.cpp:76: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `prepare`. [wob].

41. src/reloader.cpp:158: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload_all` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `reload_indexes`.

42. src/reloader.cpp:178: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload_all` indirectly reads with synchronization from `uri.user`. Potentially races with unsynchronized write in method `run`.

43. src/reloader.cpp:220: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload_indexes` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `reload_indexes`.

44. src/reloader.cpp:279: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload_range` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `reload_indexes`.

45. src/reloader.cpp:279: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::Reloader_reload_range` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `reload_range`.

46. src/controller.cpp:941: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_reload_urls_file` indirectly reads with synchronization from `uri.user`. Potentially races with unsynchronized write in method `run`.

48. src/controller.cpp:615: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_replace_feed` indirectly reads with synchronization from `uri.user`. Potentially races with unsynchronized write in method `run`.

53. src/view.cpp:449: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::view_set_feedlist` indirectly reads with synchronization from `uri.user`. Potentially races with unsynchronized write in method `run`.

54. src/controller.cpp:515: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_update_feedlist` indirectly reads with synchronization from `uri.user`. Potentially races with unsynchronized write in method `run`.

55. src/controller.cpp:1073: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_write_item` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `run`. [wob].

56. src/controller.cpp:1073: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_write_item` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `prepare`. [wob].

57. src/controller.cpp:1106: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_write_item` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `run`. [wob].

58. src/controller.cpp:1106: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_write_item` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `prepare`. [wob].

59. src/controller.cpp:1057: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_write_temporary_item` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `run`. [wob].

60. src/controller.cpp:1057: error: LOCK_CONSISTENCY_VIOLATION

      Read/Write race. Non-private method `newsboat::controller_write_temporary_item` indirectly reads without synchronization from `uri.user`. Potentially races with write in method `set_feedlist`. [wob].

Right now I don't even understand what `uri.user` it is talking about, so the first step towards resolving this would be figuring this out.

**Comment by glacambre** [comment]
infer has a pretty cool command `infer explore` which gives an in-depth explanation of what it found. For example, for the last issue, it will print the following trace:
```
  Read/Write race. Non-private method `newsboat::controller_write_temporary_item` indirectly reads without synchronizat
ion from `uri.user`. Potentially races with write in method `set_feedlist`. [wob].
Showing all 12 steps of the trace


src/controller.cpp:1057:3: <Read trace>
1055.           int fd = mkstemp(filename);
1056.           if (fd != -1) {
1057.                   write_item(item, filename);
          ^
1058.                   close(fd);
1059.                   return std::string(filename);

src/controller.cpp:1057:3: call to newsboat::controller_write_item
1055.           int fd = mkstemp(filename);
1056.           if (fd != -1) {
1057.                   write_item(item, filename);
          ^
1058.                   close(fd);
1059.                   return std::string(filename);

src/controller.cpp:1073:2: call to newsboat::controller_write_item
  1071.                 throw exception(errno);
  1072.
  1073.         write_item(item, f);
           ^
  1074.   }
  1075.

src/controller.cpp:1106:2: call to newsboat::htmlrenderer_render
    1104.
    1105.       htmlrenderer rnd(true);
    1106.       rnd.render(item->description(), lines, links, item->feedurl());
             ^
    1107.       textformatter txtfmt;
    1108.       txtfmt.add_lines(lines);

src/htmlrenderer.cpp:64:2: call to newsboat::htmlrenderer_render
      62.   {
      63.       std::istringstream input(source);
      64.       render(input, lines, links, url);
             ^
      65.   }
      66.

src/htmlrenderer.cpp:143:7: call to newsboat::utils_censor_url
        141.                            if (link.length() > 0) {
        142.                                    link_num = add_link(links,
        143.                                            utils::censor_url(
                     ^
        144.                                                    utils::absolute_url(
        145.                                                            url, link)),

src/utils.cpp:990:8: access to `uri.user`
          988.                  xmlURIPtr uri = xmlParseURI(myuri);
          989.                  if (uri) {
          990.                          if (uri->user) {
                        ^
          991.                                  xmlFree(uri->user);
          992.                                  uri->user =

src/view.cpp:449:4: <Write trace>
447.                            std::dynamic_pointer_cast<feedlist_formaction,
448.                                    formaction>(formaction_stack[0]);
449.                    feedlist->set_feedlist(feeds);
          ^
450.            }
451.    } catch (const matcherexception& e) {

src/view.cpp:449:4: call to newsboat::feedlist_formaction_set_feedlist
447.                            std::dynamic_pointer_cast<feedlist_formaction,
448.                                    formaction>(formaction_stack[0]);
449.                    feedlist->set_feedlist(feeds);
          ^
450.            }
451.    } catch (const matcherexception& e) {

src/feedlist_formaction.cpp:540:20: call to newsboat::feedlist_formaction_format_line
  538.                          ++unread_feeds;
  539.
  540.                  listfmt.add_line(format_line(feedlist_format,
                            ^
  541.                                           feed.first,
  542.                                           feed.second,

src/feedlist_formaction.cpp:997:24: call to newsboat::utils_censor_url
    995.        fmt.register_fmt('t', get_title(feed));
    996.        fmt.register_fmt('T', feed->get_firsttag());
    997.        fmt.register_fmt('l', utils::censor_url(feed->link()));
                                   ^
    998.        fmt.register_fmt('L', utils::censor_url(feed->rssurl()));
    999.        fmt.register_fmt('d', feed->description());

src/utils.cpp:992:5: access to `uri.user`
      990.                      if (uri->user) {
      991.                              xmlFree(uri->user);
      992.                              uri->user =
                 ^
      993.                                      (char*)xmlStrdup((const xmlChar*)"*:*");
      994.                      }
```

So it looks like infer thinks two concurrent calls to `censor_url` could happen for the same url, with one happening from `newsboat::controller_write_item` while the other happens from `newsboat::feedlist_formaction_set_feedlist`. I think this might be a false positive as I believe `xmlParseURI()` does not return an object shared by multiple threads, but perhaps I am wrong?

**Comment by Minoru** [comment]
Thanks for digging into this! I agree with your analysis, and since we don't have any other `uri.user`s in the code, I think this whole issue can be closed without looking into each point separately.
