### ISSUE TITLE
newsboat config.sh can not find stfl on almalinux8

### ISSUE THREAD

**Issue by jimerickson** [newsboat/newsboat#2623]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
commit acd6b9d1bae2484fa68a2debba33d848ec3c1089 (HEAD -> master, origin/master, origin/HEAD)

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
no config yet

```
INSERT COPY HERE
```

Steps to reproduce the issue:

1. build stfl from git. run sudo ldconfig. 

2. run config.sh in newsboat folder

3. it shows stfl not found. stfl is in /usr/local/lib and /usr/local/include.

**Other info you think is relevant**:
added /usr/local/lib to /etc/ld.so.conf and ran sudo ldconfig.
sudo ldconfig -v shows:
libstfl.so.0 -> libstfl.so.0.24

will gladly supply any requested info. please let me know what i did wrong here.

**Comment by Minoru** [comment]
Hi! Newsboat looks for most of its dependencies using `pkg-config`, so you should have "stfl.pc" somewhere. Here on Debian it's in /usr/lib/pkgconfig. So it's a matter of `find / -name stfl.pc` to figure out where it is on your system, and then (maybe) figuring out why `pkg-config` doesn't look for it there.

**Comment by jimerickson** [comment]
finally had a chance to figure this out.
'''
PKG_CONFIG_PATH=/usr/lib/pkg-config ./config.sh
'''
that did the trick and it built!
thanks for your help!
