### ISSUE TITLE
`feedlist-title-format` default value when added to config, doesn't  show the same result

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#2625]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.33.0 

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# Refer:
# 0. [voidrice/config at archi3 · LukeSmithxyz/voidrice](https://github.com/LukeSmithxyz/voidrice/blob/archi3/.config/newsboat/config)
# 1. [Newsboat + Bitchute + mpv + youtube-dl](https://megamorphf.github.io/software/tui/video/2018/08/25/newsboat-bitchute-mpv-youtubedl.html)
# 2. [The Newsboat RSS Feedreader](https://newsboat.org/releases/2.33/docs/newsboat.html)
# 3. [~/.newsbeuter/config](http://moparx.com/configs/newsbeuter/)
# 4. [Newsboat - ArchWiki](https://wiki.archlinux.org/index.php/Newsboat#Configuration)
# 5. [How to open newsboat feed in browser - Ask Ubuntu](https://askubuntu.com/questions/1256425/how-to-open-newsboat-feed-in-browser)

# ----------------------------- Advanced Features -------------------------------------------

# Bookmark: Refer: [Bookmark: Newsboat](https://newsboat.org/releases/2.33/docs/newsboat.html#_bookmarking)
# ========
bookmark-autopilot yes
bookmark-interactive no
bookmark-cmd "~/opt/bin/NewsboatBookmark"

# Filter: Refer: [Filter, Newsboat](https://newsboat.org/releases/2.33/docs/newsboat.html#_filter_language)
# ======
define-filter "minimal-unread" "unread_count >= 2"
run-on-startup select-filter "minimal-unread"

# articles ignore: Refer: [Killfiles, Newsboat](https://newsboat.org/releases/2.33/docs/newsboat.html#_killfiles)
# ======================
ignore-article "*" "title =~ \"Sponsor|Advertisement|[sS]horts?\""
ignore-article "*" "title =~ \"अ|आ|इ|ई|उ\""
ignore-article "*" "title =~ \"Modi|Narendra Modi|bjp|Amit Shah|Rahul Gandhi|Sonia Gandhi|Mamata Banerjee|Adani|Ambani\""
ignore-article "*" "title =~ \"Trump|Biden|Trudeau|Canada\""
ignore-article "*" "title =~ \"Brexit|Boris Johnson|Queen Elizabeth|King Charles|Prince Charles|Meghan|Prince Harry\""
ignore-article "*" "title =~ \"North Korea|Kim Jong|Ukraine|Zelenskyy|Jair Bolsonaro|Russia|Putin|Hamas|Gaza|Netanyahu|Bibi|Palestine\""
ignore-article "*" "title =~ \"Xi Jinping|Pakistan|Cpec|Nepal|Bangladesh|Bhutan|Taliban|Afghanistan|Afghan|Kabul|Maldives|Taiwan|Gaza\""
ignore-article "*" "title =~ \"Covid|Coronavirus|Corona|Pandemic|Vaccine|Lockdown\""
ignore-article "*" "title =~ \"Gondi Bulletin|Kashmir|Bachchan|priyanka chopra|cricket|virat kohli\""
ignore-article "*" "title =~ \"amazon|apple|iphone|ipad|macbook|xiaomi|huawei|samsung\""
#ignore-article "*" "title =~ \"\""
ignore-mode "display"

# Format Strings: %<no. of characters><Field Code> : Refer: [Format Strings, Newsboat](https://newsboat.org/releases/2.33/docs/newsboat.html#_format_strings)
# ==============
feedlist-format "%4i %-18T %11U %n %-30t"
articlelist-format "%4i %f %D   %?T?|%-17T|  ?%t"
notify-format "%d new articles (%n unread articles, %f unread feeds)"
podlist-format "%4i [%-5p %%] %-5S %b"
#podlist-format "%4i [%6dMB/%6tMB] [%5p %%] [%7k kb/s] %-20S %u -> %F"

# Dialog Titles
# =============
#feedlist-title-format "%N %V - %?F?Feeds&Your feeds? (%u unread, %t total)%?F? matching filter `%F'&?%?T? - tag `%T'&?"

# Macro: Refer: [Macro, Newsboat](https://newsboat.org/releases/2.33/docs/newsboat.html#_macro_support)
# =====
macro q mark-all-feeds-read ; quit
macro , open-in-browser
macro w set browser "w3m"; open-in-browser ; set browser "firefox %u"
macro m set browser "Youtube %u"; open-in-browser ; set browser "firefox %u" # Execute Youtube.sh
#macro m set browser "ytfzf %u"; open-in-browser ; set browser "firefox %u" # Execute ytfzf. Cons: No subtitles!
macro m set browser "mpv --no-config --fs --ytdl-raw-options=ignore-config=,sub-langs=[en,en-GB,de],write-subs=,write-auto-subs=,sponsorblock-mark=default,sponsorblock-remove=default -- %u"; open-in-browser ; set browser "firefox %u" # Copied from Youtube.sh
#macro m set browser "mpv --sub-auto=fuzzy --screenshot-format=png --screenshot-template=Image_%F_%wH-%wM-%wS --screenshot-directory=Image --ytdl-format=best --ytdl-raw-options=sub-format=en,write-srt= --ytdl --ontop --no-border --force-window --autofit=960x540 --geometry=-20-50 %u"; open-in-browser ; set browser "firefox %u"
#macro m set browser "mpv %u"; open-in-browser ; set browser "firefox %u"

#macro v set browser "setsid nohup mpv"; open-in-browser ; set browser google-chrome
#macro c set browser "xsel -b <<<" ; open-in-browser ; set browser google-chrome

## Task Spooler
# =============
#macro t set browser "tsp youtube-dl --add-metadata -ic"; open-in-browser ; set browser google-chrome
#macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best"; open-in-browser ; set browser google-chrome

# -------------------------------------- Appendix A: Newsboat Configuration Commands ----------------------------------------------
# Refer: [Appendix A: Newsboat Configuration Commands](https://newsboat.org/releases/2.33/docs/newsboat.html#_newsboat_configuration_commands)


# Browser (Set Default browser)
# =======
# Linux
#browser "google-chrome %u"
#browser "firefox %u"
## MacOS
#browser "open -g -a 'Google Chrome' %u"

#browser "open %u"
browser "$BROWSER %u"

# Cache
# =====
# keep-articles-days: If set the a number greater than 0, only articles that are were published within the last <n> days are kept, and older articles are deleted. If set to 0 (default value), this option is not active.
# max-items: Set the number of articles to maximally keep per feed. If the number is set to 0, then all articles are kept. [Feeds with many items are slow to open and navigate · Issue #229 · newsboat/newsboat](https://github.com/newsboat/newsboat/issues/229); Newsboat caches the article that it downloads. This means that when you start newsboat again and reload a feed, the old articles can still be read even if they aren’t in the current RSS feeds anymore. Optionally you can configure how many articles shall be preserved by feed so that the article backlog doesn’t grow endlessly (see "max-items" below).
keep-articles-days 365

# display
# =======
show-read-feeds no
feed-sort-order unreadarticlecount-asc
text-width 80

# Feed
# ====
auto-reload yes
reload-time 60
reload-threads 32
download-retries 4
download-timeout 10
prepopulate-query-feeds yes
mark-as-read-on-hover yes
#confirm-mark-all-feeds-read no

# Misc
# ====
error-log "~/Documents/.Log/Newsboat.error.log"
confirm-exit no
cleanup-on-quit yes

# navigation
# ==========
goto-next-feed no

# ---------------------------------------- Appendix C: Podboat Configuration Commands ----------------------------------------------

# Podcast # Refer: [Appendix C: Podboat Configuration Commands](https://newsboat.org/releases/2.33/docs/newsboat.html#_podboat_configuration_commands)
# =======
download-path "~/Downloads/Podcast/%h/%n"
podcast-auto-enqueue yes
max-downloads 4
player 'mpv'
max-items 0

# ------------------- Solarized Light ----------------

# Theme
# ========
# Light Solarized color scheme for newsbeuter, based on
# Ethan Schoonover's Solarized.
#
# In order to use this color scheme, you must first configure
# your terminal emulator to use the Solarized palette.
# See <http://ethanschoonover.com/solarized/> for more information.

color background         default   default
color listnormal         default   default
color listnormal_unread  default   default
color listfocus          white     yellow
color listfocus_unread   white     yellow
color info               default   white
color article            default   default

# highlights
highlight article "^(Title):.*$" green default
highlight article "https?://[^ ]+" blue default
highlight article "\\[image\\ [0-9]+\\]" red default
```

## Steps to reproduce the issue:

- Refer: [7.10.1. Dialog Titles](https://newsboat.org/releases/2.33/docs/newsboat.html#_dialog_titles)

The tile looks like the following, when config does not contain the default value: 

```
feedlist-title-format "%N %V - %?F?Feeds&Your feeds? (%u unread, %t total)%?F? matching filter `%F'&?%?T? - tag `%T'&?"
```

![image](https://github.com/newsboat/newsboat/assets/42092626/89cef3fa-8615-4db1-9bc4-a9f9c9a152d9)

---

The tile looks like the following, when config contains the default value: 

```
feedlist-title-format "%N %V - %?F?Feeds&Your feeds? (%u unread, %t total)%?F? matching filter `%F'&?%?T? - tag `%T'&?" 
```

![image](https://github.com/newsboat/newsboat/assets/42092626/e6e3412c-0e79-4163-ac94-7f159318522e)

# Issue

1. Why adding the default value changes how it looks?
2. Could you please explain what is meant by ` %?F?Feeds&Your feeds?`
3. Is it possible to display an environment variable in the feedlist-title-format? For example, I would like to display `Computer (2 unread) matching filter 'unread_count >=2'`, when `FeedListName=Computer` is there in the environment when newsboat is started from.

**Comment by dennisschagt** [comment]
To answer the points in order:
1. The default value for `feedlist-title-format` uses backtick characters (\`). These backtick characters are used in the configuration file for [shell evaluation](https://newsboat.org/releases/2.33/docs/newsboat.html#_shell_evaluation). If you want to use a backtick as-is in a config option, it needs to be escaped by placing a backslash in front of it.
    It might make sense for us to change the `title-format` defaults to not contain backticks (to avoid confusion in the future)
2. `%?F?first option&second option?` will check the value which would be printed with `%F`. If it is non-empty, it will include the first part of the text (in this case: `first option`) and if it is empty it will include the second part of the text (the part after the `&`, in this case: `second option`).
    The full formatting options, including this special operation, are described in the [format strings section](https://newsboat.org/releases/2.33/docs/newsboat.html#_format_strings) of the documentation. Specifically:
    > Another powerful format is the conditional sequence, %?[char]?[format 1]&[format 2]?: if the text of the sequence identifier [char] contains any non-whitespace characters, then [format 1] will be evaluated and inserted, otherwise [format 2] will be evaluated and inserted. The & and [format 2] are optional, i.e. if the identifier’s text is empty, then an empty string will be inserted.
3. Yes, it is possible to inject environment variables using the backtick [shell evaluation](https://newsboat.org/releases/2.33/docs/newsboat.html#_shell_evaluation). e.g.
```
feedlist-title-format "`echo $FeedListName` (%u unread)%?F? matching filter \`%F'&?"
```

**Comment by lamyergeier** [comment]
> To answer the points in order:
> 
>     1. The default value for `feedlist-title-format` uses backtick characters (`). These backtick characters are used in the configuration file for [shell evaluation](https://newsboat.org/releases/2.33/docs/newsboat.html#_shell_evaluation). If you want to use a backtick as-is in a config option, it needs to be escaped by placing a backslash in front of it.
>        It might make sense for us to change the `title-format` defaults to not contain backticks (to avoid confusion in the future)
> 
>     2. `%?F?first option&second option?` will check the value which would be printed with `%F`. If it is non-empty, it will include the first part of the text (in this case: `first option`) and if it is empty it will include the second part of the text (the part after the `&`, in this case: `second option`).
>        The full formatting options, including this special operation, are described in the [format strings section](https://newsboat.org/releases/2.33/docs/newsboat.html#_format_strings) of the documentation. Specifically:
>        > Another powerful format is the conditional sequence, %?[char]?[format 1]&[format 2]?: if the text of the sequence identifier [char] contains any non-whitespace characters, then [format 1] will be evaluated and inserted, otherwise [format 2] will be evaluated and inserted. The & and [format 2] are optional, i.e. if the identifier’s text is empty, then an empty string will be inserted.
> 
>     3. Yes, it is possible to inject environment variables using the backtick [shell evaluation](https://newsboat.org/releases/2.33/docs/newsboat.html#_shell_evaluation). e.g.
>        ```
>        feedlist-title-format "`echo $FeedListName` (%u unread)%?F? matching filter \`%F'&?"
>        ```

May I ask why a single backtick and a single quote is used just once in the following:

```
\`%F'
```

**Comment by dennisschagt** [comment]
Looks like someone else ran into the issue before and the default where already updated: https://github.com/newsboat/newsboat/issues/1520 (issue) and https://github.com/newsboat/newsboat/pull/1572 (fix)

So the default already stopped using the backtick and the documentation was updated, but it looks like there is another part of the documentation which was not yet updated.

Updated: ![image](https://github.com/newsboat/newsboat/assets/4629607/3f30e3b6-cf3b-40cc-ba8d-744e50b84a3a)
Outdated: ![image](https://github.com/newsboat/newsboat/assets/4629607/30487e5d-22d6-491b-9a12-e8ed7206d34a)

I will see if I can fix that in a moment.
