### ISSUE TITLE
Format string '%>[char]' not working as intended when placed within conditionals

### ISSUE THREAD

**Issue by captaincurrie** [newsboat/newsboat#2645]
When including `%>[char]` within a conditional block `%?[char]?[format1]&[format 2]?`, 
you do not get the expected behavior. For example,
using my articlelist-format, `%D   %?T?%-63t%> %T&%t?`, when i open a
query feed composed of multiple feeds, the `%T` does not show up as it
should. Instead, the right of the screen is filled with spaces.

However, if instead remove the conditional block and use `%D   %-63t%> %T`, then it works as intended.

This smells like a bug

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat r2.33-dirty - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2023 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2023 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat r2.33-dirty
System: Linux 6.6.8-arch1-1 (x86_64)
Compiler: g++ 13.2.1 20230801
ncurses: ncurses 6.4.20230520 (compiled with 6.4)
libcurl: libcurl/8.5.0 OpenSSL/3.2.0 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0 (compiled with 8.2.1)
SQLite: 3.44.2 (compiled with 3.42.0)
libxml2: compiled with 2.11.5

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# general
auto-reload yes
bookmark-autopilot yes
bookmark-interactive no
browser "browser openTab: %u"
confirm-mark-all-feeds-read no
confirm-mark-feed-read no
external-url-viewer "/ckc/bin/urlview"
feed-sort-order title
history-limit 10000
ignore-mode download
pager "feeder pager: %f"
prepopulate-query-feeds no
reload-threads 4
reload-time 15
show-keymap-hint no
show-read-feeds no
show-title-bar yes
suppress-first-reload yes
swap-title-and-hints no
wrap-scroll yes
toggleitemread-jumps-to-next-unread  no

# colors
color background        black color15
color listnormal        black color15
color listfocus         black color7
color listnormal_unread black color15 bold
color listfocus_unread  black color7  bold
color info              black color6
color article           black color15

# formats
datetime-format "%Y-%m-%d"
articlelist-title-format "%T"
articlelist-format "%D   %?T?%-63t%> %T&%t?"

feedlist-title-format "Feeder"
feedlist-format "%t"
searchresult-title-format "%N %V - Search results (%u unread, %t total)%?F? matching filter `%F'&?"

# keybinds
bind-key k down
bind-key l up
bind-key ENTER open
bind-key SPACE toggle-article-read
bind-key ^K pagedown
bind-key ^L pageup 
bind-key g home
bind-key ^G end
bind-key ^A mark-feed-read
bind-key r toggle-show-read-feeds 
bind-key ^R reload-all
bind-key R  reload
bind-key o open-in-browser articlelist
bind-key / open-search help
bind-key s sort
unbind-key q feedlist
bind-key ^. reload-urls

## feedlist
bind-key SPACE mark-feed-read feedlist
bind-key ; open feedlist
bind-key j prev-dialog feedlist

## articlelist
bind-key h quit articlelist
bind-key j prev-feed articlelist
bind-key ; next-feed articlelist
bind-key d delete-article articlelist

## internal pager
bind-key ; next article
bind-key j prev article

## macros
macro s set browser "signal %u &" ; open-in-browser ; set browser "browser openTab: %u"
macro y set browser "clipboard set: %u" ; open-in-browser ; set browser "browser openTab: %u"
macro p set browser "feeder setPager: internal" ; open-in-browser-noninteractively ; open ; set browser "feeder setPager: dispatch" ; open-in-browser-noninteractively ; set browser "browser openTab: %u"

```

Steps to reproduce the issue:

1. Set articlelist-format to something like `%D   %?T?%-63t%> %T&%t?`

2. Open a feed which contains different feeds

3. `%T` will not appear on the right as it should, instead the right of the screen will be filled with ' '

**Other info you think is relevant**:

**Comment by juntuu** [comment]
Can confirm this. It looks like the conditional branches are formatted without the required context, so those can not account for content before and after.

Thus the `%D   ` pushes the end of the resulting string out of the view. If `%t` would be longer than that prefix, you would see part of it.

The following patch may fix part of the problem, namely accounting for the preceding content.

```patch
From 13342136de259c4e6735f2ca83e380ec339a1b92 Mon Sep 17 00:00:00 2001
Subject: [PATCH] Fix padding in conditional branch

This is still missing the context of any trailing content
---
 rust/libnewsboat/src/fmtstrformatter/mod.rs | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/rust/libnewsboat/src/fmtstrformatter/mod.rs b/rust/libnewsboat/src/fmtstrformatter/mod.rs
index 4bf03a65..cc604a4d 100644
--- a/rust/libnewsboat/src/fmtstrformatter/mod.rs
+++ b/rust/libnewsboat/src/fmtstrformatter/mod.rs
@@ -151,13 +151,17 @@ impl FmtStrFormatter {
         width: u32,
         result: &mut LimitedString,
     ) {
+        let remaining = width.saturating_sub(result.length() as u32);
+        if remaining == 0 {
+            return;
+        }
         match self.fmts.get(&cond) {
             Some(value) if !value.trim().is_empty() => {
-                result.push_str(&self.formatting_helper(then, width))
+                result.push_str(&self.formatting_helper(then, remaining))
             }
             _ => {
                 if let Some(ref els) = *els {
-                    result.push_str(&self.formatting_helper(els, width))
+                    result.push_str(&self.formatting_helper(els, remaining))
                 }
             }
         }
-- 
2.43.0
```

**Comment by pk0dev** [comment]
I'm new to newsboat and wanted to know on how to set newsboat window width and height to have centered window. I tired to look into the documentation but I guess I need to know C for that.

Thanks in advance.
