### ISSUE TITLE
Migrate to Catch2 version 3.x

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#2716]
Now that we compile Newsboat in C++14 mode (#2692, #2694), we can finally update our testing framework from 2.x to 3.x. The main benefit (as far as I understand) is faster compilation, because the framework is no longer a header-only library.

The framework's repository is at: https://github.com/catchorg/Catch2

This will require some very light changes to our Makefile, and probably won't require any changes to the tests at all, so feel free to try your hand at this even if you've never looked at Newsboat's code.

**Comment by JosephFak** [comment]
I would like to work on this if possible!

**Comment by Minoru** [comment]
Sure, have at it! If it turns out too hard, please write down here the problems you ran into, so we have a better picture and can decide how to proceed.
