### ISSUE TITLE
[Question/Feature request] Display (toggle) all article from all feeds together with a shortcut

### ISSUE THREAD

**Issue by lamyergeier** [newsboat/newsboat#2721]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.34.0
 
From following screenshot, we can see that I have several feed with only 1 article each:

![Screenshot from 2024-03-24 07-18-20](https://github.com/newsboat/newsboat/assets/42092626/faf58b95-ff4d-4215-9a81-057f5d46d56e)

To view the articles, I have to select feed one by one and then select the article.  Is it possible to toggle with a shortcut key to display all articles from all feeds together? This will be a good user experience.

**Comment by Minoru** [comment]
It's not possible, and it doesn't really fit Newsboat I think, because it blurs the distinction between feedlist and itemlist. "The Newsboat way" would be to create a query feed with all articles: https://newsboat.org/releases/2.35/docs/faq.html#_i_want_to_have_a_feed_that_contains_all_unread_articles_of_all_feeds

Closing because I don't really see a way to persuade me otherwise, but you're still welcome to try -- an issue can always be re-opened :)

**Comment by lamyergeier** [comment]
@Minoru  IMHO I can't use query because I use Freshrss as a source. Is there still a way?

**Comment by dennisschagt** [comment]
>  IMHO I can't use query because I use Freshrss as a source. Is there still a way?

It looks like we support query feeds in combination with freshrss:
https://github.com/newsboat/newsboat/blob/eab776f523cd7d3b7bc9aa64eaae80cdca8ab8cd/src/freshrssurlreader.cpp#L45-L53

You can put the query in the urls file (by default `$HOME/.newsboat/urls`, run `newsboat -h` to print relevant locations)
Query feeds normally show a filtered list of all articles so to show all articles (unfiltered) you might need to select all articles in a creative way, e.g.:
`"query:all articles:unread = \"yes\" or unread = \"no\""`

And just a remark if you haven't used Newsboat's query feeds before:
Normally, query feeds are only filled when you try to open them or when you reload all feeds.
However, you can add `prepopulate-query-feeds yes` to your config to show the total number of articles on the query feeds at startup ([docs](https://newsboat.org/releases/2.35/docs/newsboat.html#prepopulate-query-feeds))
