### ISSUE TITLE
Changing exec command in url file making previous records dissapear.

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#2735]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Newsboat 2.35.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2024 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2024 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.35.0
System: Linux 6.5.0-0.deb12.4-amd64 (x86_64)
Compiler: g++ 12.2.0
ncurses: ncurses 6.4.20221231 (compiled with 6.4)
libcurl: libcurl/7.88.1 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13 (compiled with 7.88.1)
SQLite: 3.40.1 (compiled with 3.40.1)
libxml2: compiled with 2.9.14
```

Steps to reproduce the issue:

1. In my `url` file I have following exec (and 400 articles for that feed):
`"exec:/usr/bin/curl --insecure 'https://wolnemedia.net/kategoria/wideo/feed/'"                       "~a5.V: Video" all V_all`

2. When I change it to some other exec command like this:

`"exec:/usr/bin/lynx -dump 'https://wolnemedia.net/kategoria/wideo/feed/'"                       "~a5.V: VideoL" all V_all`

2. Now if I reload the feed I only get 100 latest, so the other 400 (or 300) get lost.

**Other info you think is relevant**:

I have to change from `curl` to `lynx` as the first is no longer working. Now is the question how can I preserve the previous content (downloaded articles when I used curl)?

**Comment by ZaxonXP** [comment]
I see that the data is stored in a Sqlite3 database. Is there a way to merge the entries from previously retrieived exec command to the new one?

**Comment by dennisschagt** [comment]
This looks related to https://github.com/newsboat/newsboat/issues/2334 (maybe even a duplicate).
I did not try it myself, but [the latest commit on that issue](https://github.com/newsboat/newsboat/issues/2334#issuecomment-2042351994) looks like a good way to do this.

**Comment by ZaxonXP** [comment]
Thanks @dennisschagt. It could be useful for part of my issue described here.
The other one I have is how to merge two databases as I have some old entries in a second cache file. Does someone have Idea how to merge two cache files?

**Comment by ZaxonXP** [comment]
Suggestion from #2334 worked. Thanks for helping.
