### ISSUE TITLE
Question: Is there an Integration with Thunderbird? Can I use Newsboat on a headless server?

### ISSUE THREAD

**Issue by ThiloteE** [newsboat/newsboat#2739]
Context: Over the years I have accumulated roughly 300 000 feed items in Mozilla Thunderbird. I have come to the conclusion that I should ideally fetch (RSS) feeds via a headless server, which would reduce my electricity usage. That also would offer the advantage that I can let that machine run 24/7. Thunderbird offers no CLI options for feeds, therefore I was looking for alternative CLI based tools. I was thinking about implementing following workflow: Use Newsboat to fetch and store feeds on the server, then sync the feed directory to my workstation (+ create backups) and look at it whenever desired with my RSS reader of choice.

Question 1: Does newsboat feature importer / exporter for Thunderbird feeds?
Question 2: Can I use Newsboat on a headless server?

**Comment by dennisschagt** [comment]
I don't think Newsboat is the right application for this job.
Newsboat does not contain any integration for Thunderbird.
It does have [integrations with some Newsreading Services](https://newsboat.org/releases/2.35/docs/newsboat.html#_newsboat_as_a_client_for_newsreading_services) but in those cases Newsboat is only acting as a client.

> Can I use Newsboat on a headless server?

It is possible to run Newsboat on a headless server, but (as far as I know) you can only read/interact with it via the terminal interface.
One way to do that is to run Newsboat in a terminal multiplexer (e.g. tmux) and connect to it via ssh.

**Comment by ThiloteE** [comment]
Thank you for the response :-)
Using a terminal multiplexer is an interesting idea. I will consider it, once I tackle this project.
Interacting with newsboat only via the terminal interface is fine for me, as long as I can set up the initial news feed, have newsboat in autostart and let it run in the background doing automated fetching. I personally prefer having a GUI for reading the feeds, but that's a separate problem and should be manageable, as long as the feed is stored in a format that is compatible with a feed reader with GUI.

Anyway, if you think Newsboat is the wrong tool for the job, maybe it is. I will look for another one. Thanks again :-)
