### ISSUE TITLE
Question: vacuum on save changes in $HOME/.newsboat/urls?

### ISSUE THREAD

**Issue by stefanos82** [newsboat/newsboat#275]
I have noticed that my database's size remained the same after I edited my `$HOME/.newsboat/urls` to remove some old RSS links I forgot to do so.

After I vacuumed my database, its size dropped from 40+ MB to 12MB.

Is there a way to automate this procedure when one removes a single link or a number of them from `urls` file?

**Comment by polyzen** [comment]
Perhaps a flag can be set if you edit the `urls` file from newsboat, and vacuum on exit.

**Comment by stefanos82** [comment]
That should be the default option in my opinion, because I'm sure lots of newsboat users either delete articles or get rid of either broken RSS links and wouldn't need to retain massive gaps inside their database.

Imagine cleaning up your whole feeder list and see your database retaining its previous size before the cleanup.

For those who edit their lists with `E` key, the best thing for them should be a message that says
```
A change in urls files has been detected.

Please do not close the program until database profiling finishes its procedure.
```

**Comment by kmws** [comment]
>the best thing for them

I don't like that mentality. I know what is the best case for my scenario. I want to do things explicitly. If that's not the case for you, you could automatise those things away, like @polyzen mentioned.

Just my 2 eurocents.
