### ISSUE TITLE
Speed up FreshRSS integration by moving HTTP requests to a separate thread

### ISSUE THREAD

**Issue by mustaruhtinas** [newsboat/newsboat#2784]
Newsboat connecting to a FreshRSS instance via greader api.
Would it be possible to background certain sync operations, or to detach them from article display?
If, for instance, I browse an article list, run mark-all-above-as-read and try to open another article in the list it will wait until the mark operation is complete (and it can take quite a while), even though the article is already downloaded.
Also, when viewing articles, moving to the next one in the list can get slow, as although the article is available the post request may take some time to complete.

**Comment by Minoru** [comment]
Sure. This is a matter of doing something like #943 to src/freshrssapi.cpp.

**Comment by Minoru** [comment]
Forgot to close this; it's fixed by https://github.com/newsboat/newsboat/pull/2832.
