### ISSUE TITLE
Unreachable feeds

### ISSUE THREAD

**Issue by OlegPQ** [newsboat/newsboat#2787]
Thank you for the app.

I see the following message on exit:

```1 unreachable feeds found. See `cleanup-on-quit` in newsboat(1) for details.```

Run " cleaning" but apparently there is some kind of error.

```
newsboat --cleanup
Starting Newsboat 2.36.0...
Loading configuration...done.
Opening cache...done.
Loading URLs from /Users/oleg/.newsboat/urls...done.
Loading articles from cache...done.
Cleaning up cache...Caught newsboat::DbException with message: database disk image is malformed
```

How exactly can one find out what is meant by "_1 unreachable feeds found_"? Which feed exactly?
As far as I understand some _url_ from _rss_feed_ table doesn't match what should be in _feedurl_ from _rss_item_ table, is that right??

```
newsboat -v
Newsboat 2.36.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2024 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2024 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.36.0
System: Darwin 23.3.0 (arm64)
Compiler: g++ Apple LLVM 15.0.0 (clang-1500.3.9.4)
ncurses: ncurses 6.0.20150808 (compiled with 6.0)
libcurl: libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.58.0 (compiled with 8.4.0)
SQLite: 3.43.2 (compiled with 3.43.2)
libxml2: compiled with 2.9.13
```

Thx!

**Comment by OlegPQ** [comment]
Okay, this can be found via the [error-log](https://newsboat.org/releases/2.35/docs/newsboat.html#error-log).

**Comment by OlegPQ** [comment]
In the logs:
`[2024-06-27 02:57:03] Unreachable feed found: exec:~/.newsboat/suffix.sh https://site.com/rss/hubs/ 3`

But _https://site.com/rss/hubs/_ is not in _urls_ or in the _database_. Don't understand where that address is coming from.
Managed to get rid of the error in `newsboat --cleanup`, but it still doesn't help, it's still "_1 unreachable feeds found. ..._".

**Comment by juntuu** [comment]
To best of my knowledge _unreachable_ means that the feed is no longer found in the _urls_ file, but exists in the database. Either `rssurl` in `rss_feed` table, or `feedurl` in `rss_item` table, if I'm not mistaken. You could check those columns in the database to see if it's there.

The "database disk image is malformed" error is bit concerning, that message comes from the sqlite3 database. I'm not sure why the cleanup doesn't work, but malformed database might explain it.

**Comment by OlegPQ** [comment]
Thanks for the reply.
I used https://sqlitebrowser.org/ to replace the text in the base and it looks like this is what broke it.

```
sqlite3 ./cache.db
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> SELECT * FROM "rss_item" WHERE feedurl LIKE '%habr.com/rss%';
sqlite> PRAGMA integrity_check;
row 4804 missing from index idx_guid
row 28618 missing from index idx_guid
row 36152 missing from index idx_guid
row 81911 missing from index idx_guid
wrong # of entries in index idx_feedurl
wrong # of entries in index idx_guid
sqlite> PRAGMA foreign_key_check;
sqlite> PRAGMA quick_check;
ok

```
But if you execute the query from the program, the result is different, but the program also does not show the string.
<img width="745" alt="Screenshot 1" src="https://github.com/newsboat/newsboat/assets/62989007/05de73c5-71b1-4de7-a592-d18bb063518c">
`DELETE FROM "rss_item" WHERE feedurl LIKE '%habr.com/rss%';` also doesn't help.

Don't understand at all what is this "invisible" string and how to fix the problem.

**Comment by juntuu** [comment]
This looks like a problem on the sqlite side. I would suggest taking a backup, and then trying to restore the corrupt database.

You could check https://sqlite.org/recovery.html, and try the `.recover` sqlite command. Or stackoverflow has some discussion e.g. https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database.

**Comment by OlegPQ** [comment]
@jonuts thx, it did help.

`sqlite3 cache.db ".dump" | sqlite3 new.db`
