### ISSUE TITLE
Title not displayed in terminal

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [newsboat/newsboat#279]
Weechat sets the title correctly: https://i.imgur.com/b95rUnA.png

Newsboat don't: https://i.imgur.com/pZ4Gb3B.png

**Comment by Minoru** [comment]
Newsboat changes the terminal's title only if all of the following holds:
* a reload of all threads just finished; and
* [`notify-xterm`](https://newsboat.org/releases/2.12/docs/newsboat.html#notify-xterm) is enabled; and
* reload brought new items, or [`notify-always`](https://newsboat.org/releases/2.12/docs/newsboat.html#notify-always) is enabled.

If you want to always set title to "Newsboat" when it starts, simply call `echo` beforehand, [like I do](https://github.com/Minoru/dotfiles/blob/12bfa2fe5f3e48ed0ca65929111410160dcaf77c/.zshrc#L112). I don't see any compelling reason to integrate that into Newsboat itself.
