### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#28]
[People need them](https://github.com/newsboat/newsboat/pull/22#discussion_r145885309).

- [ ] Mention we're in favour of modern C++ and will gladly accept patches that modernize things
- [ ] Check out [relevant GitHub help entry](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) for inspiration

**Comment by Minoru** [comment]
Should also touch upon ways in which non-programmers can help, to address questions [like this old mailing list post](https://groups.google.com/forum/#!topic/newsbeuter/7AxHEzd2xfA) (or am I misunderstanding the point of guidelines, and such questions should be answered in some part of documentation?)

**Comment by Minoru** [comment]
There are a few precedents of patches contributed via the mailing list now. Should probably mention it's acceptable, and link to [Git's](https://github.com/git/git/blob/master/Documentation/SubmittingPatches) and [kernel's](https://www.kernel.org/doc/html/latest/process/submitting-patches.html) docs on the matter.

**Comment by noctux** [comment]
I've stumbled upon newsboats code formatting recently. A precise (but hopefully minimal) styleguide might help new contributors to get up to speed and provide for a more successful review process.
Maybe [checkpatch.pl-style](https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl) automatically checked or even uncrustify- or clang-format-style automatically applied formatting could help as well.

**Comment by Minoru** [comment]
I too think it's a good idea. Don't know how we're going to keep the guidelines both precise and minimal, though :)

As for auto-formatters, we actually have an `fmt` target in our Makefile that'll run `astyle`, but the last time I tried it, it messed up some of the code (can't remember details).
