### ISSUE TITLE
highlight-article based on flags has no effect on unread articles

### ISSUE THREAD

**Issue by emanruse** [newsboat/newsboat#2814]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
$ git show
commit 40828e6e8541d3a4f6b9a9faca88000ba9c96741 (HEAD -> master, origin/master, origin/HEAD)
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# relevant part only:

highlight-article "unread == \"no\"  and flags == \"r\"" color11 color160 default
highlight-article "unread == \"yes\" and flags == \"r\"" white color160 bold
```

Steps to reproduce the issue:

1. Open a feed with some articles, make sure there are some unread ones.

2. Navigate to an unread article in the list.

3. Set flag to e.g. 'r'

### Expected

The highlight should change as configured.

### Actual

Style does not change. The article item still looks the same.

**Other info you think is relevant**:

This happens **only on unread** articles. Read ones and marking flagged as read works fine and highlight works.

In r2.35 this worked fine.

**Comment by dennisschagt** [comment]
Thanks for the clear reproduction steps, especially the config + known-good release.

Looks like this broke in https://github.com/newsboat/newsboat/pull/2084 (specifically, git bisect points to https://github.com/newsboat/newsboat/commit/0175914ee5a831fea04ecec68cf2857b9002ba3f)
