### ISSUE TITLE
Use BROWSER environment variable

### ISSUE THREAD

**Issue by olmokramer** [newsboat/newsboat#283]
**Newsboat version (copy from `newsboat -v`)**:

newsboat 2.12.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.12.0
System: Linux 4.18.9-1-ARCH (aarch64)
Compiler: g++ 8.1.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.33.0 (compiled with 7.60.0)
SQLite: 3.25.0 (compiled with 3.24.0)
libxml2: compiled with 2.9.8

It would be nice if newsboat checked the `BROWSER` environment variable as the default value for the `browser` option, it provides a single place to define which browser programs should use.

Steps to reproduce the issue:

1. Set BROWSER environment variable to something else than `lynx`.
2. Remove from your config any line that sets the `browser` option.
3. Open an article in the browser, it will try to open it in `lynx`.

**Comment by Minoru** [comment]
That's fair; thank you for the suggestion! In the meantime, you can do this:

```
browser "`echo $BROWSER`"
```

**Comment by olmokramer** [comment]
That was a quick fix :) Thanks, @kmws!
