### ISSUE TITLE
"Searching..." remains in status bar even when not searching

### ISSUE THREAD

**Issue by emanruse** [newsboat/newsboat#2837]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
Newsboat r2.36-75-gfc68
System: Linux 6.6.42-1.x86_64 (x86_64)
Compiler: g++ 12.2.0
ncurses: ncurses 6.4.20221231 (compiled with 6.4)
libcurl: libcurl/7.88.1 GnuTLS/3.7.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13 (compiled with 7.88.1)
SQLite: 3.40.1 (compiled with 3.40.1)
libxml2: compiled with 2.9.14
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# irrelevant
```

Steps to reproduce the issue:

1. Run newsboat and while in feed list, search for some string, e.g. "abc"

2. While searching, the lower status bar shows "Searching..."

3. After search completes and displays results, the "Searching..." notification disappears

4. Press 'q' to return to news feed

**Result:** "Searching..." still displays although there is no actual searching going on.

5. Navigate back and forth inside feeds and return to feeds list

**Result:** same.

**Expected:** The status information should display actual status

**Comment by dennisschagt** [comment]
Indeed, I can reproduce the issue.
Looks like I accidentally caused that in https://github.com/newsboat/newsboat/commit/4cf6a010ae81448574f489d3ead9f6e3aa696991 (part of https://github.com/newsboat/newsboat/pull/2627)
