### ISSUE TITLE
Inoreader - failed to load subscribed feeds

### ISSUE THREAD

**Issue by aviofreak** [newsboat/newsboat#285]
**Newsboat version 2.10.2:

Steps to reproduce the issue:

1. Configure to fetch feeds from Inoreader
2. Run newsboat
3. Receive the following message:
```
Starting newsboat 2.10.2...
Loading configuration...done.
Opening cache...done.
Loading URLs from inoreader...done.
It looks like you haven't configured any feeds in your Inoreader account. Please do so, and try again.
```

**Other info you think is relevant**:
I've contacted support for Inoreader and they said the following:

> It looks like the Newsboat are having API integration with our backend. Since we don't have any known issues on our side this could be an oauth issue yesterday. If you notice similar behavior again, feel free to contact us, or even better contact the Newsboat developers and ask them about that.

Regards
aviofreak

**Comment by Minoru** [comment]
Hello! Developer panel at inoreader.com tells me there were 2 unique users on 24th and 25th, and together they used up all the requests (which are [limited](https://www.inoreader.com/developers/rate-limiting) per-app, so all Newsboat users share a single limit).

You don't have `reload-time` set to `1`, do you? Or thousands of feeds, perhaps?

**Comment by aviofreak** [comment]
Hi,

I've got 32 feeds, half of them are not very active. These are my settings:
```
feed-sort-order unreadarticlecount-asc
auto-reload yes
toggleitemread-jumps-to-next-unread yes
reload-threads 5
urls-source "inoreader"
inoreader-login xxx
inoreader-passwordfile xxx
inoreader-min-items 100
inoreader-show-special-feeds no
```

Do you see anything suspicious here?

**Comment by Minoru** [comment]
No, don't see anything suspicious there.

Developer panels says there were 3 uniques so far today, and they used up 55% of the limit. Over the last 30 days (maximum amount of history I can see), there were at most 4 uniques who used up at most 20% of the limit.

Basically, I don't know what it was, Just keep using the program as usual, and I'll get back to you in a week; let's see if this continues.

**Comment by Minoru** [comment]
Over the last 7 days, there were at most 4 users, but API usage newer went over 7% of the quota. So, I still don't know what it was, but it was a fluke of some kind. I doubt you'll see this again, but if you do, please report.

And thanks for reporting in the first place!
