### ISSUE TITLE
Tracking issue for Rust rewrite

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#286]
> Are there any other resources, like a meta thread for the port? For example a discussion how the transition phase would look like, especially if a release is published during that time. I'm involved with rust on debian so I might be able to help with some of the issues.

_Originally posted by @kpcyrd in https://github.com/newsboat/newsboat/issues/89#issuecomment-424149873_

**Comment by Minoru** [comment]
Thanks for the suggestion! Indeed it's a good idea to have an issue where I can communicate some general points that don't belong in more task-centric issues.

> how the transition phase would look like, especially if a release is published during that time

C++ and Rust will co-exist for a while. This means people will need two compilers to build Newsboat.

The build will continue to be driven by Make. However, dependency resolution will happen in two (or more) different places: once in our existing config.sh and again when `cargo build` is run. If there are people who *need* to separate "configure" and "build" phases, let's talk and see what can be done about this (I don't see a way out).

I will keep the "every three months" release schedule. It's pretty much guaranteed we'll have at least a couple releases containing both C++ and Rust.

I'm not yet sure how much outside help I'll be able to use, and how much I'll get. If I work on this alone with the same amount of time I spend now, [three-point estimate](https://en.wikipedia.org/wiki/Three-point_estimation) says I'll be done in 2 years with standard deviation of 0.7 years (raw estimates are: 0.75 years / 1.5 years / 5 years).

> I'm involved with rust on debian so I might be able to help with some of the issues.

Actually, I was stuck with a build issue for the past few days, so I think it's high time for me to ask for help. I'll open a separate issue and ping you there.

**Comment by zaowen** [comment]
I would like to help with this. What sort of things need to be done?

**Comment by Minoru** [comment]
@zaowen, please take a look at #332 and #334.

**Comment by Minoru** [comment]
> If I work on this alone with the same amount of time I spend now, three-point estimate says I'll be done in 2 years with standard deviation of 0.7 years (raw estimates are: 0.75 years / 1.5 years / 5 years).

— me, September 2018.

I wasn't alone at all. In fact, I'm literally overwhelmed with support and can't keep up getting the code into portable state :) Despite that, the "2 years" estimate looks absolutely optimistic today: it's 1.75 years already, and we're only about 25% done (by LOC, anyway).

I think the original questions were answered by my first comment, and I haven't found much use for this thread since then. Thus, I'm closing this. Everyone who's interested in our porting effort should look at [the rust-port label](https://github.com/newsboat/newsboat/labels/rust-port) instead.

**Comment by J0hsHH** [comment]
no a "c" port
