### ISSUE TITLE
403 for `https://newsboat.org/releases/2.37/newsboat-2.37.tar.xz`

### ISSUE THREAD

**Issue by chenrui333** [newsboat/newsboat#2867]
👋 looks like the release tarball on the newsboat.org is not accessible. Thanks!

**Comment by noahsettersten** [comment]
I see a 403 error when clicking the documentation link from the home page as well (which goes to https://newsboat.org/releases/2.37/docs/newsboat.html). Maybe these are related?

**Comment by Minoru** [comment]
Oops! I forgot to adjust the file mode bits after uploading the tarballs. All is fixed now, thanks for the prod!

**Comment by chenrui333** [comment]
@Minoru np, thanks for the quick fix!

**Comment by noahsettersten** [comment]
Wonderful! Thank you for taking a look into it!
