### ISSUE TITLE
Podcast filename not escaped properly

### ISSUE THREAD

**Issue by j605** [newsboat/newsboat#290]
**Newsboat version (copy from `newsboat -v`)**:
newsboat r2.12-133-g1ad8c - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `/home/jagan/p/newsboat/newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat r2.12-133-g1ad8c
System: Linux 4.18.0-pf6 (x86_64)
Compiler: g++ 4.2.1 Compatible Clang 6.0.1 (tags/RELEASE_601/final)
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.33.0 (compiled with 7.61.1)
SQLite: 3.25.2 (compiled with 3.25.2)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. Add https://rss.art19.com/merriam-websters-word-of-the-day to urls file.
2. Use `download-path   ~/Podcasts/%n`, `%n` is the important part.
3. When you try to play the episode from podboat, I get
```sh
[file] Cannot open file '/home/jagan/Podcasts/Merriam-Webster%27s Word of the Day/2017-12-23-flamboyant.mp3': No such file or directory
Failed to open /home/jagan/Podcasts/Merriam-Webster%27s Word of the Day/2017-12-23-flamboyant.mp3.
```
since the actual file is "/home/jagan/Podcasts/Merriam-Webster's Word of the Day/2017-12-23-flamboyant.mp3".

**Comment by j605** [comment]
Currently hitting the issue more often after the change to using podcast episode title in the filename. Just a heads up since we might see this more often if people use titles in the filename.

**Comment by Minoru** [comment]
So we need to call `utils::unescape_url` somewhere; the only question is, where exactly?

I guess Podboat has to do that after reading the "queue" file, in src/queueloader.cpp:117. Not ready to reproduce this and dig deeper right now.

**Comment by j605** [comment]
I am thinking it could be https://github.com/newsboat/newsboat/blob/master/src/pb_controller.cpp#L448. I don't understand why `'` should be replaced with `%27` for a file that is on disk.

**Comment by Minoru** [comment]
Perhaps it was an easy way out of string-escaping mess: if `'` is turned into `%27`, the whole string can be wrapped in single quotes and passed to shell.

**Comment by j605** [comment]
What if we use `’` instead? I recently ran into an episode which used the proper quotes.

**Comment by Minoru** [comment]
it's still a hack no matter what symbol we use ;) To move this issue forward, I think the following should be done:
1. find out what function is allergic to that single quote, why do we have to turn it into something else;
2. change the function we found so it escapes its arguments itself, so we don't have to do it on the caller's side.

Attention should be paid to backwards compatibility. Since I don't yet have all the pieces to the problem, I can't say if this matters here or not, but remember that newer Newsboats should be able to work with queue files that were created by older Newsboats.

**Comment by Minoru** [comment]
Hard for me to advise if I don't know what the edge cases are there, and how exactly you fixed this. Can you submit your changes as a pull request so I can take a look, please?

**Comment by zaowen** [comment]
Sure

**Comment by j605** [comment]
@zaowen did you manage to submit that PR?

**Comment by zaowen** [comment]
@j605 no, my idea wasn't working and i got busy with school.
