### ISSUE TITLE
read selected articles from various sites.

### ISSUE THREAD

**Issue by i0rxg** [newsboat/newsboat#2906]
is there a way to use newsboat also as a read-it-later app?
i want to read an old article in it without adding the rss feed of it's site.

**Comment by Minoru** [comment]
There's no built-in way for that. I guess you could generate an RSS feed with articles and add that to Newsboat instead (perhaps via `exec:`).

While I see how this could be useful if most of your reading is done in Newsboat, I don't think it's worthwhile to add this to Newsboat proper. Keeping a list of such articles is quite different from fetching feeds, and we'd need additional UIs to add and possibly categorize such articles.
