### ISSUE TITLE
SSL connect error to the Economist feed

### ISSUE THREAD

**Issue by TomHsiung** [newsboat/newsboat#2910]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Newsboat 2.37.0

urls file:

```
https://www.economist.com/china/rss.xml
```

Steps to reproduce the issue:

1.Add the feed

2.Refresh

3.Error turns up

**Comment by amitzionii** [comment]
Cannot reproduce
Might have been a temporary error on their side

**Comment by TomHsiung** [comment]
OK. It works. Thank you, pal.
