### ISSUE TITLE
Whereis the default config file?

### ISSUE THREAD

**Issue by Arnaudv6** [newsboat/newsboat#294]
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Tapez `newsboat -vv' pour obtenir des informations supplémentaires.

newsboat 2.10.2
System: Linux 4.14.65 (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.61.1 OpenSSL/1.0.2p zlib/1.2.11 (compiled with 7.61.1)
SQLite: 3.24.0 (compiled with 3.24.0)
libxml2: compiled with 2.9.8

config file is not created by newsboat.... so I searched  where to write the (well documented) options.
thing is, neither
https://github.com/newsboat/newsboat/blob/master/doc/newsboat.txt
nor
newsboat -h
is any help here: you have to guess that it is in $HOME/newsboat/config
It sure is in the man page, but then again, not in the "-C" section...
Please update man page, website and "-h" quick help.

**Comment by Minoru** [comment]
I agree; thank you!

**Comment by Minoru** [comment]
Hmm, I agreed a bit too hastily.

The doc mentions the file in the "First steps" section, right before the table that lists all the options. Were you looking for it in some other section? If so, in which one?

I'll update `--help` to display current locations of urls and config file, and change description for `-C` to instruct the user to run `--help`.

**Comment by Minoru** [comment]
> I'll update --help to display current locations of urls and config file

Can't do that because `print_usage` was moved out of `controller` in #244; a decision that doesn't look as good now as it did back then. I need to sleep on this.

**Comment by Arnaudv6** [comment]
> The doc mentions the file in the "First steps" section, right before the table that lists all the options. Were you looking for it in some other section? If so, in which one?

the "First steps" here is a _include_ command and that's is.
So you're referring to my locally installed html files? I will never ever go read this, but I sure am the one to blame for this: I always go online.
https://github.com/newsboat/newsboat/blob/master/doc/newsboat.txt

> I'll update `--help` to display current locations of urls and config file, and change description for `-C` to instruct the user to run `--help`.  

That sounds perfect to me. I found the info now anyway. Just thought I had to search for it a bit too hard.

**Comment by Arnaudv6** [comment]
True!

**Comment by Arnaudv6** [comment]
I would add it to -h, but you can close if you feel like to.
I admit this info is given at many places already.
Only I did spend a few minutes to search for it.

**Comment by Minoru** [comment]
> I would add it to -h, but you can close if you feel like to.

Oh, no, I absolutely intend to add that info to `-h`. Just not sure how to best do it right now.

What I tried to accomplish with my other questions is to understand how you searched for the config path, in hopes that I can fix the root cause rather than add the path into every paragraph :)

**Comment by Arnaudv6** [comment]
I guess I overlooked it here; https://newsboat.org/releases/2.13/docs/newsboat.html#_first_steps
because _italic_ is faint: could be combined with color, a monospaced font...  
Or maybe simply can we have a new section 3.1, "configuration: file and syntax" begining the line before: this would make even more sense to me. The current 3.1 becoming a 3.2.  
For the moment, it is just in the middle of a big text section, not catching my eye.  
Hope this helps.

**Comment by Minoru** [comment]
>I guess I overlooked it here; 
>https://newsboat.org/releases/2.13/docs/newsboat.html#_first_steps
>because _italic_ is faint: could be combined with color, a monospaced font...

Monospace is reserved for settings and listings. Color might be too 
jarring since we only have two at the moment (well, three if user's 
browser is colouring the links with something other than dark blue).

>Or maybe simply can we have a new section 3.1, "configuration: file and 
>syntax" begining the line before: this would make even more sense to 
>me. The current 3.1 becoming a 3.2.

I'd merge a pull request with that change!

**Comment by Arnaudv6** [comment]
Yeah, I would (I almost started), I don't have the time. Thanks though : nice project & community.
