### ISSUE TITLE
Convert existing class names to CamelCase

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#295]
In #203, we decided all classes should have CamelCase names. All new-ish classes (CLIArgsParser, FeedHandler etc.) already do, while older ones (file_urlreader, controller etc.) don't.

Note: "CLIArgsParser" should be renamed to "CliArgsParser"; see discussion below for the rationale on that.

What needs to be done for each old-style class:
- rename it to CamelCase (file_urlreader → FileUrlReader). Acronyms are treated as single words, so opml_urlreader becomes OpmlUrlReader. Note that some of our old names are funny: urlreader should have been url_reader. You'll automatically fix this as you come up with proper CamelCase names;
- update class name in all `LOG` statements (`LOG("opml_urlreader::reload: downloading %s", ...)` → `LOG("OpmlUrlReader::reload: downloading %s", ...)`)
- update include guards in headers. You need to change three lines: `#ifndef` and `#define` at the start of the file, and commend after `#endif` at the end (`#ifndef NEWSBOAT_FILE_URLREADER_H_` → `#ifndef NEWSBOAT_FILEURLREADER_H_`)
- remove underscores from file names (opml_urlreader.cpp → opmlurlreader.cpp, dialogs_formaction.h → dialogsformaction.h)

It's a boring task, but it'll take you through half the codebase, so if you wanted to get some very general picture of what there is, it's as good way as any.

**Comment by zaowen** [comment]
Is there a reason OPML is all caps and Url only has the first letter capitalized?

**Comment by Minoru** [comment]
Oh, great point! `file_urlreader` should become `FileURLReader`, then. I'll update the post. Thank you for the vigilance!

**Comment by Minoru** [comment]
Hmm, or should we treat abbreviations as ordinary words? `OPMLURLReader` doesn't seem very readable to me. On the other hand, we probably won't have many such identifiers in the codebase, so it's okay as long as they look distinct enough.

**Comment by Minoru** [comment]
E.g. PEP 8 [says](https://legacy.python.org/dev/peps/pep-0008/#naming-conventions) to "capitalize all the letters of the abbreviation. Thus HTTPServerError is better than HttpServerError".

**Comment by Minoru** [comment]
Rust core team [advises](https://github.com/rust-lang-nursery/fmt-rfcs/blob/98e2c61aae24e9ec0df70118a710c1d577e72679/guide/advice.md) to use "HttpServerError" too, so let's go with that. I will update the top post to clarify.

@zaowen, the problem right now isn't with the style guide, it's with, em, running :) Different clang-format versions produce different formatting on the same input with the same options, which means we can't enforce the style on programmer's side. Enforcing it on Travis poises a question of how then to apply the edits, since Travis can't commit anything itself. See #198 for details; maybe you'll have some more suggestions.

**Comment by kmws** [comment]
>Rust core team advises to use "HttpServerError" too, so let's go with that.

Cool. Looks better in my opinion (for what it's worth).

**Comment by zaowen** [comment]
How should things like `sort_direction_t` be dealt with? 

Also I'm working on this issue, you can assign me to it if you'd like.

**Comment by Minoru** [comment]
> How should things like sort_direction_t be dealt with?

For `enum class`es, drop the `_t` postfix and apply the rules above to get CamelCase. For everything else (if any), please prepare a list and let me decide on one-by-one basis.

**Comment by zaowen** [comment]
Should the classes in the 3rd-party folder be changed?

**Comment by Minoru** [comment]
No. As the name implies, they aren't ours, and we update the contents of that directory from time to time by downloading new versions, so any changes done there will be lost eventually.

**Comment by zaowen** [comment]
Should hyphens be removed from file names? or just underscores?

**Comment by Minoru** [comment]
I think the only hyphens we have are in `test-helpers.h` and `test-helpers.cpp`. I'd keep them on a principle that they should stand out a bit (they are in the "test" directory but they *aren't* tests).

**Comment by zaowen** [comment]
Formaction or FormAction?

**Comment by Minoru** [comment]
FormAction, because it's still two separate words even if our codebase uses them as a single entity :)

**Comment by zaowen** [comment]
Ttrss or TtRss?

**Comment by Minoru** [comment]
TtRss, because "TT-RSS" is two acronyms separated by a hyphen. We treat
acronyms as words, and ignore the hyphens.

>

**Comment by zaowen** [comment]
InoReader or Inoreader?

**Comment by zaowen** [comment]
Do we want to capitalize the namespaces? rsspp newsboat and podboat?

**Comment by zaowen** [comment]
Should structs be counted like classes?

**Comment by zaowen** [comment]
configcontainer.h has an enum class called `configdata_t` as well as a struct named `configdata` under the new scheme this causes a naming confict.
How should i procede?
