### ISSUE TITLE
Add Miniflux starring support

### ISSUE THREAD

**Issue by timsofteng** [newsboat/newsboat#2966]
Hi!

I've seen this note in newsboat doc `Unlike with other backends, Miniflux’s starring/bookmarking feature is not currently supported in Newsboat.`

Is it possible to add this feature?

Thanks!

**Comment by Minoru** [comment]
Hi! [It was added in Newsboat 2.35](https://github.com/newsboat/newsboat/pull/2693), please upgrade ;)

**Comment by timsofteng** [comment]
@Minoru Awesome! Thank you.
I've added this line to config `miniflux-flag-star "a"`
What should I press to star article?

**Comment by Minoru** [comment]
Put the cursor on an article or open it to read, then press <kbd>Ctrl</kbd>+<kbd>E</kbd>, type "a" (the flag you've picked), and press <kbd>Enter</kbd>. https://newsboat.org/releases/2.38/docs/newsboat.html#_flagging_articles
