### ISSUE TITLE
Don't say  "an instance is already running" if it ain't so

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#314]
#312 reminded me that users quite often run into a situation where Newsboat tries to lock the cache file and fails with "PID: 0" error. Just like in #312, this often happens when the lockfile is in some absurd location that obviously doesn't exist.

This particular situation is easily detectable: just check if the parent directory where we're trying to create a lockfile exists. Then show a better error message: instead of misleading "an instance is already running", it should be "failed to create a lockfile" or something. It probably shouldn't create the directory for the user, because as I said, the path is often just absurd.

Actual steps:
- [ ] verify my recollection on this by searching through this and Newsbeuter's issue trackers. I might be misremembering the most popular cause of this message.
- [ ] implement the heuristic suggested above

**Comment by pickfire** [comment]
I still get this issue nowdays and no idea what to do.

**Comment by Minoru** [comment]
@pickfire Do you get it sporadically, or can you reliably reproduce it? If you can reproduce, try running `newsboat --log-file=newsboat.log --log-level=6`, and look inside "newsboat.log" file. It would probably contain just two lines:

> [2019-09-10 21:17:09] INFO: nl_langinfo(CODESET): UTF-8
[2019-09-10 21:17:09] DEBUG: FsLock: trying to lock `/dev/shm/unwriteable/cache.db.lock'

Note the path to the lock. In your case it should look like ~/.newsboat/cache.db.lock or ~/.local/share/newsboat/cache.db.lock. If it doesn't, then let's figure out why Newsboat puts it there. If it does, you'll need to tell me more about your setup; e.g. is it possible that Newsboat can't write the lock file because of permissions or lack of disk space?

**Comment by pickfire** [comment]
I solved it, seems like the directory was not created (and I set custom path for newsbeuter last time).
```
$ mkdir ~/.cache/newsboat/
```
I find the XDG dirs quite messy, it surprises me that it does not uses XDG base dir by default if `~/.newsboat` does not exist.

**Comment by Minoru** [comment]
Ok, got it! Newsboat *does* create non-existing ~/.local/share/newsboat, but if a different path is specified with `--cache-file`, no directories are created—Newsboat expects the user to do that manually. I think this behaviour is correct, because it makes the user think where they're putting their cache file. But we definitely need to add a nice message explaining what's going on.

Also, Newsboat *does* use XDG base dirs if the config one exists. The dotdir is the default that's used otherwise. I understand this isn't as seamless as in "pure XDG" software, but that's just how Newsboat is.
