### ISSUE TITLE
Reviewing my PRs

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#320]
Newsboat now has a small group of developers who pop up in issues and PRs quite regularly, so I thought I'd start requesting reviews from them. That worked all right for a few PRs, but #315 shows that I should really define some boundaries, as I don't want to impose on anyone.

When asking for reviews, my goals are (in no particular order):
* to switch roles for a minute, so both me and other contributors can see the review process from another perspective, hopefully making us all better collaborators;
* to raise the quality of my own contributions;
* to give contributors more opportunities to contribute. Reviews are a skill that's separate from coding, so perhaps a person who doesn't want to write code just now will feel inclined to review something.

Now, what I *don't* want to do it to make anyone feel obligated to do reviews. I think GitHub phrases this really well in their pop-up menu and emails: they name it "request for review", to make it explicit that the offer *can* be declined.

Alternatives to "request for review" menu are:
1. mentioning people by nickname in the body of the PR. I don't like that approach because it forces the potential reviewer to read the body and figure out what's asked of them. On the other hand, "request for review" emails are short (they're one-liners, I believe) and to the point, and one can write a one-line answer to say "I don't have the time right now";
2. not mentioning anyone, and just hoping that someone will notice. I don't like that either. First of all, I wouldn't know if anyone noticed unless they do a review. Second, to notice such a PR a potential reviewer has to either poll the PR tab manually, or watch the whole repo and fish PRs out of the other activity on the tracker.

This post is getting too long already, so let me get to the point already: I'd like to know what you guys would find most comfortable. ("Don't bother me with that, Minoru" is a valid answer too ;)

**Comment by der-lyse** [comment]
Any approach is fine with me. At least at the moment I don't have a preference.

I'm happy to do reviews, but please keep in mind I'm by no means a C++ or even Rust programmer, so I definitely won't spot a whole lot technical problems and my findings will be very limited. Therefore relying on me alone is no good for sure. I can focus on style in general if that is of any use. It probably is and that's what I did in the past. However, if you guys think I'm getting overboard with that, please stop me early on. :-)

**Comment by der-lyse** [comment]
> [I feel I was a bit pushy with requests for reviews lately.](https://github.com/newsboat/newsboat/pull/315#issuecomment-430766539)

No, you were not! As for me, that's totally fine, mate. When I couldn't do it right away I just said so and did it later. Also you always reassured people that real-world stuff has priority, so in my opinion you're already on the right track. Nothing to worry about.

**Comment by kmws** [comment]
>Any approach is fine with me.

Same here. Although if you _expect_ a certain person to take a look (because, for example, he/she did a change in this area recently), I would reference them in the PR (any way is OK with me). If I don't have time or I might have a slight delay, or even will have to pass this time, I will respond accordingly.

I haven't feel pushed to do a review in any way. :) It's nice that you wanted to make it clear (which is a sub-intention behind this thread, I guess).

**Comment by Minoru** [comment]
@der-lyse, okay, cool ^_^ I think you not being a C++ or Rust programmer actually gives you a unique perspective of things; you're less likely to not see wood for the trees (technicalities), because you don't see technicalities that clearly ;)

@kmws, oh, right, I *could* mention people explicitly. Though I think the only time I feel compelled to do that is when there is a problem with one of our remote APIs, because I don't generally want to get into debugging these myself.

Thank you for your replies \o/ I'll keep this issue open for a week or so, so anyone else who feels like it can comment too.
