### ISSUE TITLE
Goto feed by name

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#326]
Many times when I open newsboat I know exactly what feed I want to catch up on but that feed is buried with the others. For small url files there is the `goto` command but if that feed is not directly visible it can be hard to locate it.

Proposed solution: Add a feed search or an equivalent to the `goto` feature that jumps to the closest matching feed.

**Comment by tsipinakis** [comment]
I did not realize that `goto` can take a substring as an argument when filing this! I guess this is another instance of "I should've searched the docs better!".

**Comment by Minoru** [comment]
Gotta love issues that resolve themselves :)

> I guess this is another instance of "I should've searched the docs better!".

It can also be seen as "our docs could be better". I think I know what to improve here, will make a PR in a moment. Thanks for raising the issue!
