### ISSUE TITLE
Search while already inside search results searches the whole cache

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#327]
Steps to reproduce:
* Enter any feed
* Search for anything
* While the search results are being displayed do another search for something else

Result: The entire cache is searched rather than the feed the original search was performed from.

I would classify this a bug as it (in my opinion) subverts the expectations of the user but that's up to debate.

**Comment by Minoru** [comment]
Reproduced with 6aa4a9ac.

I won't debate this, my expectations align with yours—search within search should narrow down existing results rather than perform a whole new search.
