### ISSUE TITLE
Searching does not extend into and across hyperlinks

### ISSUE THREAD

**Issue by zaowen** [newsboat/newsboat#331]
newsboat r2.12-171-g410a-dirty - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat r2.12-171-g410a-dirty
System: Linux 4.18.13_1 (x86_64)
Compiler: g++ 8.2.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.61.1 LibreSSL/2.7.4 zlib/1.2.11 libssh2/1.8.0 nghttp2/1.34.0 (compiled with 7.61.1)
SQLite: 3.25.2 (compiled with 3.25.1)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. add `http://rss.slashdot.org/Slashdot/slashdot` to urls list (or any rss feed with urls attached.

2. Go to any link

3. search for `image 2\]\[2\]\[image`

``` noted that this could be a way for open source developers who don't want to
build an enterprise version of their tools (and the sales force that goes with
that) to monetize their efforts.
[image 2][2][image 4][4][image 6][6]
```
(nothing should be highlighted)

This bug also appears for hyperlinks that appear in the body of the text such as various articles from `http://lukesmith.xyz/rss.xml`

**Comment by Minoru** [comment]
Reproduced with e88fd99b3.

We probably run `RegexManager::quote_and_highlight()` too early, earlier than "numbers in square brackets" are added to links. But that's counter-intuitive to me—I thought the numbers are added by `HTMLRenderer`, and I'm pretty sure we call `quote_and_highlight` on an already-rendered text. =\

Thanks for a report, @zaowen!
