### ISSUE TITLE
<code> inside <pre> makes HtmlRenderer strip the line breaks

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [newsboat/newsboat#355]
In the following screenshot I was expecting some formatting of the code, and when unformatted it's pretty unreadable:
![2018-11-11-095136_2880x1800_scrot](https://user-images.githubusercontent.com/16899825/48310952-e46d7080-e597-11e8-8a4a-a473c277464e.png)

This is how it looks on reddit:
![2018-11-11-095223_2880x1800_scrot](https://user-images.githubusercontent.com/16899825/48310960-0830b680-e598-11e8-8292-c436bd804f2c.png)

Where is the spacing being stripped?.

**Comment by dennisschagt** [comment]
It looks like Reddit just puts all content of the codeblock on one line, without any newlines and whitespace (see below screenshots showing the difference between the HTML from the actual page  and the HTML as included in the RSS feed).
In a [`<pre>` block](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre), text should be presented exactly as written in the html file.
This is what Newsboat does so it looks like this is not a bug in Newsboat.

---
Reddit post: https://www.reddit.com/r/C_Programming/comments/9vz2y2/tricks_for_avoiding_void_when_implementing/
![image](https://user-images.githubusercontent.com/4629607/83005663-5fc73380-a011-11ea-8aae-bf963f158c64.png)

RSS feed for that post: https://www.reddit.com/r/C_Programming/comments/9vz2y2/tricks_for_avoiding_void_when_implementing/.rss
![image](https://user-images.githubusercontent.com/4629607/83006106-00b5ee80-a012-11ea-81ac-f0b8ec4694c9.png)

**Comment by Minoru** [comment]
[Forwarded to r/bugs](https://www.reddit.com/r/bugs/comments/grozxh/multiline_code_blocks_are_strung_up_into_a_single/). Thanks for the analysis, @dennisschagt!
