### ISSUE TITLE
is test case for resolve_tilde() in unset $HOME variable vallid?

### ISSUE THREAD

**Issue by ThangaAyyanar** [newsboat/newsboat#369]
when i run the test case i got 

test/utils.cpp:272: FAILED:
```
  REQUIRE( utils::resolve_tilde("~") == "~" )
```
with expansion:
```
  "test" == "~"
```

**Comment by Minoru** [comment]
Thank you for the vigilance, @ThangaAyyanar! :)

In the future, please don't ignore the "version" part of the issue template: if I haven't noticed this same issue before your report, I might've had trouble understanding what commit it refers to, and would've wasted time asking you about that and waiting for reply.

**Comment by ThangaAyyanar** [comment]
okay @Minoru
