### ISSUE TITLE
highlights feedlist overriden after load

### ISSUE THREAD

**Issue by Rahtgaz** [newsboat/newsboat#37]
**Newsboat 2.10.1**:

`highlight feedlist` is being overridden by `color list...` settings after the feedlist finishes loading.

Steps to reproduce the issue:

The following two lines in the config file will result on `color242` showing on program start on unread feeds, but being replaced by `color137` once the feeds finish loading:
```
feedlist-format "%3i %n %9u %-10T %t"

color listnormal_unread color137 default
highlight feedlist ".+ N .+" color242 default
```

**Comment by dennisschagt** [comment]
This issue can be reproduced on the current master branch (r2.18-174-gb8c7).

### Environment for reproducing:
#### config
```
color listnormal_unread red default
highlight feedlist ".*boat.*" green default
```
#### urls
```
https://newsboat.org/news.atom
https://www.archlinux.org/feeds/news/
```

### Steps to reproduce

1. Start Newsboat
2. Press `R` to reload all feeds
    - Expected: First feed has green color because the regex matches the whole line; second feed has red color.
    - Actual: Both feeds have red color
    - Might have to use arrow keys to select 2nd feed so the configured color can be seen
3. Press `A` to mark all acticles of first feed as read
    - Observe that now the first feed has green color (as expected)

When changing the config so the highlight regex does not match the full line, the highligting works as expected, e.g.:
`highlight feedlist "1.*boat.*" green default`

**Comment by dennisschagt** [comment]
Apparently the `RegexManager::quote_and_highlight()` call mixes `<0>...</>` (used for colors with stfl) with `<unread>...</>` which are added beforehand by `FeedListFormAction::format_line()`.

Before `quote_and_highlight()` call: `<unread>   1 N     (17/17) Newsboat</>`
Resulting string: `<0><unread>   1 N     (17/17) Newsboat</></><unread>`

It might be possible to add the `<unread>` + `</>` at the end (after calling `quote_and_highlight`) but I think we can't easily fix the issue that the highlight regex can also match (and thus interfere) with already applied highlights.

I might further look into this sometime soon but can't guarantee.

**Comment by Minoru** [comment]
Thanks for digging in, @dennisschagt! You mentioning `<unread>` reminded me of other issues like this: #242 and #535 (both numbers are palindromes, funny). Seems like a fundamental issue of how we add STFL tags to lines.
