### ISSUE TITLE
Disabling/hiding title bar

### ISSUE THREAD

**Issue by jailr** [newsboat/newsboat#375]
version: newsboat 2.13.0

I want to disable title. I don't want to change the default format, the default background color or the default foreground color. I just want it disabled both in feed list and in article list. Is it possible? Thanks.

**Comment by Minoru** [comment]
Hi! It's not possible at the moment, and if we add an option for that, it will hide the title in all dialogs, not just feed- and articlelist.

Can you explain why you want it hidden? Are you short on vertical space, and want to save one line?

**Comment by jailr** [comment]
Just to save one line whose content I never find useful. I open newsboat, I see the feedlist, I enter the first non-empty feed, then I switch to the next non-empty feed. A very basic usage.

**Comment by Minoru** [comment]
Hi; great to hear you want to work on this! I'm not at the computer right now so can't tell you the filename and the line number, but `git grep show-keymap-hint` should give you a good starting point. Header files are under include/ and the actual code is under src/.

I'll be back at the keyboard in 18 hours, if you post any questions by then-I'll answer them.

**Comment by Minoru** [comment]
Implemented in #478.
