### ISSUE TITLE
Chinese contents display error: there are garbage characters and some contents are lost

### ISSUE THREAD

**Issue by yang-ling** [newsboat/newsboat#38]
**Newsboat version (copy from `newsboat -v`)**:

    newsboat 2.10.1 - https://newsboat.org/
    Copyright (C) 2006-2015 Andreas Krennmair
    Copyright (C) 2015-2017 Alexander Batischev
    Copyright (C) 2006-2017 Newsbeuter contributors
    Copyright (C) 2017 Newsboat contributors

    newsboat is free software and licensed under the MIT/X Consortium License.
    Type `newsboat -vv' for more information.

    newsboat 2.10.1
    System: Linux 4.13.8-1-ARCH (x86_64)
    Compiler: g++ 7.2.0
    ncurses: ncurses 6.0.20170902 (compiled with 6.0)
    libcurl: libcurl/7.56.0 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.18.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1 (compiled with 7.56.0)
    SQLite: 3.20.1 (compiled with 3.20.1)
    libxml2: compiled with 2.9.5

Steps to reproduce the issue:

1. Subscribe a Chinese RSS, like http://feed.williamlong.info/

2. Load that RSS

3. Open one article. You will fine garbage characters at the end of some lines. Some contents are lost too.

**Other info you think is relevant**:

Please see screenshots.

Image below is newsboat's screenshot. You can find garbage characters near line endings. Some contents are lost too. You may notice there are several empty lines after garbage characters. Actually no empty lines shall be here. Some contents are lost, leaving empty lines.

![Newsboat Screenshot](https://user-images.githubusercontent.com/1992391/32096656-b3f60152-bacc-11e7-9c2b-9d7435f5357e.png)

Image below is the original article's screenshot. You can compare it with Newsboat's screenshot and you will find some contents become garbage characters and some are lost.

![Original Article](https://user-images.githubusercontent.com/1992391/32096721-e64db9e2-bacc-11e7-8eea-75e7104adfc1.png)

[The link to the article](http://www.williamlong.info/archives/5138.html)

**Comment by NoSuck** [comment]
I am affected by this bug, as well.  As a temporary work-around, resizing the terminal emulator window sometimes results in such lines reappearing (and disappearing).

**Comment by Minoru** [comment]
Don't have time to reproduce this and triage it properly, but my first guess is that [`textformatter::wrap_line()`](https://github.com/newsboat/newsboat/blob/100cbb36fd9ee161195de80a1323a6e1de9cb2b6/src/textformatter.cpp#L67) is forced to split strings at window boundary and accidentally cuts Chinese characters in two.

**Comment by dennisschagt** [comment]
I can reproduce this issue with newsboat r2.10.1 (bottom) but it seems no longer reproducable with newsboat r.2.19 (top).
![image](https://user-images.githubusercontent.com/4629607/82900341-aa3aa880-9f5c-11ea-8f29-e2a5ce166bef.png)

The screenshot shows that the first sentence is split in the middle of the [`变` grapheme](https://graphemica.com/%E5%8F%98), resulting in just the byte `0xE5` which is in my case shown as `å`.
![image](https://user-images.githubusercontent.com/4629607/82901552-65b00c80-9f5e-11ea-9adc-87e81f0703b6.png)

git bisect shows that this issue got resolved in https://github.com/newsboat/newsboat/commit/6de1a2b67305e7a6fef2dc7f92d2a2483673b9b2 (PR https://github.com/newsboat/newsboat/pull/76).

**Comment by Minoru** [comment]
Thanks! I retro-updated the changelog to reflect this.
