### ISSUE TITLE
Newsboat clears feed on auto-reload

### ISSUE THREAD

**Issue by zaowen** [newsboat/newsboat#384]
newsboat r2.13-298-g33f7 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat r2.13-298-g33f7
System: Linux 4.19.6_1 (x86_64)
Compiler: g++ 8.2.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.62.0 LibreSSL/2.8.2 zlib/1.2.11 libssh2/1.8.0 nghttp2/1.34.0 (compiled with 7.62.0)
SQLite: 3.26.0 (compiled with 3.26.0)
libxml2: compiled with 2.9.8
Steps to reproduce the issue:

1. Place any rss feed in url file.

2. Set `auto-reload` to yes and `reload-time` to anything (perferably 1 )

3. Go to any article, press down once, and wait for the reload to occur ( rarely it doesnt occur when no commands have been issued to the article)

4. After the update is complete the date will be **Wed, 31 Dec 1969 17:00:00 -0700** (Unix time 0), and the article will disappear. The Urls will still be there though, and the urlviewformaction will still work.

The program will still function perfectly well after exiting the null article, although if no keys had been pressed before the article disappears and the article was a new one, it will still be marked as new when you return to the feed.

**Comment by Minoru** [comment]
Yep, this is a long-standing bug, known since Newsbeuter: https://github.com/akrennmair/newsbeuter/issues/534 I thought I understand what's going on, but now it seems like I really don't.

**Comment by Minoru** [comment]
Fixed by #386.
