### ISSUE TITLE
Feeds are not correctly rendered when terminal window is resized

### ISSUE THREAD

**Issue by Busyvar** [newsboat/newsboat#389]
Hi,

It seems feeds are not completely displayed when terminal is resized.
text lines can be outside of window.
Maybe SIGWINCH(28) signal can trigger update of html rendering ?

BR.

**Comment by Minoru** [comment]
Reproduced with 2.13 and 9aaa83f741cd8bc5dea96ed790938c8f8e6353cf.

I opened #390 with some pointers on how to fix it in ItemViewFormAction and throughout the rest of the application.

Thanks for the report, @Busyvar!
