### ISSUE TITLE
Articles not loading URL with w3m browser command (only tested with craigslist articles)

### ISSUE THREAD

**Issue by rasputozen** [newsboat/newsboat#400]
newsboat 2.13.0
System: Linux 4.19.12-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20180831
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.35.1 (compiled with 7.61.1)
SQLite: 3.26.0 (compiled with 3.25.2)
libxml2: compiled with 2.9.8

Steps to reproduce the issue:

1. In config, put the line 'bind-key browser "w3m %u"'

2. Attempt to open craigslist article using new browser command.

3. Find that it hangs with "HTTP/1.1 200 OK" at the bottom and blinking cursor at the top left.  You will then have to press Ctrl-C in which you will be shown "Transfer Interrupted!" at the top.  Repeat step 2-3 indefinitely.

**Comment by rasputozen** [comment]
This seems to only occur with craiglist articles.  Other articles seem to work fine.

**Comment by zaowen** [comment]
Would you be able to post a feed where this bug occurs?
Are you sure 
```
bind-key browser "w3m %u"
```
is the correct contents of the config file?

**Comment by Minoru** [comment]
Hi @rasputozen!

I reproduced this with current `master` (https://github.com/newsboat/newsboat/commit/39dc05e8b7c57256f228b11d93baaafb38c57bb2), but I also see this if I run w3m directly in the terminal, e.g.:

```shell
$ w3m 'https://amsterdam.craigslist.org/acc/d/accounts-receivable-billing-accountant/6772329518.html'
```

Thus I believe this is w3m's bug, not Newsboat's, and closing this issue. Please report this to w3m developers.


My setup:
* Newsboat r2.14-15-g39dc05
* Newsboat config:
    ```
    browser "w3m %u"
    ```
    (`bind-key browser "w3m %u"` is not valid syntax, and Newsboat won't even start if I put that in config. I assume you meant what I use, above)
* Newsboat urls file:
    ```
    https://amsterdam.craigslist.org/search/acc?format=rss&lang=en&cc=gb
    ```
    (At the time of writing that feed contains one item, with a link I used in w3m call above.)
* w3m version w3m/0.5.3+git20190105, options lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,w3mmailer,nntp,gopher,ipv6,alarm,mark,migemo
