### ISSUE TITLE
Can't Download podcast with Qustion mark in title onto Fat Drive

### ISSUE THREAD

**Issue by zaowen** [newsboat/newsboat#416]
newsboat r2.14-4-g04f6 

Steps to reproduce the issue:

0. Set download location in config to a mounted, FAT formatted drive.

1. Add https://isitkino.podbean.com/feed.xml to url. Podcasts name is "Is it Keno?"

2. go to any episode and enqueue it.

3. Download will fail.

It took me a while to find out why it was failing since the error message given is "failed"
It might be a good idea to make sure Reserved Characters cant appear when trying to save to a drive that has them.

**Comment by Minoru** [comment]
The error message should be expanded with an explanation. "Couldn't create the file" is still better than "failed".

I don't think it's Newsboat's business to know which characters are allowed on a given filesystem. it shouldn't even care about filesystems; only paths.

Newsboat only runs on Unix-y systems, where FAT is only used for UEFI ESP and on USB drives (for greater compatibility), so this is a really unexpected bug to me. I'm clearly missing some use-case. Can you tell me about how you ran into this, @zaowen?

**Comment by zaowen** [comment]
I dual boot linux/Windows, and I have a exFAT formatted drive that i use for storing Podcasts so that I can reach them from both OSes.

**Comment by Minoru** [comment]
Sorry, but I don't think we can provide a solution for that in Podboat. I understand this breaks your workflow, and I feel awful doing this, but it's really not Podboat's job to know what characters are allowed on a given file system.

I considered adding URL-encoded versions of everything—feed title, episode title etc.—but that will double the number of formats for not too good a reason.

I think the best you can do is to download into your home directory, and use cron to copy/move to exFAT under a "clean" name. You might need to add a symlink on the old location, so the file can be played back in Podboat.

Once again, I apologize for not solving this within Podboat, but I hope you find my reasoning sound.

**Comment by Minoru** [comment]
Yes, gladly!

>
