### ISSUE TITLE
Number of redirects hit maximum amount 

### ISSUE THREAD

**Issue by ettom** [newsboat/newsboat#420]
**Newsboat version:
newsboat r2.14-30-gb34712
Steps to reproduce the issue:
1. Add this url to the urls file. - https://foorum.hinnavaatlus.ee/smartfeed.php?feed_type=RSS2.0&limit=1%20DAY&sort_by=standard&max_word_size=All

2. Try to reload the feed.

The feed doesn't load and I get this error:
USERERROR: Error while retrieving https://foorum.hinnavaatlus.ee/smartfeed.php?feed_type=RSS2.0&limit=1%20DAY&sort_by=standard&max_word_size=All: Number of redirects hit maximum amount

I can see the feed from the browser, by curl and it also works in another feed reader (liferea).

**Comment by Minoru** [comment]
Apparently that site gives different results depending on the user agent. If I run:

```shell
$ curl \
    --verbose \
    'https://foorum.hinnavaatlus.ee/smartfeed.php?feed_type=RSS2.0&limit=1%20DAY&sort_by=standard&max_word_size=All'
```

I see 200 OK and a feed. But if I run:

```shell
$ curl \
    --verbose \
    --user-agent 'newsboat 2.14' \
    'https://foorum.hinnavaatlus.ee/smartfeed.php?feed_type=RSS2.0&limit=1%20DAY&sort_by=standard&max_word_size=All'
```

I'm getting 302 Moved with a redirect to login.php page.

To get around this, change Newsboat's user agent string by adding the following to your config ([docs](https://newsboat.org/releases/2.14/docs/newsboat.html#user-agent)):
```
user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

You can pick any other string, of course, but a UA from a real browser is most likely to work.

Consider asking that forum's administrators to add Newsboat to their whitelist. We aren't too popular, but we aren't too obscure either :)

There's nothing else we can do about the issue, so I'm going to close it. Hope the above recipe helps.
