### ISSUE TITLE
download-path has no effect

### ISSUE THREAD

**Issue by lhanson** [newsboat/newsboat#429]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.14.0
System: Linux 4.20.4-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.0 libpsl/0.20.2 (+libidn2/2.1.0) libssh2/1.8.0 nghttp2/1.35.1 (compiled with 7.63.0)
SQLite: 3.26.0 (compiled with 3.26.0)
libxml2: compiled with 2.9.8
```

**Steps to reproduce the issue:**

1. Create config file at `~/.config/newsboat/config` containing the following:
```
download-path "~/.local/share/podcasts"
```
2. Create urls file at `~/.config/newsboat/urls` containing the following:
```
https://feeds.pacific-content.com/commandlineheroes
```

3. Run `newsboat`. Press `r` to reload, `Enter` to open the feed, `Enter` to select the first entry, and `e` to enqueue. `qqq` to quit.
 
4. Run `podboat`, press `d` to download the first podcast. After it completes, the downloaded mp3 file shows up in `~`, and not `~/.local/share/podcasts` where I would expect it.

**Comment by Minoru** [comment]
Sorry, I couldn't reproduce this. For me, the file ended up in ~/.local/share/podcasts.

When you run Podboat, it displays the path where the file will be stored, e.g.:

```
 4 [   0.0MB/   0.0MB] [  0.0 %] [   0.00 kb/s] queued               https://tracking.feedpress.it/link/18442/10987254/7a9b329b.mp3 -> /home/minoru/.local/share/podcasts/7a9b329b.mp3
```

Here you can see the path is correct. Can you check if your Podboat displays the correct path too?

Also note that `download-path` is applied at enqueueing time, not downloading time; if you change the setting, the previously enqueued podcasts will still be downloaded to the old location.

**Comment by lhanson** [comment]
> Also note that download-path is applied at enqueueing time, not downloading time; if you change the setting, the previously enqueued podcasts will still be downloaded to the old location.

That was my issue. I didn't realize that Podboat displays the path where the file will be stored because it apparently gets cut off unless I make my terminal really wide:

![image](https://user-images.githubusercontent.com/273533/52028442-a6b42000-24d4-11e9-8d85-c6177d6e932e.png)

Thanks for the help!
