### ISSUE TITLE
Dialog-selection window doesn't honor keybindings

### ISSUE THREAD

**Issue by foxdevilwild** [newsboat/newsboat#431]
**Version**:
commit 56c1dc4f on master

**Steps to reproduce the issue**:
1. In newsboat/config:
```
bind-key k up
bind-key j down
```
2. In newsboat, enter the dialog-selection menu (default key 'v'). Newsboat does not honor to the previously configured keys - instead navigation only works with the arrow-keys and pgup/pgdn.

**Additional information**:
I have tracked this issue down to a missing call to `View::set_bindings` when creating the `DialogsFormAction` in `view.cpp`. Unless there are reasons for this that I don't know of, it appears to be a simple oversight.

I have created a patch and will open a PR referencing this issue.

**Comment by Minoru** [comment]
Yep, this does look like an oversight. Thank you for the nice report and the fix, @foxdevilwild!
