### ISSUE TITLE
'%>' doesn't work in podboat.

### ISSUE THREAD

**Issue by foxdevilwild** [newsboat/newsboat#434]
**Newsboat version**:
```
newsboat r2.14-52-gd17ca
System: Linux 4.15.0-45-generic (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4
```

**Steps to reproduce the issue**:
1. In `newsboat/config`:
`podlist-format "left-text %>  right-text"`

2. In podboat: the text is not formatted as expected.

**Additional information**:
I traced the issue to `pbview.cpp:82`, where `width` is always set to 0. Sadly, I'm unfamiliar with stfl and unable to provide a fix at this moment.

**Comment by Minoru** [comment]
Thanks a lot for the `pbview.cpp:82` pointer—I feel like I hit the ground running thanks to it.

There were two bugs there. I fixed both in #435. @foxdevilwild, can you compile that and confirm it works?
