### ISSUE TITLE
Internationalization in Rust code

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#443]
The moment we start porting anything more involved than `utils`, we run into user-visible messages; #413 is an example of this. These messages are currently translated using gettext, which is the standard and overwhelmingly popular tool for the job.

We can request gettext translations from Rust using [gettext-rs](https://crates.io/crates/gettext-rs), but we then run into another problem: some of those strings contain printf-like placeholders like "%s", which are different from Rust's native format. There is no native Rust facilities to format such strings. We will have to port `strprintf::fmt` from C++ to Rust; it will call C's `snprintf`.

We could roll our own, pure-Rust implementation of `snprintf`, but I don't see any benefit in doing that.

Alternatives are:
1. convert all placeholders to Rust's `{}`, and route formatting through Rust. Pros: far easier formatting in Rust. Cons: no native formatting facilities in C++. Essentially, the problem will just get reversed.
2. abandon gettext in favour of [Fluent](https://github.com/projectfluent/fluent-rs), which I never heard of before. Fluent's syntax looks much closer to Rust's, but there are no bindings for C++; so again, formatting will have to be routed through Rust. Benefits unclear.

Does anyone spot any gaps in my thinking? Are there alternative solutions? Is the problem just in my head?

**Comment by Minoru** [comment]
After sleeping on this, Fluent doesn't seem nearly as attractive. I think we already got our plate full, and trying out yet another new technology is too risky. Let's stick to gettext for now, and fix its "unnaturalness" later when our code is mostly Rust.

I'll keep this issue open to collect other alternatives we might use; just note we won't do this right away.

**Comment by Minoru** [comment]
I looked through all PO files (and POT as well), to see what formats we use:
* `%s`
* `%d`
* `%u`
* `%i`
* `%.2f`

Replacing those with `{}` and calling `format!` looks pretty viable, but we will have to be careful about new messages—they will have to only use specifiers from the list above.

I don't mean to go that route yet, though. I'll go work on #447 first.

**Comment by Minoru** [comment]
While working on #447, I lost faith a couple times, and branched out to think though—and sometimes even explore—some alternatives. I don't expect this to be of much use since I'm finished with #447 already, but it seems like a waste to let all of this be forgotten.

Let's recap the problem: we have a number of internationalized strings stored in gettext files. These strings contain printf format specifiers like `%i`. We use `snprintf` to replace those with actual values. We have a wrapper that only lets certain types through, sometimes converting them (e.g. `string` becomes `const char*`).

Now we also have Rust code that need to print out the same strings. There are a couple of approaches we could take:
1. port the wrapper we have from C++ to Rust;
2. replace all printf-style specifiers with Rust-style ones, and use Rust's machinery to format them;
3. write a pure Rust implementation of sprintf;

## Port the `strprintf::fmt` wrapper from C++ to Rust

That's the approach outlined in #447.

The main downside is that we can't share the implementation, since it relies on language features that can't be thrown over FFI (variadic templates in C++, traits and generics in Rust). We'll have to keep two parallel implementation.

The upsides are: it's relatively easy to implement, we already know that it works well in C++, and the heavy lifting is delegated to `snprintf` from both C++ and Rust—we can expect that aside from bugs in wrappers, the formatted strings will always look the same.

## Replace printf specifiers with Rust ones

Replacement could happen either at run-time, or in gettext files themselves. Runtime replacement is suboptimal because any unanticipated format won't be replaced, resulting in incompletely formatted strings (and no compile-time errors to tell us about them!). Changing files themselves increases burden on translators—they'll need to update both C++- and Rust-style translations.

Ultimately, this approach was abandoned because `format!` macro only accepts literals for format strings. To format a `&str`, we'll have to use [runtime-fmt crate](https://crates.io/crates/runtime-fmt), which requires nightly Rust—absolutely impractical because it will turn majority of users off.

## Write a pure Rust implementation of `sprintf`

That would probably be an ideal approach from technical viewpoint: we get to keep the existing strings, and we don't ever need to touch the dreaded FFI (e.g. I managed to corrupt the heap by not resizing a Vec—I'll probably write a blog post about that later, just for the laughs).

However, this is a non-trivial undertaking.

For one, parsing specifiers requires a bit of tedious work on a parser, but this can be done; I wrote a simplistic one that only parsed precision and the format specifier itself.

But actually formatting the values is where the pain comes in. Integers are easy, but floating-point numbers have requirements on the length of exponent and default number of digits in mantissa. Those requirements don't align with `format!`'s, and there are no easy way to re-define them. There are no crates that could do the formatting for us. Writing our own formatter requires diving into some scary-looking arithmetic. Splitting and reconstructing the string returned by `format!` is brittle and will drive performance into the ground.

I believe writing a pure Rust implementation of `sprintf` is a worthwhile undertaking, but I don't think we should do it as part of Newsboat rewrite; that's too much of a distraction.

**Comment by pickfire** [comment]
@Minoru Is [project fluent](https://projectfluent.org/) in consideration? I wonder what is your opinion on that.

**Comment by Minoru** [comment]
I considered it; please see the first two comments in this thread.
