### ISSUE TITLE
Support Miniflux API

### ISSUE THREAD

**Issue by kenokenobingo** [newsboat/newsboat#448]
Enable syncing with self-hosted [Miniflux](https://miniflux.app/#features) apps like it is done with Tiny Tiny RSS.

**Comment by Minoru** [comment]
My stance hasn't changed [late since 2017](https://github.com/newsboat/newsboat/issues/78#issuecomment-351773815): I'd merge a pull request adding this. Thanks for the issue, @kenokenobingo!

**Comment by kenokenobingo** [comment]
Ah, thanks! I’m new to Miniflux as well, but didn’t want to install Tiny Tiny RSS.
