### ISSUE TITLE
Crashing whenever reloading feeds.

### ISSUE THREAD

**Issue by suroa** [newsboat/newsboat#451]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.14.1
Steps to reproduce the issue:

1. Open newsboat

2. Reload feeds

3. Crash with error "newsboat: http2.c:498: drain_this: Assertion `httpc->drain_total >= data->state.drain' failed. Aborted (core dumped)"

**Other info you think is relevant**:
This is happening on an up to date ArchLinux system. My config is the following: http://dpaste.com/08XNZHE.txt
My feeds:
http://dpaste.com/27Q2GK6.txt

**Comment by Minoru** [comment]
Hi! Thank you for the report! I'm going to sleep now and will look at this in about 18 hours. The error looks like it comes from CURL. Here are a few suggestions to narrow the problem down:

1. please post the whole output of `newsboat -v` so I can see the Curl version;
2. try deleting half the feeds from the urls file, and see if the problem persists. Keep at it until you narrow it down to a single URL that still causes the crash. You might find that *any* URL crashes it, or maybe it's some particular site that's causing this;
3. when you have a URL that you know crashes Newsboat, try it with command-line Curl to see if it will crash too;
4. the config doesn't seem to contain anything relevant, but try moving it aside and reloading without it.

**Comment by polyzen** [comment]
https://bugs.archlinux.org/task/61806
Fixed by: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/curl&id=ef420575983d2c3f2eb1069dd4ed2dcc7fe3af27

**Comment by suroa** [comment]
Closing this as what @polyzen said was right. Thanks for the answer btw!

**Comment by Minoru** [comment]
I believe there should be a "Close Issue" button next to "Comment" button. Anyway, I'm glad the problem got resolved quickly!
