### ISSUE TITLE
Unbind-key -a makes using cmdline, search, and goto-url impossible

### ISSUE THREAD

**Issue by dkmestre95** [newsboat/newsboat#454]
[Output of newsboat -v]
newsboat r2.14.1-8-gf03c - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat r2.14.1-8-gf03c
System: Linux 4.20.10-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.64.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.0 nghttp2/1.36.0 (compiled with 7.64.0)
SQLite: 3.27.1 (compiled with 3.27.1)
libxml2: compiled with 2.9.9

[Recreating the Issue]

I edited the config file and unbound all default keybindings with "unbind-key -a"
I then added keybindings for all relevant keys, including ENTER and ESC (For open and quit respectively)
However, upon loading newsboat and starting the cmdline (using ':' ), there is no way to actually send that command to newsboat. Pressing ESC does nothing as well.

[Other Details]
With default keybindings, if I open the command line and enter an invalid command (and use ENTER to send it through), newsboat will tell me it's not a valid command. Upon pressing ESC, I can cancel out of that dialog. However unbinding all keys removes those functionalities, even if I rebind ENTER and ESC back to open and quit respectively.

I have not been able to get it working by tweaking what commands ENTER and ESC are bound to. I also tried tweaking what specific dialogs I unbound all keys from, and I found that only if I unbind keys from "feedlist" can I recreate this issue. Unbinding keys from any of the other dialogs does not recreate the issue. However, even when I specifically bound the ENTER and ESC keys to open/quit in the feedlist dialog, the issue persists.

All of the above issues apply also doing anything in newsboat that requires you to manually type/enter something, such as searching and goto-url.

**Comment by kmws** [comment]
Thank you for the report.

Looks like the problem is within a territory of my feature. I will hopefully take a look in a few days.

**Comment by Minoru** [comment]
I ended up testing this as well, here's reproduction steps for future reference:

1. create Newsboat config with the following:

    ```
    unbind-key -a
    bind-key : cmdline
    ```

2. start Newsboat with that config;
3. press `:` to enter command line;
4. press Esc to leave command line.

The expected behaviour is for ":" at the bottom of the screen to disappear. The actual behaviour: colon doesn't disappear, all further keystrokes are entered into the command line.
