### ISSUE TITLE
Segfaults when toggling article's "read" status after marking all articles read

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#473]
> Also, I might have found a bug.
> With "show-read-articles no" enter a feed with articles then execute mark-feed-read followed by toggle-article-read.
> This causes a segfault, assuming that because no articles are left something goes way wrong.

_Originally posted by @sassmann in https://github.com/newsboat/newsboat/pull/472#issuecomment-477036154_

**Comment by Minoru** [comment]
I couldn't reproduce this exactly, but with slightly different steps I did get a segfault.

newsboat r2.15-41-g423b - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `./newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat r2.15-41-g423b
System: Linux 4.19.0-2-amd64 (x86_64)
Compiler: g++ 8.3.0
ncurses: ncurses 6.1.20181013 (compiled with 6.1)
libcurl: libcurl/7.64.0 GnuTLS/3.6.6 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3 (compiled with 7.64.0)
SQLite: 3.27.2 (compiled with 3.27.2)
libxml2: compiled with 2.9.4

The config is:
```
show-read-articles no
```

I used https://destinationlinux.org/feed/mp3/ as a feed, but that shouldn't matter.

Reproduction steps:
1. enter feed;
2. press `A` to mark all items read;
3. press `N` (ostensibly toggling the item's read status, but there are no item visible, and none appears after toggling);
4. press `q` to exit the feed. Note it now has one unread article in it;
5. enter the feed again.

Newsboat will segfault. Stacktrace points into the bowels of STFL (I need to install debug symbols to get a useful trace).

**Comment by Minoru** [comment]
@sassmann, did you hit this bug when on `master` branch?

**Comment by sassmann** [comment]
yes, on master.

**Comment by dennisschagt** [comment]
I can reproduce it on 2.14.1 but can no longer reproduce this on the latest version of Newsboat

Git bisect points to https://github.com/newsboat/newsboat/commit/c535b1c5f89dd76e4cc450e19cc53433c92b013e (https://github.com/newsboat/newsboat/pull/608).
