### ISSUE TITLE
RHEL7.x - error: no matching function for call to ‘std::vector<std::pair<std::basic_string<char>

### ISSUE THREAD

**Issue by a-wilkinson** [newsboat/newsboat#477]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

$git show |head -1
commit 7bd1cd1ac5e11b258fcdd166ce7967b6a0250303

Steps to reproduce the issue:

1.  $cd git/newsboat

2. make

g++ -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.15-48-g7bd1\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c     -o src/listformatter.o -c src/listformatter.cpp
src/listformatter.cpp: In member function ‘void newsboat::ListFormatter::set_line(unsigned int, const string&, unsigned int, unsigned int)’:
src/listformatter.cpp:59:25: error: no matching function for call to ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::insert(std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator, std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator, std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator)’
    formatted_text.cend());

src/listformatter.cpp:59:25: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from include/listformatter.h:7,
                 from src/listformatter.cpp:1:
/usr/include/c++/4.8.2/bits/vector.tcc:107:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, const value_type&) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*; std::vector<_Tp, _Alloc>::value_type = std::pair<std::basic_string<char>, unsigned int>]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8.2/bits/vector.tcc:107:5: note:   candidate expects 2 arguments, 3 provided
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from include/listformatter.h:7,
                 from src/listformatter.cpp:1:
/usr/include/c++/4.8.2/bits/stl_vector.h:988:7: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*; std::vector<_Tp, _Alloc>::value_type = std::pair<std::basic_string<char>, unsigned int>]
       insert(iterator __position, value_type&& __x)
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:988:7: note:   candidate expects 2 arguments, 3 provided
/usr/include/c++/4.8.2/bits/stl_vector.h:1005:7: note: void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::initializer_list<_Tp>) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*]
       insert(iterator __position, initializer_list<value_type> __l)
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:1005:7: note:   candidate expects 2 arguments, 3 provided
/usr/include/c++/4.8.2/bits/stl_vector.h:1023:7: note: void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<std::basic_string<char>, unsigned int>*; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = std::pair<std::basic_string<char>, unsigned int>]
       insert(iterator __position, size_type __n, const value_type& __x)
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:1023:7: note:   no known conversion for argument 1 from ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator {aka __gnu_cxx::__normal_iterator<const std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >}’ to ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::iterator {aka __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >}’
/usr/include/c++/4.8.2/bits/stl_vector.h:1044:9: note: template<class _InputIterator, class> void std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::iterator, _InputIterator, _InputIterator) [with _InputIterator = _InputIterator; <template-parameter-2-2> = <template-parameter-1-2>; _Tp = std::pair<std::basic_string<char>, unsigned int>; _Alloc = std::allocator<std::pair<std::basic_string<char>, unsigned int> >]
         insert(iterator __position, _InputIterator __first,
         ^
/usr/include/c++/4.8.2/bits/stl_vector.h:1044:9: note:   template argument deduction/substitution failed:
src/listformatter.cpp:59:25: note:   cannot convert ‘((newsboat::ListFormatter*)this)->newsboat::ListFormatter::lines.std::vector<_Tp, _Alloc>::cend<std::pair<std::basic_string<char>, unsigned int>, std::allocator<std::pair<std::basic_string<char>, unsigned int> > >()’ (type ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::const_iterator {aka __gnu_cxx::__normal_iterator<const std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >}’) to type ‘std::vector<std::pair<std::basic_string<char>, unsigned int> >::iterator {aka __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, unsigned int>*, std::vector<std::pair<std::basic_string<char>, unsigned int> > >}’
    formatted_text.cend());
                         ^
make: *** [src/listformatter.o] Error 1

**Other info you think is relevant**:

OS:   Red Hat Enterprise Linux Server release 7.6 (Maipo)
Kernel:  3.10.0-862.14.4.el7.x86_64

**Comment by Minoru** [comment]
It appears that you're using GCC 4.8.2, which has limited C++11 support. Sorry, but version 4.9 (or newer} is required to build Newsboat.
