### ISSUE TITLE
Quiet feeds (Automatically mark new articles in a feed as read)

### ISSUE THREAD

**Issue by Sermak-GIT** [newsboat/newsboat#482]
I'd like you to reconsider [a previous statement](https://github.com/newsboat/newsboat/issues/452#issuecomment-466138659):
> I can't agree that marking something a user didn't read as read is correct, so I'm slightly against such a feature.

Imagine using a website such as Hacker News, 4chan, TED or certain subreddits. These websites have an enormous amount of entries each day, most of which one does not care about. My usual behavior when using such websites consists of consciously opening the page (feed), reading a couple posts (articles) and then closing the feed. It does not matter if I miss some post in between. For me, it would be completely meaningless to know how many unread posts there have been since I last visited. Because I sort my feeds by number of unread articles, such websites take an unnecessary first spot. To summarize: I'm making a conscious decision when browsing a certain service habitually, i.e. reading the news every morning, so there is no need to constantly remind me all day that I have not read the entire newspaper yet.

I don't want to kill old articles after a certain time, because I still want to be able to query them, i.e. if someone recommends me to read a certain article.

I tried hacking together something using `notify-program` (for each unread feed uf, if it is in a muted-feeds file, execute `echo ":goto ${uf}Aq" | newsboat`), but I was not able to get this to work consistently. When also considering the fact that this only works when newsboat is closed (I usually keep it open in the background), my script becomes completely unusable. It would be amazing if there was a native solution for this. (maybe another magical symbol similar to the tilde in the url file?)

**Comment by Minoru** [comment]
I edited your post to add a link to my statement, so other people reading this can get some context.

Don't hesitate to comment on closed issues. They can be re-opened if need be.

Regarding your use-case:
* what do you think about a query feed with `age > 1` that I suggested in #452?
* why don't you just press `A` ("mark all items read") when you're done with the feed?

**Comment by Sermak-GIT** [comment]
> what do you think about a query feed with age > 1 that I suggested in #452?

If I applied this filter when entering a feed, all old articles would be hidden, meaning that I can not find them by searching. More relevantly, this misses the point.

> why don't you just press A ("mark all items read") when you're done with the feed?

Let me re-state my issue: Some feeds, for example my news feed, have new articles every 10 minutes. newsboat then pushes these feeds to the very top. When I open newsboat, I need to spend half a second of frustration mentally iterating over the first few feeds to find the actually interesting ones. I know my news feeds exist, I just don't want to be reminded of it every 10 minutes. I guess pinning a feed to the bottom would also solve this. (Yes, I know that this is a first world problem combined with severe autism).

**Comment by Minoru** [comment]
Sorry for a very delayed reply, but it took me a long while to think this through. I believe I got the gist of the problem now: there is a feed that produces a lot of content, and you:
* want to archive it all;
* want to check on it whenever you want, consuming only as little as you feel like at the time. *There is no intent to consume it all*;
* want that feed not to distract you from other, smaller, slower-paced feeds.

I still maintain a belief that Newsboat shouldn't mark anything read unless explicitly told so by the user. Luckily, it doesn't have to. Your use-case can be implemented with tags:
1. tag your "firehose" news feed with some tag;
2. tag the rest with some other tag;
3. use `t` key to switch between "normal" and "firehose" feeds. This keeps the "firehose" out of the way, while also archiving all of its contents and letting you browse through it at any time.

Does that sound reasonable?

**Comment by Minoru** [comment]
Closing this because the question appears to be answered.
