### ISSUE TITLE
print-unread doesn't take killfiles into account (if ignore-mode is "display")

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#484]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 86097d60a143dd87e700586b2609a679ba7082dc

Steps to reproduce the issue:

1. Add https://newsboat.org/news.atom to urls file (here's [a copy](https://github.com/newsboat/newsboat/files/3065171/news.atom.gz), for reproducability's sake)

2. Configure Newsboat to ignore articles that have the word "fails" in the title:

    ```
    ignore-article "*" "title =~ \"fails\""
    ignore-mode "display"
    ```

3. Start Newsboat and load the feed. Observe there are 11 unread articles in it. Quit Newsboat.

4. Run `newsboat -x print-unread` and observe the output:

    ```
    12 unread articles
    ```

**Other info you think is relevant**:
This doesn't happen if `ignore-mode` is set to "download", which is expected: "download" mode simply doesn't store the articles in the DB.

The root of the problem is that `print-unread` doesn't take killfiles into account, running [a simple SQL query instead](https://github.com/newsboat/newsboat/blob/86097d60a143dd87e700586b2609a679ba7082dc/src/cache.cpp#L1006).

**Comment by Brn9hrd7** [comment]
Is the method get_unread_count in cache.cpp even needed? I just tried replacing `rsscache->get_unread_count()` with `feedcontainer.unread_item_count()` (in controller.cpp) and now print-unread returns the correct values. I'm not really a programmer though, so I'm not sure if this has any disadvantages.

**Comment by Minoru** [comment]
@Brn9hrd7, you're spot on! I committed your solution and will submit it as a PR, to be merged a few days later. You'll be credited in the changelog, of course.

Thank you for figuring this out! (I'm a bit embarrassed I didn't think of this myself, looks so easy in hindsight...)
