### ISSUE TITLE
Feeds show count 0/0 on startup when using `query:...:tags` syntax

### ISSUE THREAD

**Issue by edi9999** [newsboat/newsboat#486]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
newsboat 2.15.0
System: Linux 4.15.0-47-generic (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4
```

Using following URLS : 

```
http://radiofrance-podcast.net/podcast09/rss_16173.xml "!grand_bien" grand_bien
"query:grand_bien_vous_fasse:tags # \"grand_bien\""
http://radiofrance-podcast.net/podcast09/rss_13940.xml "!affaire_sensibles" affaire_sensibles
"query:affaire_sensibles:tags # \"affaire_sensibles\""
http://radiofrance-podcast.net/podcast09/rss_11176.xml "!tel_sonne" tel_sonne
"query:tel_sonne:tags # \"tel_sonne\""
http://radiofrance-podcast.net/podcast09/rss_11549.xml "!epaules_darwin" epaules_darwin
"query:epaules_darwin:tags # \"epaules_darwin\""
https://www.arteradio.com/xml_sound_emission?emissionname=%22UN%20PODCAST%20A%20SOI%22 "!podcast_a_soi" podcast_a_soi
"query:podcast_a_soi:tags # \"podcast_a_soi\""
https://rss.art19.com/tim-ferriss-show "!tim_ferris" tim_ferris
"query:tim_ferris:tags # \"tim_ferris\""
https://rss.art19.com/the-distance-podcast "!the_distance" the_distance
"query:the_distance:tags # \"the_distance\"
https://rss.art19.com/rework "!rework" rework
"query:rework:tags # \"rework\"
```

Steps to reproduce the issue:
![record_2019-04-11_124319](https://user-images.githubusercontent.com/2071336/55951726-3524ea80-5c58-11e9-8ac7-f4133d8307a0.gif)

1. Open newsboat

2. View the feeds in the list, all theses feeds show up a count of 0/0

3. Press enter on the feed, I see some feeds instantly so it means that the entries were already on disk

4. Press q to go back to list, there you see the count that is updated for the feed.

Why is the count not uptodate on startup ?

**Other info you think is relevant**:

All feeds that I have that do not use the `query:...:...` syntax work as expected.

**Comment by Minoru** [comment]
Hi! I'm not sure why, but Newsbeuter (Newsboat's predecessor) didn't populate query feeds on startup; users had to set [`prepopulate-query-feeds` setting](https://newsboat.org/releases/2.15/docs/newsboat.html#prepopulate-query-feeds) to `yes`. Newsboat inherited that behaviour, but if I see a way to get rid of that, I will definitely do so.

**Comment by edi9999** [comment]
Ok, thanks for the fast answer, it works indeed !

It seems strange that this is not the default. I think we could change it safely as the new default even without a major version release, as this is most likely what users expect I think, no ?

**Comment by Minoru** [comment]
Sorry for a delayed response; I hoped to dig up some more details on this option, but failed. There is no apparent reason why the option even exists, but that's how it was designed: when query feeds were implemented, they were populated only on reload. Then out of the blue, an option was added to change that. I would rather not change something I don't understand. Hopefully I'll grok this better during the Rust rewrite, and will have a better answer then.
