### ISSUE TITLE
Highlighting spans more than it should

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#488]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 75622130f42a5686b58651860f3063072b22b62f

Steps to reproduce the issue:

1. Add the following to the config;

    ```
    highlight article "^(Feed|Link):.*$" color6 default bold
    highlight article "^(Title|Date|Author):.*$" color6 default bold
    highlight article "https?://[^ ]+" color10 default underline
    ```

2. Add http://antirez.com/rss to urls file.

3. Reload the feed and open any article.

4. Observe that the first paragraphs of the text are highlighted the same way as the header. Expected behaviour is that just header and links are highlighted.

**Other info you think is relevant**:
This is the first commit where this happens (found with git bisect). The bug is still present in master (cca42583618d09579de15f4c0929c3cd40db9dc2).

**Comment by dennisschagt** [comment]
Looks like this is caused by two rexes matches overlapping on a line like:
```
Link: http://antirez.com/news/131
```

That line is currently converted to the following by `RegexManager::quote_and_highlight()`:
```
<0>Link: <2>http://antirez.com/news/131</></><0>
```

The trailing `<0>` causes the following lines of text to be colored as well.
