### ISSUE TITLE
`include` relative paths

### ISSUE THREAD

**Issue by mjsir911** [newsboat/newsboat#489]
```
$ newsboat -v
newsboat 2.13.0
System: Linux 4.14.83-gentoo (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.64.0 OpenSSL/1.0.2q zlib/1.2.11 (compiled with 7.64.0)
SQLite: 3.25.3 (compiled with 3.25.3)
libxml2: compiled with 2.9.8
```

Right now, to include a file also in my `~/.newsboat` configuration directory, I need to put this in my `~/.newsboat/config` file:
```
include ~/.newsboat/kill
```
It would nice to be able to just specify a relative path to the including config file, ie
```
include kill
```
or
```
include ./kill
```

**Comment by Minoru** [comment]
I think this is a good idea.

What would you expect to happen if an included file contains mode `include` directives? Would they be resolved relative to the "topmost" config, or to the one that contains them? In other words:
* `/home/minoru/.newsboat/config` contains `include ../../joe/settings`;
* `/home/joe/settings` contains `include kills`.

What file should be included — `/home/minoru/.newsboat/kills` or `/home/joe/kills`?

**Comment by mjsir911** [comment]
I would expect includes to be relative to the containing config file: `/home/joe/kills`

The reasoning for this is a single file in a subdirectory could be included `include vimlike/setup` and it would be able to include multiple config files in that directory no matter the name

I think there is ambiguity when including a file that's relative to the application's startup directory. eg
```sh
$ tail ~/.newsboat/config
include test.conf
$ pwd
/tmp/tmp.Zz4bBBqzlA
$ ls 
test.conf
$ newsboat # existing behaviour: newsboat loads the test.conf in the current directory. In any other directory, fails
$ touch ~/.newsboat/test.conf
$ newsboat # which config file does this load?
```

**Comment by Minoru** [comment]
I think both `include kills` and `include ./kills` should resolve relative to the containing config file. If a user wants to include relative to current directory, they can do so with ```include `pwd`/kills```. There is no ambiguity then. How does that sound?

**Comment by mjsir911** [comment]
That sounds pretty reasonable
