### ISSUE TITLE
Is there a way to load an article saved as a txt file?

### ISSUE THREAD

**Issue by f8122dac** [newsboat/newsboat#497]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: `newsboat 2.13.0`

Is there a way to reload the articles from the saved text files?

**Comment by Minoru** [comment]
Hi! No, there is no way to do that. Saving to a text file is more like an export; it's out of Newsboat's hands after that.

Can you describe why you need that, what's your use-case like? Newsboat has many other features, perhaps one of them will suit your needs better.

**Comment by f8122dac** [comment]
Hello there, thanks for a response. I just thought that it would be nice if I could aggregate marked articles into a single buffer. I tried flagging, but I just couldn't figure out how you could list all the flaged articles in a single buffer when the articles that I flagged had different sets of tags. For example, let's say there are a few articles with "news" tag and some other articles with "tech" tag, and they all are flagged with "a". I want to view all of them in a single list. I thought if I could load up all the saved articles, then I could use them for bookmarking, read it later, etc.

**Comment by Minoru** [comment]
>  just couldn't figure out how you could list all the flaged articles in a single buffer when the articles that I flagged had different sets of tags

You can use [query feeds](https://newsboat.org/releases/2.15/docs/newsboat.html#_query_feeds) to achieve that. Add the following to your urls file:

```
"query:Articles flagged \"b\":flags # \"b\""
```

This will add a new feed called *Articles flagged "b"* which will contain—you guessed it!—articles that have a "b" flag. You can add more conditions to narrow it down if need be; see [filter language](https://newsboat.org/releases/2.15/docs/newsboat.html#_filter_language) for details.

**Comment by f8122dac** [comment]
Thanks! This works great!
