### ISSUE TITLE
Appropriate line breaks are not inserted for certain articles

### ISSUE THREAD

**Issue by j605** [newsboat/newsboat#512]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
r2.15-78-g37ca

Steps to reproduce the issue:

The following article shows the error https://blog.debiania.in.ua/posts/2019-05-05-i-underestimated-the-dangers-of-rust-ffi.html

Instead of proper line breaks you see
![2019-05-05 21:39:06](https://user-images.githubusercontent.com/1107327/57199469-77072f00-6f7f-11e9-959e-973182675737.png)

@Minoru thinks `newsboat` is not handling nested spans in the HTML properly.

**Comment by Minoru** [comment]
Reproduced with a8972c6d7e6cdb500861d5bc058c62732387553c. Thank you!
