### ISSUE TITLE
Split "test helpers" into their own .h/.cpp files

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#516]
We have a number of "test helpers" that manage temporary files, create argc/argv pairs, etc. All of this code lives in a single header file, test/test-helpers.h. It grew to 418 lines already, which makes it harder to manage.

Furthermore, including this file into every test increases compilation times, and makes it harder to iterate on new classes when they're added to the header—changing the file forces recompilation of many test files.

To combat that, let's do the following:
1. create a directory test/test-helpers/;
2. move each class from test/test-helpers.h into its own pair of .h and .cpp files, stored under test/test-helpers/;
3. make test/test-helpers.h include just the headers from test/test-helpers/ directory;
4. update the Makefile to build cpp files from test/test-helpers/;
5. re-run `make depslist` to update the dependencies.

This seems like a good first issue, so tagging it as such.

Feel free to ask questions here or on IRC if you get stuck with something!

**Comment by pavellaminar** [comment]
I have a question about point 2 of decision this issue - "move each class into its own pair .cpp & .h ". Is it mean what i must to move implementation of classes methods from .h (like you have in test-helpers.h now) file into .cpp?

**Comment by Minoru** [comment]
Hi! Thanks for working on this!

Yes, just move all the definitions to .cpp. The point of this refactor is to speed up compilation, so let's keep header files as small as possible.

**Comment by pavellaminar** [comment]
I'm ready to make attempt, if you don't mind.

**Comment by Minoru** [comment]
Of course I don't mind! ;) Submit a pull request when ready, I'm always glad to review and help out.

**Comment by Minoru** [comment]
This is fixed by #849.
