### ISSUE TITLE
OPML Import Issues?

### ISSUE THREAD

**Issue by OLYCHORI** [newsboat/newsboat#526]
**newsboat 2.15.0**:

Steps to reproduce the issue:

1. 

> user@desktop
> ~/.config/newsboat/ newsboat -i /home/user/Downloads/feedlist.opml
> Import of /home/user/Downloads/feedlist.opml finished.

2. 

> user@core 
> ~/.config/newsboat/ newsboat                                      
> Starting newsboat 2.15.0...
> Loading configuration...done.
> Opening cache...done.
> Loading URLs from /home/user/.config/newsboat/urls...done.
> Error: no URLs configured. Please fill the file /home/user/.config/newsboat/urls with RSS feed URLs or import an OPML file.

I can load URLs manually in ~/.config/newsboat/urls, but I am unable to import an OPML.

**Comment by OLYCHORI** [comment]
I learned that it loaded it automatically to `/root/.newsboat/urls`, hence my issue.

**Comment by Minoru** [comment]
Glad you've solved it, but I'm still curious what the issue was. You ran `sudo newsboat -i`?

**Comment by OLYCHORI** [comment]
> Glad you've solved it, but I'm still curious what the issue was. You ran `sudo newsboat -i`?

Correct, `sudo newsboat -i `automatically imports to `/root/.newsboat/urls`.  Running `newsboat -i` gives me the following warning:  `I/O warning : failed to load external entity "/home/user/Downloads/feed.opml"
An error occurred while parsing /home/user/Downloads/feed.opml`.

**Comment by colin-i** [comment]
Before using `newsboat -i rss.opml`, `touch ~/.newsboat/urls` else it is: "No such file or directory"
