### ISSUE TITLE
Support concurrent searches within a feed

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#529]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: a85f1dae4ff5b921f5e36ec55f04c5f6baf68e11

Steps to reproduce the issue:

1. Open any feed

2. Search for some term

3. Press `v` to open a list of dialogs, and go back to the item list

4. Search for some other term

5. Press `v` again, and go back to the results of the first search

6. Choose any item, and open it

The expected result is that the item is displayed. The actual result is that an empty item view is displayed, with no title, no body, and a bogus date.

**Other info you think is relevant**:
This happens because both `FeedListFormAction` and `ItemListFormAction` contain an `std::shared_ptr<RssFeed> search_dummy_feed`, which is populated with search results. Naturally, each new search clears the dummy feed, removing the existing results.

A better approach would be to remove `search_dummy_feed`, and create a new empty feed for each search.

Blocked by #527.

**Comment by dennisschagt** [comment]
It looks like this got fixed (I can't reproduce it on current master).

Git bisect points to https://github.com/newsboat/newsboat/commit/c3e972b8a8500359f39f73cfb4466722ba3ef0a4 (part of PR https://github.com/newsboat/newsboat/pull/1088) which seems reasonable.
