### ISSUE TITLE
More entries from RSS feed.

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#537]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.15.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat 2.15.0
System: Linux 3.16.0-4-686-pae (i686)
Compiler: g++ 4.9.2
ncurses: ncurses 5.9.20140913 (compiled with 5.9)
libcurl: libcurl/7.38.0 GnuTLS/3.3.30 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 (compiled with 7.38.0)
SQLite: 3.8.7.1 (compiled with 3.8.7.1)
libxml2: compiled with 2.9.1
```
Steps to reproduce the issue:
1. Add the Youtube channel to URL's and reload the feed.
Example:
https://www.youtube.com/feeds/videos.xml?channel_id=UCz75RVbH8q2jdBJ4SnwuZZQ "~YT:Blender Animation Studio"
2. This will only get 15 last entries.

Is there a way (by some scripting) to pull all the entries from the channel and add them to the RSS feed in Newsboat?

The script part I already have, so I could create local feed in order to have the missing entries. But this will give me two feeds: one with the live records and one with the old local.
Would it be possible to combine these two in one in the current version of Newsboat?

**Comment by j605** [comment]
Feeds are coming from youtube and most websites seem to limit the feed items to the last N items. There is no solution to this unless the publisher makes available the complete RSS feed.

**Comment by Minoru** [comment]
Generally @j605 is right, but the asker already got the old items. All that's left is to re-assign them to the real feed, which can be done with a bit of command-line magic:

```
$ sqlite3 ~/.newsboat/cache.db 'update rss_item set feedurl = "https://www.youtube.com/.." where feedurl = "file:///path/to/local/feed"'
```

`file:///path/to/local/feed` is the URL of the feed with old items, and `https://www.youtube/...` is the URL of the YouTube's real feed.

Make a backup before actually running this, just in case.

Pretty sure this answers the question, so I'm closing the issue. Feel free to comment if it doesn't, I can always re-open this.
