### ISSUE TITLE
Enhancement: One Shot Mode

### ISSUE THREAD

**Issue by cf020031308** [newsboat/newsboat#538]
Hi I'm a heavy user of newsboat.

Recently I wrote a script to get unread feeds from sqlite db and send them to instapaper via mails:

https://github.com/cf020031308/cf020031308.github.io/blob/master/bin/unread-feeds-to-instapaper

The next thing I hope to do is to deploy newsboat to a raspberry pi and run this script with crontab at a specific time everyday.

It will be very handy to make it scheduled if newsboat can have a OneShot Mode or something, in which it fetches all the feeds just once and then quits.

**Comment by j605** [comment]
You can use `newsboat -x reload`.
