### ISSUE TITLE
Homebrew recipe?

### ISSUE THREAD

**Issue by rnkn** [newsboat/newsboat#54]
Can you please add Newsboat to [Homebrew](https://brew.sh)?

For reference, here is the Newsbeuter recipe: https://github.com/Homebrew/homebrew-core/blob/master/Formula/newsbeuter.rb

**Newsboat version (copy from `newsboat -v`)**:
newsbeuter 2.10-7c98
System: Darwin 17.2.0 (x86_64)

Steps to reproduce the issue:

1. see that Newsboat has superseded Newsbeuter
2. try to install Newsboat on macOS via Homebrew
3. see that no recipe is available
4. become sad

**Comment by Minoru** [comment]
It's in the works: https://github.com/Homebrew/homebrew-core/pull/20094

**Comment by Minoru** [comment]
Oh, and I'll close this issue because there's nothing we can do about it in the context of Newsboat. Thanks for asking though!

**Comment by rnkn** [comment]
Cool, thanks 👍
