### ISSUE TITLE
Notify user if the podcast couldn't be renamed

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#545]
After downloading the podcast file, Podboat [tries to rename it](https://github.com/newsboat/newsboat/blob/3320e011ae9004519af8b7e6b6b90bf45565a9e1/src/poddlthread.cpp#L120) to remove the ".part" suffix. However, the return value of that call is never checked; if rename failed, the user won't know.

Problem flagged by Coverity Scan.

**Comment by ATM-SALEH** [comment]
I can pick up this one, if nobody is working on this issue

**Comment by Minoru** [comment]
@nick-cd considered working on this, but he's now busy with #1271, so I guess it's fine if you pick up this one.

**Comment by ATM-SALEH** [comment]
Apologies for responding after a long time. Had a quite busy few weeks.

I had a quick look at this one and have a question

If we get a non-zero return code from [rename](https://linux.die.net/man/3/rename), should we update `status` to some value that indicates error (like, using `dl->set_status(DlStatus::FAILED)`)? Or it should fail silently, without notifying the user?

**Comment by Minoru** [comment]
Hey, no problem! Yes, I think it should set the status to "failed", and display an error message in the status bar at the bottom of the screen.

**Comment by kartikeya100** [comment]
Can I pick it up, if nobody is working on this issue?

**Comment by Minoru** [comment]
Looks like no-one does, so please go ahead @kartikeya100!

**Comment by kartikeya100** [comment]
@Minoru, I was just looking at the code and it seems status line is not yet implemented for podboat. Do I need to implement the interface first or is there any work around available? I am very new to all this code and open source work, if there is any documentation available please let me know as well.

**Comment by Minoru** [comment]
Oh, you probably searched for a `StatusLine` object, but that's not used in Podboat yet. In Podboat, status line is tied to download's status (see https://github.com/newsboat/newsboat/pull/1256), so what you have to do is: depending on the return value of `rename`, either call `set_status(DlStatus::READY)`, or call `set_status` with some different `DlStatus` constant and a string explaining the error. We might not have a good constant for this yet; if so, just add it.

I don't think there's any docs for this, sorry. Looks like previous pull requests, and the source code itself, are the best source of knowledge.
