### ISSUE TITLE
"content" attribute not working inside a query

### ISSUE THREAD

**Issue by qoxxxx** [newsboat/newsboat#548]
newsboat 2.13.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2018 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2018 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat 2.13.0
System: Linux 4.15.0-50-generic (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4

Steps to reproduce the issue:
Add in the "url" file :
`"query:test:content =~ \"test\""`

Is this supposed to work ? It doesn't seem to get anything while `"query:test:title =~ \"test\""` works as expected.

Also, is there a way to set up a query that filter by both title and content, in the same line, without using "or" ?

Thanks.

**Comment by Minoru** [comment]
>Add in the "url" file :
>`"query:test:content =~ \"test\""`
>
>Is this supposed to work ? It doesn't seem to get anything while 
>"query:test:title =~ \"test\"" works as expected.

I think it should work, it looks correct.

>Also, is there a way to set up a query that filter by both title and 
>content, in the same line, without using "or" ?

No, but I see how it could be useful if you have the same regex for both 
title and content. Hmm.

I'm busy until Tuesday, so won't be able to look into this until 
then—sorry.

**Comment by qoxxxx** [comment]
> No, but I see how it could be useful if you have the same regex for both title and content. Hmm.

You currently have to maintain 2 sets of queries :
```
"query:q1_title:title =~ \"foo|bar\""
"query:q1_content:content =~ \"foo|bar\""
```
or 
`"query:q1:(title =~ \"foo|bar\" or content =~ \"foo|bar\")"`

But it's no big deal.

I have a lot of those and I noticed the content attribute doesn't pick anything up, even when it should. Or I think it should, maybe I misunderstood what "content" is.

> I'm busy until Tuesday, so won't be able to look into this until then—sorry.

I'm not in any hurry :)
If it's supposed to work, I'll do some more testing.

**Comment by Minoru** [comment]
>If it's supposed to work, I'll do some more testing.

I *think* it should, but I haven't looked at the code. Maybe it needs 
something like ".*test.*" instead of "test"—I definitely need to look at 
the code and try this out to tell for sure.

**Comment by Minoru** [comment]
I reproduced this with somewhat recent master, 219562131b05a08c20d7b064f19cc3508644d1da. Also found that we already have an issue about this, #111, so I am closing this one as a duplicate. Let's continue the investigation in the other one.

I suspect the items aren't fully loaded, and the "content" attribute is always empty. I'm checking this now.
