### ISSUE TITLE
error[E0308]: match arms have incompatible types

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#552]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

`newsboat-2.16 from the tar archive` 

Steps to reproduce the issue:

1. ./config.sh

2. make

**Other info you think is relevant**:
Here is the error I got:
[log.txt](https://github.com/newsboat/newsboat/files/3328923/log.txt)

**Comment by Minoru** [comment]
Hi! I think this is fixed by #551, which is released already as 2.16.1. Sorry for breaking it in the first place.
