### ISSUE TITLE
Relocating ~/.newsboat to ~/.config/newsboat obviates cache.db

### ISSUE THREAD

**Issue by rowet** [newsboat/newsboat#553]
newsboat 2.14.1

There were some info/warning prints in the console about using ~/.config/newsboat instead of ~/.newsboat. So I moved my config directory there. In the new location newsboat shows no article history at all. The path must be in the schema somehow? Ideally you should be able to relocate cache.db anywhere without losing all the history.

**Comment by Minoru** [comment]
> There were some info/warning prints in the console about using ~/.config/newsboat instead of ~/.newsboat.

What did they say? We didn't change the default location, it's still ~/.newsboat.

> So I moved my config directory there.

With those XDG dirs, files are split between ~/.config/newsboat and ~/.local/share/newsboat. Please see [this section of the docs](https://newsboat.org/releases/2.14.1/docs/newsboat.html#_xdg_base_directory_support) for the exact details.. That should fix it; please comment if it doesn't, and I'll re-open the issue.
