### ISSUE TITLE
Mouse wheel scroll marks items as read

### ISSUE THREAD

**Issue by JindrichPilar** [newsboat/newsboat#567]
## Problem
Scrolling up goes down the list of items and marks unread items as read. I would like to disable this. Preferably only marking unread but entirely disabling scrolling using mouse is also acceptable.

## version
2.15.0

## Steps to reproduce the issue:

- Open newsboat
- Scroll UP using mouse wheel or Touchpad 

## What I tried
I tried disabling key binding and it didn't have any effect.
```
unbind-key wheel-up
unbind-key wheel-down
```

**Comment by Minoru** [comment]
Hi! This is a problem common to all console applications; e.g. I experience the same with Mutt. Wheel movement is turned into repeated Up/Down presses by the terminal, and as far as I know, Newsboat can't influence that.

To make it just scroll without marking as unread, you can set [`mark-as-read-on-hover`](https://newsboat.org/releases/2.16.1/docs/newsboat.html#mark-as-read-on-hover) to "no", but this will also affect your normal scrolling with Up/Down and J/K. There is no way to distinguish wheel scrolling from ordinary keypresses, so there is no way to disable this *just* for the wheel.

Newsboat doesn't have `wheel-up` or `wheel-down` keys, and our config parser simply ignores those two `unbind-key` lines. I'll open an issue to fix that.

Since there is nothing we can do about this issue, I'm closing it; sorry.

**Comment by JindrichPilar** [comment]
Hi @Minoru! Thank you for responding and really quickly at that. 

I just tried ``mark-as-read-on-hover no`` as you suggested and it didn't have any effect - scrolling still marks as read. 

## Current config
My full config if it helps:
```
#Press t to show tags

#External programs
browser "chromium %u || w3m %u"
#macro i set browser "feh %u"; #does not work

# Showing
show-read-feeds yes

#Sorting
feed-sort-order firsttag

#Reloading
refresh-on-startup true
auto-reload true
reload-threads 4
reload-only-visible-feeds no
download-retries 4

# Dark solarized color scheme for newsbeuter, based on
# Ethan Schoonover's Solarized.
#
# In order to use this color scheme, you must first configure
# your terminal emulator to use the Solarized palette.
# See <http://ethanschoonover.com/solarized/> for more information.

color background         default   default
color listnormal         default   default
color listnormal_unread  blue   default
color listfocus          black     yellow
color info               default   black
color article            default   default
color listfocus_unread   black yellow

# highlights
highlight article "^(Title):.*$" blue default
highlight article "https?://[^ ]+" red default
highlight article "\\[image\\ [0-9]+\\]" green default

mark-as-read-on-hover no
```

**Comment by Minoru** [comment]
Hmm. Just tried with your config and Newsboat 2.15, and it doesn't mark anything as read as I scroll. Also doesn't mark anything if I scroll with J and K keys. That's with XFCE Terminal.

Can you check if articles are marked as read when you go through the feed with J and K keys?

**Comment by Minoru** [comment]
@JindrichPilar, ping. Have you been able to try my suggestions from the previous comment?

**Comment by JindrichPilar** [comment]
@Minoru  Thank you for the ping, this issue slipped my mind.

`J`, `K`, `↑`, `↓` don't mark as read. I always use explicit `shift`+`n`.

I tried running it in different emulator (Termite) and scrolling there doesn't mark as read. So it looks like its Alacritty specific problem.

In Alacritty scrolling down marks as read not only articles, but also entire feeds when scrolling on feed list. 

Any idea what could be the problem or should I ask someone on the Alacritty side?

**Comment by Minoru** [comment]
My guess is: scrolling in Alacritty sends not just a sequence of "up"/"down" keypresses, but also some extra stuff that Newsboat interprets as "N". https://github.com/jwilm/alacritty/issues/1228 seems related; maybe try playing with `TERM` environment variable?

**Comment by JindrichPilar** [comment]
Thank you @Minoru. Setting `TERM` to `screen-256color` fixed the issue.
