### ISSUE TITLE
Incorrect feed is displayed in unread feed list

### ISSUE THREAD

**Issue by mrschyte** [newsboat/newsboat#569]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.15.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat 2.15.0
System: Linux 5.1.16-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.65.1 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.36.0 (compiled with 7.64.1)
SQLite: 3.28.0 (compiled with 3.27.2)
libxml2: compiled with 2.9.9

**Steps to reproduce the issue:**

1. Open newsboat and refresh the feed list (have at least 2 unread feeds)

2. Press "l" (lowercase L) to show only unread feeds

3. Go to the last feed and press A to mark it as read

4. Press Enter. The removed feed is displayed instead of the highlighted feed.

5. Press Enter again. Now the correct feed is loaded.

https://asciinema.org/a/GSetrAPkoR5Q2frrxGeQhUNux

**Comment by Minoru** [comment]
Hi! This sounds like a duplicate of #72. Can you check what version of STFL library you have? Can you roll back to STFL 0.23 or earlier and check if the bug persists?

**Comment by mrschyte** [comment]
Hi! I've downgraded to 0.23 and the issue is gone, so it's the same issue. Closing as duplicate. Thanks!
