### ISSUE TITLE
Add CLI argument to set history.cmdline, history.search and pb-lock.pid

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#57]
**Newsboat version (copy from `newsboat -v`)**: 2.10.1

Newsboat got `--cache-file`, `--config-file` and `--url-file` options, which allow the user to run multiple copies of Newsboat with different settings. But [as this post on Newsbeuter mailing list mentions](https://groups.google.com/forum/#!msg/newsbeuter/U878kuJ1eUc/1cvLdokITrUJ), there's no way to set paths to history.cmdline, history.search and pb-lock.pid files.

To make it possible to have completely independent profiles, we should have such options.

it might also make sense to add `--queue-file` to Newsboat.

**Comment by spiridoncha** [comment]
Hi, @Minoru.
Maybe I don't understand something.
history.cmdline and history.search is options for newsboat?
pb-lock.pid and `--queue-file` is options for podboat, right?

**Comment by Minoru** [comment]
> history.cmdline and history.search is options for newsboat?

No, they're files that Newsboat creates next to the cache file and the config. The problem is that you can move cache and config (and then use `--cache-file` and `--config-file` options), but not the history files. I want to add options for history files so that they can be moved, too.

pb-lock.pid is a file created by Podboat. Again, there's no way for user to make Podboat create this file elsewhere. (Maybe there's no need to—this file should always be next to the cache file?)

`--queue-file` is an existing option of Podboat; I just want to copy it to Newsboat, because right now it doesn't make much sense—even though you can ask Podboat to get its queue elsewhere, you can't tell Newsboat to *write* to that other queue.

**Comment by kmws** [comment]
So, new `--history-cmdline` and `--history-search` option names will be added, but what about letters? I think it's important, because once set they will probably be permanent.

**Comment by Minoru** [comment]
I'm not convinced that these new options should have short names at all. Short names are useful for stuff that is tweaked before each run, like log file location and level. History files, not so much.

Let's only add long names for now, and if there is demand for short ones, we'll add them later.

**Comment by CookiePieWw** [comment]
Hi @Minoru, is the issue still active? If so, I'd like to try to work on this.
