### ISSUE TITLE
Parse "media" namespace tags in Atom feeds

### ISSUE THREAD

**Issue by Eucyon** [newsboat/newsboat#595]
In some Atom feeds, e.g. from Youtube, the media namespace is used. It contains important tags like /feed/entry/media:group/media:description. It would be helpful if these were parsed and shown, too.

Example:
https://www.youtube.com/feeds/videos.xml?user=llelectronics

**Comment by Minoru** [comment]
Can't tell anything off-hand. Need to read the spec and think how this fits into Newsboat. Thanks for the suggestion though!

**Comment by Eucyon** [comment]
Thank you for your steady work!

**Comment by azmeuk** [comment]
For the record, [here is the specification](http://www.rssboard.org/media-rss#media-group).
