### ISSUE TITLE
Provide a script to migrate feeds to new URLs

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#601]
(These are notes from IRC.)

@tsipinakis says that he wanted to migrate a number of feeds from HTTP to HTTPS, and had to manually adjust Newsboat's cache.db to match new URLs; otherwise he would've lost the articles he already had. The SQL query he used is:

```
update rss_item set feedurl = replace(feedurl, 'http://', 'https://') WHERE feedurl like 'http://%';
```

He noted that this should be part of Newsboat somehow. I suggested to put that into a script, and ship that with Newsboat. In my mind, the script would take two parameters, the old URL and the new, and adjust the cache accordingly. This would let users migrate not just from HTTP to HTTPS, but also from host to host, and even merge multiple feeds into one.

I don't think this is blocked in any way. Somebody just has to write it, test it, and document it. Tagging as "good first issue" since all the in-depth Newsboat knowledge is already in the SQL query above; what's remaining is learning the ropes.

**Comment by tsipinakis** [comment]
> In my mind, the script would take two parameters, the old URL and the new, and adjust the cache accordingly

That's good for manual adjusting and can be done easily in a quick and dirty python script. So, yeah, really good first issue and would be nice to have either way.

---

For the more power-user side I'd love to see some more advanced maintenance functionality, for example automatically detecting possible protocol upgrades such as `http`->`https` as well as 301 redirects and allowing the user to replace these with a prompt.

If this is done in a third party script it probably would require a partial re-write of the url parser which I'm unsure how much effort that would take. I guess this goes back to #83, if we have choose to migrate to a standard urls format we'd be able to do this much easier without custom parsing code.

**Comment by velaja** [comment]
done: https://github.com/newsboat/newsboat/pull/647

the bash script checks if the new https url returns code 200
it also tests all urls for 301 http codes and updates the urls to their new location
if it gets http codes in the 4xx and 5xx range then it adds the tag "_dead" in the url file

**Comment by Minoru** [comment]
This is done indeed, I just forgot to close the issue.
