### ISSUE TITLE
Use fixed-size types in FFI bindigs

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#619]
While reviewing #618 [I noticed](https://github.com/newsboat/newsboat/pull/618#discussion_r319181520) that we're using `int`s in our FFI bindings, even when the other, Rust side expects a fixed-width type. This is bad, because a mismatch will lead to some surprising behaviour (not sure if underfined or unspecified, but definitely surprising).

Need to read all the files in `libnewsboat-ffi` crate, and replace `int`s and such with fixed-width types (`std::uint32_t` etc.) to match Rust. We can keep `int`/`unsigned int` where it makes sense, but Rust has to be adjusted to use `isize`/`usize` then.

**Comment by rnestler** [comment]
> We can keep int/unsigned int where it makes sense, but Rust has to be adjusted to use isize/usize then.

Don't `isize` / `usize` correspond to `ptrdiff_t` / `size_t` in C++ instead of `int` / `unsigned int`?

**Comment by Minoru** [comment]
Docs for [`isize`](https://doc.rust-lang.org/nightly/std/primitive.isize.html) and [`usize`](https://doc.rust-lang.org/std/primitive.usize.html) say they're "pointer-sized", so that's more like [`intptr_t` and `uintptr_t`](https://en.cppreference.com/w/cpp/types/integer) I guess. Your point is still valid though.

We could probably use [`std::os::raw::c_int`](https://doc.rust-lang.org/std/os/raw/type.c_int.html) and [`std::os::raw::c_uint`](https://doc.rust-lang.org/std/os/raw/type.c_uint.html), but since we'll have to convert those into Rust's native types anyway, it's probably better to use fixed-size types in FFI, and perform all the conversions on C++ side (always upcasting, e.g. `int` turns into `std::int64_t`, even on 32-bit platforms).

**Comment by dennisschagt** [comment]
Is this still necessary, now that we use CXX to specify the interface between Rust and C++?

**Comment by Minoru** [comment]
Nope: the bindings are generated from Rust code which uses fixed-size types. Thanks for noticing, @dennisschagt — I *love* closing issues :)
