### ISSUE TITLE
Port FSLock to Rust

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#633]
We use `FSLock` object to ensure that only one Newsboat instance is working with an SQLite database at a time. The object creates a lock file, writes process's PID into it, and locks the file using POSIX locking (`lockf(3)`).

The class is deceptively simple, but there are a few problems with porting it:
- I have no idea how to test it. We need to either mock `lockf` call, or write some pretty elaborate integration tests
- I don't seem to find any bindings to `lockf` for Rust. We might need to write our own wrapper.

If you're of adventurous sort, take up this issue :) And even if you're unsuccessful, please report what you learn.

**Comment by kpcyrd** [comment]
[fd-lock](https://crates.io/crates/fd-lock) might work.

**Comment by pickfire** [comment]
Looks good, but one think I think not necessary is the dependency on failure crate, which we do not have and not suitable for library. Let me check on that crate.

**Comment by pickfire** [comment]
How about https://crates.io/crates/lockfile and https://crates.io/crates/fs2?

**Comment by Minoru** [comment]
> one think I think not necessary is the dependency on failure crate, which we do not have

[We do depend on it transitively](https://github.com/newsboat/newsboat/blob/af8542480205d9a29fc562c125b65a156a0b3377/Cargo.lock#L868), and the version is compatible, so it's fine.

> How about https://crates.io/crates/lockfile

It doesn't do POSIX locking, which we use to detect if the original process is still running.

The problem we're trying to avoid with that is: if Newsboat crashes, the next instance has to somehow learn about this. It's not enough to read the PID from the lockfile and check if such process exists—PIDs are fixed-width integers, and they do roll over, so it's possible that:

1. Newsboat with some PID X starts, creates the lockfile, writes X into it;
2. it crashes, leaving the lockfile in place;
3. PIDs roll over, and another process gets PID X from the OS;
4. another instance of Newsboat starts, checks the lockfile, sees X in there, checks if X is still running—and it turns out that it does.

I believe checking if X is running is OS-dependent, and checking if X is actually Newsboat is OS-dependent too. I think that's why we use advisory locking, which has the same POSIX API across many OSes. lockf also has a nice property: when a process finishes or crashes, the lock is removed, so we always know if the original instance of Newsboat is still running.

> and https://crates.io/crates/fs2

That [uses `flock` instead of `lockf`](https://github.com/danburkert/fs2-rs/blob/9a340454a8292df025de368fc4b310bb736f382f/src/unix.rs#L26-L44). Cursory search got me [this explanation of the differences](https://stackoverflow.com/questions/22409780/flock-vs-lockf-on-linux#22411531).

Actually, [fd-lock uses `flock` as well](https://github.com/yoshuawuyts/fd-lock/blob/4b2f8650778a83586c2eec54f724fc93872ae1da/src/unix.rs#L59), so we're back to the square one here.

I think it'd be pretty fine if we rolled our own bindings. I'm working with bindgen right now for #701, and it seems pretty simple to wrap small C APIs. (Except glibc defines error codes in regex.h in a really obtuse way, and I'm now fighting with bindgen to create bindings for those.)

**Comment by pickfire** [comment]
@Minoru Do you want me to take a look at this? Should we use `fnctl` which is more portable or we just stick to `lockf` which is a wrapper around `fnctl`? These stuff are available in https://docs.rs/libc/0.2.68/libc/struct.flock.html.

**Comment by Minoru** [comment]
> Do you want me to take a look at this?

Sure!

> Should we use fcntl which is more portable or we just stick to lockf which is a wrapper around fcntl?

The SO link above says that `lockf` is a wrapper only on Linux. On FreeBSD and macOS, it's separate from `fcntl`. Of course, we strive to support as many Unix-like systems as possible, so try not to rely on any specifics.

I strongly believe we should use `lockf`, because:
1. it gives us compatibility with previous versions of Newsboat;
2. by not switching to a new mechanism, we open ourselves to fewer new bugs.

With that said, if you hit a wall, please explain the problem and we'll see if abandoning `lockf` is worthwhile.

**Comment by pickfire** [comment]
https://crates.io/crates/file-lock uses fcntl

**Comment by pickfire** [comment]
A prototype for this based on our current `FsLock`. @Minoru What do you think?

```rust
use libc::{fcntl, flock, pid_t, F_SETLK, F_UNLCK, F_WRLCK, SEEK_SET};
use std::fs::{self, File, OpenOptions};
use std::io::{Error, Write};
use std::os::unix::io::AsRawFd;
use std::path::Path;

pub struct FsLockGuard<P: AsRef<Path>> {
    path: P,
    file: File,
}

impl<P: AsRef<Path>> Drop for FsLockGuard<P> {
    fn drop(&mut self) {
        let fl = flock {
            l_type: F_UNLCK as i16,
            l_whence: SEEK_SET as i16,
            l_start: 0,
            l_len: 0,
            l_pid: 0,
        };

        if unsafe { fcntl(self.file.as_raw_fd(), F_SETLK, &fl) } != 0 {
            panic!("Could not unlock the file descriptor");
        }
        fs::remove_file(&self.path).expect("Fail to remove lock file");
    }
}

#[derive(Debug)]
pub struct FsLock;

impl FsLock {
    pub fn try_lock<P: AsRef<Path>>(path: P, pid: pid_t) -> Result<FsLockGuard<P>, Error> {
        let mut file = OpenOptions::new().write(true).create(true).open(&path)?;

        let fl = flock {
            l_type: F_WRLCK as i16,
            l_whence: SEEK_SET as i16,
            l_start: 0,
            l_len: 0,
            l_pid: pid,
        };

        match unsafe { fcntl(file.as_raw_fd(), F_SETLK, &fl) } {
            0 => {
                file.write_all(&pid.to_ne_bytes())?;
                Ok(FsLockGuard { path, file })
            }
            code => Err(Error::from_raw_os_error(code)),
        }
    }
}
```

**Comment by Minoru** [comment]
Hmm, file-lock uses a pretty interesting approach: instead of Rust talking directly to libc, they [create a small, static C library](https://gitlab.com/alfiedotwtf/file-lock/-/blob/b9dd84e183683c9f84ad3bece713ba58a718ff26/src/file_lock.c) that does all the interfacing with libc. Rust then [calls into that library](https://gitlab.com/alfiedotwtf/file-lock/-/blob/b9dd84e183683c9f84ad3bece713ba58a718ff26/src/lib.rs#L99) and propagates errors.

That's pretty neat, but I see two down-sides:
1. `gcc` crate is a heavy dependency because it transitively pulls in a lot of stuff that we don't have: mktemp, nix, uuid, md5, possibly more (I stopped checking at this point)
2. this approach requires a C compiler. That's okay in the short run, since G++/Clang++ often pulls in the C version as well, and we require C++ compiler anyway. In the long run, though, Newsboat will become a pure Rust application, and requiring a C compiler would look weird.

I'd still try bindgen, and if that doesn't work or is intractable, we can take the file-lock approach.

@pickfire I think you have a typo in `drop`: it tries to obtain a lock, instead of unlocking. Also, this does use `fcntl`, which I still believe is not the correct way to port this. Do you have any ideas about moving this to `lockf` somehow?

**Comment by kpcyrd** [comment]
As a sidenote, the `gcc` crate is deprecated, file-lock should migrate to the `cc` crate instead.

**Comment by pickfire** [comment]
@Minoru Typo in `drop`? If you meant `F_SETLK`, it is used for both acquire and release lock according to `fnctl(2)`, also I stole that from `file-lock`, pure rust port of the c code with some modification. I took mainly from 3 places, our `FsLock` for API usage (I think it is not rusty but following it is easier), `fd-lock` on how they design the API, and `file-lock` on how they use `fnctl`.

@kpcyrd Yes, I feel like `file-lock` is unmaintained, who still uses this approach nowadays?

**Comment by Minoru** [comment]
> Typo in drop? If you meant F_SETLK

Yeah, sorry, the import of `F_UNLK` confused me. I now see that this is passed as a field in a structure, not as a direct parameter to `fcntl`.

> Some idea to move to lockf, either use the gcc-like approach or contribute lockf to libc

Contributing to libc sounds like a perfect solution to me, but it indeed requires more work than gcc/cc or bindgen would. Don't rule out bindgen :P

**Comment by pickfire** [comment]
@Minoru But what do you think of that code, can we use something like that to replace the current one? But I think we may need to get some tests ready, at least try out `fnctl` and see if it break stuff.

**Comment by Minoru** [comment]
> can we use something like that to replace the current one?

Eventually, once all users of FsLock are in Rust -- yes we can. Right now, though, we're just porting existing functionality from C++ to Rust; we don't change APIs and we don't change observable behaviour. So, right now -- no, we can't use that. We have to re-create the same API, make it available through FFI, then port the parts that depend on this API. After that, we can remove the FFI, and refactor and evolve the API purely in Rust.

C++ FsLock has practically total coverage, by the way. Porting that to Rust is a good start too.

**Comment by Minoru** [comment]
I should've said "don't change observable behaviour *unless it's broken*". Filter parser and `Matcher` are an example of this: they mostly work, but #701 uncovered a whole lot of inconsistencies and weird corner cases. [Describe them](https://github.com/newsboat/newsboat/pull/701#issuecomment-593002181), and we'll see if these bugs are worth re-implementing.

So far, I'm not convinced our existing `FSLock` contains any bugs that are worth fixing during the rewrite. The API indeed can be improved, but it has to be done either now, while all the code is still in C++, or later, when all the code is already in Rust; matching the impedance doesn't seem like a good use of anyone's time.

**Comment by pickfire** [comment]
@Minoru I tried adding `lockf` to `libc` but it did not seemed that hard for me? Let see if they accept https://github.com/rust-lang/libc/pull/1707 the patch.

**Comment by pickfire** [comment]
@Minoru It's here now. https://github.com/rust-lang/libc/pull/1708 guess we can just use the `lockf` from `libc`, if you want it to be quick, can just use the git version and wait for it to release later.

**Comment by Minoru** [comment]
Let's wait for their release, @pickfire. They don't seem to have a release schedule, so it's conceivable that they won't make one before we release 2.20. If we depended on their Git, we'd have to either roll back the work (and everything that depended on it), or release with Git dependency (which I think will make packagers in distros upset).

**Comment by pickfire** [comment]
Is there some sort of wait hook to know that they have release and bump us here?

**Comment by Minoru** [comment]
Dunno. GitHub provides Atom feeds for releases, but I might forget to act when I see 0.2.69. So I added a few tasks to Taskwarrior: I'll do weekly checks for new release until 2020.05.25, and then I'll ask the libc maintainers to cut a new release. That should give us about a month to port FSLock, merge it into `master`, and fix the bugs found by early adopters.

**Comment by Minoru** [comment]
This is now blocked on a PR that makes a new libc release: https://github.com/rust-lang/libc/pull/1732.

**Comment by Minoru** [comment]
That PR got merged, and new libc is already on crates.io, so this issue is unblocked. You can proceed, @pickfire :tada:

**Comment by pickfire** [comment]
Should we split fslock into another package?

**Comment by Minoru** [comment]
I don't think so. It requires `logger` from libnewsboat anyway, so I don't see much gain in having fslck as a separate crate. Except I'm missing something?

**Comment by pickfire** [comment]
@Minoru Solved, time to port some other parts to rust, anything you want me to help out with?

**Comment by Minoru** [comment]
@pickfire As always, take a look at [the rust-port label](https://github.com/newsboat/newsboat/labels/rust-port) and see if there's something you'd like to work on.
