### ISSUE TITLE
Migrate away from AsciiDoc

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#645]
Debian testing got an update to asciidoc today, and with it, this message in the changelog:

> asciidoc (8.6.10+git20190307.51d7c14-1) unstable; urgency=medium
>
>  This new version of asciidoc is using the unreleased python3 implementation
>  as python2 is deprecated. This implementation has a very low maturity to it
>  and has not seen an upstream release yet. As the maintenance of this upstream
>  is very low and they advise to use asciidoctor in the past, we advise you to
>  use asciidoctor instead as it is now the official reference for the AsciiDoc
>  language and is way ahead of this Python implementation both in terms of
>  maintenance and support of language features.
>
> -- Joseph Herlant <aerostitch@debian.org>  Sat, 07 Sep 2019 20:41:47 -0700

I've been eyeing asciidoctor for a while, but haven't tried it at all.

This might also be a good opportunity to look back at AsciiDoc and decide if it fits our purposes well, or should we be looking for another format altogether.

**Comment by polyzen** [comment]
Python 2 still has more than 3 months to go.. wonder why they did that. asciidoctor requires Ruby, which I try to avoid outside of web apps.

Love me some Sphinx with reStructuredText. The only viable Rust SSG I know of is Zola, but it supports only Markdown and seems blog-centric.

**Comment by Minoru** [comment]
> This might also be a good opportunity to look back at AsciiDoc and decide if it fits our purposes well, or should we be looking for another format altogether.

Just moving from older Asciidoc syntax to newer one was enough for me to decide it's not worth it. [Asciidoctor's Quick Reference](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) makes it pretty easy to read and write even if one never used Asciidoc before.
