### ISSUE TITLE
cannot bind left/right arrow keys

### ISSUE THREAD

**Issue by sunaku** [newsboat/newsboat#649]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat  - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat
System: Linux 5.2.17_1 (x86_64)
Compiler: g++ 9.1.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.66.0 LibreSSL/2.9.2 zlib/1.2.11 libssh2/1.9.0 nghttp2/1.39.2 (compiled with 7.65.1)
SQLite: 3.29.0 (compiled with 3.28.0)
libxml2: compiled with 2.9.9

```

Steps to reproduce the issue:

1. Add the following snippet to `~/.newsboat/config` file:
```sh
unbind-key right
bind-key right open
unbind-key left
bind-key left quit
```

2. Run `newsboat`

3. Press the right & left arrow keys and observe that nothing happens.  You still have to use the `Enter` & `q` keys to open and close a news item: right & left arrows don't work.

**Other info you think is relevant**:

This comment in issue #110 seems to indicate that perhaps the left & right arrows need to be specially handled in the code before they can be bound in the user's configuration file. :thinking: 
https://github.com/newsboat/newsboat/issues/110#issuecomment-431656389

**Comment by Minoru** [comment]
Hi! All special keys, and combinations with Control, have to be written in uppercase. This snippet works:

```
unbind-key RIGHT
bind-key RIGHT open
unbind-key LEFT
bind-key LEFT quit
```

I consider this just another ramification of #568, so closing as duplicate. Thanks for taking the time to file this anyway!

**Comment by sunaku** [comment]
Thank you! :+1::100::sparkles:
