### ISSUE TITLE
Add "rust" to the list of dependencies in the compilation instruction in the documentation

### ISSUE THREAD

**Issue by Eucyon** [newsboat/newsboat#651]
And to the dependency checks in the Makefile.

**Comment by Minoru** [comment]
Hi! The second item in Dependencies section mentions it already:

> Stable Rust and Cargo (Rust's package manager) (1.26.0 or newer)

https://github.com/newsboat/newsboat/blob/master/README.md#dependencies

Or did you mean something else?

**Comment by Eucyon** [comment]
Hello!

I was following https://newsboat.org/releases/2.17/docs/newsboat.html#_compiling_and_installing.

**Comment by Eucyon** [comment]
However, is it possible to add a check to the Makefile?

**Comment by Minoru** [comment]
Oh, *that* list totally feel of my radar! I don't think I ever updated it at all ._. Thanks for pointing it out!

Yeah, checking for "cargo" in config.sh is doable.

**Comment by Eucyon** [comment]
Fine, thank you. NB is getting better and better.

**Comment by Minoru** [comment]
I updated the lists and made a comment to hopefully help keep them in sync, but I decided against adding the check to the Makefile—[here's my reasoning](https://github.com/newsboat/newsboat/pull/664#issuecomment-538734073).
