### ISSUE TITLE
Decide on which `rustfmt` version to use

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#654]
In #653, [the CI build that checks formatting failed](https://travis-ci.org/newsboat/newsboat/jobs/590531476), because a new version of Rust was recently released, apparently changing the behaviour of `rustfmt`. This is exactly the same problem as we had with `clang-format` earlier; cf. https://github.com/newsboat/newsboat/issues/198#issuecomment-408687556

For `clang-format`, my preferred solution is to pick a version and stick to it. SeanBE contributed a Docker container for that, and now all that's left is to streamline its usage, write docs, and add it to CI.

For Rust, I'm not so sure. Rust ecosystem pushes for small, frequent updates, so it kinda makes sense to require the latest `rustfmt`. On the other hand, some people might be installing Rust from a repository that's lagging behind the upstream. I guess we could add the latest `rustfmt` to the same Docker image as `clang-format`, and ask people to either use that, or install the latest `rustfmt` directly.

Need to sleep on this.

**Comment by SeanBE** [comment]
I prefer keeping a fixed stable toolchain version and using the rustfmt component that is linked to it. I feel like formatting isn't going to change that much and if it does we could always review the rust version at a later stage.

We should all really be using `rustup` to manage our toolchains. That means everyone would be using the same toolchain locally and in the CI job. 

Maybe we should also add a `rustfmt.toml` config file? 

I don't mind picking this and updating the Dockerfile if we decide on a solution.

**Comment by Minoru** [comment]
> We should all really be using rustup to manage our toolchains.

I don't want to leave out the folks that are content with what their distro ships. As long as they use a version that fits Newsboat's build requirements, they should be good to go. That keeps the barrier of entry reasonably low, so we still get drive-by contributors from people who aren't that much into Rust. So I don't want to make rustup a requirement.

That said, those folks won't have much control over what rustfmt version they get, and we can't guess their version number either. So let's just assume that no matter what version we pick, those folks will either use our Docker container, or grab a patch from the failed CI job.

Pinning rustfmt version forever (like we did for `clang-format`) seem contrary to what Rust ecosystem does in general—as far as I've seen, many crates are only tested on stable, beta and nightly. So we should just use rustfmt that's linked to the latest stable. (That's what I already did with Rust 1.38 and rustfmt 1.4.4, as you pointed out.)

> I don't mind picking this and updating the Dockerfile if we decide on a solution.

The Dockerfile we already have is using Alpine 3.10, which is already behind Rust upstream ([it ships 1.34.2](https://pkgs.alpinelinux.org/packages?name=rust&branch=v3.10), latest upstream is 1.38). I guess we'll need a new Dockerfile, one that tracks Alpine edge and latest stable Rust. Can you do that?

Adding `.rustfmt.toml` is a good idea as well! If you'll be submitting a PR with new Dockerfile, please include the TOML config as well. I'd prefer it to be a dotfile, to keep it out of the way (same as we do with other such configs).

**Comment by SeanBE** [comment]
>I don't want to leave out the folks that are content with what their distro ships. As long as they use a version that fits Newsboat's build requirements, they should be good to go. That keeps the barrier of entry reasonably low, so we still get drive-by contributors from people who aren't that much into Rust. So I don't want to make rustup a requirement.

Fair enough.

> Pinning rustfmt version forever (like we did for clang-format) seem contrary to what Rust ecosystem does in general—as far as I've seen, many crates are only tested on stable, beta and nightly. So we should just use rustfmt that's linked to the latest stable. (That's what I already did with Rust 1.38 and rustfmt 1.4.4, as you pointed out.)

Sorry I meant pinning the version of rust and using the linked version of rustfmt i.e. rust 1.32.0 come with 1.0.0 where 1.38.0 comes with rustfmt 1.4.4. 

>The Dockerfile we already have is using Alpine 3.10, which is already behind Rust upstream (it ships 1.34.2, latest upstream is 1.38). I guess we'll need a new Dockerfile, one that tracks Alpine edge and latest stable Rust. Can you do that?

There are two ways we can go about this. It really depends how we use them locally and on CI. The official rust images include versions with alpine `3.10` and rust `1.38`. We could replace the base image with this one and just add clang on top of it so that we have one Dockerfile. 

Or we just have two separate Dockerfiles. 

>Adding .rustfmt.toml is a good idea as well! If you'll be submitting a PR with new Dockerfile, please include the TOML config as well. I'd prefer it to be a dotfile, to keep it out of the way (same as we do with other such configs).

:+1:

**Comment by Minoru** [comment]
> The official rust images include versions with alpine 3.10 and rust 1.38. We could replace the base image with this one and just add clang on top of it so that we have one Dockerfile.

Can we? I thought Alpine 3.10 doesn't have the clang-format version that we need.

But if it's indeed possible to have a single Dockerfile, I think we should. CI can fail the job if either of formatters fail; users will have one less command to type to get a container. Win-win.
