### ISSUE TITLE
Do not provide "for all" options in `save-all` when there is a single conflict

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#657]
In #656, @der-lyse points out a flaw in our [conflict prompt](https://github.com/newsboat/newsboat/blob/6e72dcc934791a7867773230a4f5bd88606d4a49/src/itemlistformaction.cpp#L1518-L1521):

> The second overwrite message without any further conflicts is quite
weird: If there are no further conflicts, the "yes to all" and "no to
all" choices don't make any sense. However, in order to get rid of them,
the source code has to be changed to allow for a more user-friendly
interface, which considers a case where the initial conflict prompt
refers to a single case.

I agree. We should re-use [the prompt for a single conflict case](https://github.com/newsboat/newsboat/blob/6e72dcc934791a7867773230a4f5bd88606d4a49/src/itemlistformaction.cpp#L1438-L1439).

**Comment by eeqlsmc3** [comment]
Hello, I would like to work on this issue. I have read the code style guide. Can you direct me on how I should proceed with it?

**Comment by Minoru** [comment]
Hi! I'm not sure what kind of guidance you need, but one thing that the above post doesn't explain is what the `save-all` even is, and how to use it. Here's a quick intro:

0. create a temporary directory somewhere (we'll use it later);

1. create ~/.newsboat/config with the following content:

    ```
    bind-key S save-all
    ```

2. create ~/.newsboat/urls with the following content:

    ```
    https://newsboat.org/news.atom
    ```

    This is an Atom feed about Newsboat's news (mostly releases).

3. compile Newsboat (the instructions are in the README);

4. start Newsboat: `./newsboat`;

5. press `r` to reload the only feed. After a second or two, the URL will get replaced by the feed title, "Newsboat";

6. press Enter to view the list of articles. Currently there are 22;

7. press `S` to invoke `save-all` command. That will ask you to choose a directory where you want to save the articles -- choose a temporary directory you created earlier. Confirm saving, then check the directory -- it should contain 22 txt files, one per each article;

8. press `S` *again*, and choose the same directory. Now for each conflict, Newsboat will ask you for confirmation;

9. remove all but one file from the temporary directory;

10. press `S` yet again, and choose the same directory. This time, just one article will create a conflict (because there's only one file in the directory prior to creating new files). Note that the prompt that tells you about conflicts will include "yes to all" and "no to all" options -- which doesn't make sense since we already counted the conflicts and know for sure that this one is the only one. That's the bug that this issue is about.

Hope this helps. Please ask more questions as they arise, I'm happy to help!

**Comment by Minoru** [comment]
Hey @eeqlsmc3, have you started on this? Are there any roadblocks?

I'm not trying to hurry you, just making sure you aren't stuck with something. Please ask questions!

**Comment by Minoru** [comment]
I assume @eeqlsmc3 abandoned this issue (which is fine, we're all volunteers here), so I'm un-assigning them. This issue is now up for grabs!

**Comment by ATM-SALEH** [comment]
Actually, I was looking at this issue. Haven't looked over in detail, though. I will try to allocate some time next week and come back with a plan.

**Comment by Minoru** [comment]
Cool, looking forward to that @ATM-SALEH!
