### ISSUE TITLE
Delete downloaded files from disk

### ISSUE THREAD

**Issue by hfel** [newsboat/newsboat#669]
Hello!

It would be nice if podboat could remove the files on disk its list entries refer to, instead of just the list entries themselves. At the moment, to keep the downloads folder from ballooning, the user has to regularly go into the folder and delete old podcasts, which can become a chore when there's a huge number of them both already downloaded but not yet listened to and also already listened to and removed from podboat's list.

**Comment by Minoru** [comment]
Hi! Thank you for the suggestions. This makes perfect sense; I'll keep it. However, Podboat doesn't get any attention nowadays, so I'm not sure when this would be implemented.

**Comment by dennisschagt** [comment]
This is fixed now but, if you still have files left from before, the following script might be useful in creating an overview:
https://gist.github.com/dennisschagt/84e738579f2384e3d9eff5393c9c5b80

**Comment by hfel** [comment]
Are there any plans as to when the next release incorporating this change will be made?

**Comment by Minoru** [comment]
We release every three months, so around 20th of March, @hfel.
