### ISSUE TITLE
Missing installation tips for cygwin

### ISSUE THREAD

**Issue by rajeshduggal** [newsboat/newsboat#67]
I spent some time trying to get this working on cygwin today.  I couldn't get stfl to build with gcc.  Anyone know the steps to get newsboat working on cygwin?, and can we get the instructions/tips  added to a readme in the repo in the interim.  Might be better than waiting for the build code to be updating to accomodate cygwin. Much appreciated!

**Comment by Minoru** [comment]
Hi! What problems, specifically, are you hitting? I don't have any experience with compiling under Cygwin, nor do I have access to Windows machine, but perhaps I can help you with resolving some of the issues.

Newsboat isn't that much different from Newsbeuter (yet), so you can Google for both. I failed to find much, though. [This comment](https://geektivities.wordpress.com/2008/06/24/console-rss-news-reader/#comment-58) from Newsbeuter's original author even promises us some trouble (Newsboat uses ncursesw too.)

**Comment by Minoru** [comment]
No response in almost three years, so apparently no-one is interested in this. Closing. Feel free to comment here if you're interested and would like to answer the questions above.
