### ISSUE TITLE
Bookmarks/favorites inside Newsboat

### ISSUE THREAD

**Issue by hfel** [newsboat/newsboat#680]
Hi!

Newsboat comes with bookmarking support, however it would also be nice to see which articles in a feed are bookmarked _from within_ Newsboat itself. This could be implemented by for example introducing another column for bookmark status, or some specific marker in the article row. As the bookmarking system is a somewhat sophisticated routine that plays into an external application, it may also be more suitable to introduce a 'favorites' system that just allows the marking of articles, in order to keep the two functions clearly separate. An additional command could also be added that filters out all unfavorited/unbookmarked articles, giving Newsboat the functionality of a "bookmarks browser" as well.

**Comment by Minoru** [comment]
Hi! Newsboat does have a favourites system—[flags](https://newsboat.org/releases/2.17.1/docs/newsboat.html#_flagging_articles). The flags themselves aren't displayed in the article list, but flagged articles are marked by `!`. Flags can be viewed in the article view.

> An additional command could also be added that filters out all unfavorited/unbookmarked articles

You can use [filter language](https://newsboat.org/releases/2.17.1/docs/newsboat.html#_filter_language) to query [`flags` attribute](https://newsboat.org/releases/2.17.1/docs/newsboat.html#attr-flags) to achieve that.

Does that sufficiently cover your use-case?

**Comment by hfel** [comment]
Absolutely, my bad for not being more thorough in going through the documentation. Thank you!
