### ISSUE TITLE
Multi-byte unicode characters in article titles spoil layout of article list

### ISSUE THREAD

**Issue by mglh** [newsboat/newsboat#683]
### Issue ###

On my system, when using an articlelist format that left-aligns a field with a fixed width,
and the article title contains emojis (which are multi-byte unicode characters, I assume), 
apparently the number of characters of the article title, which is used to calculate
the position of the first character of the following field on the screen, is counted wrong. 

For each emoji that is used in the article title, the first character of the following field 
is shifted one place to the right.

See the sample of an article list at the bottom of this post.

### Operation System ###

Debian Stretch

Note: newsboat was installed with linuxbrew.

### Locale ###

```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

### Newsboat Versions ###

```
newsboat 2.17.1
System: Linux 4.9.0-11-amd64 (x86_64)
Compiler: g++ 5.5.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.66.0 OpenSSL/1.0.2t zlib/1.2.11 (compiled with 7.66.0)
SQLite: 3.29.0 (compiled with 3.29.0)
libxml2: compiled with 2.9.9
```

### Config ###

```
datetime-format "%Y-%m-%d"
articlelist-format "%4i %f %-60t %D"
```

### Feed URL ###

https://www.youtube.com/feeds/videos.xml?channel_id=UCZiL6BoryLWxyapUuVYW27g

(This is the RSS feed of videos in a YouTube channel)

### Article list ###

```
   9 N  How to upgrade Linux Mint 19.1 to 19.2                       2019-08-07
  10 N  CloudBerry Backup for Linux Server 💽 with web interface 😱    2019-07-31
  11 N  15 Things to do After Installing elementary OS (2019)        2019-07-27
  12 N  Picture in picture in Elementary OS                          2019-07-19
  13 N  SUDO: another fun program? 🤔                                 2019-07-13
```

**Comment by Minoru** [comment]
Thank you for the report! I haven't tried to reproduce it yet. I'll try to get to that on the weekend.

I believe Newsboat counts graphemes, i.e. "symbols". That'd break if some symbols are wider than the others, as is the case here—emojis are two columns wide. I'll have to track down where the problem originates (`TextFormatter`?), and then think how best to fix this.

**Comment by Minoru** [comment]
Reproduced with f27408b56446aefe473eff60fe66580fbe200050.
