### ISSUE TITLE
In macros, don't require space between operation and following semicolon

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#702]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.17.1

Consider this example macro from [our docs](https://newsboat.org/releases/2.17.1/docs/newsboat.html#_macro_support):

```
macro i set browser "feh %u"; open-in-browser ; set browser "elinks %u"
```

If we remove the space between `open-in-browser` and the following semicolon, Newsboat won't start:

```
Starting newsboat r2.17.1-63-g407fc...
Loading configuration...Error while processing command `macro i set browser "feh %u"; open-in-browser; set browser "elinks %u"' (/home/minoru/src/newsboat/data/macro-config line 1): `open-in-browser;' is not a valid key command
```

Yet it's somehow fine to omit the space after `set X Y`. This is confusing and, I believe, is an unnecessary restriction.

Need to investigate why this exists, and if/how can it be fixed.

**Comment by dennisschagt** [comment]
There are two different ways in which a semicolon is not detected.
Those are triggered in the following config lines:
a. `macro a set browser "firefox"; open-in-browser`
b. `macro a set browser firefox; open-in-browser` (I don't think this is an issue but it might be nice to support example line `c`)
c. `macro b open-in-browser; quit`

1. The config parser makes use of `utils::tokenize_quoted()`. That function seems to ignore the first character after a closing `"` so it in effect removes the semicolon in config line `a`.
2. The macro configuration handling (in `KeyMap::handle_action()`) only checks for separate `";"` tokens (see [1](https://github.com/newsboat/newsboat/blob/e26eae889574b9993eecb8b01c846f83dd70f1f8/src/keymap.cpp#L735) and [2](https://github.com/newsboat/newsboat/blob/e26eae889574b9993eecb8b01c846f83dd70f1f8/src/keymap.cpp#L749)). This causes it to not handle the semicolon in examples `b` and `c`.

**Comment by Minoru** [comment]
Thanks for investigating!

> The config parser makes use of utils::tokenize_quoted(). That function seems to ignore the first character after a closing " so it in effect removes the semicolon in config line a.

That's a regression introduced by https://github.com/newsboat/newsboat/commit/4b327fbff264c69bb78765304e16c2403c65b5e1. I'm working on re-doing that commit to fix the regression without re-introducing the second loop.

> The macro configuration handling (in KeyMap::handle_action()) only checks for separate ";" tokens (see 1 and 2). This causes it to not handle the semicolon in examples b and c.

That answers the question from the top post; thanks! So to fix this issue, we have to tokenize by `;`, not by space. But tokenization is done higher up the call tree, somewhere in `ConfigParser`, and it's the same for all lines. Are there any solutions other than moving `tokenize_quoted` down, into every `handle_action` method?

**Comment by dennisschagt** [comment]
> That answers the question from the top post; thanks! So to fix this issue, we have to tokenize by ;, not by space. But tokenization is done higher up the call tree, somewhere in ConfigParser, and it's the same for all lines. Are there any solutions other than moving tokenize_quoted down, into every handle_action method?

In PR #1119 I have fixed this by adding an extra method to `ConfigActionHandler` which can be overridden to get the argument string without tokenizing.
https://github.com/newsboat/newsboat/commit/ed127578c5267c9b8777f27feae254b244cb2df1#diff-32b8bd4a05169381ed35c31e146efd91
