### ISSUE TITLE
newsboat stuck on some Chinese feed sources

### ISSUE THREAD

**Issue by xiaket** [newsboat/newsboat#71]
**Newsboat version 2.10.1**:

Steps to reproduce the issue:

1. `rm ~/.newsboat/*`

2. `echo "http://www.ruanyifeng.com/blog/atom.xml" > ~/.newsboat/urls`

3. `newsboat`

4. Press R to force a refresh

5. Press Enter to enter this feed.

6. Choose the article published on Nov 07/Nov 23/Oct 17 will make newsboat stuck, article is not displayed while the CPU usage quickly reaches 100%. `q` will not work, I have to kill the process in another terminal session to end it. However, the article published on Nov 15 and Oct 24 is working alright.

**Other info you think is relevant**:

Other RSS feeds have this issue on my end include:

```
http://www.matrix67.com/blog/feed
http://www.ifanr.com/feed
http://onevcat.com/rss
```

At times, some encoding error message will show up in the interface that looks like this:

```
encoding error : input conversion failed due to input error, bytes 0x79 0xA1 0xA2 0xC7
```

I've seen this message before, but they will not freeze the application. So I don't know whether it is relevant.

**Comment by Minoru** [comment]
Hi, thanks for the report!

All articles in all four feeds worked fine for me on Linux with en_US.UTF-8 locale. What OS and locale do you have? I recall some problems on FreeBSD, and also with locales that didn't match the articles' language.

There are a few GitHub issues—[first](https://github.com/mitmproxy/mitmproxy/issues/657), [second](https://github.com/honghaoz/Ji/issues/44)—that mention the same error and `libxml2`, which we also use. Can you post the output of `newsboat --version`, and also check what libxml2 version do you have installed? (I have 2.9.5, compiled Newsboat with it.)

**Comment by nmtake** [comment]
Hi, I have same problem. Newsboat HEAD (7f119a4), installed on Mac,
stuck when I try to read some feed written in Japanese. 
Here is [the feed](https://github.com/newsboat/newsboat/files/1509905/it.txt) retrieved from http://b.hatena.ne.jp/hotentry/it.rss
and the output of `newsboat --version` and `locale`:

```
$ ../newsboat --version
newsboat r2.10.1-110-g7f11 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `../newsboat -vv' for more information.

newsboat r2.10.1-110-g7f11
System: Darwin 15.6.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.43.0 SecureTransport zlib/1.2.5 (compiled with 7.43.0)
SQLite: 3.8.10.2 (compiled with 3.8.10.2)
libxml2: compiled with 2.9.7

$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

Here is steps to reproduce I took:

```
$ touch empty.conf
$ curl -O http://b.hatena.ne.jp/hotentry/it.rss
$ echo "file://$(pwd)/it.rss" > url.txt

$ ../newsboat --url-file=./url.txt --config-file=empty.conf --cache-file=./cache.db
```

When I press `r` to read the RSS and then press `Enter` on the article named
"デザイナーと働くなら知っておきたい4タイプのデザイナー像 | ベイジの社長ブログ",
the newsboat process stuck.

FYI I tried newsboat 2.9_2 and it works fine for the feed.

**Comment by xiaket** [comment]
Sorry I'm a bit late in response, my version info:

```
newsboat 2.10.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT/X Consortium License.
Type `newsboat -vv' for more information.

newsboat 2.10.1
System: Darwin 15.6.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.43.0 SecureTransport zlib/1.2.5 (compiled with 7.51.0)
SQLite: 3.8.10.2 (compiled with 3.14.0)
libxml2: compiled with 2.9.2
```

my locale info:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by nmtake** [comment]
I ran git-bisect and it finishes at 885760. And I found this from the debug log:

```
[2017-11-29 21:40:08] DEBUG: textformatter::format_text_plain: stored `があり、異なる価値観を持っています。この多種多様なデザイナーを一種類にまとめて扱うこと<E3>'
[2017-11-29 21:40:08] DEBUG: textformatter::format_text_plain: stored `<81><AF>、デザイナーとのミスマッチに繋がり、デザイナーを擁する組織のマネジメントにとって、深刻な問題を引き起こすこともあります。 '
```

It look like that Japanese character `は` (`E3 81 AF` in UTF8) is splitted with a new line.

**Comment by Minoru** [comment]
Thanks for the bisect! Looks like it's the same as #38, only the language is different.

Need to look into proper ways of chunking strings into graphemes. I wonder if converting to `std::wstring` will do the job?

**Comment by nmtake** [comment]
I think `std::wstring` is suitable for storing code points (as far as wchar_t is 4 bytes long) rather than graphemes,
but at least, this issue may solve if we use `std::wstring` to cut the line on the valid character or code point boundaries.

If I understand this issue correctly, it is caused by 1) `wrap_line()` produces broken UTF-8 string by cutting single multi-byte character in two, then 2) the broken string gets passed into `stfl::quote()`, e.g.,  `stfl::quote("\xE3");`, the the process stuck. I don't know why `stfl::quote()` doesn't return for some invalid UTF-8 strings at this time.
