### ISSUE TITLE
Very slow to move to the next unread feed when connected to Inoreader

### ISSUE THREAD

**Issue by rpietro** [newsboat/newsboat#710]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.17.1
System: Linux 4.19.88-1-MANJARO (x86_64)
Compiler: g++ 9.1.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.39.2 (compiled with 7.66.0)
SQLite: 3.30.1 (compiled with 3.29.0)
libxml2: compiled with 2.9.9

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
show-read-feeds no

urls-source "inoreader"
inoreader-login "name@gmail.com"
inoreader-password "ZZZZZZZZZ"

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key l open
bind-key h quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread blue default
color listfocus_unread yellow default bold
color info red black bold
color article cyan default

macro v set browser "mpv %u&!"; open-in-browser ; set browser "brave %u"

```

So, I gave Inoreader a shot and then connected it to Newsboat instead of using a local urls file. The problem is that it got incredibly slow, to the point where moving toward the next unread feed takes seconds (I can go through about four feeds/minute tops). That is surprising since I would not think that, once synchronized, Newsboat would have to connect to Inoreader to simply move from one feed to the next. Am I missing something? Just wondering if anybody had the same experience. 

Steps to reproduce the issue:

1. wait until sync is over

2. open one feed

3. press n to get to the next feed - it takes a few seconds (can get through a mas of four feeds/minute) 

**Other info you think is relevant**:

**Comment by Minoru** [comment]
Hi! Sorry for the delay—took a bit of time off the project for the New Years :)

Does Newsboat consume one of your CPU cores after you press `n`? If so, try setting `show-read-articles` to `no`. Newsboat has to format the whole list before displaying it, so if you have a lot of feeds or article, the program takes a while to display them all.

**Comment by Minoru** [comment]
(Not sure if this is a bug or just a question, so tagging with both for now)

**Comment by scateu** [comment]
+1

Probably it's caused by the delay of updating read status with inoreader.com. Sadly, I became a paid user of inoreader just because newsboat has support for it.

Hope this delay got fixed someday.

Thank you for the nice work!

**Comment by scateu** [comment]
Borrowed some code from ttrssapi.cpp. Still compiling.. 

```patch
diff --git a/src/inoreaderapi.cpp b/src/inoreaderapi.cpp
index a27f66a3..0bdd69d4 100644
--- a/src/inoreaderapi.cpp
+++ b/src/inoreaderapi.cpp
@@ -4,6 +4,7 @@
 #include <curl/curl.h>
 #include <json.h>
 #include <vector>
+#include <thread>
 
 #include "config.h"
 #include "strprintf.h"
@@ -214,8 +215,18 @@ bool InoreaderApi::mark_all_read(const std::string& feedurl)
 
 bool InoreaderApi::mark_article_read(const std::string& guid, bool read)
 {
-	std::string token = get_new_token();
-	return mark_article_read_with_token(guid, read, token);
+	// Do this in a thread, as we don't care about the result enough to wait
+	// for it. // borrowed from ttrssapi.cpp
+	std::thread t{[=]()
+	{
+		LOG(Level::DEBUG,
+			"InoreaderApi::mark_article_read: inside thread, marking "
+			"thread as read...");
+		std::string token = get_new_token();
+		mark_article_read_with_token(guid, read, token);
+	}};
+	t.detach();
+	return true;
 }
 
 bool InoreaderApi::mark_article_read_with_token(const std::string& guid,
```

**Comment by Minoru** [comment]
@scateu, after you've tested it, can you submit it as a pull request? Thanks for working on it either way!

**Comment by scateu** [comment]
Yay. I'm so lucky that it works. Pull request right on the way.

**Comment by mredaelli** [comment]
I have the same problem with nextcloud. Could the fix be similarly straightforward?

**Comment by scateu** [comment]
@mredaelli Yes. Since nextCloud share the same API with ownCloud, I believe it's here: https://github.com/newsboat/newsboat/blob/master/src/ocnewsapi.cpp#L157

However I don't have an instance of nextCloud/ownCloud, maybe you can patch it and file a pull request.
