### ISSUE TITLE
Finished entries are shown as "incomplete" after quitting and reopening podboat

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#714]
**Newsboat version**: commit 17670a1619bd6407cf137dcfbc8f3f5624f3b169 (origin/master)

Steps to reproduce the issue:
1. Add item to queue using newsboat
2. Open podboat
3. Play file; Mark entry as finished
4. Quit podboat
5. Open podboat

Expected behaviour: Entry is shown as "finished"

Actual behaviour: Entry is shown as "incomplete"

**Comment by Minoru** [comment]
Fixed by #715.
