### ISSUE TITLE
Feedlist position is not always updated with `show-read-feeds false`

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#72]
**Newsboat version (copy from `newsboat -v`)**: r2.10.1-110-g7f11

As reported by @polyzen in #70:

1. Disable `show-read-feeds`
2. Enter the feed at the bottom of the feed list
3. Mark its articles as read
4. Go back to the feed list
5. Enter the bottom feed (that was second from the bottom previously) while it's still highlighted
6. The feed that you had just marked as read is shown instead

**Other info you think is relevant**:

[My asciinema cast](https://asciinema.org/a/VHPuAum6RsmVFJf1LlmtquTah) that shows the steps, but not the results. This was shot with STFL 0.22.

I now reproduced this with STFL 0.24. Couldn't reproduce with STFL 0.23 (behaviour is the same as with 0.22).

**Comment by Minoru** [comment]
@polyzen, I think you'll have to revert back to STFL 0.23 for now. I'll try to find time to take a look at what changed in STFL between 0.23 and 0.24 to see if I can submit a patch upstream.

**Comment by polyzen** [comment]
Note that this only affects the bottom feed, so fairly minor, but I've downgraded nonetheless. :)

**Comment by Minoru** [comment]
There was only a handful of patches between 0.23 and 0.24, and two of them had to do with "pos_name" attribute, which was ostensibly broken and then fixed. Apparently, not *completely* fixed.

But after looking at the code for a bit, I think I'd rather figure out a way to move off libstfl to something maintained, than work on fixing the library itself.

**Comment by Minoru** [comment]
@polyzen this library seem to provide ready-made dialogs rather than widgets that we can use to build our own UIs. We have a separate issue for STFL work, #232; please see [my comment](https://github.com/newsboat/newsboat/issues/232#issuecomment-419732632) there.

**Comment by dennisschagt** [comment]
This is caused by a bug in stfl (description: https://github.com/dennisschagt/stfl/issues/3).
I've created a fix for it in my own fork of stfl (PR: https://github.com/dennisschagt/stfl/pull/4).

@Minoru: Is it useful to mention this in the changelog?

**Comment by Minoru** [comment]
> Is it useful to mention this in the changelog?

Absolutely! You can mark this issue closed from the commit that adds a changelog entry; there's nothing more that we can do here. Thanks for investigating and developing a fix!

Re-tagging as "invalid" since the bug isn't with Newsboat itself.
