### ISSUE TITLE
Podboat occasionally creates a directory named <filename>.part instead of a regular file

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#725]
**Newsboat version**: 2.18.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload yes
reload-time 10

browser /home/dennis/cr
player mpv

download-path "~/podcasts/%n"
podcast-auto-enqueue no

highlight article     "^Podcast Download URL:.*"            color71  default
```

Steps to reproduce the issue:
Unknown, I just discovered that there was a directory with the same `.part` name of a download which was failing (directory named `Waking_Up_138_Harari.mp3.part`).
Removing the .part directory made downloading possible again for that specific entry.

Output in log when failing:
```
[2020-01-22 11:45:58] DEBUG: KeyMap::get_operation: keycode = d context = podbeuter
[2020-01-22 11:45:58] INFO: PodDlThread::run: stat ok: starting download from 4096
[2020-01-22 11:45:58] DEBUG: PbView::run: updating view... downloads().size() = 591
```

**Other info you think is relevant**:
I expect it is caused by `directory` not being explicitly NULL-terminated in [poddlthread.cpp](https://github.com/newsboat/newsboat/blob/6ad28e2b8787d578c8c941af5abb038e0a723ce9/src/poddlthread.cpp#L89-L90).
If at some point the vector memory is allocated directly before some memory containing a slash, the `dirname` command will return the full file path instead of just the path until the containing directory.

I also had a directory in my podcasts folder named `Making_Sense_168_Tversky_RSS.mp3.part6367`. This probably had the same cause but had some non-NULL bytes ("6367") between the end of the vector and a '/'.

**Comment by Minoru** [comment]
Thanks for the report and the bugfix!
