### ISSUE TITLE
keybinding delete all

### ISSUE THREAD

**Issue by ralpheeee88** [newsboat/newsboat#73]
**Newsboat version (copy from `newsboat -v`)**:
newsboat 2.10.1

Feature Request: currently i have to press shift D for each article to be deleted. Would it be possible to have a keybinding to delete all news feeds just like shift A marks all news feeds as read?

**Comment by Minoru** [comment]
It's feasible, though ideally I'd like to have akrennmair/newsbeuter#235 so that users can write such keybindings themselves.
