### ISSUE TITLE
error while compiling: dependencies installed but still errors

### ISSUE THREAD

**Issue by franshesco** [newsboat/newsboat#74]
Hello, 

nice project but I have some errors while compiling on ubuntu 16:
```
/newsboat# make
Makefile:30: config.mk: No such file or directory
Checking for package sqlite3... not found

You need package sqlite3 in order to compile this program.
Please make sure it is installed.

You can download sqlite3 from here: newer)](http://www.sqlite.org/download.html)
newsboat
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... found
Checking for package ncursesw... found

One or more dependencies couldn't be found. Please install
these packages and retry compilation.
Makefile:316: recipe for target 'config.mk' failed
make: *** [config.mk] Error 1
```
I see the message about sqlite3 missing but it is installed 
```
# dpkg -l | grep sqlite3
ii  libaprutil1-dbd-sqlite3:amd64         1.5.4-1build1                              amd64        Apache Portable Runtime Utility Library - SQLite3 Driver
ii  libdbd-sqlite3-perl                   1.50-1                                     amd64        Perl DBI driver with a self-contained RDBMS
ii  libsqlite3-0:amd64                    3.11.0-1ubuntu1                            amd64        SQLite 3 shared library
ii  sqlite3                               3.11.0-1ubuntu1                            amd64        Command line interface for SQLite 3
ii  sqlite3-doc                           3.11.0-1ubuntu1                            all          SQLite 3 documentation
ii  sqlite3-pcre                          0~git20070120091816+4229ecc-0ubuntu1       amd64        Perl-compatible regular expression support for SQLite
```

so I don't understand which dependencies are still missing. On centos 7 and arch linux 2017 I have problems with stfl which I can't install.
On Arch
```
# make
gcc -pthread -I. -Wall -Os -ggdb -D_GNU_SOURCE -fPIC   -c -o public.o public.c
In file included from public.c:23:0:
stfl_internals.h:31:10: fatal error: ncursesw/ncurses.h: No such file or directory
 #include <ncursesw/ncurses.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: public.o] Error 1
```

On centos
```
cd perl5 && swig -perl5 stfl.i && perl Makefile.PL
../swig/basedecls.i:87: Warning 314: 'dump' is a perl keyword
../swig/basedecls.i:181: Warning 314: 'dump' is a perl keyword
Can't locate ExtUtils/MakeMaker.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 1.
BEGIN failed--compilation aborted at Makefile.PL line 1.
make: *** [perl5/build_ok] Error 2
```

Can you help me to understand what's going wrong, please?

EDIT: I have updated the errors

Thx

**Comment by tsipinakis** [comment]
You're missing the development headers, `libsqlite3-dev`.

**Comment by franshesco** [comment]
Hello @tsipinakis ,

thx for your reply. I have installed the dev headers you mentioned but I get another error:
`# make
Makefile:30: config.mk: No such file or directory
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... found
Checking for package ncursesw... found
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\" -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/json-c -D_GNU_SOURCE -I/usr/include/ncursesw -o doc/generate doc/generate.cpp
doc/generate doc/configcommands.dsv > doc/newsboat-cfgcmds.txt
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\" -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/json-c -D_GNU_SOURCE -I/usr/include/ncursesw -o doc/generate2 doc/generate2.cpp
doc/generate2 doc/keycmds.dsv > doc/newsboat-keycmds.txt
a2x -f manpage doc/manpage-newsboat.txt
make: a2x: Command not found
Makefile:184: recipe for target 'doc/newsboat.1' failed
make: *** [doc/newsboat.1] Error 127`

**Comment by tsipinakis** [comment]
From the [newsboat package](https://ftp-master.debian.org/new/newsboat_2.10.1-1.html) the full dependency list for debian/ubuntu is
```
libncursesw5-dev, ncurses-term, debhelper (>=9), libxml2-dev, libstfl-dev, libsqlite3-dev, perl, pkg-config, libcurl4-gnutls-dev, libjson-c-dev, asciidoc, libxml2-utils, xsltproc, docbook-xml, docbook-xsl, bc
```

You're probably missing the last ones related to building the docs (asciidoc and the like).

---

PS. You can use code blocks like this
```
` ``
Text here
` `` 
```

To get a much prettier text block (remove the space between the ticks, just there to prevent github catching it as actual formatting.

**Comment by franshesco** [comment]
@tsipinakis thx for your suggestion, i will the code blocks. 

Now i am trying to install all the dependencies if any can be missing. 

I will inform you. thx

**Comment by franshesco** [comment]
hello @tsipinakis ,

thx for your help. I have finally installed on Ubuntu 16 by installing all the dependencies. 

Now I will try it on Centos 7 and arch linux 2017 too. 

thx

**Comment by franshesco** [comment]
Hello @tsipinakis ,

I have a problem on centos 7, I have installed stfl
` ``
make -C perl5 DESTDIR=/ PREFIX=/usr/local install_vendor
make[1]: Entering directory `/root/stfl/stfl-0.24/perl5'
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Appending installation info to //usr/lib64/perl5/perllocal.pod
make[1]: Leaving directory `/root/stfl/stfl-0.24/perl5'
mkdir -p //usr/lib64/python2.7/site-packages/
mkdir -p //usr/lib64/python2.7/site-packages/lib-dynload/
cp python/_stfl.so //usr/lib64/python2.7/site-packages/lib-dynload/
cp python/stfl.pyc //usr/lib64/python2.7/site-packages/
cp python/stfl.py //usr/lib64/python2.7/site-packages/
mkdir -p //usr/local/lib/pkgconfig
mkdir -p //usr/local/include
install -m 644 libstfl.a //usr/local/lib
install -m 644 stfl.h //usr/local/include/
install -m 644 stfl.pc //usr/local/lib/pkgconfig/
install -m 644 libstfl.so.0.24 //usr/local/lib
ln -fs libstfl.so.0.24 //usr/local/lib/libstfl.so
` `` 

But when compiling newsboat, it doesn't find stfl

` ``
Makefile:30: config.mk: No such file or directory
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... not found

You need package stfl in order to compile this program.
Please make sure it is installed.

You can download stfl from here: newer)](http://www.clifford.at/stfl/)
Checking for package json... found
Checking for package ncursesw... found

One or more dependencies couldn't be found. Please install
these packages and retry compilation.
make: *** [config.mk] Error 1
` ``

**Comment by Minoru** [comment]
@franshesco, I edited your post to fix formatting of the code blocks. Check out [this help page](https://guides.github.com/features/mastering-markdown/), it got examples!

As for your problem with STFL: do you have `//usr/local/lib/pkgconfig/` in your `PKG_CONFIG_PATH` environment variable? Please show the output of `env | grep PKG_CONFIG_PATH | grep '//usr/local/lib/pkgconfig/'`.

**Comment by franshesco** [comment]
Hello  @Minoru,

thx for your help and the link because I was using spaces in the code blocks.

The command `env | grep PKG_CONFIG_PATH | grep '//usr/local/lib/pkgconfig/'` doesn't give a return but the pkgconfig package is installed

```
# rpm -qa | grep pkg
pkgconfig-0.27.1-4.el7.x86_64
```

**Comment by Minoru** [comment]
Okay, run this: `export PKG_CONFIG_PATH=//usr/local/lib/pkgconfig/`, then *in the same terminal* try to build Newsboat. `pkg-config` simply can't find a description of `libstfl` because it doesn't know where to look. By providing `PKG_CONFIG_PATH`, we tell it where to search. Hope this helps!

**Comment by franshesco** [comment]
hello @Minoru ,

thx for the help. I have configure the path and all the libraries are found while compiling newsboat but I get some news errors as below:

```
# make
Makefile:30: config.mk: No such file or directory
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... found
Checking for package ncursesw... found
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o doc/generate doc/generate.cpp
doc/generate doc/configcommands.dsv > doc/newsboat-cfgcmds.txt
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o doc/generate2 doc/generate2.cpp
doc/generate2 doc/keycmds.dsv > doc/newsboat-keycmds.txt
a2x -f manpage doc/manpage-newsboat.txt
doc/generate doc/podboat-cmds.dsv 'pb-' > doc/podboat-cfgcmds.txt
a2x -f manpage doc/manpage-podboat.txt
sed -E 's/^([^|]+)/[[\1]]<<\1,`\1`>>/' doc/configcommands.dsv > doc/configcommands-linked.dsv
sed -E 's/^([^|]+)/[[\1]]<<\1,`\1`>>/' doc/keycmds.dsv > doc/keycmds-linked.dsv
sed -E 's/^([^|]+)/[[\1]]<<\1,`\1`>>/' doc/podboat-cmds.dsv > doc/podboat-cmds-linked.dsv
mkdir -p doc/xhtml
a2x -f xhtml -D doc/xhtml doc/newsboat.txt
chmod u+w doc/xhtml/docbook-xsl.css
echo "/* AsciiDoc's new tables have <p> inside <td> which wastes vertical space, so fix it */" >> doc/xhtml/docbook-xsl.css
echo "td > p { margin: 0; }" >> doc/xhtml/docbook-xsl.css
echo "td > p + p { margin-top: 0.5em; }" >> doc/xhtml/docbook-xsl.css
echo "td > pre { margin: 0; white-space: pre-wrap; }" >> doc/xhtml/docbook-xsl.css
mkdir -p doc/xhtml
a2x -f xhtml -D doc/xhtml doc/faq.txt
chmod u+w doc/xhtml/docbook-xsl.css
echo "/* AsciiDoc's new tables have <p> inside <td> which wastes vertical space, so fix it */" >> doc/xhtml/docbook-xsl.css
echo "td > p { margin: 0; }" >> doc/xhtml/docbook-xsl.css
echo "td > p + p { margin-top: 0.5em; }" >> doc/xhtml/docbook-xsl.css
echo "td > pre { margin: 0; white-space: pre-wrap; }" >> doc/xhtml/docbook-xsl.css
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/configcontainer.o -c src/configcontainer.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/configparser.o -c src/configparser.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/colormanager.o -c src/colormanager.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/keymap.o -c src/keymap.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/stflpp.o -c src/stflpp.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/logger.o -c src/logger.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/exception.o -c src/exception.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1-110-g7f11\"   -I/usr/include/libxml2   -I/usr/local/include   -I/usr/include/json-c    -o src/utils.o -c src/utils.cpp
src/utils.cpp: In static member function ‘static std::string newsboat::utils::make_title(const string&)’:
src/utils.cpp:1027:40: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [1])’
  title = std::regex_replace(title,rx,"");
                                        ^
src/utils.cpp:1027:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from src/utils.cpp:26:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
src/utils.cpp:1027:40: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
  title = std::regex_replace(title,rx,"");
                                        ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from src/utils.cpp:26:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
src/utils.cpp:1027:40: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
  title = std::regex_replace(title,rx,"");
                                        ^
make: *** [src/utils.o] Error 1
```
thx for your time

**Comment by Minoru** [comment]
```
In file included from /usr/include/c++/4.8.2/regex:62:0
```

Judging by this line, you have GCC 4.8.2, which is a bit too old to build Newsboat. Try GCC 4.9 (or newer), or Clang 3.6 (or newer).

**Comment by franshesco** [comment]
Hi,

It is true that I have tried to install gcc 4.9.2 by compiling but even
after the installation, when checking it is always the 4.8 gcc version.

 Now I will try to install a more recent version and let you know

**Comment by Minoru** [comment]
@franshesco, did you have any luck compiling with a newer GCC?

**Comment by Minoru** [comment]
No response in half a year, and the issue seems resolved anyway. Closing.

**Comment by TheFatDave** [comment]
Hello, sorry for reopening this! I am on CentOS 7 and had exactly the same problems, but managed to successfully compile and install newsboat with a newer gcc. 

However when I run newsboat it returns: 

> newsboat: error while loading shared libraries: libstfl.so.0: cannot open shared object file: No such file or directory

/usr/local/lib contains libstfl.so and libstfl.so.0.24

I don't know how to get a more verbose error output.

I am not familiar with stfl at all and can' say I'm going to become a big fan after the ordeal it has given me so far :)

Thank you.

**Comment by Minoru** [comment]
@TheFatDave The error message says "libstfl.so.0", with a zero at the end. That should be a symlink to "libstfl.so.0.24". Usually the package manager sets those up, I don't know why it didn't in your case. Hope this helps!

**Comment by TheFatDave** [comment]
Hi,

I built stfl myself, because (as far as I am aware) there is no package for RHEL/Centos. 
I tried `ln -s libstfl.so.0.24 libstfl.so.0`, but that didn't help. Do you know what sort of other linking would need to be done (and which location)?

Thank you for your help so far!

**Comment by Minoru** [comment]
Try re-create ld cache by running `sudo ldconfig`. Then run `ldd newsboat` (where "newsboat" is a filename, so if you don't have it in the current directory -- navigate there, or use a proper path):

```
$ ldd newsboat
	linux-vdso.so.1 (0x00007fffb1bfa000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f18fa015000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f18fa010000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f18f9ee6000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f18f9e55000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f18f9c9c000)
	libstfl.so.0 => /usr/lib/libstfl.so.0 (0x00007f18f9c8d000)
…
```

That should list libraries along with their paths.

If that doesn't help, check if ld even looks into /usr/local/lib. There is a config in /etc/ld.so.conf, it should mention that directory. (There might also be /etc/ld.so.conf.d/, look in there too).

**Comment by TheFatDave** [comment]
Ld didn't look into /usr/local/lib, so i added `/usr/local/lib` to it and now it works! Now I feel stupid.

Thank you very much!

**Comment by Minoru** [comment]
Don't feel stupid! Distributions like Centos exist so that you don't need to know all this stuff.

Glad you've resolved it! ^_^
