### ISSUE TITLE
Feed titles disappear if reload brought no new items

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#748]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat r2.18-117-gd6ea - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `./newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat r2.18-117-gd6ea
System: Linux 5.4.0-3-amd64 (x86_64)
Compiler: g++ 9.2.1 20200123
ncurses: ncurses 6.1.20191019 (compiled with 6.1)
libcurl: libcurl/7.67.0 GnuTLS/3.6.11 zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.40.0 librtmp/2.3 (compiled with 7.67.0)
SQLite: 3.31.1 (compiled with 3.31.1)
libxml2: compiled with 2.9.4

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload yes
download-retries 5
reload-threads 100
goto-first-unread no
text-width 72
confirm-exit yes
mark-as-read-on-hover yes
show-read-articles no
show-read-feeds no

# Due to https://github.com/akrennmair/newsbeuter/issues/457 , I'm un-learning
# to delete processed articles—something I used to do before. To that end, I'm
# re-binding d from delete-article to toggle-article-read.
unbind-key D
bind-key d toggle-article-read

bind-key ESC quit

unbind-key O
bind-key O open-all-unread-in-browser-and-mark-read

# make currently focused unread item more visible
color listnormal blue black
color listnormal_unread green black
color listfocus white black
color listfocus_unread white black bold

highlight article "^Feed: .*$" white default
highlight article "^Title: .*$" white default bold
highlight article "^(Author|Link|Date):.*$" cyan default

browser /usr/bin/firefox

urls-source "local"
```

Steps to reproduce the issue:

1. Add any feed URL

2. Reload the feed once. Notice that the URL is replaced by the title in the feed list

3. Immediately reload the feed again. If that reload adds no new items, the title is replaced by the URL again.

The expected behaviour is for titles to remain, even if reload brought no new items.

**Other info you think is relevant**:
@Seirdy reproduced it too:

```
newsboat r2.18-117-gd6ea - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat r2.18-117-gd6ea
System: Linux 5.4.15-200.fc31.x86_64 (x86_64)
Compiler: g++ Clang 9.0.0 (Fedora 9.0.0-1.fc31)
ncurses: ncurses 6.1.20190803 (compiled with 6.1)
libcurl: libcurl/7.66.0 OpenSSL/1.1.1d-fips zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 (compiled with 7.66.0)
SQLite: 3.30.0 (compiled with 3.30.0)
libxml2: compiled with 2.9.10
```

Config:

```
# vim: set ft=conf
browser "firefox-nightly %u &"
prepopulate-query-feeds yes
bookmark-cmd "$XDG_DATA_DIR/newsboat/send-to-pocket.sh"
bookmark-autopilot yes
history-limit 400
text-width 88
# user-agent "Lynx/2.8.9rel.1 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/1.0.2s"
# html-renderer "w3m -dump -T text/html"
external-url-viewer "url-picker"
suppress-first-reload yes

# Display and sort by first tag
feed-sort-order firsttag
feedlist-format "%4i %n %10T %9u %t"

# Reloading
refresh-on-startup no
auto-reload yes
reload-time 10
reload-threads 400
download-retries 4

# Notifications
notify-always no
notify-program notify-send
notify-format "Newsboat: %n unread articles in %f feeds"

# Keybinds
unbind-key k
bind-key k up
unbind-key j
bind-key j down
unbind-key q
bind-key q hard-quit
unbind-key l
bind-key l open
unbind-key h
bind-key h quit
unbind-key m
bind-key m toggle-show-read-feeds
unbind-key g
unbind-key G
bind-key g home
bind-key G end
bind-key f pb-mark-as-finished

# Filter out some articles
ignore-mode "display"
ignore-article https://lwn.net/headlines/newrss "title =~ \"Security updates for\""
ignore-article https://lwn.net/headlines/newrss "title =~ \"stable kernel\""

# Macros
macro y set browser "echo -n %u | wl-copy"; open-in-browser ; set browser "$BROWSER %u"
macro p set browser "pockyt put -i %u"; open-in-browser ; set browser "$BROWSER %u"
# Downloading stuff
macro Y set browser "ytdl-rss %u"; open-in-browser ; set browser "$BROWSER %u"
macro m set browser "mpv %u"; open-in-browser ; set browser "$BROWSER %u"
podcast-auto-enqueue yes
macro E set browser "echo %u >> $XDG_DATA_DIR/newsboat/queue" ; open-in-browser ; set browser "$BROWSER %u"
macro w set browser "w3m -o display_image=false" ; open-in-browser ; set browser "$BROWSER %u"
macro W set browser "w3m-sandbox-tor" ; open-in-browser ; set browser "$BROWSER %u"
macro r set browser "tuir" ; open-in-browser ; set browser "$BROWSER %u"
macro R set browser "reader-mode" ; open-in-browser ; set browser "$BROWSER %u"

# Podcast downloading
download-path "~/Podcasts/%Y/%N"
download-filename-format "%F_%u"
max-downloads 50
player "mpv --profile=podcast"
podlist-format "%4i [%6dMB/%6tMB] [%5p %%] %10S %F"
```

**Comment by Minoru** [comment]
I'm already running git-bisect to figure out when this bug was introduced.

**Comment by Minoru** [comment]
Interestingly, this doesn't happen to all feeds. E.g. it happens to https://blog.torproject.org/blog/feed, but doesn't happen to https://www.reddit.com/r/mikrotik/.rss

**Comment by Minoru** [comment]
Regression introduced in d5a7ec1573b6d81a996305b96169347f285b48a9. Still don't quite understand how =\

**Comment by dennisschagt** [comment]
> Interestingly, this doesn't happen to all feeds. E.g. it happens to https://blog.torproject.org/blog/feed, but doesn't happen to https://www.reddit.com/r/mikrotik/.rss

That's probably also why I didn't catch it during some manual testing for PR #746 

> Still don't quite understand how =\

I'm wondering if this could be caused by an rss feed not being reloaded if `last-modified` header is present (resulting in a `replace_feed()` call with a feed that has no title set because the feed loading was skipped, just a guess)

I probably have time to further look into this in about an hour.

**Comment by Minoru** [comment]
> I'm wondering if this could be caused by an rss feed not being reloaded if last-modified header is present

You seem to be right on point: a quick check with `curl` confirms that the first feed sets ETag and Lat-Modified, while the second one doesn't.

My first hunch is to return `nullptr` instead of an unpopulated structure, but I need to re-read the surrounding code to see if there are better options available.
