### ISSUE TITLE
Additional tags for NextCloud feeds

### ISSUE THREAD

**Issue by mredaelli** [newsboat/newsboat#761]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
newsboat 
System: Linux 4.19.80 (x86_64)
Compiler: g++ 8.3.0
ncurses: ncurses 6.1.20190112 (compiled with 6.1)
libcurl: libcurl/7.65.3 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.9.0 nghttp2/1.39.2 (compiled with 7.65.3)
SQLite: 3.28.0 (compiled with 3.28.0)
libxml2: compiled with 2.9.9
```

I'm using newsboat with the News app in my Nextcloud instance, and it's working fine, with:
```
urls-source "ocnews"
ocnews-url "https://next.typish.io"
ocnews-login "..."
ocnews-passwordeval "..."
ocnews-flag-star "s"
```

My question is if it's possible to add additional tags to the feeds that are imported from nextcloud, beside the one coming from the nextcloud folder, specifying them in newsboat config files.

**Comment by Minoru** [comment]
Hi! This isn't possible. Can you describe a use-case for that? Why would you create two "sources of truth", and how would you handle discrepancies (e.g. a feed that's in the urls file is absent on Nextcloud, or vice versa)?

**Comment by mredaelli** [comment]
Sorry, I should have investigated a bit more (new user here). I think I can use filters to do the same thing I wanted.

Thanks!

**Comment by Minoru** [comment]
Ah, no problem ;) See also query feeds, they're a commonly used power-tool as well.
