### ISSUE TITLE
send to pocket fail

### ISSUE THREAD

**Issue by dmaglio** [newsboat/newsboat#78]
**Newsboat version (copy from `newsboat -v`)**:
```
newsboat 2.10.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Digita `newsboat -vv' per maggiori informazioni.

newsboat 2.10.1
System: Linux 4.13.16-202.fc26.x86_64 (x86_64)
Compiler: g++ 7.2.1 20170915 (Red Hat 7.2.1-2)
ncurses: ncurses 6.0.20170212 (compiled with 6.0)
libcurl: libcurl/7.53.1 NSS/3.33 zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.3) libssh2/1.8.0 nghttp2/1.21.1 (compiled with 7.53.1)
SQLite: 3.20.1 (compiled with 3.20.1)
libxml2: compiled with 2.9.4
```
Steps to reproduce the issue:

1. add macro in config:
```
macro k set browser "sh /home/damaglio/.config/newsboat/send-to-pocket.sh %u %T" ; open ; set browser opera
```

2. press 'k' in the article

3. check in getpocket page.... nothing....

**Other info you think is relevant**:
The attachment is the debug.log
[debug.log](https://github.com/newsboat/newsboat/files/1555845/debug.log)

**Comment by dmaglio** [comment]
same issue if my macro is
```
macro k set browser "sh /home/damaglio/.config/newsboat/send-to-pocket.sh %u %T" ; open-in-browser ; set browser opera
```

**Comment by Minoru** [comment]
Macros are invoked by pressing comma first, then the macro's letter; in your case, you have to type `,k`. And indeed using `open-in-browser` is correct because `open` displays the article in Newsboat itself, not the browser.

**Comment by dmaglio** [comment]
thank you, i have missing the comma. sorry... :)
ps: i searching for extend newsboat to Miniflux rss reader ;) Miniflux support json-rpc api and fever api

**Comment by Minoru** [comment]
You're welcome ;)

As for Miniflux, Newsboat doesn't support it at the moment. Such support is added by people who actually use such services, because it's hard to keep the code up-to-date without continuous testing. I'd be happy to review a PR to that end.
