### ISSUE TITLE
Match-beginning-of-line operator (^) also matches directly after a previous match

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#795]
**Newsboat version**: `r2.18-240-gb462e`

Config file:
```
highlight article "^." blue default
```

**Steps to reproduce the issue**:

1. Start newsboat, load a feed with at least 1 article

2. Open the first article of the feed

Expected behaviour:
The first character of each line is colored blue, all other characters have the default (white) color.

Actual behaviour:
All of the text is colored blue.

**Other info you think is relevant**:
Probably caused by calling `regexec(..)` again which does not know that this is not the start of string `str`.
https://github.com/newsboat/newsboat/blob/510ca21d834e0ea4f959622aeb984229e68f9c2a/src/regexmanager.cpp#L156-L157

I believe the `RegexManager::quote_and_highlight(..)` is called line-by-line.
If that is the case (I'm not complete sure), a solution might be to break out of the loop if the regular expression starts with character `'^'`.

**Comment by Minoru** [comment]
Good catch! Thanks for the report.

> I believe the RegexManager::quote_and_highlight(..) is called line-by-line.

That's correct: it's used only in two places, in [`ListFormatter`](https://github.com/newsboat/newsboat/blob/510ca21d834e0ea4f959622aeb984229e68f9c2a/src/listformatter.cpp#L82) and [`TextFormatter`](https://github.com/newsboat/newsboat/blob/510ca21d834e0ea4f959622aeb984229e68f9c2a/src/textformatter.cpp#L149), both of which call it inside `for (const auto& line : lines)` loop.

> a solution might be to break out of the loop if the regular expression starts with character '^'

That won't work with a regexp like `(^foo|^bar)`: it doesn't start with `^`, yet it will only match at the beginning of the line. `egrep` manages to work fine somehow even on that (tested with `echo foobar | egrep --colour '(^foo|^bar)'`).

**Comment by Minoru** [comment]
Oh, actually, we just need to pass `REG_NOTBOL` into `regexec`. Here's a quote from [regex(3)](http://man7.org/linux/man-pages/man3/regex.3.html):

              The match-beginning-of-line operator always fails to match
              (but see the compilation flag REG_NEWLINE above).  This flag
              may be used when different portions of a string are passed to
              regexec() and the beginning of the string should not be
              interpreted as the beginning of the line.

Precisely our situation!

There's also a symmetrical `REG_NOTEOL` that does the same to `$`, but I don't think we need it since (as you quote above) we only add offset at the beginning, never at the end.

**Comment by dennisschagt** [comment]
> That won't work with a regexp like (^foo|^bar): it doesn't start with ^, yet it will only match at the beginning of the line.

Good catch!
