### ISSUE TITLE
Feed title is not shown when it contains angle brackets (`<title>`)

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#796]
**Newsboat version**: r2.18-240-gb462e

Config file:
```
# empty
```

Urls file:
```
http://antirez.com/rss
```

**Steps to reproduce the issue**:

1. Setup urls file, open newsboat

2. Reload feed
    - **expected**: feed title is shown as `<antirez>`
    - **actual**: feed title is empty/invisible

3. Enter feed, open first article
    - **expected**: article shows `Feed: <antirez>`
    - **actual**: article shows `Feed: `

**Other info you think is relevant**:
Executing `sqlite3 .newsboat/cache.db "select title from rss_feed where rssurl == 'http://antirez.com/rss'"` shows `<antirez>` so the title is correctly retrieved and stored in the cache.

I expect the `<antirez>` title is interpreted as a style tag.

Solution might be to encode `<` and `>` according to stfl rules.
See http://svn.clifford.at/stfl/trunk/example.stfl:
```
"a smaller-than sign: <>"
"a greater-than sign: >"
```

**Comment by Minoru** [comment]
Linking old Newsbeuter issue: https://github.com/akrennmair/newsbeuter/issues/554
