### ISSUE TITLE
Problem with the SSL CA cert 

### ISSUE THREAD

**Issue by anishmittal2020** [newsboat/newsboat#805]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.18
usage: /home/linuxbrew/.linuxbrew/bin/newsboat

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# Browser
# =======
#browser google-chrome -private-window "$@" & # google-chrome Incognito --incognito
browser google-chrome "$@" & # google-chrome

# Macro
# =====
macro q mark-all-feeds-read ; quit
macro , open-in-browser
macro m set browser "mpv --sub-auto=fuzzy --screenshot-format=png --screenshot-template=Image_%F_%wH-%wM-%wS --screenshot-directory=Image --ytdl-format=best --ytdl-raw-options=sub-format=en,write-srt= --ytdl --ontop --no-border --force-window --autofit=960x540 --geometry=-20-50 %u > /dev/null 2>1 &"; open-in-browser ; set browser google-chrome
macro w set browser "w3m"; open-in-browser ; set browser google-chrome

## Not Used
# =========
#macro v set browser "setsid nohup mpv"; open-in-browser ; set browser google-chrome
#macro c set browser "xsel -b <<<" ; open-in-browser ; set browser google-chrome

## Task Spooler
# =============
#macro t set browser "tsp youtube-dl --add-metadata -ic"; open-in-browser ; set browser google-chrome
#macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best"; open-in-browser ; set browser google-chrome

# UI Colors
# =========
#color listnormal cyan default
#color listfocus black yellow standout bold
#color listnormal_unread blue default
#color listfocus_unread yellow default bold
#color info red black bold
#color article cyan default

color listnormal green default
color listnormal_unread green default
color listfocus green default reverse
color listfocus_unread green default reverse
color info green default reverse
color background green default
color article green default

# Format
# ======
feedlist-format "%4i %15T %30t %n %11u"
articlelist-format "%4i %f %D   %?T?|%-17T|  ?%t"
notify-format "%d new articles (%n unread articles, %f unread feeds)"

# Feed
# ====
auto-reload yes
reload-time 60
mark-as-read-on-hover yes
download-path "/home/nikhil/Downloads"

# articles hide and save
# ======================
ignore-article "*" "title =~ \"Sponsor\""
ignore-article "*" "title =~ \"Advertisement\""
ignore-mode "display"
save-path "~/Documents/Git/Other/PersonalManagement/Note/ArticlesNewsboat"

# URL Error Log
# ======================
error-log "~/.newsboat/error.log"

# Cache
# ========
# max-items: Set the number of articles to maximally keep per feed. If the number is set to 0, then all articles are kept.
# keep-articles-days: If set the a number greater than 0, only articles that are were published within the last <n> days are kept, and older articles are deleted. If set to 0 (default value), this option is not active.
max-items 0
keep-articles-days 0
```

# Issue

I was able to open Newsboat successfully till recently, but today I am getting the following errors. But, I am able to open the feed url in my browser.

# Error Log

```
[2020-03-10 21:11:04] Error while retrieving https://www.youtube.com/feeds/videos.xml?channel_id=UC6gNjP1W4FXWExT5QpYkmhQ: Problem with the SSL CA cert (path? access rights?)
[2020-03-10 21:11:04] Error while retrieving https://www.psychologytoday.com/intl/blog/essentials/feed: Problem with the SSL CA cert (path? access rights?)
```

**Comment by Minoru** [comment]
Hi! I couldn't reproduce this with Newsboat r2.18-280-g73a1 (current `master`) on an up-to-date Debian testing. The error itself comes from cURL, and the most likely cause seem to be an outdated root certificate.

First of all, check if `CURL_CA_BUNDLE` environment variable is set. Normally it shouldn't be, but if it is, you'll have to make sure it contains a path to an up-to-date CA bundle.

Second, check if your system has an up-to-date list of CA certificates. On Debian, that'd be `ca-certificates` package. Mine is on version 20190110. (Curiously, Firefox in Debian doesn't depend on this package, so apparently we can't say "works in browser so should work in Newsboat"—programs use different sets of certificates!)

Third, let's figure out if cURL is the culprit:

1. post the *whole* output of `newsboat -v`;
2. post the whole output of `curl --version`;
3. try to fetch one of the erroring feeds with cURL CLI:

    $ curl https://www.psychologytoday.com/intl/blog/essentials/feed

I expect that `curl` and `newsboat` list the same configuration for cURL, and for `curl` to fail on the last step.

I'm not convinced this is a bug in Newsboat, so labeling as question for now.

**Comment by anishmittal2020** [comment]
Yes, you are right. The problem was with curl. For all those who install `newsboat` using `brew` can refer this: [FAQ · Linuxbrew/brew Wiki](https://github.com/Linuxbrew/brew/wiki/FAQ#why-does-curl-fail)
