### ISSUE TITLE
Request: podcast URL in internal urlview

### ISSUE THREAD

**Issue by Spacewalker2** [newsboat/newsboat#809]
Hello,

first of all thanks for this cool feed reader! I'm using xclip instead of a browser. Defined in the config file. All the URLs I catch with o oder #< number > end up in a clipboard manager which is capable of filtering and auto executing scripts. In this setting it would be nice to have the podcast URLs available as well. Maybe this is interesting for others too?

Thanks for the effort!

**Comment by Minoru** [comment]
Hey, thanks for the kind words :heart: I'd accept a PR adding this.

This is fairly easy to implement; here's a few pointers:
- articles are displayed by a class called `ItemViewFormAction`. Its sources are in *include/itemviewformaction.h* and *src/itemviewformaction.cpp*;
- in that class, `prepare()` does all the heavy lifting of formatting the article and preparing a list of links. The links are stored in a member variable called `links`;
- inside `prepare()` we have access to a variable called `item` of type `RssItem` (its header and source are under *include/* and *src/*, of course). `item` stores the type and the URL of the enclosure, i.e. the podcast file. They can be accessed with methods `enclosure_type()` and `enclosure_url()`.

Piecing all of the above together, one should be able to add the enclosure link to the beginning of urls list. From there, it'll become available for `#` (`goto-url`) and `u` (`show-urls`).

**Comment by Spacewalker2** [comment]
I give it a try but I'm not a C++ developer at all. I did wrote some C programs now and then.
