### ISSUE TITLE
Why does Newsboat require me to manually create urls file?

### ISSUE THREAD

**Issue by Dubidubiduu** [newsboat/newsboat#823]
Installed by https://snapcraft.io/install/newsboat/debian#install, programm didn't started. Needed to create "urls" file by myself. :-/

**Comment by Minoru** [comment]
Newsboat lets you put configs either into a "dotdir" (~/.newsboat) or the XDG dirs. Since it doesn't know which one you prefer, it refuses to start until you state your preference by creating the `urls` file.

Does that answer your question?

**Comment by Dubidubiduu** [comment]
Wow, that is a fast reply.

Actually I don't care that much where the config is, though I guess it could be important. Somehow I spent half an hour searching how to get your program running. Would prefer any location for the configuration and a hint to change the config location before that time sink.

(Also as installed by snap, folder has been /home/xx/snap/newsboat/1617/.newsboat)

Other than that, now it is running and it looks great!

**Comment by Minoru** [comment]
> Somehow I spent half an hour searching how to get your program running. Would prefer any location for the configuration and a hint to change the config location before that time sink.

I'm on Debian testing, and here's what I just did:

```plain
$ sudo apt install snapd
[sudo] password for minoru: 
… output skipped …

$ sudo snap install newsboat
Warning: /snap/bin was not found in your $PATH. If you've not restarted your session since you
         installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more
         details.

newsboat r2.18 from Alexander Batischev (minoru) installed

$ /snap/bin/newsboat
Starting newsboat r2.18-dirty...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/minoru/snap/newsboat/1614/.newsboat/urls...done.
Error: no URLs configured. Please fill the file /home/minoru/snap/newsboat/1614/.newsboat/urls with RSS feed URLs or import an OPML file.
```

I'd say that the last sentence of that message isn't just a hint, it's a very clear instruction on what to do. Have you somehow missed it?

**Comment by Minoru** [comment]
Well, I think this is resolved, so I'm closing it. Please comment if you disagree, we can always re-open and delve further.
