### ISSUE TITLE
Couldn't find a view in @views for document

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#829]
Trying to compile the latest 2.19 from the sources. Config went ok, but make returns such error:
```
asciidoctor --backend=manpage doc/manpage-newsboat.asciidoc
Couldn't find a view in @views for document
  Use --trace for backtrace
Makefile:205: recipe for target 'doc/newsboat.1' failed
make: *** [doc/newsboat.1] Error 1
```
What I am missing?

**Comment by dennisschagt** [comment]
From [what I can find](https://github.com/asciidoctor/asciidoctor/issues/913#issuecomment-36811972), `"Couldn't find a view in @views for document"` is shown when a backend is not supported.

It looks like the `manpage` backend was added in asciidoctor 1.5.3:
https://github.com/asciidoctor/asciidoctor/blob/master/CHANGELOG.adoc#user-content-1-5-3-2015-10-31-mojavelinux

I expect that updating asciidoctor on your system will solve this issue.

**Comment by ZaxonXP** [comment]
Can I somehow skip the docs creation and just compile the reader? 

Currently I am running on Debian Jessie, and the asciidoctor is in the latest version for that distro.

**Comment by dennisschagt** [comment]
Running `make newsboat podboat mo-files` (instead of `make` or `make all`) might do what you want.
That would allow you to run `./newsboat` in the sources directory.

I'm not sure what to run instead of `make install` (the `install-newsboat` make target seems to depend on the manpage generated by asciidoctor).
Removing that dependency on the docs will probably require some changes in the Makefile.

---

Applying the following diff to the Makefile will remove the dependency on the doc from `make`, `make all`, and `make install` (I haven't tested this so no guarantees):
```
diff --git a/Makefile b/Makefile
index 8cde3dfe..174245cd 100644
--- a/Makefile
+++ b/Makefile
@@ -100,7 +100,7 @@ RUST_SRCS:=Cargo.toml $(shell find rust -type f)
 TEXTCONV=./txt2h
 RM=rm -f
 
-all: doc $(NEWSBOAT) $(PODBOAT) mo-files
+all: $(NEWSBOAT) $(PODBOAT) mo-files
 
 NB_DEPS=xlicense.h $(LIB_OUTPUT) $(FILTERLIB_OUTPUT) $(NEWSBOAT_OBJS) $(RSSPPLIB_OUTPUT) $(NEWSBOATLIB_OUTPUT)
 
@@ -242,17 +242,13 @@ cppcheck:
 		2>cppcheck.log
 	@echo "Done! See cppcheck.log for details."
 
-install-newsboat: $(NEWSBOAT) doc/$(NEWSBOAT).1
+install-newsboat: $(NEWSBOAT)
 	$(MKDIR) $(DESTDIR)$(prefix)/bin
 	$(INSTALL) $(NEWSBOAT) $(DESTDIR)$(prefix)/bin
-	$(MKDIR) $(DESTDIR)$(mandir)/man1
-	$(INSTALL) -m 644 doc/$(NEWSBOAT).1 $(DESTDIR)$(mandir)/man1 || true
 
-install-podboat: $(PODBOAT) doc/$(PODBOAT).1
+install-podboat: $(PODBOAT)
 	$(MKDIR) $(DESTDIR)$(prefix)/bin
 	$(INSTALL) $(PODBOAT) $(DESTDIR)$(prefix)/bin
-	$(MKDIR) $(DESTDIR)$(mandir)/man1
-	$(INSTALL) -m 644 doc/$(PODBOAT).1 $(DESTDIR)$(mandir)/man1 || true
 
 install-docs: doc
 	$(MKDIR) $(DESTDIR)$(docdir)
@@ -274,7 +270,7 @@ install-examples: doc/example-config
 	$(INSTALL) -m 755 doc/example-bookmark-plugin.sh $(DESTDIR)$(docdir)/examples/example-bookmark-plugin.sh || true
 
 
-install: install-newsboat install-podboat install-docs install-examples install-mo
+install: install-newsboat install-podboat install-examples install-mo
 
 uninstall: uninstall-mo
 	$(RM) $(DESTDIR)$(prefix)/bin/$(NEWSBOAT)
```

**Comment by Minoru** [comment]
> I'm not sure what to run instead of make install

A bit hacky, but far easier for the end user: just create empty files:

```
$ touch doc/newsboat.1 doc/podboat.1
```

I'll submit a PR to move manpage installations from `install-newsboat` and `install-podboat` targets to `install-docs`. Then users will be able to `make newsboat && sudo make install-newsboat` without even installing Asciidoc.

**Comment by ZaxonXP** [comment]
Thank you all for your help! I managed to compile and install the 2.19 on my old debian system. :)
