### ISSUE TITLE
Sanitizing forward-slashes in %t for download-filename-format

### ISSUE THREAD

**Issue by kentdobias** [newsboat/newsboat#836]
If a podcast has a forward-slash in its title, podboat will interpret the forward-slash as a directory break. It shouldn't do this.

I would prefer if forward-slashes were replaced by a unicode solidus (∕ versus /), but I'm open to other solutions.

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.19.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.19.0
System: Linux 5.5.10-arch1-1 (x86_64)
Compiler: g++ 9.3.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.69.1 OpenSSL/1.1.1e zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.39.2 (compiled with 7.69.1)
SQLite: 3.31.1 (compiled with 3.31.1)
libxml2: compiled with 2.9.10
```
**Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):**

```
download-filename-format "%n/%F - %t.%e"
```

**URLs file:**

```
https://feeds.soundcloud.com/users/soundcloud:users:622072686/sounds.rss podcast
```

**Steps to reproduce the issue:**

1. Start `newsboat` with above config and urls.

2. Enqueue any episode of the feed with "w/" in its title.

3. Start `podboat` and download the enqueued episode.

4. Look for podcast in output directory:
```
% ls -R ~/Hear\ the\ Bern 
'Hear the Bern':
'2020-03-24 - 50 - Shelter & Grace (w'

'Hear the Bern/2020-03-24 - 50 - Shelter & Grace (w':
' Natalie Wynn).mp3'
```
The podcast was saved as ' Natalie Wynn).mp3' to the directory 'Hear the Bern/2020-03-24 - 50 - Shelter & Grace (w'.

**Comment by Minoru** [comment]
Thanks for the report!

> a unicode solidus (∕ versus /)

Wow, didn't know about this character; thanks! But it looks like it's not solidus, it's [a division slash](https://www.fileformat.info/info/unicode/char/2215/index.htm); solidus is [the good old ASCII slash](https://www.fileformat.info/info/unicode/char/2f/index.htm).

Division slash looks nifty, but I'd hate to type it, e.g. to unblock the autocomplete in the terminal. I got XCompose to help me, but I'd have to figure out the right accord to type. I'd rather use an underscore here.

**Comment by kentdobias** [comment]
I understand not everyone leans on tab-complete as much as I do—an underscore is a fine solution.
