### ISSUE TITLE
How to reload URL file?

### ISSUE THREAD

**Issue by ZaxonXP** [newsboat/newsboat#839]
Is there a way to reload the URL file without closing and opening the newsboat nor using E key to edit it?

Sometimes I update the file with a new sources, and I would like to reload it.

**Comment by Minoru** [comment]
Yes, via [`reload-urls` operation](https://newsboat.org/releases/2.19/docs/newsboat.html#reload-urls), bound to `^R` by default.

Presumably you looked through the docs before asking the question, so I have to wonder: what exactly did you search for? I'd like to improve docs to make this more discoverable, if I can.

**Comment by ZaxonXP** [comment]
Indeed, this is what I needed. Somehow I overlooked it in the help screen. And the help description is clear.

In which version this feature was added?

**Comment by dennisschagt** [comment]
> In which version this feature was added?

Looks like it was already added in Newsbeuter (long before the fork into Newsboat),
see commit https://github.com/newsboat/newsboat/commit/0329d21a74f27b02d4ba5a58849c9d1c9cd0e12f#diff-4735f2efdba4d425e7c959ea1f5b73d3R36
which was released as part of Newsbeuter 0.6.

**Comment by ZaxonXP** [comment]
So then I must overlooked it somehow. Thanks for the info,
