### ISSUE TITLE
FTBFS on GNU/Hurd

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#85]
Copy of akrennmair/newsbeuter#413 adding it here since it was re-submitted to the [debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884894)

---

Newsbeuter fails to build with the hurd kernel on the [debian package builder](https://buildd.debian.org/status/package.php?p=newsboat) ([full build log](https://buildd.debian.org/status/fetch.php?pkg=newsboat&arch=hurd-i386&ver=2.10.1-1&stamp=1513625723&raw=0))

The reason appears to be that hurd does not have the MAXPATHLEN macro defined, [wiki confirms it and provides some example patches](https://www.gnu.org/software/hurd/hurd/porting/guidelines.html#PATH_MAX_tt_MAX_PATH_tt_MAXPATHL)

While I am not sure how well newsboat would work on hurd (I do not use the system myself so I am unable to test it) it's probably worth looking into.

**Comment by Minoru** [comment]
Geometrically growing buffer seem to be the best solution (simple yet absolutely portable). I'll implement it tomorrow, but will only test on Linux and OS X as I don't have a Hurd system.

**Comment by Minoru** [comment]
BTW, @tsipinakis, you don't need to backport this—I intend to push out a new version before New Year.

**Comment by tsipinakis** [comment]
Oh, thanks for the heads up I'll wait for a new release then.
