### ISSUE TITLE
Change default highlighted text colour

### ISSUE THREAD

**Issue by bitigchi** [newsboat/newsboat#863]
System: Darwin 19.4.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2 (compiled with 7.64.1)
SQLite: 3.31.1 (compiled with 3.31.1)
libxml2: compiled with 2.9.4

I am aware that colours can be configured, but the default yellow-on-cyan colour scheme is a bit too bright on (at least) my configuration on iTerm2. Cyan background is fine, but changing the default text colour to black or at least something darker would help with readability a lot.

<img width="682" alt="Ekran Resmi 2020-04-03 18 29 31" src="https://user-images.githubusercontent.com/2769571/78378199-530dfc80-75d9-11ea-9dd5-c65b50eee660.png">

Steps to reproduce the issue:

1. Open newsboat

**Comment by Minoru** [comment]
There's no knowing what colorscheme user's terminal would use. Optimizing defaults for your colorscheme will break someone else's default look, so we simply use what other similar programs use.
