### ISSUE TITLE
String format sequence "%>[char]" doesn't work with articlelist-title-format

### ISSUE THREAD

**Issue by mikepierce** [newsboat/newsboat#88]
Newsboat r2.10.1-110-g7f11

I've got the following lines in my newsboat config:

    feedlist-title-format "%N - feeds %>-"
    articlelist-title-format "%N - %T %>-"
    itemview-title-format "%T %>-"

That [format sequence](https://newsboat.org/releases/2.10.1/docs/newsboat.html#_format_strings) `%>-`, which is supposed to create a line of hyphens to the right edge of the terminal window, doesn't work for `articlelist-title-format`, although it works for the other two. It also appears to not work with (at least) `help-title-format` too.

**Comment by Minoru** [comment]
Reproduced; thanks for the report! I'll look into this once I've pushed out 2.10.2.
