### ISSUE TITLE
Automatically open specific feed upon startup

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#888]
yaymukund on IRC just asked if it's possible to automatically open a specific feed when Newsboat starts up. They aren't the first one to request that, see https://github.com/akrennmair/newsbeuter/issues/402 for the previous discussion.

**Comment by dennisschagt** [comment]
This will be possible in the next releaseof Newsboat (or by building from the current master branch).

You can use the `run-on-startup` option in the config file to select a feed based on (part of) its title and then open it, e.g.:
```
run-on-startup      goto-title "newsboat" ; open
```
