### ISSUE TITLE
Run command by name from newsboat cli

### ISSUE THREAD

**Issue by mjsir911** [newsboat/newsboat#892]
It would be nice to run a command not bound by a key for those rare use-cases that don't warrant a full keybind.

> Although a sane person would probbaly expect it to be available through the command line... But sadly, command line is totally separate from ops.

Either:
- having it run from the command line directly, eg 
```
:open-all-unread-in-browser-and-mark-read
```
- implementing an `:exec` command a-la mutt so:
```
:exec open-all-unread-in-browser-and-mark-read
```

**Comment by Minoru** [comment]
I prefer the first option. I guess the next step is to compile a list of conflicting names and decide how to resolve each one.

**Comment by mjsir911** [comment]
There are not many cli commands, only conflict is `quit`, which does different things as a cli command vs a newsboat bound command

cli command: quits entire newsboat
bound command: returns to previous dialog

**Comment by Minoru** [comment]
Bound command also quits the program if we're in the topmost dialog, i.e. feedlist.

Thinking about this a bit more, I realize there's something else that a sane person might expect to find on the command line: all the configuration commands, like `bind-key` or `include`. That's where your second suggested design, `exec`, starts looking more appropriate.

Let me sleep on this, and I'll get back to you tomorrow.

**Comment by Minoru** [comment]
Okay, let's go with `exec`. It's more generic, i.e. we can add more command-line commands without adding them as bindable operations.
