### ISSUE TITLE
Cannot bind special keys like "UP" and "DOWN" to operations

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#903]
**Newsboat version**: 2.19

Config file:

```
bind-key UP open
bind-key DOWN open
bind-key HOME open
bind-key END open
bind-key PPAGE open
bind-key NPAGE open
```

Steps to reproduce the issue:

1. Start Newsboat with given config file

2. Press any of the configured keys

3. Observe that none of those keys result in opening the selected feed

**Other info you think is relevant**:
These keys are handled directly by STFL.
We currently add `"**"` (see [1]) to each of the `bind_<action>` variables which causes STFL to apply the default key-bindings (see [2]).

Related to #546 which reports a similar issue with the `"SPACE"` key.

[1] [`View::set_bindings`](https://github.com/newsboat/newsboat/blob/4edcbddc4f0d27c4df6a736df45b6edf08baf049/src/view.cpp#L103-L134)
[2] http://svn.clifford.at/stfl/trunk/README (search for `"**"`)

**Comment by Minoru** [comment]
> We can handle actions like OP_SK_UP directly instead of putting it on the input queue of STFL

Meaning we'll keep track of where the cursor is, and move it up/down ourselves? Can we tell STFL to move the cursor without putting something onto its queue, though?

Handling it ourselves will also enable us to add half-page scrolling requested in https://github.com/newsboat/newsboat/issues/36.

**Comment by dennisschagt** [comment]
> Meaning we'll keep track of where the cursor is, and move it up/down ourselves?

Either that or get the current position from STFL and write the updated position.

> Can we tell STFL to move the cursor without putting something onto its queue, though?

Yes, we are doing that already in some places, see for example:
- Getting current position: https://github.com/newsboat/newsboat/blob/4edcbddc4f0d27c4df6a736df45b6edf08baf049/src/feedlistformaction.cpp#L788
- Writing the new position: https://github.com/newsboat/newsboat/blob/4edcbddc4f0d27c4df6a736df45b6edf08baf049/src/feedlistformaction.cpp#L796

`"feedpos"` is bound to `"pos"` [in our .stfl files](https://github.com/newsboat/newsboat/blob/4edcbddc4f0d27c4df6a736df45b6edf08baf049/stfl/feedlist.stfl#L23). STFL also [changes the position using it's `"pos"` variable](https://github.com/dennisschagt/stfl/blob/cc355eb6a28e5ad25d20d5b83b57ad6ea1ada316/widgets/wt_list.c#L219-L269) (seach for `L"pos"`).

> Handling it ourselves will also enable us to add half-page scrolling requested in #36.

Yes, nice find.

Another one is issue https://github.com/newsboat/newsboat/issues/215

Scrolling can be controlled using the "offset" variable of a list.
STFL automatically does that for us [when the currently selected position is out of view](https://github.com/dennisschagt/stfl/blob/cc355eb6a28e5ad25d20d5b83b57ad6ea1ada316/widgets/wt_list.c#L64-L69).
We can also directly change that variable in the same way as we are changing the position (by making the `"offset"` variable accessible in our .stfl files).

**Comment by Minoru** [comment]
> Scrolling can be controlled using the "offset" variable of a list.

Oh, that would let us implement a Vim-like "scrolloffset" setting: https://github.com/akrennmair/newsbeuter/issues/191

Sounds like an extremely fruitful change, @dennisschagt, thanks for realizing that this is possible!
