### ISSUE TITLE
Query feeds with multiple filters?

### ISSUE THREAD

**Issue by Mati20187** [newsboat/newsboat#912]
I'll keep it simple. I want to create a query feed that would contain unread articles from feeds tagged with "News" but it requires two filter expressions: `unread = \"yes\""` and `tags # \"News\""`.
How can I create such a query? I couldn't find any information on how to use multiple filters in one query.

**Comment by der-lyse** [comment]
[According to the second example in the docs](https://newsboat.org/releases/2.19/docs/newsboat.html#_filter_language) you can use the logical operators `and` resp. `or`.

**Comment by Mati20187** [comment]
Yeah, you're right. I didn't think it also works with queries. The correct syntax in my case is `"query:Unread-Video:unread = \"yes\" and tags # \"Video\"" "Unread"`. Thanks!
