### ISSUE TITLE
Get rid of "none" logging level

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#921]
Newsboat writes logs (two, in fact, but that's not important for this issue). On the C++ side, we have a `LOG` macro, and on the Rust side we have `log!`. We also have a list of "logging levels"; it's implemented as [`enum class Level` in C++](https://github.com/newsboat/newsboat/blob/0b86c8e5044abbd7540eb808d9bc64f40a83808b/include/logger.h#L19) and [`enum Level` in Rust](https://github.com/newsboat/newsboat/blob/0b86c8e5044abbd7540eb808d9bc64f40a83808b/rust/libnewsboat/src/logger.rs#L18-L56).

`NONE` (C++) / `None` (Rust) level is special. We never actually pass it into `LOG`/`log!`. This level is purely for `Logger`'s internal usage, so that the logger knows that it *shouldn't* log anything at all.

It's a bit lame to expose an external detail to the users of the `log!` macro, so let's hide this. The loglevel is stored in an `AtomicUsize` variable, so we can't use `Option`. Instead, let's change it to `AtomicIsize`, and encode `None` as `-1`.

Rough TODO:
1. Make Rust `Logger` struct store the loglevel in `AtomicIsize`.
2. Adjust `rs_get_loglevel()` to return a signed value.
3. Figure out what to do with `set_loglevel()`, as it won't be able to set loglevel to "none". Just add an `unset_loglevel()` that simply sets loglevel to `-1`?
4. We have a `--log-level` CLI option, make sure its values are still parsed as they should.
5. Drop `NONE`/`None` level.

**Comment by nick-cd** [comment]
I think I can help out with this one! This one looks interesting.

**Comment by Minoru** [comment]
Cool! Have at it ;)
