### ISSUE TITLE
Ability to apply pre-defined filter on startup

### ISSUE THREAD

**Issue by dikeert** [newsboat/newsboat#93]
Currently if I have 'local' as my urls-source I can apply specific tag and hide feeds from feed list.
I use this functionality to hide all of the feeds and show Query Feeds instead.

However, if I switch urls-source to have something different than local (tt-rss in my case), I loose that ability. I still can have my Query Feed in urls file but I can't hide those feeds anymore.

So I created a pre-defined filter which shows only feeds with tag _QUERY_ to filter feeds out, but I need to apply this filter manually each time I open newsboat.

That would be awesome to have ability to specify 'on-startup' filter to be applied automatically.

**Comment by Minoru** [comment]
I think that's a good idea; thanks for bringing it up!

**Comment by dennisschagt** [comment]
It looks like this is possible with the `run-on-startup` option (https://github.com/newsboat/newsboat/pull/1134).

An example configuration:
```
run-on-startup      set-filter "tags # \"QUERY\""
```
or
```
run-on-startup      set-tag "QUERY"
```

**Comment by dennisschagt** [comment]
Closing this issue as the requested option is now available (see my previous comment).
Feel free to reopen this issue if you disagree or if anything is unclear.

**Comment by Minoru** [comment]
I was hoping @dikeert would check it out, but apparently that's not going to happen, so it's fine. Thanks for keeping the issue tracker tidy, @dennisschagt  ^_^

**Comment by dikeert** [comment]
Sorry for long replay, yes I did check it out and it works perfectly, thank you very much =)
