### ISSUE TITLE
Add HOME and END to supported key identifiers. 

### ISSUE THREAD

**Issue by ottopiramuthu** [newsboat/newsboat#934]
The `HOME` and `END` keys are used for the `home` and `end` operations:

... | ... | ...
-- | -- | --
home | HOME | Go to the first item in the list.
end | END | Go to the last item in the list.
macro-prefix | , | Initiate macro execution. The next key press selects the actual macro and runs it.

They aren't mentioned in the key identifier section of the docs that follows:

> Keys, as used in the bind-key configuration command, use a special syntax. Lowercase keys, uppercase keys and special characters are written literally. The "Enter" key is written as ENTER, while the "Esc" key is written as ESC. The function keys "F1" to "F12" are written as F1 to F12. The "Space" key is written as SPACE. Key combinations with the "Ctrl" key, such as "Ctrl-R", are written as ^R. Please be aware that all Ctrl-related key combinations need to be written in uppercase. The following identifiers for keys are supported:

> ENTER (Enter key)
> BACKSPACE (backspace key)
> LEFT (left cursor)
> RIGHT (right cursor)
> UP (up cursor)
> PPAGE (page up cursor)
> NPAGE (page down cursor)
> DOWN (down cursor)
> ESC (Esc key)

**Comment by Minoru** [comment]
Thanks for spotting this, @ottopiramuthu! I submitted a PR that fixes this, #937.
