### ISSUE TITLE
Provide "jump to the entry with index n" for tag list

### ISSUE THREAD

**Issue by Eucyon** [newsboat/newsboat#939]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.19.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
N/a.

Steps to reproduce the issue:
In the tag list, it is not possible to jump to an entry by simply inputting the index number, like in the feed or article list. You need to input an ":" before. Is it possible to provide this feature here?

**Other info you think is relevant**:
In the documentation, it says:
"Jump to the entry with the index <number> (usually seen at the left side of the list). This currently works for the feed list and the article list."

**Comment by Minoru** [comment]
Makes sense. Thanks for the suggestion!
