### ISSUE TITLE
Featurerequest: Operator mark-unread

### ISSUE THREAD

**Issue by ikarus36** [newsboat/newsboat#94]
An operator that changes an article's status from read to unread. It would be quite handy when you open an article that is quite long and you want to read it, but don't have the time right now. You can make in unread again and wouldn't forget it.
Sorry if that's the wrong place for requests, or if it's currently a feature.

**Comment by Minoru** [comment]
Hi! There's `toggle-unread`, IIRC bound to `N` in articlelist by default 
(consult the help in the dialog). Is that good enough?

**Comment by ikarus36** [comment]
Thank you! Must have overread that in the documentation.
