### ISSUE TITLE
Not all keys are registered in all of the relevant contexts

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#958]
**Newsboat version**: `newsboat r2.19-331-g7a8a-dirty` (dirty because of temporarily changing `-O2` to `-O0` in Makefile)

Steps to reproduce the issue:

1. Add at least 2 urls to the `urls` file and start newsboat

2. Press 2 (while being on the feedlist form)

*Expected behaviour*: Newsboat starts command line with `2` filled out (same effect as manually pressing `:` followed by pressing `2`)
*Actual behaviour*: Newsboat ignores the keypress

**Other info you think is relevant**:
Saw this issue while looking into https://github.com/newsboat/newsboat/issues/939.
There might be more keys which are not registered in all of the relevant contexts.
I'm planning to look through all operations and close this issue when identified keymap issues are fixed.

Relevant keymap entry: https://github.com/newsboat/newsboat/blob/f9da3abe4d693ec7cc22c9e04ecd1d749514445d/src/keymap.cpp#L390
It worked correctly in Newsboat release 2.19 because the keymap registered bindings for all contexts without checking the value like `KM_URLVIEW | KM_ARTICLE`.
Probably caused/revealed by https://github.com/newsboat/newsboat/pull/841

**Comment by Minoru** [comment]
Thanks for the report!

BTW, you don't need to edit the Makefile to get `-O0` — just compile everything with `make PROFILE=1`.
