### ISSUE TITLE
add option to pass second argument to notify-program

### ISSUE THREAD

**Issue by uinput** [newsboat/newsboat#96]
Hi there,

thank you for maintaining newsboat. I'd love to use `notify-send` as my notify-program. It works, but as we can only pass a singe argument, the notification title will always default to "notify-send". It would be awesome if we could change that, even if it would say "newsboat" statically. To do so, the first argument passed has to be the notification title, and the second one would be the text displayed in the notification.

**Comment by Minoru** [comment]
Hi! Thanks for using Newsboat ;)

As for you request: in situations like that, write a script that'll be used as a notify-program. For example:

```shell
#!/bin/sh
notify-send "$1" "News items arrived!"
```

Would that work for you?

**Comment by uinput** [comment]
Yes, of course. Thanks for the quick response!

**Comment by Minoru** [comment]
Cool! I'll close the issue then.
