### ISSUE TITLE
`make extract` fails on current master

### ISSUE THREAD

**Issue by dennisschagt** [newsboat/newsboat#966]
**Newsboat version**: Current master: e5b02e781bbffedeac61c35ae6b8c81e979b71a2

Steps to reproduce the issue:

1. Checkout current master or just commit https://github.com/newsboat/newsboat/commit/e5b02e781bbffedeac61c35ae6b8c81e979b71a2

2. Run `make extract`

3. Observe error message:
```
$ make extract
rm -f po/newsboat.pot
xgettext -c/ -k_ -k_s -o po/cpp.pot *.cpp src/*.cpp rss/*.cpp
xtr rust/libnewsboat/src/lib.rs rust/regex-rs/src/lib.rs --omit-header -o po/rust.pot
error: Found argument 'rust/regex-rs/src/lib.rs' which wasn't expected, or isn't valid in this context

USAGE:
    xtr [FLAGS] [OPTIONS] <INPUT>

For more information try --help
make: *** [Makefile:305: extract] Error 1
```

**Other info you think is relevant**:
git bisect shows that this is failing since https://github.com/newsboat/newsboat/commit/0dc480ad572e0170022f4178091e34e0a4302b1a

**Comment by Minoru** [comment]
What `xtr` version are you running? This works for me with xtr 0.1.4 and 0.1.5. Judging by https://github.com/woboq/tr/issues/2, multiple files are supported since 0.1.4.

If that turns out to be a version issue, I'll update the README.

**Comment by dennisschagt** [comment]
Apparently I was running 0.1.3.
It works fine after updating to xtr version 0.1.5.
