### ISSUE TITLE
"Couldn't get a file descriptor referring to the console" on PureOS

### ISSUE THREAD

**Issue by xird** [newsboat/newsboat#97]
**Newsboat version (copy from `newsboat -v`)**: newsboat 2.10.1

Steps to reproduce the issue:

1. Install newsboat on PureOS, a Debian derivative

2. Have at least one feed URL in the "urls" file

3. Launch newsboat

4. Use "open in browser" on one of the feed items

**Other info you think is relevant**: On my machine, nothing happens when the above steps are followed. Once I quit newsboat, I see the following:

$ newsboat
Starting newsboat 2.10.1...
Loading configuration...done.
Opening cache...done.
Loading URLs from /home/testuser/.newsboat/urls...done.
Loading articles from cache...done.
Couldn't get a file descriptor referring to the console
Cleaning up cache...done.
$

Any ideas?

**Comment by Minoru** [comment]
Hi! Thank you for the report.

Judging by the numerous reports with the same error ([1](https://github.com/markbates/cover_me/issues/55), [2](https://stackoverflow.com/questions/42463929/couldnt-find-a-file-descriptor-referring-to-the-console-on-ubuntu-bash-on-win), [3](https://github.com/schneems/explain_shell/issues/1), [4](https://unix.stackexchange.com/questions/253376/open-command-to-open-a-file-in-an-application), [5](https://superuser.com/questions/477819/how-to-open-a-particular-file-from-a-terminal)), Newsboat tries to open a URL using `open` or something like that. Can you try and set a browser in your config, like `browser "/usr/bin/firefox"`?

There are a few more reports ([1](https://unix.stackexchange.com/questions/342841/loadkeys-says-couldnt-get-a-file-descriptor-referring-to-the-console-in-chroo), [2](https://bugzilla.redhat.com/show_bug.cgi?id=831098), [3](https://www.linuxquestions.org/questions/linux-newbie-8/keymapping-couldnt-get-a-file-descriptor-515144/), [4](https://askubuntu.com/questions/962917/cant-get-startx-to-work-couldnt-get-a-file-descriptor-referring-to-the-consol)) dealing with similar error in programs that run in TTYs, not X terminal emulators. Are you running Newsboat in TTY? If so, you'll probably have to run it under `strace` and post the resulting log so I can see which call results in an error.

**Comment by xird** [comment]
Changing the config fixed it. It was originally "browser open", as you suspected. Thanks!
