### ISSUE TITLE
Support pre-processing the contents of an entry

### ISSUE THREAD

**Issue by Oppen** [newsboat/newsboat#979]
AFAIK, there's ongoing effort to add per-side configuration. This would depend on it.

I'll start with the use case. I'm subscribed to LWN featured articles, and have a minor annoyance with the way they publish their articles. When you open the URL, it doesn't send you directly to the article itself, but to an abstract with a link to the full article. Now, when I'm using Newsboat, if I decide to pass it the browser, I think it's obvious I want the full article. However, I can't change how LWN behaves. What I could change is whether I pass the full article's URL to w3m (or whaterver browser I use), which follows a very simple pattern based on the feed's URL.

I could simply use a wrapper to the browser, but since there's only one browser setting for all feeds, I'd need to special case each site there. What I propose is to add a simple setting to each site that tells it to first run a program on the URL before starting the browser. Alternatively, this could be done by setting per-feed browsers and going with the wrapper approach.

Extra points for using this feature to apply cosmetic fixes, such as removing the sidebar or putting all image links at the end of the page, since LWN nowadays put it interleaved with the text contents.

**Comment by Minoru** [comment]
Please take a look at `filter:` and `exec:` URLs, I think they cover these use-cases.

**Comment by Oppen** [comment]
Oh. I will look at them, thanks!

**Comment by Minoru** [comment]
Yes, both produce feeds. But feeds contain articles a.k.a. entries, so I don't really see the problem:

> skipping the abstract part

Parse the feed, for each item parse contents as HTML, find the link to the full version, fetch it, replace the item's body with resulting HTML, print out the modified feed.

> the removal of irrelevant elements from the page

That's even simpler: parse the feed, for each item parse contents as HTML, cut out the elements you don't want, re-assemble the feed and print it out.

Last I looked into this, Python with its feedparser, beautifulsoup, and request libraries were the easiest tools for these jobs.

> Not unless I have some server process or something like that to "fetch" the pages from.

Why would you need a server process to cut out irrelevant elements?

**Comment by Oppen** [comment]
> Yes, both produce feeds. But feeds contain articles a.k.a. entries, so I don't really see the problem:
> 
> > skipping the abstract part
> 
> Parse the feed, for each item parse contents as HTML, find the link to the full version, fetch it, replace the item's body with resulting HTML, print out the modified feed.
> 
OK, this makes sense. I was seeing the "open in browser" part as a whole separate thing from the reader. What you suggest is to make the article itself the feed item, right?

> > Not unless I have some server process or something like that to "fetch" the pages from.
> 
> Why would you need a server process to cut out irrelevant elements?
>
In context of the previous post, because I'd need a link to tell the browser where to fetch the modified version. But the filter could create temporary files and nothing stops w3m from reading those. Then again, as you suggested (I think) I can simply embed the new version in the filtered feed and not even need w3m. Is that right?

**Comment by Minoru** [comment]
> OK, this makes sense. I was seeing the "open in browser" part as a whole separate thing from the reader. What you suggest is to make the article itself the feed item, right?

Well, `open-in-browser` *is* separate from viewing an article inside Newsboat. So you're right on that one.

"Make the article the feed item" doesn't make sense to me. An article *is* a feed item. Those two are synonyms (they can also be called entries). What I suggest is to process the item while it's still a part of the feed.

It feels like you haven't fully understood what `fillter:` does. Try writing a simple filter e.g. one that adds some string to every item's title.

> Then again, as you suggested (I think) I can simply embed the new version in the filtered feed and not even need w3m. Is that right?

Yes, the browser shouldn't be needed. The link is already in the feed, it's part of the entry. You fetch it using any HTTP client (curl, Python's request, whatever), take the contents of the `<body>`, and use that as the entry's new body. Again, you can write a simple filter that replaces the entry's body with the entry's link.

**Comment by Oppen** [comment]
OK, beside me not knowing the correct terms, I think we're on the same page now. Thanks!

**Comment by Minoru** [comment]
Cool! I think `filter:` and `exec:` make the suggested new options redundant, so I'm closing the issue.
