### ISSUE TITLE
[FR] Mark as unread

### ISSUE THREAD

**Issue by joemaro** [newsboat/newsboat#992]
Quite often i'm wondering why the amazing newsboat can't toggle read items as unread.

For me thats quite a central feature and just wanted to share my liking of such a feature here.

Thanks for making newsboat so amazing!!

**Comment by Minoru** [comment]
Doesn't [`toggle-article-read`](https://newsboat.org/releases/2.19/docs/newsboat.html#toggle-article-read) do what you want?

**Comment by joemaro** [comment]
oh, yes it does exactly what i want @Minoru ... i don't know how i could've missed that ... i'm sorry for the inconvenience!

**Comment by Minoru** [comment]
No inconvenience caused ;)
