### ISSUE TITLE
Feature request: Share with ...

### ISSUE THREAD

**Issue by dermitdemdino** [newsboat/newsboat#998]
for instance, Mastodon

**Comment by Minoru** [comment]
Hi! Newsboat supports [bookmarking](https://newsboat.org/releases/2.19/docs/newsboat.html#_bookmarking). Take a look at [the contrib/ directory](https://github.com/newsboat/newsboat/tree/d481c9c88a3de16bc106bebe609e921fa98a095c/contrib) for examples of how to write a bookmarking script. Or have you tried that already and ran into some problems, @dermitdemdino?

**Comment by dj-bauer** [comment]
You could write a script as well which utilizes pipe-to and grep the Link out.

**Comment by Minoru** [comment]
@dermitdemdino, have your question been answered?

**Comment by dermitdemdino** [comment]
Yes.

**Comment by Minoru** [comment]
Cool! I'm closing this, then.
