### ISSUE TITLE
Where can I find the full documentation for string formating?

### ISSUE THREAD

**Issue by dj-bauer** [newsboat/newsboat#999]
Hello Guys,
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.19

Hello, I am currently playing around with the newsboat string formatting
I now try to develop further, and the documentation says there are plenty of sequences to format strings. Although I don't find any more documentation for it, than in the doc.
I would like to find out if it is possible to center a string between the cursor to the next 20 charachter like shown for example. I only know this functionality for right aligning it.

Known behaviour (with %>=%t):
Test================
Wished behaviour:
========Test========

t that it with the couple of sequences in the documentation, or are there actually more possibilities to explore?

Thank you for this great software,
Daniel.

**Comment by Minoru** [comment]
Hi! Why did you close the issue?

I believe [the documentation](https://newsboat.org/releases/2.19/docs/newsboat.html#_format_strings) is complete. We indeed don't have a format sequence for centering. I don't see a reason not to add it. If someone wants to work on that, the code is here: https://github.com/newsboat/newsboat/tree/d481c9c88a3de16bc106bebe609e921fa98a095c/rust/libnewsboat/src/fmtstrformatter (tests will have to be ported to https://github.com/newsboat/newsboat/blob/d481c9c88a3de16bc106bebe609e921fa98a095c/test/fmtstrformatter.cpp as well, to check that everything works fine across the FFI).

**Comment by dj-bauer** [comment]
Ah, thank you! I just started reading into it and will propably completly get on it tomorrow.

**Comment by dj-bauer** [comment]
Seems like I got it working and wrote a test and documentation for it. Now I don't know if I have to create a fork and set a merge request from there, how I am going to show my work. I tried pushing a different branch, but got (obviously) no permission for it. I have never contributed in a github project, but I know the git basics.

**Comment by Minoru** [comment]
> I have to create a fork and set a merge request from there

That's right:
- click the "Fork" button in the top right corner of this page (or any other page of this repository). That will create a "newsboat" repository under your account;
- push your changes to that repository (just [add a remote](https://help.github.com/en/github/using-git/adding-a-remote) to your existing clone, and push there);
- follow [this help page](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to create a pull request.

Don't hesitate to ask if you run into any problems, I'm happy to help!

**Comment by dj-bauer** [comment]
I also thought about about a grouping sequence to allow character perfect padding for multiple tags.
And I had the idea to ad the tags isFirstFeed and isLastFeed for feedlist, which contain a char if true and are empty if false. With these two features together you could draw custom borders all around your feeds . I don't know if that are too specific use cases, but I just thought, what things you could do more with string modifiers.

**Comment by Minoru** [comment]
> I also thought about about a grouping sequence to allow character perfect padding for multiple tags.

Can you expand on this? With some examples, perhaps?

> With these two features together you could draw custom borders all around your feeds

Frankly, this sounds like useless decoration. Is there any benefit to having those?

**Comment by dj-bauer** [comment]
> Can you expand on this? With some examples, perhaps?
 My initial Idea was to draw a right horizontal border.
My current format kinda looks like this:
\\(%T\\) %t
Through variable length of the first tag and the title with grouping them You could give them a padding for nice alignment.
 
> Frankly, this sounds like useless decoration. Is there any benefit to having those?
Basically both idea where just useless cosmetics, without any benefits but visuals.

**Comment by Minoru** [comment]
> Through variable length of the first tag and the title with grouping them You could give them a padding for nice alignment.

Can't you just pad the tag to some optimistic width, like `(%20T) %t`?

**Comment by dj-bauer** [comment]
> Can't you just pad the tag to some optimistic width, like `(%20T) %t`?

Thank you. That was the way i was looking for.

**Comment by Minoru** [comment]
You're welcome! :) Does this make #1001 redundant?

**Comment by dj-bauer** [comment]
#1001 is still not redundant, but because I have troubles fixing the mentioned problem and just being a cosmetics I'd suggest to close the pull request until I get it working.

**Comment by Minoru** [comment]
Ah no, let's keep it open if you're working on it. Just wanted to make sure it didn't become unnecessary. Thanks!

**Comment by Minoru** [comment]
#1001 is merged now, so closing this.
